### ISSUE TITLE
Deferred statements not running when non-returning function is called

### ISSUE THREAD

**Issue by kennethmaples** [odin-lang/Odin#1008]
## Context

* Operating System: Linux

```sh
sh-5.1$ uname -r
5.12.6-arch1-1
sh-5.1$ ldd --version
ldd (GNU libc) 2.33
[...]
sh-5.1$ opt -version
LLVM (http://llvm.org/):
  LLVM version 11.1.0
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake
```

* Please paste `odin version` output: `odin version dev-2021-06:f41150f8`

## Code

```odin
package main

import "core:os"
import "core:fmt"

main :: proc() {
    fmt.println("hello");
    defer fmt.println("world");
    os.exit(0);
}
```

## Expected Behavior

```
$ ./prog
hello
world
$
```

## Current Behavior

```
$ ./prog
hello
$
```

**Comment by gingerBill** [comment]
This is not a bug and actually a complicated question. The question is, if you are calling a diverging procedure (`-> !`) should you call the `defer`s in that current scope? It can be a good idea and a bad idea depending on the situation.

Sometimes you cannot recover and just you want to terminate, and in that case calling the `defer`s is not a good idea.

**Comment by kennethmaples** [comment]
Yeah, it occurred to me after posting that there was a further ambiguity for `defer` statements in previous calling frames, which (if we expected to run) would effectively require unwinding the entire call stack (which doesn't seem like the expected behavior of a diverging proc call to me).

This came up when I needed to give different exit codes in my main procedure depending on the precise error state of my program, while also ensuring that my log file buffers were flushed. If anyone else is running into this problem, my solution was to replace my `main` proc with a `main_inner` proc which I can return from, thus triggering my `defer`s:

```
main_inner :: proc() -> int {
  ...
}

main :: proc() {
  retcode := main_inner();
  os.exit(retcode);
}
```

**Comment by timmyjose** [comment]
I think having an explicit note (error/warning) would be better than silently exiting.

**Comment by gingerBill** [comment]
The issue is that adding a warning or error may not be correct either. "Silently exiting" (as you call it) is probably the better option because of the semantics.

**Comment by krixano** [comment]
This isn't considered a bug or error, imho. If you want to call stuff before an exit, then you have to actually call the stuff. One way you could do this is by using signals, things like that. Or, you can do what was suggested above, too. Or you can just call the functions before the exit. Or you can code your program in a way that to exit you just return from your functions until it gets to the end of main.

Also, turning this into an error would be bad, because then nobody can write a completely valid piece of code that does what they expect because of the chance that it's not what other people might have expected. In that case, it should be a warning if anything, not an error.

**Comment by timmyjose** [comment]
I mean, I agree with @gingerbill that it depends on the semantics.

For instance, in Zig, it is an error, which makes sense to me since that
defer will never actually run.

```

    const std = @import("std");

    pub fn main() void {
        defer std.debug.print("Adios!\n", .{});
        std.debug.print("Hello!\n", .{});
        std.os.exit(0);
    }

    ~/dev/playground:$ zig run defer.zig
    ./defer.zig:4:11: error: unreachable code
        defer std.debug.print("Adios!\n", .{});
              ^
    ./defer.zig:3:20: note: referenced here
    pub fn main() void

```

**Comment by gingerBill** [comment]
That has made me think. That's not a bad way to handle `defer` within a scope that contains a diverging call. If the `defer` is outside of a scope, then it's not necessarily an error, but within one it is.

**Comment by gingerBill** [comment]
I have added this basic unreachable `defer` checking in 8f57bb07991930f242ec4ab4d9fb3a851a4e9662
