### ISSUE TITLE
Structs being passed incorrectly to C foreign function on MacOS.

### ISSUE THREAD

**Issue by powerc9000** [odin-lang/Odin#1020]
## Context

Passing a struct that looks like this:

```
struct {
   data: rawptr,
   width: i32,
   height: i32,
}
```
to a c foreign function results in all the values in the struct becoming zero.
When logging out the struct in odin the data looks like this. ```{data = 0x7F8047000000, width = 512, height = 512}```
But when in C foreign function it is:

```{data=0x7ffee67d19f8, width=0, height=0}```

* Operating System: MacOS Big Sur Intel.
* `dev-2021-06:266b5d7d`

(Could not test on current master because of other issue.)

## Expected Behavior

The values in the struct should not differ between C and odin

## Current Behavior

The struct is somehow corrupted when passing it into C.

**Comment by Kelimion** [comment]
At what optimization level was this code compiled?

**Comment by powerc9000** [comment]
I didn't set any flags besides `-out`
```	
odin build game -out:build/game
```

**Comment by powerc9000** [comment]
`opt:3`, `opt:2` and `o:speed` no longer have `0` for width and height. Instead having ```{data=0x7ffee96086b8, width=584873889, height=32767}``` 

every other opt and `o` have the same issue.

**Comment by Kelimion** [comment]
Thanks. That should be useful information to chase things down.

**Comment by powerc9000** [comment]
Update still happens on latest master: ```dev-2021-06:84a4188c```

**Comment by gingerBill** [comment]
Could you please give the basic code to replicate this.

**Comment by powerc9000** [comment]
Yes. I have isolated that it's when there is a return value involved as well.
[test.zip](https://github.com/odin-lang/Odin/files/6666663/test.zip)

should just be able to run `make` and it will build and run the test.

**Comment by powerc9000** [comment]
Can't replicate on latest odin `dev-2021-07:3930a32b`

**Comment by powerc9000** [comment]
The test code I posted works fine now but still seeing issues with foreign functions in MacOS that didn't exist in earlier versions of odin.

Passing structs to `proc "c"` procs in MacOS gives incorrect data. Even if not a foreign function.

**Comment by powerc9000** [comment]
Looks like this isn't nearly as simple as I thought in terms of reproduction. The simple case works fine. So I'll close this in favor of a new issue when I can isolate.

**Comment by brunodeangelis** [comment]
Is this still an issue? Because I'm having problems with Raylib's Camera2D on macOS not rendering anything, and [I found this](https://powerc9000.itch.io/cute-asset-pipeline/devlog/199537/working-with-odin-on-macos) which explains a workaround for a perhaps-related problem. So it seems this issue hasn't been fixed yet?
