### ISSUE TITLE
Large boolean array compiles but produces wrong behaviour at runtime

### ISSUE THREAD

**Issue by jockus** [odin-lang/Odin#1021]
## Context
```odin
package bug

import "core:fmt"
// size :: max(u32) / 3; // Works
// size :: max(u32) / 2; // Compiler complains about image size
size :: max(u32); // Compiles but produces wrong behaviour at runtime
array : [size]bool;
main :: proc() {
	for i in 0..<size {
		if array[i] {
			fmt.println(i);
			assert(false);
		}
	}
}

```

* Operating System:
odin version dev-2021-06:55e472cd

## Expected Behavior

Uncommented case above should not compile.

## Current Behavior

The array seems to contain true values when it shouldn't - probably accessing memory beyond itself.

**Comment by gingerBill** [comment]
"Large" is an understatement. That's 4 GiB.

**Comment by gingerBill** [comment]
I may require a check on the size of global variables, like I do with static variables.
