### ISSUE TITLE
`@(align_as=<integer|type>)` 

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#1033]
`@(align_as=<integer|type>)`  attribute for variable declarations

```odin
@(align_as=8)
f: Foo;

@(align_as=i32)
b: u8;
```

This will define the _minimum_ alignment that the variable must have as a stack/global variable.

**Comment by ThisDrunkDane** [comment]
_sidenote:_ We should really align on, do we actually want to use the github discussion feature or not? There is a proposal category in there (and we can define our own), we converted a bunch of discussion and proposal issues to it during the great issue-reduction stream a little while ago. So do we want to keep the issues for _actual_ issues or not?

**Comment by krux02** [comment]
In C, ``_Alignas`` works not only on variables, but also on fields.

**Comment by gingerBill** [comment]
@krux02 That's not needed because record types have `#align` directives:
```odin
Foo :: struct #align 8 {
    x: Bar,
}
```

**Comment by krux02** [comment]
> @krux02 That's not needed because record types have `#align` directives:

Sure. But with the same argument could be applied for the align_as directive for variable declarations, because you can wrap everything in a struct and put the alignment constraint to that wrapping type instead of the variable.

I am just saying, fields and local variables are not that different semantically after all. I've often converted fields into local variables and and local variables into fields during code refactoring.

**Comment by gingerBill** [comment]
> > @krux02 That's not needed because record types have `#align` directives:
> 
> Sure. But with the same argument could be applied for the align_as directive for variable declarations, because you can wrap everything in a struct and put the alignment constraint to that wrapping type instead of the variable.
> 
> I am just saying, fields and local variables are not that different semantically after all. I've often converted fields into local variables and and local variables into fields during code refactoring.

This proposed _attribute_ (not directive) is conceptually distinct and does not have the same semantics. I know C's `_Alignas` unifies the concepts but that's because it didn't want to add new keywords for the different concepts. `_Alignas` applies in a lot of places.

**Comment by krux02** [comment]
What different concepts of `_Alignas` do you mean?

**Comment by gingerBill** [comment]
In C/C++
```c
struct alignas(float) struct_float {
    ...
};

struct alignas(16) foo {
    float e[4];
};

alignas(128) unsigned char cache_line[128];
```

Odin's approach would be this:
```odin
struct_float :: struct #align align_of(float) {
    ...
}

foo :: struct #align 16 {
    e: [4]f32,
}

@(align_as=128)
cache_line: [128]u8;
```

**Comment by krux02** [comment]
Ah, ok you mean the attachment to the variable declaration and the type declaration. Yes those are two different concepts.

But just for compleness, this one is missing:

```C
struct data {
  char x;
  alignas(128) char cacheline[128]; // over-aligned array of char, 
                                    // not array of over-aligned chars
};
```

AFAIK there is no proposed odin solution for this. I am pretty sure you've seen it, it is from [here](https://en.cppreference.com/w/c/language/_Alignas). There is another use case for `_Alignas` for struct fields in C. On Linux 32 bit a `double` and a `float64_t` have an alignment of 4 even though they have the size of 8. Meaning they are not self aligned, even though it would be beneficial for performance reasons. I have no idea why this is. All I know is, struct layouts may be  different on windows and linux and also between linux 64bit and linux 32bit. I worked on the alignment/offset computation in the Nim compiler and Nim wants to be 100% C compatible here. A solution for compatible struct layouts, e.g. for serialization, would then be fix the alignment through explicit `alignas(8)` in the struct fields.
