### ISSUE TITLE
Global rawptr bugs

### ISSUE THREAD

**Issue by SentientCoffee** [odin-lang/Odin#1044]
## Context

- ~~Setting a global `rawptr` in one procedure and trying to access it in a different one, as soon as it exits the procedure where it gets set the `rawptr` becomes `nil`~~ Caused by variable shadowing. Not a bug.
```
resizeDIBSection :: proc(width, height: i32) {
    if bitmapMemory != nil {
        virtualFree(bitmapMemory, 0, u32(FreeType.Release));
    }

    bitmapWidth, bitmapHeight = width, height;
    // ...
    bytesPerPixel : i32 = 4;
    bitmapMemorySize := uint(bitmapWidth * bitmapHeight * bytesPerPixel);

    bitmapMemory := virtualAlloc(nil, bitmapMemorySize, u32(AllocationType.Commit), u32(MemoryProtection.ReadWrite));
    bitmap := mem.byte_slice(bitmapMemory, cast(int) bitmapMemorySize);
    // ...

    // Neither of these asserts go off
    assert(bitmap != nil);
    assert(bitmapMemory != nil);
}

//...
mainWindowProc :: proc "std" (window: winapi.HWnd, message: u32, wParam: winapi.WParam, lParam: winapi.LParam) -> (result : winapi.LResult) {
    // ...
    width  := clientRect.right  - clientRect.left;
    height := clientRect.bottom - clientRect.top;
    resizeDIBSection(width, height);
    // This assert does go off
    assert(bitmapMemory != nil);
    // ...
}
```
- Explicitly setting a `rawptr` to `nil` in global (or file/package) scope triggers a compiler bug
```odin
bitmapMemory : rawptr;         // No explicit setting, runs fine

main :: proc() {
    // ...
}
```
```odin
bitmapMemory : rawptr = nil;         // Explicit setting, compiler bug

main :: proc() {
    // ...
}
```
## Operating System:
`odin version` output: `odin version dev-2021-06:84a4188c`

## Expected Behavior

- ~~Using a global `rawptr` should retain its value throughout the length of the program, regardless of what procedure I am currently in.~~ Caused by variable shadowing. Not a bug.
- Setting a `rawptr` to nil explicitly in global scope (or file/package scope, as it were) should have the same behaviour as not setting it to anything (i.e. both get set to `nil` properly)

## Current Behavior

See above.
- ~~Setting a `rawptr` to some value inside a procedure that returns sets the `rawptr` back to `nil`~~ Caused by variable shadowing. Not a bug.
- Setting a `rawptr` to `nil` explicitly in global scope (or file/package scope, as it were) triggers a compiler bug and gives no error when trying to compile.

#### Global `rawptr` set to `nil` after procedure:
Caused by variable shadowing. Not a bug.
~~1. New empty project, make a global `rawptr` and don't set it to anything
2. Make a seperate procedure that sets the value of the `rawptr` (something that can persist outside of a procdure return)
3. Inside the `main` proc, call the procedure and assert that the `rawptr != nil` (should fire)~~

#### Global `rawptr = nil`:
1. Make a global `rawptr` and don't set it to anything (should run fine)
2. Set the global `rawptr` to nil explicitly in global scope (triggers compiler bug)

## Failure Information (for bugs)

Debugging the `odin` executable in Visual Studio using [my project](https://github.com/SentientCoffee/CappuccinoEngine-v3):
- Arguments: `build src\main.odin -collection:externals=externals -out:"build\debug\cappuccino_d.exe" -opt:0 -debug`
- Working directory: `<project root>`

In `llvm_backend.cpp(15010:67)`:
![image](https://user-images.githubusercontent.com/22991229/123522915-8df0ca00-d68e-11eb-84dd-78976e2ea5c1.png)

Call stack:
![image](https://user-images.githubusercontent.com/22991229/123522950-bc6ea500-d68e-11eb-800c-f57fd26e6381.png)

Value of `init` at the panic site:
![image](https://user-images.githubusercontent.com/22991229/123522982-e922bc80-d68e-11eb-9beb-317eca5d80c4.png)
![image](https://user-images.githubusercontent.com/22991229/123522992-f770d880-d68e-11eb-89ef-b95bcffa9421.png)

**Comment by gingerBill** [comment]
There are two errors here.

The first one is that you are redefining a global variable `bitmapMemory :=` 
i.e. variable shadowing

As for the second one, that is a backend bug for definite.

**Comment by SentientCoffee** [comment]
Ah man, I gotta be more vigilant with those...is there a way to trigger some kind of warning/error when variable shadowing happens?

**Comment by gingerBill** [comment]
`-vet` may be useful in that case.

**Comment by SentientCoffee** [comment]
Thank you. I updated my issue to reflect the mistake.
