### ISSUE TITLE
128-bit integers cannot be passed to or returned from C

### ISSUE THREAD

**Issue by sci4me** [odin-lang/Odin#1045]
The following is a repro of this issue:
```c
#include <stdio.h>
#include <x86intrin.h>

typedef unsigned long long u128 __attribute__((__vector_size__(16), __aligned__(16)));

u128 test(u128 x) {
    printf("%llu %llu\n", _mm_extract_epi64(x, 0), _mm_extract_epi64(x, 1));
    return x;
}
```
```odin
package main

import "core:fmt"

foreign import lib "./test.a"

foreign lib {
    test :: proc(x: u128) -> u128 ---;
}

main :: proc() {
    fmt.println(test(42));
}
```
I compiled and ran the program as such:
```
gcc -c test.c -o test.o
ar rcs test.a test.o
odin run test.odin
```
And here is what it printed:
```
0 0
4
```
I would've expected it to print:
```
42 0
42
```
OS: 5.11.8-arch1-1
Odin: dev-2021-06

**Comment by gingerBill** [comment]
```c
typedef unsigned long long u128 __attribute__((__vector_size__(16), __aligned__(16)));
```
is this equivalent to 
```c
unsigned __int128
```

in the first place?

**Comment by sci4me** [comment]
> ```c
> typedef unsigned long long u128 __attribute__((__vector_size__(16), __aligned__(16)));
> ```
> 
> is this equivalent to
> 
> ```c
> typedef unsigned __int128 u128;
> ```
> 
> in the first place?

Ah, apparently not; I guess this isn't a bug after all. I changed it to `typedef unsigned __int128 u128;` and that worked.
I had gotten the first typedef out of one of the intrinsics headers from GCC, assuming that'd be the most proper thing to use.
