### ISSUE TITLE
Unexpected behavior when returning a numeric slice literal

### ISSUE THREAD

**Issue by streof** [odin-lang/Odin#1052]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: macOS 10.14.6 (x86_64)
* Please paste `odin version` output: odin version dev-2021-07:f7413ca9

## Expected Behavior

The code below should return
```odin
[42, 42, 42, 42, 42, 42, 42, 42]
[42, 42, 42, 42, 42, 42, 42, 42]
```

Note: This is also the observed behavior when using the old backend (version 0.13.1-nightly-aa846d0e)

## Current Behavior

```odin
package bug

import "core:fmt"

bar :: proc() -> (foo: []u64) {

  foo = { 0..<8 = 42 };
  fmt.println(foo);

  return;
}

main :: proc() {

  fmt.println(bar());
  // Returns:
  // Mode: -o:"minimal"
  // [42, 42, 42, 42, 42, 42, 42, 42]
  // [1, 4416469754, 140732799292456, 4416626327, 1, 4416626327, 1, 140732799292352]

  // Mode: -o:"size"
  // [42, 42, 42, 42, 42, 42, 42, 42]
  // [140732702975008, 4512771809, 42, 4512853271, 1, 4512853271, 1, 140732702974960]

  // Mode: -o:"speed"
  // [42, 42, 42, 42, 42, 42, 42, 42]
  // [140732889809968, 8, 42, 42, 42, 42, 42, 42]

  // Similar behavior occurs when bar() returns []u8, []i16, []f32, []int, etc
  return;
}

```

### Steps to Reproduce

- `odin run bug.odin -o="minimal"`
- `odin run bug.odin -o="size"`
- `odin run bug.odin -o="speed"`

**Comment by gingerBill** [comment]
This is not actually a bug in the compiler but how slices work. You are returning stack backed memory into a parent frame.
```odin
x := []f64{1, 2, 3};
```
is essentially this:
```odin
x_backing := [3]f64{1, 2, 3};
x := x_backing[:];
```


One thing for the future (which is not that easy to do) is to do pointer escape analysis to see when things escape a stack frame and warn the user when it happens.

**Comment by streof** [comment]
Ah ok, that makes more sense. Thanks for the explanation!
