### ISSUE TITLE
Can't negate non constants in default procedure parameters

### ISSUE THREAD

**Issue by Skytrias** [odin-lang/Odin#1053]
## Context

* Operating System: `Linux Mint 20 - Kernel 5.4.0-73-generic`
* Please paste `odin version` output: `odin version dev-2021-07:f7413ca9`

## Expected Behavior

Negate a default procedure parameter just like constants are allowed to be negated.

## Current Behavior

Works as expected on constants, but doesn't on "non constants".

### Steps to Reproduce

```go
TEST :: 0.1;
non_constant: f32 = 0.2;
a :: proc(param1: f32 = -TEST, param2: f32 = -non_constant) {
    fmt.println("hi", param1, param2);
}
main :: proc() {
    a();
}
```

### Failure Logs

```
/home/michael/Schreibtisch/experimental/main.odin(17:46) Default parameter must be a constant, 2
/home/michael/Schreibtisch/experimental/main.odin(22:2) Too few arguments for 'a', expected 2 arguments, got 0
```

**Comment by gingerBill** [comment]
This is not a bug but it does require a better error message

**Comment by Skytrias** [comment]
okay :+1:
