### ISSUE TITLE
Unexpected successful compilation when writing slightly incorrect syntax

### ISSUE THREAD

**Issue by judah-caruso** [odin-lang/Odin#1054]
## Context

A slightly pedantic issue but writing invalid procedures causes the compiler (`35230b1a`) to silently fail, not showing any errors or warnings. 

```odin
package main

import "core:fmt"

call_proc :: proc(p: () int) {
    return_value :: p()
    fmt.println(return_value)
}

main :: proc() {
    call_proc(() {
        fmt.println("Inside procedure")
        return 1
    });

    fmt.println("At the end!");
}
```

Fixing syntax errors for the procedures causes the other errors to be raised correctly.

* Operating System:
version dev-2021-07:35230b1a

## Expected Behavior

Errors for the incorrect procedures, lack of semicolons, etc.

## Current Behavior

Silent failure and no generated files.

**Comment by awwdev** [comment]
**Minimal version that will cause the compiler crash:**
```odin
 foo :: proc(p: ()) {} 
```
I think this is invaild syntax but the compiler should of course generate an error (so it's a bug).
If you want to pass a proc as parameter, you can do this afaik:
```odin
foo :: proc(p: proc()->int)
//or
Proc :: #type proc() -> int;
foo :: proc(p: Proc)
```
