### ISSUE TITLE
Having multiple files causes endless loop

### ISSUE THREAD

**Issue by pJotoro** [odin-lang/Odin#1063]
## Context

operating system: Windows 10
odin version output: dev-2021-07-nightly:e17593be (I had the wrong version written before because my path was screwed up; that said, my build.bat is correct so this issue still stands)

## Expected Behavior

I was expecting to be able to have multiple files in my project without any strange behavior.

## Current Behavior

The same lines of code at the end of the file get repeated over and over again. My program is just a blank white screen.

## Failure Information (for bugs)

It only happens if you have at least two files.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Have multiple files in your program.

### Failure Logs

This video should be helpful: https://www.youtube.com/watch?v=sGHu05ZaB0g&feature=youtu.be

**Comment by gingerBill** [comment]
This is some absolutely bizarre error which I can 100% not replicate. It seems like bizarre code gen bug that LLVM has produced.
