### ISSUE TITLE
odin test no longer finds any tests

### ISSUE THREAD

**Issue by DanielGavin** [odin-lang/Odin#1068]
## Context

Windows 10 
Run with the latest odin version (dd8fa1d690db5a6a42a300c1a09b821806ea39e8)

## Expected Behavior

Finds all my tests in the specified folder and runs them.

## Current Behavior

It returns no tests ran.

### Steps to Reproduce

odin test test_folder

**Comment by Platin21** [comment]
This also happens on MacOS.
