### ISSUE TITLE
`-build-mode:shared` fails on Linux with `ld` error `recompile with -fPIC`.

### ISSUE THREAD

**Issue by Kelimion** [odin-lang/Odin#1071]
## Context

Odin doesn't build a shared libary on Linux.

* Operating System: Ubuntu 20.04 LTS
* Please paste `odin version` output: odin version dev-2021-08:40b4f3a9

## Expected Behavior

I expect Odin to successfully build a `.so` file when invoked with `-build-mode:shared` and at least one procedure was tagged with `@export`.

## Current Behavior

```
$ odin build . -build-mode:shared
ld: /mnt/w/odin-test/odin-test.o: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
```

## Minimum repro case

Compile using `odin build . -build-mode:shared`. Creates a `.dll` on Windows as expected, creates `.o` file but doesn't create the desired `.so` file at the end.

```odin
package minrep

@export foozle :: proc "c" () -> (res: int) {
	return 42;
}

main :: proc () {

}
```

**Comment by AlectronikForge** [comment]
Can confirm this, also happens with -build-mode:obj with the following ld call, and with the current master code. -extra-linker-flags:-fPIE solves this but unsure whether it's the intended way or even does what I want, as I couldn't test the resulting object yet because of that I somehow failed to decouple the runtime (-no-crt working??).

**Comment by kim366** [comment]
I additionally get `ld: Error: unable to disambiguate: -arch (did you mean --arch ?)`, which I assume means I have an incompatible version of ld/lld. When I build to object (`odin build . -build-mode:object`) and then link manually (`cc -shared abc.o`), I get the `-fPIC` error, as mentioned above: `/usr/bin/ld: abc.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC`.

I guess a solution to this would be to add position independent compilation as an explicit compiler flag

**Comment by Kelimion** [comment]
![image](https://user-images.githubusercontent.com/194614/148998757-361efa64-faf7-47f9-a33e-05615804aa56.png)
Fixes were made yesterday. Do you still have these issues on HEAD?

**Comment by kim366** [comment]
Interesting. Does everything work for you now? Yes, I am using HEAD, I will manually fix the -arch/--arch issue and see if Odin using the linker itself will fix it. Thanks for the quick reply!

**Comment by kim366** [comment]
Thanks for the quick reply. It does indeed work now, I didn't notice that I didn't do a successful pull. So I guess we can close this now. I'm very grateful it works now, I've been waiting for this for a while :)

**Comment by Kelimion** [comment]
I consider it closed provisionally. Will test it tomorrow with `tests\core\math\big`'s library for the Linux CI. But it's promising.

**Comment by gingerBill** [comment]
Should I close this?

**Comment by Kelimion** [comment]
> Should I close this?
I'll close it tomorrow after I verify it successfully builds and runs the big maths tests on Linux.
