### ISSUE TITLE
sync2 pthread primitives doesn't build

### ISSUE THREAD

**Issue by graphitemaster** [odin-lang/Odin#1084]
The `sync2` primitives package `primitives_pthreads` uses `runtime.current_thread_id()` which doesn't exist, all other primitives implementation just uses `current_thread_id()` directly (not through a `runtime.` accessor). Removing this appears to work except `sync2`'s `primitives.odin` also wraps `current_thread_id` expecting there to be one named `_current_thread_id()` like on Windows, which doesn't exist here. The Windows one should just be renamed to `current_thread_id` and that wrapper function should just be removed I believe?

**Comment by gingerBill** [comment]
This should be fixed now.

**Comment by graphitemaster** [comment]
Yep, seems fixed, thanks.
