### ISSUE TITLE
segfault on filepath.glob() if no matches are found

### ISSUE THREAD

**Issue by awwdev** [odin-lang/Odin#1114]
Odin `dev-2021-09:e2f035d6`
Tested on both Windows and Linux

```odin
paths, ok := filepath.glob("")
```
Will segfault or terminate with exit code 1 when it cannot find any matches.
It works fine if it finds matches.

The bug was probably introduced when adding the `or_return` logic on 4035fec784fc7e0109d2f8a3d3bbfb5696512de1
On an earlier commit (for example `a3930cb4`) the above code will not segfault and return an empty slice as expected.

**Comment by awwdev** [comment]
Additionally:

```odin
import "core:path/filepath"
import "core:fmt"
main :: proc() { 
    files, ok := filepath.glob("*.txt"); 
    fmt.println(ok, files);
}
```
Compile. Place a text file next to the exe. Run the exe directly (over command line). 
This worked previously, but crashes with latest Odin.

**Comment by track-5** [comment]
I've just attempted a repro on master (461ca408487c7831ba3bd635b4ca2106215abf02) and the program executed correctly for me.

**Operating system: Windows 10.**

I don't have a Linux system at my disposal, so might be worth double checking it there.
@awwdev the issue might've been corrected already. Can you try it again by building Odin's master branch and trying to reproduce this on Linux? We might be able to just close this issue :)

## No .txt file in directory

`filepath.glob("*.txt")`  returned an empty slice and `None`, respectively.

![Empty directory glob result](https://user-images.githubusercontent.com/90465881/132880522-89ae3686-ad31-4735-a9eb-0b7819d50e29.PNG)

Output on the console:

```
p:\debug>repro.exe
None []
```

## Single text file in directory
After that, I created a new text file (test.txt) in the same directory the executable is found and ran it.

![One file in glob result](https://user-images.githubusercontent.com/90465881/132880952-025bc1d5-5c94-4cd3-b264-2dcbc6f7b24d.PNG)

Output on the console:
```
p:\debug>repro.exe
None [test.txt]
```

**Comment by awwdev** [comment]
Thank you for testing! 
I can confirm this is fixed on both Windows and Linux. 
However, it's not clear to me when the fix happened (or when the bug was introduced).
