### ISSUE TITLE
enum + #any_int + $T

### ISSUE THREAD

**Issue by awwdev** [odin-lang/Odin#1125]
Odin `dev-2021-09:e2f035d6`
Windows, Linux

Seems like `enum` + `#any_int` + `$T` don't play together. Example:
```odin
Foo :: enum { A }
bar :: proc(#any_int n: int, $T: typeid) {}
bar(Foo.A, f32)
```
`Odin\src\llvm_backend_proc.cpp(6): Assertion Failure: entity->flags & EntityFlag_ProcBodyChecked`

It works without the generic:
```odin
Foo :: enum { A }
bar :: proc(#any_int n: int) {}
bar(Foo.A) //no generic
```
It works without the enum:
```odin
bar :: proc(#any_int n: int, $T: typeid) {}
bar(int, f32) //no enum
```

**Comment by awwdev** [comment]
I will close this Issue because it no longer triggers the compiler assertion but builds+runs fine.
Tested with `dev-2022-05:d1fc9d30`.

**Comment by gingerBill** [comment]
@awwdev Thank you for closing loads of things!
