### ISSUE TITLE
Passing `any`s between host/library bounds

### ISSUE THREAD

**Issue by alichay** [odin-lang/Odin#113]
When an Odin program passes an `any` to a library (also written in Odin), that any is unusable.

My guess is that this happens because the `Type_Info` contained within the `any` is a pointer to a value in the host application, whereas the Library is comparing that pointer to *its* pointers.

-----------------------

This is a difficult problem, but I believe I have an idea how to fix it.

The proposal is to include an array of type hashes, and when an any or union is received in an `#export` proc or when it's returned from a `#foreign` or dynamically loaded proc, it should search the hash table and remap the type_info if possible.

It's not a great solution, but this is a hard problem to solve.

**Comment by bpunsky** [comment]
I think all you really need is to determine type equivalency via a hash rather than by pointer. Rather than `type_info_of(string) == any_value.type_info`, `type_hash_of(string) == any_value.type_info.hash`.

If `match` and type assertions used this, you should be able to pass `any` and `union` into a DLL and have things still work.

**Comment by bpunsky** [comment]
I also think this is useful for more than just passing `any`s into a dynamic library. It also allows you to serialize types - you can pass a type around, in a saved file, across the network, between processes, etc. This would be a no-go with the current system of using pointers, obviously. An even bigger problem - `any` won't work across *static* library boundaries either.

**Comment by gingerBill** [comment]
This issue entirely depends on _iff_ any type containing `^Type_Info` should be passed across library boundaries at all. I would personally prefer if the vast majority of Odin applications were statically built (or self contained).

This might mean that `union`s cannot store a `^Type_Info` but just an integer specifying which type it is (like it was previously). Getting the `^Type_Info` should not be difficult but it would not be a simple data access.

**Comment by gingerBill** [comment]
For `union` I have now made it so that the variant type is stored as an integer rather than storing the type information. This will allow for a `union` to be passed across a library boundary if needed.

**Comment by bpunsky** [comment]
This is an interesting fix. Too bad it won't work for `any`. Is there currently a way to get the `^Type_Info` from `union` types?

Also, working with static/dynamic libraries is just one of the upsides of the hash fix. It affords a lot of flexibility with (de)serialization, passing info between processes or over the wire, and probably a bunch of things I haven't even thought of. Personally, to me, it also feels more *correct* in that comparing the pointers feels sort of hacky, although it works just fine in a limited set of circumstances.

Even with your own libraries/packages, you *still* would need to change the way type equivalency is determined to avoid this problem, unless no precompiled code is used.

**Comment by bpunsky** [comment]
I think hashing the type name (and packing etc) and the type name and identifier of every field would be a perfect fix. It would allow the exact same type in different files to be equivalent, but since it's exactly the same right down to the name, I don't see the harm. It would also be at compile time, so performance isn't a non-issue but it's not a bloated feature either.

```Foo :: struct #packed #align 16 {
    x, y, z: f32,
    name: string,
}```

rough pseudocode to hash `Foo`:

```hs := FNV64_State{};

hash.fnv64_partial(&hs, "Foo");
hash.fnv64_partial(&hs, "struct #packed #align 16");
hash.fnv64_partial(&hs, "x");
hash.fnv64_partial(&hs, "f32");
hash.fnv64_partial(&hs, "y");
hash.fnv64_partial(&hs, "f32");
hash.fnv64_partial(&hs, "z");
hash.fnv64_partial(&hs, "f32");
hash.fnv64_partial(&hs, "name");
hash.fnv64_partial(&hs, "string");

final := hs.result;```

There's probably a better way to do it, but it's at least possible this way.

**Comment by H-225** [comment]
​@bpunsky
Comparing pointers is fast and simple, not hacky. Where'd you get that from?

**Comment by gingerBill** [comment]
@bpunsky The type information for the union's variants can be in the type information of the union. See fmt.odin for more examples.

But as @H-225 has said, comparing pointers is not hacky. It's the correct way since a different pointer will refer to a distinct type.
```
My_Int :: int;
assert(My_Int != int);
assert(type_info_of(My_Int) != type_info_of(int));
```

**Comment by gingerBill** [comment]
I should also note, that hashing a "type" is not as easy as you may think. I have recently added most of the functionality in `types.odin` so you can manually compare to see if two `^Type_Info` are identical (`are_types_identical`). This procedure is very very similar to how it is done in the compiler.

**Comment by bpunsky** [comment]
The biggest problem I see is the recursion. That could make the hashing costly at compile time for complex types. However, once the hash is done, that could be used to compare types instead of whatever the compiler equivalent of `types.are_types_identical` is, which could end up being a net win for performance.

**Comment by Tetralux** [comment]
All you'll actually do by using hashes is to require more processing power to compute whether two types are the same.
In both cases, it comes down to two values that are either the same or they aren't. Pointers in one case, (which won't change throughout the life of a program) and integers in the other (that won't change unless the structure of the type is changed.)

**Comment by Tetralux** [comment]
Whoops! Posted it before I was done writing! 😛
