### ISSUE TITLE
`lstat` is not working correctly for OSX

### ISSUE THREAD

**Issue by rasa-silva** [odin-lang/Odin#1142]
## Context

The call to `_lstat` is given wrong values for the `OS_Stat` struct, in particular the `mode` field.

* Operating System: OSX 10.15
* Please paste `odin version` output: `odin version dev-2021-09:d4f5ef04`

**Comment by 0800LTT** [comment]
@rasa-silva can you provide a small repro program?

It would be great to see what values you expected to get and which ones you actually do.

**Comment by rasa-silva** [comment]
```odin

walk_proc :: proc(info: os.File_Info, in_err: os.Errno) -> (err: os.Errno, skip_dir: bool) {
	fmt.printf("visiting %s, error: %s", info, in_err)
	return 0, false
}

main :: proc() {
	filepath.walk("<some-dir>", walk_proc)
}
```

will report `is_dir = false` on the root dir.

**Comment by rasa-silva** [comment]
Working after the merged PR.
