### ISSUE TITLE
Support LLVM bitcode files in the foreign system for LTO oppertunities with 3rd party code.

### ISSUE THREAD

**Issue by JesseRMeyer** [odin-lang/Odin#1169]
If the foreign system understands LLVM bitcode files, then *any* library compiled by LLVM to LLVM bitcode will be ready for LTO opportunities in Odin programs (I don't know what the ABI implications are for non C libraries).  Zig already provides native, out of the box LTO for Zig and C code together, but through the foreign system, Odin's reach would extend much further by comparison.

For example:
`foreign import lib "../lib/stb_image_resize.bc"`

This feature would, naturally, be conditional on the LLVM backend.

**Comment by JesseRMeyer** [comment]
Implementing this should be fairly straight forward since I expect all that really needs to happen is for the compiler to feed the linker a file '.bc' file..  Just a matter of priorities.

**Comment by gingerBill** [comment]
Is this actually useful?

**Comment by JesseRMeyer** [comment]
Maybe, here are two situations to consider:
* .bc would afford Odin essentially LTO=thin for packages built by *any* language targeting LLVM bitcode.  Including itself.
* May interact favorably with `-use-separate-modules`.
