### ISSUE TITLE
Error on unused variable without -vet

### ISSUE THREAD

**Issue by khvorov45** [odin-lang/Odin#1172]
## Context

* windows 10
* odin version dev-2021-09:d2aa6af8

## Expected Behavior

Expected not passing `-vet` to allow unused variables. 

## Current Behavior

Error on unused variable when it's under an `if` statement.

### Steps to Reproduce

Code in `test.odin`

```odin
package test

main :: proc() {
    x := 1
    if x == 1 {
        y := 2
    }
}
```

Compiled with

```
odin build test.odin
```

### Failure Logs

```
test.odin(6:9) 'y' declared but not used
```

**Comment by gingerBill** [comment]
Not a bug and completely intended. 

This is prevent a common mistake when declaring something in a block only when it's the only statement.
