### ISSUE TITLE
Fix Map RTTI formatting

### ISSUE THREAD

**Issue by Skytrias** [odin-lang/Odin#1174]
## Context

* Operating System: Linux Mint 20 - Kernel 5.4.0-73-generic
* Please paste `odin version` output: `odin version dev-2021-09:4cb7f056`

## Expected Behavior

Format map content correctly per RTTI

## Current Behavior

Looks like [map formatting](https://github.com/odin-lang/Odin/blob/master/core/fmt/fmt.odin#L1703) is broken right now
Try replacing the i8 / u8 with different types and it will print bad results, even though the map content is valid

```go
test: map[i8]u8 = {
    0 = 1,
    1 = 2,
}
fmt.println(test)
```
prints
`map[76=76, 76=76]`

### Steps to Reproduce

```go
test: map[i8]u8
fmt.println("before", test)
test[i8(0)] = u8(1)
test[i8(1)] = u8(2)
fmt.println("after", test)

for key, value in test {
    fmt.println("key", key, "value", value)
}
```

prints

```go
before map[]
after map[76=76, 76=76]
key 0 value 1
key 1 value 2
```

other example

```go
test: map[string]f32
fmt.println("before", test)
test["test"] = 1
test["asd"] = 2
fmt.println("after", test)

for key, value in test {
    fmt.println("key", key, "value", value)
}
```
prints
```
before map[]
after map[=-100885748010033639349202582570532864.000, =-1027799040994726035587072.000]
key test value 1.000
key asd value 2.000
```

**Comment by Kelimion** [comment]
odin version dev-2021-09:21b6ef87

I can replicate the first example. The second example crashes for me.
```
before map[]
after map[76=76, 76=76]
key 0 value 1
key 1 value 2
before map[]
after map[      <- crashes here
```

**Comment by Kelimion** [comment]
Found the offending commit, also asserts on that minrep. Can you confirm this, @Skytrias?
```cpp
W:\Odin>git bisect bad
fb8fa5217d4a5081dacc0a74a786cd2efc964fdb is the first bad commit
commit fb8fa5217d4a5081dacc0a74a786cd2efc964fdb
Author: gingerBill <bill@gingerbill.org>
Date:   Mon Sep 13 00:58:39 2021 +0100

    Begin minimize `Type` size by replacing `Array` with `Slice` etc

 src/array.cpp                | 13 +++++++++++
 src/check_builtin.cpp        | 32 +++++++++++++-------------
 src/check_expr.cpp           | 36 +++++++++++++++++++----------
 src/check_type.cpp           | 55 +++++++++++++++++++++++---------------------
 src/checker.cpp              | 39 +++++++++++++++++--------------
 src/llvm_backend.cpp         |  6 ++---
 src/llvm_backend_const.cpp   |  4 ++--
 src/llvm_backend_expr.cpp    |  8 +++----
 src/llvm_backend_general.cpp |  2 +-
 src/llvm_backend_proc.cpp    |  4 ++--
 src/llvm_backend_stmt.cpp    |  6 ++---
 src/llvm_backend_type.cpp    |  4 ++--
 src/types.cpp                | 48 ++++++++++++++++++++------------------
 13 files changed, 147 insertions(+), 110 deletions(-)
```

**Comment by gingerBill** [comment]
@Kelimion How do you get that assert?

**Comment by Kelimion** [comment]
> @Kelimion How do you get that assert?

On commit fb8fa5217d4a5081dacc0a74a786cd2efc964fdb, `odin run . -vet -strict-style` on:

```odin
package test

import "core:fmt"

main :: proc() {
	test: map[i8]u8
	fmt.println("before", test)
	test[i8(0)] = u8(1)
	test[i8(1)] = u8(2)
	fmt.println("after", test)

	for key, value in test {
	    fmt.println("key", key, "value", value)
	}

	test2: map[string]f32
	fmt.println("before", test2)
	test2["test"] = 1
	test2["asd"] = 2
	fmt.println("after", test2)

	for key, value in test2 {
	    fmt.println("key", key, "value", value)
	}
}
```

**Comment by gingerBill** [comment]
@Kelimion But does this assert happen on HEAD? If not, this is kind of a useless bug since it was most likely fixed. And the current bug is something else

**Comment by Kelimion** [comment]
> @Kelimion But does this assert happen on HEAD? If not, this is kind of a useless bug since it was most likely fixed. And the current bug is something else

The assert doesn't happen on `HEAD`. But this is the commit the map print bug was introduced. I figured the assert might be useful.

**Comment by gingerBill** [comment]
I think I know what the bug is now, and that's an interesting bug.

**Comment by gingerBill** [comment]
So the bug is that the `offsets` array in the underlying struct type for the map is not getting set correct for whatever reason.
