### ISSUE TITLE
typeid_of(type_of(nil)) - panic

### ISSUE THREAD

**Issue by awwdev** [odin-lang/Odin#1180]
Odin `dev-2021-09:809b3a87`
Windows

```odin
bug := typeid_of(type_of(nil))
```
`Odin\src\llvm_backend_type.cpp(12): Panic: NOT FOUND lb_type_info_index untyped nil @ index -1`

**Comment by awwdev** [comment]
With Odin version `dev-2022-05:d1fc9d30` the following ICE is produced:
```
Internal Compiler Error: Type_Info for 'untyped nil' could not be found
```

**Comment by Kelimion** [comment]
Still present: `Internal Compiler Error: Type_Info for 'untyped nil' could not be found`.

**Comment by jrfondren** [comment]
I think this is probably a very similar error:

```odin
package main

import "core:fmt"

main :: proc() {
	x : Maybe(type_of(nil)) = nil
	fmt.println(x)
}
```

Crashing with

```
Odin/core/runtime/core_builtin.odin(6:29) Invalid type definition of untyped nil
src/types.cpp(3500): Assertion Failure: `is_type_typed(t)` 
Illegal instruction (core dumped)
```
