### ISSUE TITLE
creating a parametric struct with mismatched parameter count

### ISSUE THREAD

**Issue by awwdev** [odin-lang/Odin#1184]
Odin `dev-2021-09:b3dc3f59`

```odin
Foo :: struct($A: typeid) {}
foo: Foo(int, f32, 123, rawptr, nil, ODIN_DEBUG) //mismatch
fmt.println(foo)
```
should be a syntax error, but the compiler does not report an error
instead compilation stalls and never finishes

**Comment by awwdev** [comment]
Still a problem in `dev-2022-12:1d6f7680`.
Please reopen.

**Comment by rick-masters** [comment]
I'm submitting a PR which I believe fixes this and related issues.

The following code reproduces a variety of errors if too many parameters are passed to a polymorphic record type:

```
package main

main :: proc() {
    Foo :: struct($A: typeid) {}

    bar: Foo(i32, 1, 1, 1, 1) = {};
    // stalls and never finishes with odin built debug

    // bar: Foo(int, 1, 1, 1, 1, 1)
    // munmap_chunk(): invalid pointer

    // bar: Foo(int, f32, 1, 1, rawptr, ODIN_DEBUG)
    // free(): invalid pointer

    // bar: Foo(A = int, A = int);
    // src/array.cpp(61): Assertion Failure: `cast(usize)index < cast(usize)count` Index 1 is out of bounds ranges 0..<1

    // ^ IMPORTANT: you may need to move the uncommented line above the other commented out lines
    // to get the exact error.
}
```

Note that these problems were reproduced using a debug version of odin.
A release build may act somewhat differently but it still won't work.

See the PR for details of the fix.
