### ISSUE TITLE
Undefined symbols for architecture x86_64 - Mac Os

### ISSUE THREAD

**Issue by DHunte** [odin-lang/Odin#1185]
## Context

When trying to compile a shared library using :

`package main
import "core:runtime"
import "core:strings"

@export mainCall :: proc "c" (a, b: cstring) -> () {
    context = runtime.default_context();
}`

`odin build main.odin -build-mode:shared`

* Operating System: Mac Os - Big Sur
* Please paste `odin version` output: odin version dev-2021-09-nightly:b2cf0755

## Expected Behavior

Expected the program to compile and produce a shared library.

## Current Behavior

Produces the following error:

`Undefined symbols for architecture x86_64:
  "__$startup_runtime", referenced from:
     -init command line option
     (maybe you meant: ___$startup_runtime)
ld: symbol(s) not found for architecture x86_64`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Compile the code listed above on mac os.

**Comment by weshardee** [comment]
https://github.com/odin-lang/Odin/pull/1379 should address this issue

**Comment by DHunte** [comment]
Thanks for the update. I will test as soon as possible and update the status of this ticket if its resolved.

**Comment by DHunte** [comment]
Tested the commit and works fine for me and can finally build the shared libraries I was looking for. Thanks.
