### ISSUE TITLE
Add `intrinsics.likely` and `intrinsics.unlikely`

### ISSUE THREAD

**Issue by Kelimion** [odin-lang/Odin#1190]
We have:
```odin
// Compiler Hints
expect     :: proc(val, expected_val: T) -> T ---
```

Please consider adding:
```odin
expect_not :: proc(val, expected_not_val: T) -> T ---
likely     :: proc(is_likely: bool) -> bool
unlikely   :: proc(is_unlikely: bool) -> bool
```
`unlikely` can be used in practice as `likely(!test)`, but for code readability I'd suggest adding both. 

Where `likely` and `unlikely` pass through the bool they're given, such that:
```odin
if foozle(1) && unlikely(barzle == baz) {

}
```
Is equivalent to the below, except for telling the compiler the branch is unlikely.
```odin
if foozle(1) && barzle == baz {

}
```

**Comment by krux02** [comment]
Not sure about the usefulness of `expect_not` as you can always write `expect(<expr>, !value)`, can't you?

**Comment by Kelimion** [comment]
> Not sure about the usefulness of `expect_not` as you can always write `expect(<expr>, !value)`, can't you?
> 
> You get my full support for `likely` and `unlikely`.

No, `!value` only works for booleans. You couldn't express `expect_not(val, 42)` like that.

**Comment by Kelimion** [comment]
Maybe add `likely` and `unlikely` as builtins (so you don't have to import `intrinsics`) and add a deprecation tag to `intrinsics.expect`.

**Comment by Robert42** [comment]
I think it might make sense to add empty implementations of `likely`/`unlikely`

```odin
likely :: #force_inline proc(x: bool) -> bool {return x}
unlikely :: #force_inline proc(x: bool) -> bool {return x}
```

This would allow manually hinting branches in the code as preparation for the day, when this actually gets actually properly implemented.
