### ISSUE TITLE
Compiling for target `freestanding_wasm32` results in an assertion

### ISSUE THREAD

**Issue by thebirk** [odin-lang/Odin#1200]
## Context
* Operating System: Windows 10 21H1, x64
* Commit: bd1e1c66f3e56ba03fbd18ea1e928a6eb1f90205 

## Failure Information (for bugs)
Compiling for freestanding_wasm32 currently results in some debug prints followed by an assertion.

### Steps to Reproduce

`odin build main.odin -target=freestanding_wasm32 -no-entry-point`

```odin
package main

@export
add :: proc(a, b: i32) -> i32 {
    return a + b
}
```

### Failure Logs

```
[DEBUG] 9007199254740992
int -> 4
G:\Dropbox\bin\odin\src\llvm_backend_const.cpp(335): Assertion Failure: `sz >= max_count` max_count: 7, sz: 4, written: 0  
```

**Comment by phillvancejr** [comment]
Same for OSX 10.13

**Comment by phillvancejr** [comment]
@thebirk the newest builds are working for me on Mac for both feestanding_wasm32 and js_wasm32, try again with a new version of the compiler
