### ISSUE TITLE
Ability to assign a global variable to be stored in `.rodata` section

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#1244]
Ability to assign a global variable to be stored in `.rodata` section of the executable. 

This will be achieved with an attribute (name undecided yet). It will most likely make the variable `private` to the package too by default since that thing it will be making private will most likely only be used by the package.

An important use case for this is for security purposes, especially with the new `core:crypto`.

**Comment by Tetralux** [comment]
This can currently be achived using:
```odin
// On Unixes:
@(link_section=".rodata")
my_global := "Hello, World"

// Or on Windows:
@(link_section=".rdata")
my_global := "Hello, World!"
```
However, there exists no way to just say "I want this to be read-only."
So you'd have to use `when` in some form in order to conditionally pick the section name accordingly.
