### ISSUE TITLE
Another issue with nested struct initialization

### ISSUE THREAD

**Issue by brokenbeta** [odin-lang/Odin#125]
The issue is that the number 32 does not make it into the struct, which trips the assert.

    import "core:fmt.odin"
    
    Attributes :: struct
    {
        colour: u32,
        number: int
    }
    
    Thing :: struct
    {
        char: u8,
        attributes: Attributes
    }
    
    main :: proc()
    {
        attributes := Attributes { 0x0, 0 };
    
        rtc := Thing { 32, attributes };
        assert(rtc.char == 32);
    }

**Comment by gingerBill** [comment]
This bug is absolutely weird. The LLVM code _should_ initialize it with constant values: 
```llvm
store %demo-0.Thing {%demo-0.Attributes zeroinitializer, i8 32}, %demo-0.Thing* %2
```
However, it doesn't seem to store it the `char` parameter.

**Comment by gingerBill** [comment]
This seems to have been fixed.
