### ISSUE TITLE
Optimization failure in `strings.count` at `-o:speed`.

### ISSUE THREAD

**Issue by Kelimion** [odin-lang/Odin#1250]
## Context

* Operating System: Windows 10
* Please paste `odin version` output: odin version dev-2021-10:ef29ffeb

## Expected Behavior

Not to crash when compiled when optimized for speed.

## Failure Information (for bugs)

Crashes on line  https://github.com/odin-lang/Odin/blob/70793236abc278dd51ca577b35ca1757851380d3/core/strings/strings.odin#L578

It goes away when marking `strings.count` as `force_no_inline`.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

```odin
package test

import "core:fmt"
import "core:os"
import "core:strings"

main :: proc() {
	file, ok := os.read_entire_file("./test.txt")
	assert(ok)

	fmt.printf("len(file): %v\n", len(file))
	lines := strings.split(string(file), "\n")
	fmt.printf("%v\n", len(lines))

	delete(file)
	delete(lines)
		
	return
}
```
`odin run .` outputs the file length and line count.
`odin run . -opt:2` or `odin run . -o:speed` output only the file length and crash in `strings.count` as called from `strings.split` while determining the line count.

**Comment by hinkg** [comment]
This no longer seems to be an issue in `odin version dev-2021-12-nightly:9f0a30e3`? Unsure when it was fixed but the test program and other uses of `strings.split()` now work without any issues for me.
