### ISSUE TITLE
core/crypto/blake: Test failures when built with optimization

### ISSUE THREAD

**Issue by Yawning** [odin-lang/Odin#1274]
## Context

Odin: dev-2021-11:ee259e42
OS:   Fedora Linux 35 (Workstation Edition), Linux 5.14.15-300.fc35.x86_64
CPU:  11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
RAM:  15699 MiB

## Expected Behavior

The core/crypto tests pass when optimization is enabled.

## Current Behavior

The BLAKE variant tests (and possibly others) fail.

### Steps to Reproduce

Run the core/crypto tests with `-o:speed`.

### Failure Logs

```
Your branch is up to date with 'upstream/master'.
alesia :: tests/core/crypto ‹master*› % odin test . -o:speed                                                         
[Package: test_core_crypto]
[Test: test_blake2b]
/home/yawning/Documents/Development/Odin/tests/core/crypto/test_core_crypto.odin(739:9): Expected: 786a02f742015903c6c6fd852552d272912f4740e15847618a86e217f71f5419d25e1031afee585313896444934eb04b903a685b1448b755d56f701afe9be2ce for input of , but got 744edde1e51a71240000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 instead
/home/yawning/Documents/Development/Odin/tests/core/crypto/test_core_crypto.odin(739:9): Expected: a8add4bdddfd93e4877d2746e62817b116364a1fa7bc148d95090bc7333b3673f82401cf7aa2e4cb1ecd90296e3f14cb5413f8ed77be73045b13914cdcd6a918 for input of The quick brown fox jumps over the lazy dog, but got 69ee096708d0c23c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 instead
[test_blake2b : FAILURE]
[Test: test_blake2s]
/home/yawning/Documents/Development/Odin/tests/core/crypto/test_core_crypto.odin(758:9): Expected: 69217a3079908094e11121d042354a7c1f55b6482ca1a51e1b250dfd1ed0eef9 for input of , but got 85a7df0c00000000000000000000000000000000000000000000000000000000 instead
/home/yawning/Documents/Development/Odin/tests/core/crypto/test_core_crypto.odin(758:9): Expected: 606beeec743ccbeff6cbcdf5d5302aa855c256c29b88c8ed331ea1a6bf3c8812 for input of The quick brown fox jumps over the lazy dog, but got 5534d7ab00000000000000000000000000000000000000000000000000000000 instead
[test_blake2s : FAILURE]
[Test: test_blake_224]
/home/yawning/Documents/Development/Odin/core/crypto/blake/blake.odin(697:28) Invalid slice indices: 6363392:64:64
```

**Comment by Gohryt** [comment]
seems like error from ols

**Comment by Yawning** [comment]
This has to do with how the context stuff is implemented, along with LLVM trying to be clever.  Using groestl as an example.

Looking at `_create_groestl_ctx`, `_hash_impl.internal_ctx` is type `any` (reference type).  The assignment of a literal allocates a `Groestl_Context` on the current stack frame.  The stack gets unwound, so as far as LLVM is concerned, the reference is dangling on return from `_create_groestl_ctx`.  Since no read accessed were made through the reference before returning from `_create_groestl_ctx`, the store is a no-op, and is eligible for pruning via DSE.

Since `_create_groestl_ctx` is annotated with `#force_inline` there is arguably a disconnect between LLVM's lifetime tracking and how this "should" behave.  If the function is *always* inlined, it could be argued that the scope of the reference should extend till when the caller returns, since that's when the stack frame that contains the `any` literal gets invalidated.

While I personally am inclined to agree with LLVM here (and would argue for defining the Odin behavior to be that "stack allocations do not survive past the return of a function, even if the function is annotated `#force_inline`"), this is a project maintainer level decision.

Steps from here:
 * Use heap allocations for `_hash_impl.internal_ctx` or rethink the internals here.
 * Long term figure out how stack allocations and `#force_inline` should interact.
 * Wire in LLVM's ASAN, which can catch things like this (https://github.com/google/sanitizers/wiki/AddressSanitizerUseAfterScope)

**Comment by zhibog** [comment]
The context switching stuff is now gone from core. The issue with opt has also been addressed.

**Comment by Yawning** [comment]
The latest changes fix the issues for me, thanks!
