### ISSUE TITLE
-opt: > 0 causes undefined output in demo.odin matrix section.

### ISSUE THREAD

**Issue by JesseRMeyer** [odin-lang/Odin#1282]
Calling `odin run demo.odin -opt:1` will showcase the 3rd column output of the y matrix to vary wildly between runs.

Run 1
`
y matrix[1.000, 5.000, 1160280648225464447327216967075076505.000, 1160281713051968639039914221556989950.000; 2.000, 6.000, 0.000, 0.000]
`

Run 2
`y matrix[1.000, 5.000, -119665009363682761706120193695333482490.000, -119665145661475298245345429954488172540.000; 2.000, 6.000, 0.000, 0.000]
`

`odin report`:

```Odin: dev-2021-11
OS:   Windows 10 Home Basic (version: 21H1), build 19043.1320
CPU:  Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
RAM:  32717 MiB

**Comment by gingerBill** [comment]
This should now be fixed in the latest commit
