### ISSUE TITLE
Parapoly union with 2 typeid as parameters results in compilation error

### ISSUE THREAD

**Issue by Sharundaar** [odin-lang/Odin#1313]
## Context

I'm trying to more or less reproduce the Result pattern of Rust using unions, for this I'm trying the following code :
```
package main

Result :: union( $OkType, $ErrorType: typeid ) { OkType, ErrorType }

main :: proc() {

}
```
This results in a compiler error that's not very helpful, reading the documentation it looks to me that it should be legal code.

* Operating System & Odin Version:
        Odin: dev-2021-11:fc920a63
        OS:   Windows 10 Professional (version: 21H1), build 19043.1348
        CPU:  Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
        RAM:  16346 MiB

## Expected Behavior

I'm expecting a parapoly union with 2 parametrized types

## Current Behavior

I'm getting the following compiler error :
```
> C:\Home\Odin\odin build main.odin
C:/Home/Workspace/Odin/ResultIssue/main.odin(3:58) Duplicate variant type 'type'
```

## Repro steps
1. Create a new folder and add a main.odin inside
2. Push code above in main.odin
3. compile with `odin build main.odin` 
4. see error

**Comment by Naboris** [comment]
From my understanding, the key information you've missed in the documentation was

```
...
// runtime type information specific type
typeid
any
```

**Comment by jrfondren** [comment]
This works:

```odin
package main

import "core:fmt"

Ok :: struct($T: typeid) {
    _: T,
}
Err :: struct($T: typeid) {
    _: T,
}

Result :: union($T, $U: typeid) {
    Ok(T),
    Err(U),
}

main :: proc() {
    t : Result(int, string) = Ok(int){5}
    fmt.println(t)
}
```

And having separate types fixes the first problem of $T and $U not being able to be the same type, when that's possible with result types in other languages - `Result<i32, i32>`
