### ISSUE TITLE
No error when dividing by zero

### ISSUE THREAD

**Issue by TatriX** [odin-lang/Odin#1314]
Hi! The language seems to be very interesting!
I'm trying to play with it, and here's what I've found:

## Context
```
package main

import "core:fmt"

foo :: proc(x, y: int) -> int {
      return x / y;
}

main :: proc() {
      fmt.println("got", foo(42, 0));
      fmt.println("mkay");
}
```

* Please paste `odin report` output:
	Odin: dev-2021-11:9be0d18e
	OS:   Arch Linux, Linux 5.14.7-arch1-1
	CPU:  AMD Ryzen 9 3900X 12-Core Processor
	RAM:  32030 MiB

## Expected Behavior
Some kind of error

## Current Behavior
Nothing happens:
```
% time Odin/odin run hello.odin
Odin/odin run hello.odin  0.38s user 0.19s system 107% cpu 0.533 total
```

**Comment by gingerBill** [comment]
It has errored, but it's just causing a hardware exception for the divide by zero. Nothing special.

This behaviour would happen in other similar languages too, such as C.

**Comment by TatriX** [comment]
Right, I see. I was confused, because I have seen this error before:
```
/hello.odin(10:14) Division by zero not allowed
```

Thanks for the clarification!

**Comment by Kelimion** [comment]
> Right, I see. I was confused, because I have seen this error before:
> 
> ```
> /hello.odin(10:14) Division by zero not allowed
> ```
> 
> Thanks for the clarification!

That is likely when you used a constant. In this case you're dividing by a variable that you set to `0`.
