### ISSUE TITLE
strings.split fails when compiled to js_wasm32

### ISSUE THREAD

**Issue by Gaunsessa** [odin-lang/Odin#1323]
Odin version: ```dev-2021-11:daebaa8b```

String split fails when compiled  to js_wasm32:
```odin
strings.split("Hello World", " ")
```
Output:
```/Odin/core/strings/strings.odin(276:7) Index 0 is out of bounds range 0:0 ```

**Comment by gingerBill** [comment]
It fails because there is no allocator set. 

This is not a bug, per se.
