### ISSUE TITLE
Make mutating the same value that is returned, in a defer, an error

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#1325]
### Discussed in https://github.com/odin-lang/Odin/discussions/1324

<div type='discussions-op-text'>

<sup>Originally posted by **Tetralux** November 21, 2021</sup>
```odin
f :: proc() -> int {
	x := 1
	defer x = 99
	return x
}

main :: proc() {
    result := f()
    // what is 'result' ?
}
```
Spoiler: `result == 1`.

 I think this is should be a compile error.
I'm struggling to think of even a single case where this isn't a bug: Mutating the same value that is returned, in a defer statement.

If you internalise that defers run after the return statement, then it might be easier to resolve this in your mind - but I think it's a bit error prone, as it is easy to fall into the trap here. And, more importantly, if you do fall into the trap, it's likely a bugger to debug!

You could also extend this to procedure calls in defers, as well.
```odin
f :: proc() -> int {
	x := 1
	defer g(&x)
	return x
}

g :: proc(ptr: ^int) {
    ptr^ = 101
}
```
Perhaps this can also be an error.

If, when checking procedure bodies, the 'mutability' of parameters is flagged, then detection for this within `f` is trivial:
- `g` writes through its pointer parameter `ptr`
- `&x` is passed to it in the defer; and 
- `x` is returned from `f`.</div>

**Comment by hasenj** [comment]
I think instead of checking for how functions mutate parameters, the compiler can just treat the return variable as a const reference  within the defer block -- the same way it treats input parameters within a procedure body.
