### ISSUE TITLE
Error when enum member name starts with number(s).

### ISSUE THREAD

**Issue by elusivePorpoise** [odin-lang/Odin#1340]
Odin: dev-2021-11-nightly:9f0a30e3
	OS:   Windows 10 Home Basic (version: 20H2), build 19042.1348
	CPU:  11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
	RAM:  7771 MiB

When an enum member name starts with a number, the compiler errors:
```
test :: enum{
 foo, // OK
 foo420, // OK
 420foo, // NOT OK
}
```

**Comment by ThisDrunkDane** [comment]
Identifiers cannot start with numbers so that is correct behavior unless you mean that a compiler assert happens and not a compile error
