### ISSUE TITLE
Fixed array literals in a basic for loop produces unexpected syntax errors

### ISSUE THREAD

**Issue by perplexedMurfy** [odin-lang/Odin#1387]
## Context
* Operating System & Odin Version: 

Odin: dev-2021-12:5752a374
OS:   Windows 10 Home Basic (version: 20H2), build 19042.1415
CPU:  Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
RAM:  32502 MiB

## Expected Behavior

A for loop which contains fixed array literals compiles successfully, ex:
``` Odin
for Value := [2]int{0, 0}; Value != [2]int{10, 10}; Value += [2]int{1, 1} {
	// ...
}
```

## Current Behavior
For loops which contain an array literal like `[2]int{0, 0}` do not compile successfully.
The same loop can be expressed with named constants and it will compile successfully.

## Failure Information (for bugs)
Depending on where the fixed array literal appears in the for loop, different syntax errors are emitted.

### Steps to Reproduce
``` Odin
main :: proc() {

	Init :: [2]int{0, 0}
	Max :: [2]int{10, 10}
	Inc :: [2]int{1, 1}

	// Does compile
	for Value := Init; Value != Max; Value += Inc {
		// ...
	}

	for Value : [2]int = {0, 0}; Value != Max; Value += Inc {
		// ...
	}

	// The following do not compile

/*
	// When compiled in isolation
	// repo.odin(24:26) Syntax Error: Expected 1 expression
	// repo.odin(24:27) Syntax Error: Expected 'boolean expression', found a simple statement.	
	for Value := [2]int{0, 0}; Value != [2]int{10, 10}; Value += [2]int{1, 1} { // This is line 24
		// ...
	}
*/

/*
	// When compiled in isolation
	// repo.odin(33:26) Syntax Error: Expected 1 expression
	// repo.odin(33:27) Syntax Error: Expected 'boolean expression', found a simple statement.
	for Value := [2]int{0, 0}; Value != Max; Value += Inc { // This is line 33
		// ...
	}
*/

/*
	// When compiled in isolation
	// repo.odin(42:36) Syntax Error: Expected ';', got {
	// repo.odin(42:43) Syntax Error: Expected 1 expression
	for Value := Init; Value != [2]int{10, 10}; Value += Inc { // This is line 42
		// ...
	}
*/

/*
	// When compiled in isolation:
	// repo.odin(50:55) Syntax Error: Expected 1 expression
	for Value := Init; Value != Max; Value += [2]int{1, 1} { // This is line 50
		// ...
	}
*/
	
}
```

**Comment by Tetralux** [comment]
This is a known syntax ambiguity.
It cannot know if you want `Value := [2]int` or `Value := [2]int{ ... }`.
`Value := ([2]int{...})` should work though.

**Comment by gingerBill** [comment]
As @Tetralux states, this is not a bug, and solved by wrapping the expression in parentheses.
