### ISSUE TITLE
Compiler crashes with "Assertion Failure: `elem_count == max_count` 1 != 16" when trying to assign invalid value to matrix

### ISSUE THREAD

**Issue by kleeon** [odin-lang/Odin#1398]
## Context

Windows 10. Tried it on dev-2021-11 and the latest commit.

## Expected Behavior

Compiler should probably give me a compile error.

## Current Behavior

Compiler crashes with assertion failure.

## Failure Information

It crashes when I try to assign a list of values smaller than the size of the matrix.

### Steps to Reproduce

```
package main

main::proc() {
  m : matrix[4, 4]int = {1}
}
```

### Failure Logs

```
>odin build test.odin
C:\Program Files\Odin\src\llvm_backend_const.cpp(1047): Assertion Failure: `elem_count == max_count` 1 != 16
```

**Comment by gingerBill** [comment]
This is a frontend bug, I think, even if this error is from the backend.  

The error should be that code should not be allowed since a `matrix[4, 4]int` requires 16 elements in the compound literal.
