### ISSUE TITLE
Panic when setting context's user_data or user_ptr to nil

### ISSUE THREAD

**Issue by WalterPlinge** [odin-lang/Odin#1408]
## Context

Odin: dev-2022-01:1d1d684c
OS:   Windows 10 Professional (version: 21H1), build 19043.1415
CPU:  AMD Ryzen 5 5600X 6-Core Processor
RAM:  16294 MiB

## Expected Behavior

No LLVM backend panic on compilation

## Current Behavior

LLVM backend panic on compilation

## Failure Information (for bugs)

Error when setting `context.user_data = nil`:
```
<path to odin>\src\llvm_backend_type.cpp(12): Panic: NOT FOUND lb_type_info_index Context @ index 163
```

Error when setting `context.user_ptr = nil`:
```
main.main
lb_emit_conv: src -> dst
Not Identical Context != rawptr
Not Identical struct {allocator: Allocator, temp_allocator: Allocator, assertion_failure_proc: Assertion_Failure_Proc, logger: Logger, user_data: any, user_ptr: rawptr, user_index: int, _internal: rawptr} != rawptr
Not Identical 20797260660 != 7ff7acb448b8
Not Identical 207972606e0 != 7ff7acb448b8
<path to odin>\src\llvm_backend_expr.cpp(2097): Panic: Invalid type conversion: 'Context' to 'rawptr'
 for procedure 'main.main'
```

### Steps to Reproduce

```
package main
main :: proc() {
	context.user_data = nil
}
```
```
package main
main :: proc() {
	context.user_ptr = nil
}
```

**Comment by WalterPlinge** [comment]
Just thought I'd update this issue, as there's been a change.
```
Odin: dev-2022-02:23be56af
OS:   Windows 10 Professional (version: 21H1), build 19043.1526
```
Setting `user_data` fails with a different error now:
`Internal Compiler Error: Type_Info for 'Context' could not be found`

**Comment by IanLilleyT** [comment]
I had this problem too. Here's a workaround for anyone else visiting this issue.

```
context.user_ptr = cast(rawptr)nil
```
```
context.assertion_failure_proc = cast(runtime.Assertion_Failure_Proc)nil
```
etc.
