### ISSUE TITLE
Prebuilt ARM(64) binaries

### ISSUE THREAD

**Issue by leapofazzam123** [odin-lang/Odin#1411]
I don't want to build Odin in my ARM64 machine and waste a ton of gigabytes just to build Odin.

**Comment by Platin21** [comment]
? Odin doesn’t take gb’s to build, but requires llvm and opt always.
But yeah can understand why one would rather not build it himself.

Also for what platform do you want to have a build? As it’s pretty difficult right now to get Arm64 machines for windows and or linux and macOS.


If you are on discord i can give you a arm64 binary for macOS.

**Comment by leapofazzam123** [comment]
I want an arm64 binary for Linux (maybe make it static-linked so it works in other Linux distros with different libc like Alpine)

**Comment by Platin21** [comment]
1. I don’t think we support static linking right now also you still need opt and lld which isn’t delivered with odin
2. I don’t think there are arm64 runners for github actions so if you want such a build it basically requires a fast enough arm64 platform to build which doesn’t seem to exist right now.
