### ISSUE TITLE
Problem with shadowing ( -vet ) 

### ISSUE THREAD

**Issue by ghost** [odin-lang/Odin#1440]
## Context
```odin
package is_a_bug

import "core:fmt"

main :: proc()
{
	my_value := 3; 

	{
		my_value := "String";
		fmt.println(my_value);
	}

	fmt.println(my_value);
}
```

* Operating System & Odin Version:
```
	Odin: dev-2022-01:cfbc1a44
	OS:   Arch Linux, Linux 5.16.1-arch1-1
	CPU:  AMD Ryzen 7 3800X 8-Core Processor             
	RAM:  16010 MiB
```
## Expected Behavior

Should throw an error for redeclaration of `my_value`.

## Current Behavior

Odin compiles this with or without the `-vet` flag. Basically if i redeclare a variable in the same scope i get an error so I assumed i should get an error even if it is redeclared it in a inner scope but that's not the case with or without the `-vet` flag.

**Comment by Platin21** [comment]
I think this was already discussed somewhere else. And it doesn’t make a lot of sense to throw an error when you explicitly make a new scope. But that’s a @gingerBill topic. I would understand a warning or hint bug that at the utter most.

**Comment by ab0v3g4me** [comment]
Turns out `-vet` only currently works in case of re-declaring variables of the same type.

**Comment by awwdev** [comment]
here is another finding: `-vet` variable shadowing detection will not work with generic procs

the following will trigger the shadowing error as expected (both type and name match):
```odin
foo :: proc() -> int { return {} }

  bar := foo(); fmt.println(bar)
{ bar := foo(); fmt.println(bar) }
```
`Declaration of 'bar' shadows declaration at line [...]`

however, if you make the proc generic, then it will compile fine and no longer report an error:
```odin
foo :: proc(_: $T) -> int { return {} } //generic

  bar := foo(42); fmt.println(bar)
{ bar := foo(42); fmt.println(bar) }
```
note that the return type of the proc stayed the same (int)
both variables (bar and scoped bar) have matching name and matching type and should therefore trigger the vet shadowing error
