### ISSUE TITLE
Inconsistent Type_Info_Named.pkg value

### ISSUE THREAD

**Issue by thePHTest** [odin-lang/Odin#1460]
## Context

I am running the following snippet on a Named field of types `linalg.Vector3f32` and `glsl.vec3`.
The pkg field of the type `linalg.Vector3f32` is `linalg` while the pkg field of `glsl.vec3` is `math_linalg_glsl`.
I would expect the latter to be `glsl` .

```
if named, named_ok := field.type.variant.(reflect.Type_Info_Named); named_ok {
    write_string(&current_struct_builder, fmt.tprintf(": {}.{},\n",
        fmt.tprint(named.pkg), fmt.tprint(field.type)))
}
```

* Operating System & Odin Version:
 Odin: dev-2022-01:714ab516
        OS:   Windows 10 Home Basic (version: 20H2), build 19042.1466
        CPU:  Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
        RAM:  8055 MiB

## Expected Behavior
Type_Info_Named.pkg contains the string used an the declaration site. In this case just `glsl` rather than `math_linalg_glsl`

**Comment by gingerBill** [comment]
Not a bug. That's the package name itself.
