### ISSUE TITLE
Two failing assertions when taking the pointer to a SOA slice

### ISSUE THREAD

**Issue by kim366** [odin-lang/Odin#1462]
## Context

	Odin: dev-2022-01:763de448
	OS:   Unknown Linux Distro, Linux 5.16.3-arch1-1
	CPU:  Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz
	RAM:  15908 MiB

## Expected Behavior

Assignment to the members of the SOA slice as if it were AOS

## Current Behavior

What is the current behavior?

This gives `src/llvm_backend_utility.cpp(952): Panic: TODO(bill): struct_gep type: ^^#soa[]X, 0`. When using `using` instead, we get the following: `src/llvm_backend_general.cpp(1008): Assertion Failure: 't->kind == Type_Struct && t->Struct.soa_kind != StructSoa_None'`

```odin
package main
main :: proc() {
    X :: struct {a: int}
    xs: #soa[]X
    for x in &xs {
        // using x
        // a = 3
        x.a = 3
    }
}
```

**Comment by cshenton** [comment]
I'm also seeing issues iterating over a mutable soa type when using `soa_zip`. This could be related.

```odin
xs := make([]f32, 100)
ys := make([]f32, 100)
points := soa_zip(x=xs, y=ys)
for p in &points {
    p.x = 1.0
    p.y = 1.0
}
```

Hits the following panic in the compiler:
```
Odin\src\llvm_backend_utility.cpp(952): Panic: TODO(bill): struct_gep type: ^^#soa[]struct {x: f32, y: f32}, 0
```
