### ISSUE TITLE
odinfmt won't build on MacOS

### ISSUE THREAD

**Issue by weshardee** [odin-lang/Odin#1463]
## Context

	Odin: dev-2022-01:965b962b
	OS:   macOS 11.6 Big Sur
	CPU:  Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
	RAM:  32768 MiB

## Expected Behavior

`odin build tools/odinfmt/main.odin` should build.

## Current Behavior

Several core library procedures appear to be undefined for MacOS :

`tools/odinfmt/main.odin(93:5) 'is_file' is not declared by 'os'`
`tools/odinfmt/main.odin(99:5) 'rename' is not declared by 'os'`
`tools/odinfmt/main.odin(102:6) 'remove' is not declared by 'os'`
`tools/odinfmt/main.odin(113:12) 'is_dir' is not declared by 'os'`

**Comment by kim366** [comment]
There are a couple issues with odinfmt in this repo. I have been advised to use odinfmt from ols (https://github.com/DanielGavin/ols/tree/master/tools/odinfmt). We should clarify the status of odinfmt in this repository

**Comment by Platin21** [comment]
Seems like os is missing some calls there let me fix that shouldn't take long..

**Comment by Platin21** [comment]
Already in the makings => #1471 / https://github.com/odin-lang/Odin/pull/1471

**Comment by Platin21** [comment]
@kim366 and @weshardee please check if it works now with this change.

**Comment by Platin21** [comment]
Ok checked it out on arm seems like this also needs to be fixed:

Undefined symbols for architecture arm64:
  "_fdopendir$INODE64", referenced from:
      _os._fdopendir-943 in main.o
  "_readdir_r$INODE64", referenced from:
      _os._readdir-946 in main.o
ld: symbol(s) not found for architecture arm64
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Platin21** [comment]
This is a arm only problem doesn't happen at x64 normally. I tried to add the calls for arm but it seems like it doesn't allow when inside foreign..?

**Comment by Platin21** [comment]
Should be done now tested it on arm64 macOS
