### ISSUE TITLE
Procedure arguments debug info not present

### ISSUE THREAD

**Issue by nico-bb** [odin-lang/Odin#1464]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System & Odin Version:
Odin: dev-2022-01-nightly:763de448
        OS:   Windows 10 Professional (version: 21H2), build 19044.1466
        CPU:  Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
        RAM:  16353 MiB

## Expected Behavior

Procedure arguments debug info showing up correctly when using a debugger

## Current Behavior

None of the arguments show up in the debugger.

**Comment by jasonKercher** [comment]
Can confirm for Linux

**Comment by gingerBill** [comment]
Should be fixed in eac74631ecb74689dbe6bb1e1d07cd15f1fc677a.
