### ISSUE TITLE
Errors when running all_vendor.odin (portmidi): Undeclared name: lib

### ISSUE THREAD

**Issue by shybyte** [odin-lang/Odin#1466]
## Context

	Odin: dev-2022-02-nightly:a04d849e
	OS:   Ubuntu 18.04.6 LTS, Linux 4.15.0-166-generic
	CPU:  Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	RAM:  31935 MiB

## Expected Behavior

`./odin run examples/all/all_vendor.odin` should not output any errors.

## Current Behavior

`./odin run examples/all/all_vendor.odin`  outputs:
```

/home/marco/Downloads/odin/vendor/miniaudio/device_io_types.odin(742:36) Undeclared name: ptr
/home/marco/Downloads/odin/vendor/miniaudio/device_io_types.odin(743:36) Undeclared name: ptr
/home/marco/Downloads/odin/vendor/portmidi/portmidi.odin(45:9) Undeclared name: lib
/home/marco/Downloads/odin/vendor/portmidi/portmidi.odin(118:9) Undeclared name: lib
/home/marco/Downloads/odin/vendor/portmidi/portmidi.odin(139:9) Undeclared name: lib
/home/marco/Downloads/odin/vendor/portmidi/portmidi.odin(233:9) Undeclared name: lib
/home/marco/Downloads/odin/vendor/portmidi/portmidi.odin(300:9) Undeclared name: lib
/home/marco/Downloads/odin/vendor/portmidi/portmidi.odin(463:9) Undeclared name: lib
/home/marco/Downloads/odin/vendor/portmidi/util.odin(50:9) Undeclared name: lib
/home/marco/Downloads/odin/vendor/portmidi/portmidi.odin(81:10) Undeclared name: lib
/home/marco/Downloads/odin/vendor/portmidi/portmidi.odin(93:10) Undeclared name: lib
/home/marco/Downloads/odin/examples/all/all_vendor.odin(1:2) Undefined entry point procedure 'main'
```

I'm interested in using portmidi but after reading these errors I'm afraid, that it won't work correctly.

### Steps to Reproduce

1. `./odin run examples/all/all_vendor.odin`

**Comment by gingerBill** [comment]
This isn't really a "bug" but more of a "Linux is not yet supported for portmidi and miniaudio".

**Comment by shybyte** [comment]
Thank you for your fast reply. And for all your work on Odin of course.
Actually I'm mainly looking for an excuse to learn Odin and accidentally I need some midi tooling for a music project. But implementing this in a language, that I know already, would anyway be faster. Therefore my need for Odin Portmidi Linux support is not crucial.
However:
* Is it planned to support portmidi on Linux in the near future?
* Is there anything I could help with? (Considering that I have zero experience in Odin and only very rusty portmidi knowledge from an old Rust project some years ago, where I used an existing portmidi wrapper.)
* Additionally It might be helpful to mention on https://pkg.odin-lang.org/vendor/ if some packages work only on some operating systems, to avoid confusion.
