### ISSUE TITLE
Compiler doesn't recognize type alias of a type alias as a type

### ISSUE THREAD

**Issue by khvorov45** [odin-lang/Odin#1470]
## Context

Odin: dev-2022-02:abb26e0b
OS:   Windows 10 Professional (version: 21H1), build 19043.1466
CPU:  Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
RAM:  16338 MiB

## Bug

This code
```odin
package temp
INSTANCE_TYPE :: Instance;
Element :: ElementPublic;
Window :: Element;
ElementPublic :: struct {
    window :   ^Window,
}
Instance :: struct {
    window :   ^Window,
}
main :: proc() {}
```
Doesn't compile
```
odin build temp.odin
temp.odin(6:17) 'Window' is not a type
```

**Comment by gingerBill** [comment]
Just fixed this in 3a81f2ab898d537bba51b9ea81e047652112574e
