### ISSUE TITLE
Nested proc + `-debug` cause inifinite recursion in LLVM

### ISSUE THREAD

**Issue by jasonKercher** [odin-lang/Odin#1477]
## Context

I've tried this against LLVM 12 and 13

```
Odin: dev-2022-02:3c2ed3bb
OS:   Arch Linux, Linux 5.15.13-arch1-1
CPU:  Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
RAM:  7833 MiB
```

## Expected Behavior

Program should compile

## Current Behavior

LLVM enters infinite recursion.  Due to tail-call optimization, it never actually crashes. The function that recurses infinitely is `llvm::DebugHandlerBase::getBaseTypeSize`.

## Failure Information (for bugs)

The bug is definitely related to the nested proc + `-debug` option.  If I un-nest that proc in the full project (8000+ loc), the project builds no problem.

### Steps to Reproduce

I have a repository for the bug.  It has 1 file under 30 lines and a tiny package: https://github.com/jasonKercher/compilebug

```sh
git clone https://github.com/jasonKercher/compilebug.git
cd compilebug
odin build ./ -debug
```

Here is the main code:

```odin
package streamql

import "fifo"

main :: proc()
{
	root_fifo_vec := make([dynamic]fifo.Fifo(^Record))

	process: Process
	process_activate(&process, &root_fifo_vec, 0)
	
	for f in &root_fifo_vec {
		fifo.set_size(&f, 1)
	}
}

process_activate :: proc(process: ^Process, root_fifo_vec: ^[dynamic]fifo.Fifo(^Record),  base_size: int) {
	/*** IF THIS IS NOT NESTED, NO BUG ***/
	_new_fifo_root :: proc(root_fifo_vec: ^[dynamic]fifo.Fifo(^Record)) -> ^fifo.Fifo(^Record) {
		return nil
	}
	/***  ***/
	if process.input == nil {
		process.input = fifo.new_fifo(^Record, u16(base_size))
		fifo.advance(process.input)
	}
}

Record :: struct {fields: []string}
Process :: struct {input: ^fifo.Fifo(^Record)}
```

**Comment by JesseRMeyer** [comment]
I think the sync package on your platform has updated since this ticket was submitted.  Would you mind updating the repo?  Thanks.

```
repro/fifo/fifo.odin(11:12) 'Condition' is not declared by 'sync'
repo/fifo/fifo.odin(11:17) 'sync.Condition' is not a type
... (and many more of the same)
```
