### ISSUE TITLE
Casting pointers to slices LLVM issue?

### ISSUE THREAD

**Issue by bumbread** [odin-lang/Odin#1483]
## Context

Trying to build a kernel using Odin. The code I'm trying to compile is the following:

```
package kernel;
import "core:mem";
@(export, link_name="kmain")
kmain :: proc () {
    vga: [^]u8 = cast([^]u8)cast(uintptr)0xb8000; // relevant line of code
    vga[0] = 'h';
    vga[1] = 0x2a;
}
```

Then I'm building it using the following command (bash):

```
odin build kernel -build-mode:obj \
    -disable-assert \
    -no-crt \
    -no-bounds-check \
    -default-to-nil-allocator
```

* Operating System: xubuntu
* Please paste `odin report` output: dev-2021-11:daebaa8b

## Expected Behavior

I want to create a slice (a pointer?) that points to VGA buffer, which has an absolute physical address of 0xb8000 so that I'd be able to address individual bytes of that buffer.

## Current Behavior

The compiler crashes trying to compile my code above. The error message is the following:

```
LLVM CODE GEN FAILED FOR PROCEDURE: kmain
define dllexport void @kmain(i8* noalias nocapture nonnull %__.context_ptr) {
decls:
  %0 = alloca i8*, align 8
  br label %entry

entry:                                            ; preds = %decls
  %1 = bitcast i8* %__.context_ptr to %runtime.Context*
  store i8* null, i8** %0, align 8
  store i0 753664, i8** %0, align 1
  %2 = load i8*, i8** %0, align 8
  %3 = getelementptr i8, i8* %2, i64 0
  store i8 104, i8* %3, align 1
  %4 = load i8*, i8** %0, align 8
  %5 = getelementptr i8, i8* %4, i64 1
  store i8 42, i8* %5, align 1
  ret void
}




Stored value type does not match pointer operand type!
  store i0 753664, i8** %0, align 1
 i8*
```

### Steps to Reproduce

Compile the code as I wrote it above with the build script I provide.

**Comment by gingerBill** [comment]
This is already fixed in master.
