### ISSUE TITLE
Panic on ast.clone

### ISSUE THREAD

**Issue by DanielGavin** [odin-lang/Odin#1503]
## Context

 Odin: dev-2022-02:2a7f9349
        OS:   Windows 10 Home Basic (version: 21H1), build 19043.1526
        CPU:  Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
        RAM:  16234 MiB

Running on branch `odin-ast-changes`

````
import "core:odin/ast"

main :: proc() {
	field := ast.new(ast.Field, {}, {});
	b := ast.clone(field)
}
````

## Expected Behavior

No panic.

## Current Behavior

Panic with `Unhandled node kind: Any_Node`

**Comment by DanielGavin** [comment]
Would be really nice to get this fixed, so we can get closer to merging odin-ast-changes to master.

**Comment by gingerBill** [comment]
Still not fixed, yet.

**Comment by DanielGavin** [comment]
@gingerBill The derived value of the cloned is nil. So something is still wrong.

**Comment by gingerBill** [comment]
This should be fixed already in the latest commit on that branch.

**Comment by gingerBill** [comment]
https://github.com/odin-lang/Odin/blob/2944969ca027f87d278233bb327f12b271522f62/core/odin/ast/clone.odin#L102

**Comment by DanielGavin** [comment]
It's the output of `b := ast.clone(field)`

`fmt.println(b.derived)` is nil.

**Comment by gingerBill** [comment]
@DanielGavin How about now?

**Comment by DanielGavin** [comment]
CI failed. Not sure if you get notifications when it failed, so just letting you know.

**Comment by DanielGavin** [comment]
Seems good now.
