### ISSUE TITLE
tprintf breaks when single curly bracket is used

### ISSUE THREAD

**Issue by WhoAteDaCake** [odin-lang/Odin#1523]
## Context

Odin: dev-2022-02-nightly:edc13c29
OS:   Ubuntu 21.10, Linux 5.13.0-28-generic
CPU:  Intel(R) Pentium(R) Gold G6400 CPU @ 4.00GHz
RAM:  23958 MiB

## Expected Behavior

```odin
package main

import "core:fmt"

main :: proc() {
    fmt.println(fmt.tprintf("Hello {"))
}
```
should print `"Hello {"`

## Current Behavior

Prints `Hello %!(MISSING CLOSE BRACE)`

## Failure Information (for bugs)

Works fine with `fmt.println`

### Steps to Reproduce

Code snippet provided above

### Failure Logs

None

**Comment by Tetralux** [comment]
This is because `core:fmt` will parse and format both C-style `%s` format syntax and Rust-style `{}` syntax.
You can use `{{` to escape it.

**Comment by WhoAteDaCake** [comment]
Oh briliant, thanks :)
