### ISSUE TITLE
Silent parsing failures for string literals

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#153]
```go
using import "core:fmt.odin";
main :: proc() {
	s := "Hello""World";
	println(s);
}
```

Output:
```
Hello     World
```

**Comment by gingerBill** [comment]
I think I might have to disallow this feature (which is borrowed from C) and only allow for the constant binary expressions for string constants.

**Comment by Tetralux** [comment]
For clarity, my particular use case here was that I meant for the two double-quotes in the middle of the string, to be characters _in the string._

It took me some time to figure out that what was happening.
```go
s := "Hello""World";
assert(s[5] == '"'); // false
```

**Comment by ratchetfreak** [comment]
escaping quotes is usually through backslash. That's my first recourse for one

**Comment by Tetralux** [comment]
@ratchetfreak No, I know. I was rather tired at the time... x)
It just took me a while to realise what was happening. Particularly since it give me no error.

**Comment by ThisDrunkDane** [comment]
since `"Hello""World"` seems to have been disallowed, it just says there's a missing `;` now I'm guessing this should be closed?

**Comment by gingerBill** [comment]
I removed this feature in favour of compile time concatenation using `+`
