### ISSUE TITLE
odin shouldn't read os-release file in usr/lib

### ISSUE THREAD

**Issue by panekj** [odin-lang/Odin#1532]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System & Odin Version: Alpine Linux & Odin dev-2022-02:e6a7b85d
* Please paste `odin report` output:
```
 Odin: dev-2022-02:e6a7b85d
 OS:   Unknown Linux Distro, Linux 5.15.16-0-lts
 CPU:  AMD Ryzen Threadripper 1920X 12-Core Processor
 RAM:  15976 MiB
src/gb/gb.h(6096): Assertion Failure: `(fc->data) != NULL` fc->data must not be NULL
fish: Job 1, './odin report' terminated by signal SIGILL (Illegal instruction)
```

## Expected Behavior

`odin report` checks if `/etc/os-release` is a file or a symlink, and reads it if it's a file or follows the symlink otherwise

## Current Behavior

`odin report` reads `/usr/lib/os-release`

https://github.com/odin-lang/Odin/blob/e6a7b85da44e141f170a528321ce02452731a3d4/src/bug_report.cpp#L480

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use OS that doesn't ship `os-release` file in `usr/lib` (e.g. `docker run -ti --rm alpine:edge`)
2. `odin report` shows `Unknown Linux Distro`
3. you get it...

**Comment by Kelimion** [comment]
Thanks! Found and fixed. The crash turned out to be the unconditional deferred freeing of the file contents, so that procedure now just returns if the file contents it's given is of size zero. Additionally, to fix the bug itself, it looks at `/etc/os-release` instead of `/usr/lib/os-release`.

Reading `/etc/os-release` through symlink.
```
Where to find more information and get into contact when you encounter a bug:

        Website: https://odin-lang.org
        GitHub:  https://github.com/odin-lang/Odin/issues


Useful information to add to a bug report:

        Odin: dev-2022-02:e6a7b85d
        OS:   Ubuntu 20.04.3 LTS, Linux 5.4.72-microsoft-standard-WSL2
        CPU:  AMD Ryzen 7 1800X Eight-Core Processor
        RAM:  51363 MiB
```
If `/etc/os-release` symlink or file is broken or doesn't exist:
```
Where to find more information and get into contact when you encounter a bug:

        Website: https://odin-lang.org
        GitHub:  https://github.com/odin-lang/Odin/issues


Useful information to add to a bug report:

        Odin: dev-2022-02:e6a7b85d
        OS:   Unknown Linux Distro, Linux 5.4.72-microsoft-standard-WSL2
        CPU:  AMD Ryzen 7 1800X Eight-Core Processor
        RAM:  51363 MiB
```

**Comment by skoobiii** [comment]
#1532
