### ISSUE TITLE
`filepath.split_list` requires a trailing separator to work.

### ISSUE THREAD

**Issue by FancyKillerPanda** [odin-lang/Odin#1537]
## Context

Occurs on both operating systems.

Odin: dev-2022-02:e6a7b85d
OS:   Ubuntu 20.04.3 LTS, Linux 5.10.60.1-microsoft-standard-WSL2
CPU:  11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
RAM:  12572 MiB

Odin: dev-2022-02:
OS:   Windows 10 Home Basic (version: 21H2), build 19044.1526
CPU:  11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
RAM:  16122 MiB

## Expected Behavior

The output from `filepath.split_list` should contain the last item in the input list even if there is no trailing separator character (`;` on windows or `:` on unix).

## Current Behavior

`filepath.split_list` ignores the last list item. This is problematic because neither `echo %PATH%` (windows) nor `echo $PATH` (linux) supplies a trailing separator.

### Steps to Reproduce

1.
```odin
package main;

import "core:fmt"
import "core:path/filepath"

printf :: fmt.printf;

main :: proc() {
	// For Unix
	printf("{}\n", filepath.split_list("/opt/butler:/home/fancykillerpanda/Projects/Odin/Odin:/usr/local/sbin"));

	// For Windows
	printf("{}\n", filepath.split_list("C:\\Odin;C:\\Visual Studio;\"C:\\Some Other\""));
}
```

2. The output on Windows is `[C:\Odin, C:\Visual Studio]`, but when a trailing `;` is added the output becomes `[C:\Odin, C:\Visual Studio, C:\Some Other]`. Same deal for linux.

**Comment by skoobiii** [comment]
#1537
