### ISSUE TITLE
(rawptr{}) == {} - Internal Compiler Error

### ISSUE THREAD

**Issue by awwdev** [odin-lang/Odin#1540]
## Context
Odin `dev-2022-02:8f13724a`

## Current Behavior
```odin
bug := (rawptr{}) == {}
bug := (rawptr{}) == (rawptr{}) //same error
```
`Internal Compiler Error: match_exact_values: How'd you get here? Invalid ExactValueKind 7`

## Expected Behavior
Successful compilation.

**Comment by gingerBill** [comment]
I think I've fixed this already on the latest commit.

**Comment by awwdev** [comment]
Yes, the code from above compiles now. Thanks!

**Comment by skoobiii** [comment]
#1540
