### ISSUE TITLE
Provide a way to combine nils in error unions

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#1559]
With:
```odin
E :: enum {
    Ok,
    Failure,
}
U :: union {
    E,
}
```
This works fine:
```odin
work :: proc() -> E {
    return .Ok
}
outer :: proc() -> U {
    work() or_return // works as expected; you'll never return .Ok here
    // ...
}
```
But this causes trouble:
```odin
work :: proc() -> U {
    return .Ok
}
outer :: proc() -> U {
    work() or_return // `U(.Ok)` will be early-returned here!!!
    // ...
}
```
It's fixed by doing this instead:
```odin
work :: proc() -> U {
    return nil
}
```
Bill suggested adding `union #shared_nil` which, to quote the man himself:
>  The idea is that when you assign to a union, it will check to see if the value it is assigning is nil or not, and if it is, then it will just zero out the target (to nil). Otherwise, it will assign it as normally.

i.e: normalise `E.Ok` to `U(nil)`; this would mean that this:
```odin
work :: proc() -> U {
    return .Ok
}
```
would become this, in effect [1]:
```odin
work :: proc() -> U {
	if .Ok == nil {
		return nil // In this case, this is the path taken
	} else {
		return E.Ok
	}
}
```
This will mean that `work() or_return` will no longer erroneously early-return.

Normalising to nil upon assignment is likely more efficient than on comparison, since there's only one instance of assigning the value, but potentially many places where `or_return`/comparison is used.

---
[1] This particular example could be constant-folded to avoid the branch, you just imagine the enum is stored in a variable 😛

**Comment by skoobiii** [comment]
E.ok

**Comment by Tetralux** [comment]
This feature was added in 3f935bea2505b3ee7e169a29b7aed50c0e5614b7.
