### ISSUE TITLE
Compiler appears to contradict itself in error messages

### ISSUE THREAD

**Issue by flysand7** [odin-lang/Odin#1593]
First I make `math` package in my game code that imports `core:math`.

```
package math;
import "core:math";
[...]
```

Here's the error message I get (relevant part in bold):

> /home/bumbread/Odin/core/math/math.odin(1:2) Duplicate declaration of 'package math'
>	A package name must be unique
>	There is **no relation between a package name and the directory** that contains it, so they can be completely different
>	A package name is required for link name prefixing to have a consistent ABI

Then, according to the error message, I change the package declaration in my math file to:

```
package gamemath;
```

The error message:

```
/home/bumbread/blocks/math/matrix.odin(1:2) Syntax Error: Different package name, expected 'math', got 'gamemath'
```

So the first error message says that the package name and the containing directory name can be different, but in truth the compiler expects them to be the same. Thus contradiction.

## Expected behaviour

One of:
- Replace the contradictory sentence in the error message for duplicate package
- Allow package name to differ from containing directory name

As a side note I wish you replaced the requirement for the uniqueness of the **package name** with the requirement for the uniqueness of the **namespace name** to which the package gets imported. This goes way better with the purpose of renaming that namespace, which is to prevent collisions of different libraries that export packages with the same names.

## Context

Version: `dev-2022-03:410b85b5`
OS: xubuntu

**Comment by Kelimion** [comment]
The package name *is* allowed to be different from the directory name, but all Odin files in that directory must have the same package name. There's no contradiction.

That you got `/home/bumbread/blocks/math/matrix.odin(1:2) Syntax Error: Different package name, expected 'math', got 'gamemath'` suggests there's another file that hasn't had its `package` updated to `package gamemath`.
