### ISSUE TITLE
-no-crt with -debug causes access violation in default temp allocator on close

### ISSUE THREAD

**Issue by Lperlind** [odin-lang/Odin#1620]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Odin: dev-2022-03:d4ccb69c
OS:   Windows 10 Home Basic (version: 21H2), build 19044.1586
CPU:  AMD Ryzen 7 5800X 8-Core Processor
RAM:  32711 MiB

## Expected Behavior

Nothing to be thrown and the application to exit cleanly

## Current Behavior

When the application is closed an access violation is thrown in ```default_temporary_allocator.odin, line 35```
i.e.
```
default_temp_allocator_destroy :: proc(s: ^Default_Temp_Allocator) {
	if s == nil {
		return
	}
	for ptr in s.leaked_allocations { << access violation here
		free(raw_data(ptr), s.backup_allocator)
	}
	delete(s.leaked_allocations)
	delete(s.data, s.backup_allocator)
	s^ = {}
}
``` 

### Steps to Reproduce

Just compile and run the minimal setup
i.e.
```
package main
main :: proc() { }
```

**Comment by semarie** [comment]
it segfaults at the same place in #1570. are you able to test the diff for workaround it (it requires recompiling odin binary) ?

**Comment by Lperlind** [comment]
Still have the access violation after the patch

**Comment by semarie** [comment]
thanks for testing it. so it might be something else

**Comment by Lperlind** [comment]
Can this be re-opened? The issue is still present.

**Comment by flysand7** [comment]
Does not reproduce with version `dev-2024-07:1770e3a9a`.

@Lperlind can you verify whether the issue still occurs on your end?
