### ISSUE TITLE
Missing return statement at the end of the procedure 'cumsum_inplace'

### ISSUE THREAD

**Issue by cshenton** [odin-lang/Odin#1627]
## Context

Odin: dev-2022-03-nightly:7e5342f4
OS:   Windows 10 Home Basic (version: 21H2), build 19044.1586
CPU:  AMD Ryzen 9 5900HS with Radeon Graphics
RAM:  32160 MiB

## Expected Behavior

`math.cumsum_inplace` should return a value and compile succesfully 

## Current Behavior

Compilation fails since the implementation doesn't return a value.

### Steps to Reproduce

```odin
package main

import "core:math"

main :: proc () {
    n :: 64
    nums := make([]i32, n)

    for num in &nums {
        num = 1
    }

    math.cumsum_inplace(nums)
}
```

### Failure Logs
```
odin-windows-dev-2022-03/core/math/math.odin(1211:1) Missing return statement at the end of the procedure 'cumsum_inplace'
```

**Comment by StanislavNikolov** [comment]
`cumsum_inplace` should not return anything at all. The actual problem is that the procedure has a return type although it shouldn't. This amazingly complex and time consuming pull request has the 5 offending bytes ` -> T` from the source code removed.

**Comment by Kelimion** [comment]
Well spotted. Thanks!
