### ISSUE TITLE
os.args leaks on exit

### ISSUE THREAD

**Issue by graphitemaster** [odin-lang/Odin#1633]
Not really a bug per-se, since `os.args` should stick around the whole application, but it is annoying when using leak checking tools like valgrind to have instances of `os.args` appear as possible leaks. We already cleanup the runtime when returning from main and when calling `os.exit`, I propose freeing `os.args` inside there as well to help filter out these non-leak-leaks.

**Comment by gingerBill** [comment]
So we'd need to add something like the opposite of `@(init)` to the compiler since `os.args` is initialized before `main`.

Another interesting thing is that it's not actually required IF `runtime.args__` is already set.

**Comment by haesbaert** [comment]
> So we'd need to add something like the opposite of `@(init)` to the compiler since `os.args` is initialized before `main`.

Until then, how about freeing it in `os.exit()` for now, it catches most cases where the user aborts and can be added to the end of main.

**Comment by haesbaert** [comment]
PR using `fini` https://github.com/odin-lang/Odin/pull/4680
