### ISSUE TITLE
Invalid struct values with a global variable (repro)

### ISSUE THREAD

**Issue by eeromutka** [odin-lang/Odin#1634]
The following code prints   `thing2  Foo{type = , print = nil, value = 0}`

```
package main

import "core:fmt"

Foo :: struct {
	type: typeid,
	print: proc(),
	value: int,
}

thing1 := Foo{
	type = i64,
	print = proc() {
		fmt.println("hello!")
	},
	value = 36,
}

thing2 := thing1

main :: proc() {
	fmt.println("thing2 ", thing2)
}
```

Odin: dev-2022-03:ae644118
OS:   Windows 10 Home Basic (version: 21H2), build 19044.1526
CPU:  AMD Ryzen 5 5600H with Radeon Graphics
RAM:  16252 MiB

**Comment by IanLilleyT** [comment]
It looks like this got fixed at some point

Now it prints:
```
thing2  Foo{type = i64, print = proc() @ 7FF7A73D65E0, value = 36}
```
