### ISSUE TITLE
Confusing compiler error message

### ISSUE THREAD

**Issue by ftphikari** [odin-lang/Odin#1638]
```odin
package bug2

import win32 "core:sys/windows"

backbuffer: win32.BITMAPINFO

main :: proc() {
	backbuffer.bmiHeader.biSize = size_of(win32.BITMAPINFO.bmiHeader)
}
```

Compiler error:
```
'win32.BITMAPINFO' of type 'BITMAPINFO' has no field 'bmiHeader'
	Suggestion: Did you mean?
		bmiHeader
```

**Comment by awwdev** [comment]
The syntax in your code example is not valid. 
In order to access struct fields you need an **instantiated** struct. 

The following will solve the Issue:
```odin
size_of(win32.Bitmap_Info{}.header) // struct instantiation with {}
````

As side note, you would access "constant fields" of a struct with your syntax.
```odin
Foo :: struct(N: int) {}
num := Foo(42).N
```

However, the compiler error message is highly confusing and should be corrected (so maybe keep this Issue open).

**Comment by ftphikari** [comment]
> However, the compiler error message is highly confusing and should be corrected (so maybe keep this Issue open).

Yes, that is indeed the issue, not my syntax, but the compiler reaction to it.

**Comment by ftphikari** [comment]
Updated code:
```odin
package bug2

import win32 "core:sys/windows"

backbuffer: win32.BITMAPINFO

main :: proc() {
	backbuffer.bmiHeader.biSize = size_of(win32.BITMAPINFO.bmiHeader)
}
```

**Comment by ftphikari** [comment]
With recent commits the error became:
```
Type 'win32.BITMAPINFO' has no field 'bmiHeader'
	... buffer.bmiHeader.biSize = size_of(win32. ...
	                                            ^
```
However it is still wrong.

**Comment by laytan** [comment]
That seems like a correct error message, the type does not have that field. Also looked at the code and it's a deliberately added error message for it (added in 59a601f2cf1f7575662e4e7f1c3cabd079280d0a), so I am considering this fixed.
