### ISSUE TITLE
LLVM wasm instrinsic generation via foreign system error

### ISSUE THREAD

**Issue by JesseRMeyer** [odin-lang/Odin#1657]
The following Odin code:

``` odin
@(default_calling_convention="none")
foreign _ {
    @(link_name="llvm.wasm.memory.grow.i32") grow :: proc(θ, page_count: i32) -> i32 ---
}
```

Produces the following wasm code, when called, instead of the wasm opcode `0x40` for this 'grow' variant:
```wasm
(func $env..llvm.wasm.memory.grow.i32 (;1;) (import "env" "env..llvm.wasm.memory.grow.i32") (param i32 i32) (result i32))
```

Which causes the wasm runtime in Chrome to error with `Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #1 module="env" function="env..llvm.wasm.memory.grow.i32" error: function import requires a callable`.

https://pengowray.github.io/wasm-ops/

I'm not sure if this qualifies as a bug report or a feature request.

**Comment by gingerBill** [comment]
Trying to call an LLVM intrinsic through the foreign system is rarely a good idea. If we need this intrinsic, I can add it directly.

**Comment by JesseRMeyer** [comment]
I should have explained that the only remaining recourse I had to try to get this opcode after finding a few similar examples already in core.  So that this *doesn't* work itself may be indicative of a compiler bug, separate from the need for this particular intrinsic.  There was also some resistance to the idea of adding this intrinsic from an earlier discussion in Discord, but I see no other alternative if first-class memory management in Odin via wasm is a goal.
