### ISSUE TITLE
aliasing maps no longer works

### ISSUE THREAD

**Issue by bpunsky** [odin-lang/Odin#166]
```haskell
import "core:fmt.odin"

Dict :: map[string]string;

main :: proc() {
    dict := Dict{};

    dict["foo"] = "bar";
    dict["why"] = "god";

    for key, val in dict {
        fmt.println("%s: %s\n", key, val);
    }
}
```
```
C:\odin\bin/opt: W:\test2.ll:41:107: error: expected top-level entity
%test2-0.Dict = type {{i64*, i64, i64, %Allocator}, {{%__Map_Key, i64, %..string}*, i64, i64, %Allocator}}*

    ^
```

I expect this has to do with the change to a reference type for maps.

**Comment by gingerBill** [comment]
Oh how do I hate LLVM at times. 
This is an issue with LLVM as it does not like having a named type that is pointer to an anonymous structure e.g.
```llvm
%foo = type {}*
```

**Comment by ThisDrunkDane** [comment]
This seems to work now so I'll close it

**Comment by gingerBill** [comment]
It works now because I reverted back to the map is a struct rather than the experiment of the map is a pointer.
