### ISSUE TITLE
Possible bug with append return value when used directly when indexing

### ISSUE THREAD

**Issue by vassvik** [odin-lang/Odin#168]
Minimal reproduction: 
```go
main :: proc() {
	arr: [dynamic]int;

	when false {
		// Index 0 is out of bounds range 0..0
		i := arr[append(&arr, 0)-1];
	} else {
		n := append(&arr, 0);
		i := arr[n-1];
	}
}
```

**Comment by ThisDrunkDane** [comment]
Still reproducible as of v0.8.1

**Comment by gingerBill** [comment]
One of solving this bug is to just make `append` return nothing at all. This may not be the best solution but it might be a good one in other respects.

**Comment by Kelimion** [comment]
Still reproducible as of 0.9.2.

Having append not return anything might be an okay solution as far as this particular repro case is concerned, as you could also simply set i to be whatever you just inserted, or first set i and then insert that.

**Comment by gingerBill** [comment]
I think return returning anything is actually a better design choice anyway. If you need the length, you can just call `len`
