### ISSUE TITLE
Syntax proposal

### ISSUE THREAD

**Issue by VoOoLoX** [odin-lang/Odin#169]
Here is my proposal for the new syntax.

I know odin is explicit language, but instead of defining everything explicitly why not make syntax more explicit.

So here is more explicit syntax for:
* Enums
* Structs
* Unions
* Structs with polymorphic types
* Procedures

And few features I'd like to see.

* <...> = Optional

* <<...>> = Required

* ... = Body

### Enums
```
Identifier :<enum> = [
	...
]
```
##### Example:
```
EntityType := [
		Player,
		Enemy,
		GameObject,
]
```
### Structs
```
Identifier :<struct> = {
	...
}
```
##### Example:
```
Entity := {
	id : i32,
	hp : f32,
	mp : f32,
}
```
### Unions
```
Identifier :<union> = {[
	...
]}
```
#### In one line
```
Identifier :<union> = {[...]}
```
##### Example:
```
Value := {[i32, f32]}
```
### Structs with polymorphic types
```
Identifier(<<polymorphic arguments>>) :<struct> = {
	...
}
```
##### Example:
```
KeyValuePair(K, V) := {
	key : K,
	value : V,
}
```
### Procedures
```
Identifier :<proc> = (<args>) {
	...
}
```
##### Examples:
```
main := () {
	
}
```
#### Procedures as arguments
```
exec := (f : proc) {
	f();
}
```
#### Procedures with arguments as arguments
```
exec := (f : proc(x: i32), v : i32) {
	f(v);
}
```
#### Procedures with return value as arguments
```
exec := (f : proc -> i32) -> i32 {
	return f();
}
```
#### Procedures with arguments and return value as arguments
```
exec := (f : proc(x: i32) -> i32, v : i32) -> i32 {
	return f(v);
}
```

As a feature I'd like to see string interpolation.

Here is my proposal for string interpolation syntax:
```
bob := "Bob";
```
```
name := `My name is {bob} and my name is {number_of(bob)} characters long`; //Note: using ` not '
```
##### or
```
name := #"My name is {bob} and my name is {number_of(bob)} characters long"; //Something like a preprocessor statement???
```
##### or
```
name := $"My name is {bob} and my name is {number_of(bob)} characters long"; //C# like syntax
```
Also it would be nice to have:

`number_of()` or `count_of()`, it returns number of characters in a string, number of elements in array, number of digits in a number, number of fields in a struct, etc.

And since all primitive types have short names why not change `string` to `str`?

This syntax is shorter, easier to type, more consistent and still pretty explicit in my opinion.

**Comment by gingerBill** [comment]
Short answer: No.

This syntax is inconsistent with itself and ambiguous to parse. 

What you want is not Odin. If you want this new construction, please make your own language.
