### ISSUE TITLE
Streaming (byte at a time) ULEB128 encoder and decoder

### ISSUE THREAD

**Issue by graphitemaster** [odin-lang/Odin#1716]
In byte-oriented streams using the existing ULEB128 encoder and decoder in the `varint` package is really inconvenient since it expects a full buffer of up to `LEB128_MAX_BYTES`. A streaming variant of the encoders and decoders would be faster and more convenient to use in these contexts and can be used to implement the others that already exist via tail-call.

**Comment by Kelimion** [comment]
Added streaming decoder. Encoder to follow.
