### ISSUE TITLE
Sdl2/net binding CheckSockets Timeout should be i32 not u32

### ISSUE THREAD

**Issue by Inch4Tk** [odin-lang/Odin#1724]
Referring to this line here: https://github.com/odin-lang/Odin/blob/939973acd7a8ea17cc9dfda2a55e79dd0109a49c/vendor/sdl2/net/sdl_net.odin#L149
Since negative timeout means wait forever, the timeout should be i32 not u32, as explained in the sdl_net docs:
https://www.libsdl.org/projects/SDL_net/docs/SDL_net_46.html#SEC46

**Comment by codename-irvin** [comment]
@Inch4Tk , interestingly, the documentation you linked lists the input as Uint32. Does it actually work with a value of -1 in C?

**Comment by Inch4Tk** [comment]
Oh, you are right. I didn't even check that, just saw the -1 timeout and assumed. I did not check if -1 will actually work. I assume -1 will just autoconvert to be uint max instead, which is a legal value and would also match the 49 days "joke", kind of stupid of me... Closing this as u32 is correct, sorry.
