### ISSUE TITLE
Assertion bug when aliasing procedure multiple times in a specific way

### ISSUE THREAD

**Issue by ftphikari** [odin-lang/Odin#1738]
## Context

        Odin: dev-2022-04:f92ffe60
        OS:   Windows 10 Unknown Edition (0000007d) (version: 21H2), build 19044.1645
        CPU:  Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz
        RAM:  8086 MiB

## Bug
In this directory structure:
![image](https://user-images.githubusercontent.com/92269215/164113827-f40c2c2c-9771-4c3a-a3e4-90db812f29b2.png)

`alias.odin`
```odin
package alias

import a "alias_pkg"

main :: proc() {
	a.wait_vblank()
}
```

`alias_pkg.odin`
```odin
package alias_pkg

wait_vblank :: _wait_vblank
```

`alias_pkg_windows.odin`
```odin
//+build windows
package alias_pkg

import win32 "core:sys/windows"

_wait_vblank :: win32.DwmFlush
```

When compiling this error happens:
```
Odin\src\llvm_backend_proc.cpp(65): Assertion Failure: `entity->flags & EntityFlag_ProcBodyChecked` DwmFlush :: proc "stdcall" () -> HRESULT
```

**Comment by ftphikari** [comment]
but is still there

**Comment by ftphikari** [comment]
Update: as of 5d39780 this produces a different message:
```
Odin\src\llvm_backend_proc.cpp(72): Panic: DwmFlush :: proc "stdcall" () -> HRESULT (was parapoly: 0 0)
```

**Comment by Beefster09** [comment]
I have seen this bug too. Seems to happen when trying to resolve overloads but I'm not exactly sure what triggers it.
