### ISSUE TITLE
Very strange behavior with optimizations

### ISSUE THREAD

**Issue by bpunsky** [odin-lang/Odin#180]
Making a minimal repro of this is not feasible, so here's the code:

https://github.com/bpunsky/odin-json

and the problem:

https://i.imgur.com/yzVSdsb.gifv

This works just fine on `opt=0`, but any other optimization level causes the `if` seen on the left to trigger. Removing the `panic` seems to stop this from happening for some reason.

I think it's likely that this is a separate issue that is only being *triggered* by optimizations, in that they're changing the LLVM IR in such a way as to trigger the problem and cause the `if` to fire (possibly by overwriting `lexer.errors`).

**Comment by bpunsky** [comment]
This is probably fixed, and the code has changed so much at this point it would hardly even make sense to test it.

I think there was an alignment bug at one point? Or something like that

**Comment by gingerBill** [comment]
I am going to close this bug and if it returns, please create a new issue.
