### ISSUE TITLE
type checker does not check parapoly constness when passing parapoly parameters

### ISSUE THREAD

**Issue by graphitemaster** [odin-lang/Odin#1821]
If you pass a non-const parapoly to a const parapoly or vise-versa, there does not appear to be any type checking. This is just malformed, but if the parapoly parameter happens to be a function then LLVM codegen will fail, as can be seen here
```
Instruction does not dominate all uses!
  %3 = alloca i8 (i64*, i64*, i8*)*, align 8
  %38 = load i8 (i64*, i64*, i8*)*, i8 (i64*, i64*, i8*)** %3, align 8
```

Here's a trivial reproduction
```odin
foo :: proc($x: $X) { x(); }
bar :: proc(x: $X) { foo(x); } // omit constness in parapoly, forward to const
main :: proc() { bar(proc(){}); }
```

**Comment by Kelimion** [comment]
Fixed. Now returns "Expected a constant value for this polymorphic name parameter".
