### ISSUE TITLE
simd.from_array and .to_array causes compiler panic (Linux/macOS)

### ISSUE THREAD

**Issue by kururen** [odin-lang/Odin#1834]
## Context

Odin: dev-2022-06-nightly:ba5f7c4e
OS:   Fedora Linux 36 (Workstation Edition), Linux 5.17.9-300.fc36.x86_64
CPU:  Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
RAM:  7850 MiB

Using from_array or to_array with integer and boolean types causes the compiler to panic with the following error message:
`src/llvm_abi.cpp(813): Panic: Unhandled integer width for vector type`

For float types, the message is different:
`src/array.cpp(13): Assertion Failure: '0 <= index && index < count' Index 2 is out of bounds ranges 0..<2`

## Expected Behavior

Both methods successfully convert from a #simd type to a regular array.

## Current Behavior

Compiler panic / asserts

## Failure Information (for bugs)
Minimal example:
```
package bug

import "core:simd"

main :: proc() {
    data: #simd[64]u8
    arr := simd.to_array(data)
}
```
or
```
package bug

import "core:simd"

main :: proc() {
    arr: [64]u8
    data := simd.from_array(data)
}
```
respectively.

The problem seems to be related to the polymetric parameters used by both procedures, since using transmute(...) directly does not result in a panic. It is independent from the array size used. This also happened while testing on macOS (Catalina).

**Comment by CircArgs** [comment]
Similar error with 

Code:
```Odin
add_vectors :: proc(a, b: simd.f64x4) -> simd.f64x4 {
	return a + b
}

main :: proc() {
	x := add_vectors(simd.f64x4{1, 2, 3, 4}, simd.f64x4{1, 2, 3, 4})
	fmt.print(x)
}
```

Error:
```
src/array.cpp(13): Assertion Failure: `0 <= index && index < count` Index 2 is out of bounds ranges 0..<2
Illegal instruction (core dumped)
```

**Comment by CircArgs** [comment]
Not a real clue what the implications of this are, but my little example above works fine without the lines in `src/array.cpp` e.g. commenting out:

```cpp
  T &operator[](isize index) {
    // #if !defined(NO_ARRAY_BOUNDS_CHECK)
    // 		GB_ASSERT_MSG(0 <= index && index < count, "Index %td is out of bounds
    // ranges 0..<%td", index, count); 	#endif
    return data[index];
  }
```

**Comment by Tetralux** [comment]
@CircArgs This is not the right fix I think, as that removes the bounds checking for the array.
Meaning that when it works, you're just getting lucky: `data[index]` is actually some space just past the bounds of the array, which happens to remain otherwise untouched by anything else for the duration of the program.

**Comment by CircArgs** [comment]
> @CircArgs This is not the right fix I think, as that removes the bounds checking for the array.
> Meaning that when it works, you're just getting lucky: `data[index]` is actually some space just past the bounds of the array, which happens to remain otherwise untouched by anything else for the duration of the program.

Yeah I had no doubt it's not even a fix at all. Just was noting my monkey patch worked in my very specific scenario. What I don't understand is what about my case triggers the check to fail but I'll leave that for someone qualified like you to explore
