### ISSUE TITLE
Illegal declaration cycle of 'Texture'

### ISSUE THREAD

**Issue by sharpcdf** [odin-lang/Odin#1835]
## Context

The operating system is Fedora 36 with the newest Odin compiler(dev-2022-06)
```
Texture :: struct {
    using Texture: ^sdl2.Texture,
    width, height: f32,
    children: []Texture,
}
```
## Expected Behavior

I expect to be able to set the children field type to a slice of struct `Texture`

## Current Behavior

The compiler errors with `Illegal declaration cycle of 'Texture'`

## Failure Information (for bugs)

When trying to set the type of a struct field to the parent struct the compiler errors with `Illegal declaration cycle of 'Texture'`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a struct such as `foo :: struct{}`
2. Add field of type foo such as `bar: []foo`
3. compile and the error should be reproduced

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Kelimion** [comment]
That's not a bug. You could remedy this with a pointer to `Texture` for example. As is it's called an illegal cycle, because what would it even mean for a struct to contain itself?

**Comment by Tetralux** [comment]
Since `[]Texture` is a `[^]Texture` and an `int`, I don't think this is actually a cycle.

**Comment by AaronGlazer** [comment]
It's not a cycle, but that's not what seems to actually be causing the bug. `using Texture: ^sdl2.Texture` is the faulty line. `using texture: ^sdl2.Texture`, on the other hand, works.

**Comment by csharpdf** [comment]
> It's not a cycle, but that's not what seems to actually be causing the bug. `using Texture: ^sdl2.Texture` is the faulty line. `using texture: ^sdl2.Texture`, on the other hand, works.
> 
> edit: it actually appears to be the combination of both the field named `Texture` and the slice of `Texture`. one or the other alone won't cause any compiler error.

I find that a weird fix, but a fix nonetheless, thanks :)

**Comment by Tetralux** [comment]
Probably should leave it open, as it's definitely in need of or a fix of some sort.
Field names being the same as the enclosing type really should not be causing declaration cycles, and neither should slices!

**Comment by csharpdf** [comment]
Oh ok, I do agree with that :)
