### ISSUE TITLE
build_odin.sh fails on systems without bash in /bin/bash

### ISSUE THREAD

**Issue by sio-k** [odin-lang/Odin#1838]
## Context

* Operating System & Odin Version: GuixSD, though similar issues will crop up on a variety of Linux distributions
* Please paste `odin report` output: irrelevant

## Expected Behavior

Build script runs fine.

## Current Behavior

`/bin/bash` does not exist, but the script tries to use it.

## Suggested fix

Change the shebang from `#!/bin/bash` to `#!/usr/bin/env bash`. I'm unsure if this fix will work fine on OS X, or the various BSDs.

**Comment by YellowKll** [comment]
I can confirm, that this fix works on OpenBSD.
