### ISSUE TITLE
invalid LLVM code gen for arithmetics between `f32` and shifted untyped integer

### ISSUE THREAD

**Issue by DaseinPhaos** [odin-lang/Odin#1840]
## Context

Odin: dev-2022-06-nightly:ba5f7c4e
OS:   Windows 10 Unknown Edition (00000063) (version: 21H1), build 19043.1706
CPU:  Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
RAM:  16300 MiB

## Expected Behavior

The following code snippet should either compile or fail with proper error messages:
```odin
package test
main :: proc() {
    r := u32(3)
    a := f32(1.0)
    x := a * (1<<r)
}
```

## Current Behavior

Compilation fails with invalid LLVM code gen.

Changing the last line to `x := a * f32(1<<r)` also triggers invalid code gen.

But this works: `x := a * f32(u32(1)<<r)`

### Steps to Reproduce

compile and run the code snippet above

### Failure Logs

```text
>odin run test.odin -file
LLVM CODE GEN FAILED FOR PROCEDURE: test.main
define internal void @test.main(i8* noalias nocapture nonnull %__.context_ptr) {
decls:
  %0 = alloca i32, align 4
  %1 = alloca float, align 4
  %2 = alloca float, align 4
  br label %entry

entry:                                            ; preds = %decls
  %3 = bitcast i8* %__.context_ptr to %runtime.Context*
  store i32 0, i32* %0, align 4
  store i32 3, i32* %0, align 4
  store float 0.000000e+00, float* %1, align 4
  store float 1.000000e+00, float* %1, align 4
  store float 0.000000e+00, float* %2, align 4
  %4 = load float, float* %1, align 4
  %5 = load i32, i32* %0, align 4
  %6 = uitofp i32 %5 to float
  %7 = icmp ult float %6, i0 32
  %8 = shl float 1.000000e+00, %6
  %9 = select i1 %7, float %8, float 0.000000e+00
  %10 = fmul float %4, %9
  store float %10, float* %2, align 4
  ret void
}

Both operands to ICmp instruction are not of the same type!
  %7 = icmp ult float %6, i0 32
Shifts only work with integral types!
  %8 = shl float 1.000000e+00, %6
```

**Comment by gingerBill** [comment]
So this is a weird edge case indeed. And I'm not sure what type `1` ought to be in that expression

**Comment by jaspergeer** [comment]
`int` could be appropriate, since thats the type assigned to the results of shifts calculated at compile time.

**Comment by gingerBill** [comment]
I think the correct approach would be to say `(1<<r)` would get the type hint of `f32` and then say that `f32(1)<<r` is not an allowed operation.

**Comment by jaspergeer** [comment]
I see, thanks for the clarification. I'll go ahead and try implementing that fix, could you close my PR?
