### ISSUE TITLE
false `-vet` error: `declare but not used` on aliased intrinsics in parapoly procedures

### ISSUE THREAD

**Issue by DaseinPhaos** [odin-lang/Odin#1853]
## Context

```
Odin: dev-2022-06-nightly:f1e8738a
OS:   Windows 11 Unknown Edition (00000063) (version: 21H2), build 22000.675
CPU:  12th Gen Intel(R) Core(TM) i9-12900H
RAM:  16076 MiB
```

## Expected Behavior

1. define some parapoly procedures referencing `sync.atomic_xxx` in a module
2. write a program referencing that module (either via `import` or in the same module as demonstrated in the mini-repro below)
3. don't reference that parapoly proc from your `main` procedure
4. the program should be able to compile with `-vet`

See the minimum reproducible snippet:
```odin
package play
import "core:sync"

main :: proc() { }

add :: proc(ptr: ^$T, v: T) {
    sync.atomic_add(ptr, v)
}
```

## Current Behavior

The snippet above doesn't compile. 
- Replacing all `sync` with `intrinsics`: compiles
- Make `add` non-parapoly: compiles 

### Steps to Reproduce

1. compile the snippet above

### Failure Logs

```
>odin run play.odin -file -vet
>.\play.odin:2:8: 'sync' declared but not used
```

**Comment by Kelimion** [comment]
That isn't a bug. It happens with anything imported referenced in a parapoly unless that parapoly is specialized somewhere.

A way to silence vet here is to make a dummy reference to the package, like so: `_ :: sync`

**Comment by DaseinPhaos** [comment]
> That isn't a bug. It happens with anything imported being referenced in a parapoly, because unless that parapoly is specialized somewhere, it's not actually used.

In that case, guess I have to explicitly silence vet here. This makes module development a bit more annoying than it should be IMO.

Also then the fact that replacing `sync` with `intrinsics` wouldn't trigger vet would indicate another bug?...

**Comment by gingerBill** [comment]
> Also then the fact that replacing sync with intrinsics wouldn't trigger vet would indicate another bug?...

Still not a bug. `intrinsics` is not really a normal package and built into the compiler. It is something that does not trigger `-vet` on purpose.

**Comment by Kelimion** [comment]
> Also then the fact that replacing `sync` with `intrinsics` wouldn't trigger vet would indicate another bug?...

No, because as it says at the top of `intrinsics`: `// This is purely for documentation`. The `intrinsics` are built into the compiler within the `intrinsics` namespace. The package is there for us to glean what those are, but it's not real Odin user code if that makes sense.

A package like `core:mem` and its parapoly is a better example, I think.

Apart from `_ :: package_name`, another thing you could do is add a specialization for something from that package, or even just an alias.
```odin
foo :: sync.something
```

And in fact, it appears that your example could be written like this.
```odin
import "core:sync"

add :: sync.atomic_add
```

**Comment by DaseinPhaos** [comment]
> Apart from `_ :: package_name`, another thing you could do is add a specialization for something from that package, or even just an alias.
> 
> ```odin
> foo :: sync.something
> ```

Right, I think this should make the intent clearer.

> And in fact, it appears that your example could be written like this.
> 
> ```odin
> import "core:sync"
> 
> add :: sync.atomic_add
> ```

Of course, I was trying to make the snippet as short as possible, in case it was a bug that's worth look into

This came up as an issue for me bc I was trying to use `sync.atomic_xxx` in procedures of a container module. The rules of `-vet` wasn't clear enough for me. Thanks for all the clarifications.
