### ISSUE TITLE
suggested addition to `mem.odin`: `any_to_bytes`

### ISSUE THREAD

**Issue by bpunsky** [odin-lang/Odin#186]
```
any_to_bytes :: proc "contextless" (val: any) -> []byte {
	return transmute([]byte)raw.Slice{val.data, val.type_info.size};
}
```
sorry for doing this through an issue... I'll make a fork for the next time 😛

**Comment by bpunsky** [comment]
If I PR this will you accept? Or is there a philosophical reason

**Comment by ThisDrunkDane** [comment]
I'll close this issue as `any_to_bytes` has now been added to mem.odin by another PR
