### ISSUE TITLE
or_return fails to compille when omitting result of multi-return value expression with place-holder variable name

### ISSUE THREAD

**Issue by graphitemaster** [odin-lang/Odin#1866]
When given a procedure that returns two (or more) values, for instance:
```odin
foo :: proc() -> (x: int, ok: bool) {
  return 0, false;
}
```
Using this procedure in another with `or_return` while omitting all but the last value of `foo`, i.e ignoring `x` here since only the status of the procedure is needed:
```odin
bar :: proc() -> bool {
  _ := foo() or_return;
  // ...
  return true;
}
```
Odin fails to compile this with the following error
> No new declarations on the lhs

This forces a requirement on giving this variable a name even though it isn't used
```odin
bar :: proc() -> bool {
  ignore := foo() or_return;
  // ...
  return true;
}
```
However, since `ignore` is not actually used, the compiler also errors with
> 'ignore' declared but not used

**Comment by HomelikeBrick42** [comment]
cant you just do `foo() or_return` without the assignment?

**Comment by graphitemaster** [comment]
> cant you just do `foo() or_return` without the assignment?

You're right actually, I dunno why I didn't think of this. We should probably have a better diagnostic for this or allow the `_ :=` case somehow, thanks

**Comment by gingerBill** [comment]
@graphitemaster If you want to show the assignment, why not do `_ = ...` rather than `_ := ...`?

The error message will need to show this improvement.
