### ISSUE TITLE
import path tolerates arbitrary dots and whitespaces at the end [Windows only]

### ISSUE THREAD

**Issue by awwdev** [odin-lang/Odin#1872]
## Context
Odin `dev-2022-06:bfcb527b`
Windows Issue

## Current Behavior
```odin
import "core:fmt...."
import "core:fmt . . . ."
```
This compiles on Windows but not on Linux.

## Expected Behavior
Should it be prohibited in Odin? 

Note: The default Windows commandline tolerates such ill-formed (?) paths while the default Ubuntu commandline (on my end) does not.

**Comment by Kelimion** [comment]
I think that should definitely be prohibited, because it's a source of possible confusion with no upside.

**Comment by Kelimion** [comment]
We've figured out it's a Windows path handling bug in the OS itself, not an Odin thing.
For example `type W:\Odin\odin.exe. . .` will echo the contents of the compiler executable to the console.

This is going to make it an interesting problem to figure out whether it's a legit path in and of itself, or this kind of peculiar alias to the normally named file. There's no `inode` like on Linux that would allow you to compare both paths to see if they're the same actual file.

Might have to call a canonicalization function?
