### ISSUE TITLE
Build fails on Windows 10 with Visual Studio 2022

### ISSUE THREAD

**Issue by numbers-zz** [odin-lang/Odin#1875]
## Context

source code version:  bd48561
OS: Windows 10 Home Edition v 10.0.19043
Visual Studio Command Prompt version: Visual Studio 2022 Developer Command Prompt v17.1.3

## Expected Behavior

build process succeeds, creates an odin.exe

## Current Behavior

build process fails

Installing the current release dev-2022-07 doesn't expose similar issues. The compiler builds the doc's "Hello World" example correctly.

## Failure Information (for bugs)

Running build.bat does not correctly compile, fails at main.cpp

### Steps to Reproduce

1. git clone the source code
2. Open the Developer Command Prompt for VS 2022
3. Navigate to source location
4. run build.bat

### Failure Logs

[odin build failure log.txt](https://github.com/odin-lang/Odin/files/9056606/odin.build.failure.log.txt)

A warning about a signed/unsigned mismatch in string_set.cpp is treated as an error.

**Comment by Kelimion** [comment]
You've run the 32-bit command prompt, not the 64-bit one.

**Comment by numbers-zz** [comment]
Well that was easy, thanks. I followed the first instructions on the linked page, not realizing that initializing the default VS command prompt on an x64 machine wouldn't start the x64 version.

**Comment by Kelimion** [comment]
Yeah, Microsoft is daft that way. Still pretending we're living 20 years ago.
