### ISSUE TITLE
When I try running the Hellope example I get strange errors?

### ISSUE THREAD

**Issue by wijiler** [odin-lang/Odin#1878]
## Context

* Operating System & Odin Version:
* Manjaro Linux, odin version 0.13.0-4231497
* typing odin report just outputs the help screen
## Expected Behavior
print out "Hellope"

## Current Behavior
it fails and says

 ```
/home/wijiler/ferengine/main.odin(6:24) Syntax Error: Expected ';' after expression statement, got }
/home/wijiler/ferengine/main.odin(8:1) Syntax Error: Expected '}', got 'EOF'
```

### Steps to Reproduce
step 1:install odin via paru
step 2: paste 

```odin
package main

import "core:fmt"

main :: proc() {
	fmt.println("Hellope!")
}
``` into your main.odin file
step 3: run "odin run  main.odin"
### Failure Logs

Please include any relevant log snippets or files here.

**Comment by gingerBill** [comment]
That is an EXTREMELY old version of Odin. I highly recommend using the latest release.

**Comment by wijiler** [comment]
> That is an EXTREMELY old version of Odin. I highly recommend using the latest release.

oh I didnt even know thank you for commenting

**Comment by wijiler** [comment]
Installed the git version from aur and it works
😄
