### ISSUE TITLE
Iterating a slice that's a parameter or a procedure by reference is not allowed.

### ISSUE THREAD

**Issue by KoziLord** [odin-lang/Odin#1891]
## Context
```odin
increment_all :: proc(slice : []i32)
{
    for _, i in slice do slice[i] += 1;
}

increment_all_shadow :: proc(slice : []i32)
{
    slice := slice;
    for x in &slice do x += 1;
}

increment_all_broken :: proc(slice : []i32)
{
    for x in &slice do x += 1; // ERROR: Cannot take the pointer address of 'slice' which is a procedure parameter
}
```
Currently, trying to iterate a parameter slice via `for x in &param_slice` errors out. This seems odd as the loop doesn't actually get the address of the slice itself, which is what the compiler is complaining about.

This also doesn't seem to align with current parameter immutability rules as mutating the parameter_slice contents is already allowed, you're only not allowed to mutate the slice itself.

Odin: dev-2022-07-nightly:1676c643
OS:   Windows 10 Professional (version: Dev), build 21390.2025

## Expected Behavior

`increment_all_broken` should compile and work exactly the same way `increment_all_shadow` does.

## Current Behavior

`increment_all_broken` fails to compile.

**Comment by gingerBill** [comment]
The last one is not a bug as I said on the Discord server, but needs a better error message with a suggestion explaining why.
