### ISSUE TITLE
Filename missing

### ISSUE THREAD

**Issue by JesseRMeyer** [odin-lang/Odin#1897]
![aye](https://user-images.githubusercontent.com/5846309/180484651-f590d247-b65e-4d50-9621-a105267f35d7.JPG)

```
F:\webgl2\src>odin build build_test_data -debug -show-debug-messages
[DEBUG] build_paths[0]: F:/webgl2/src/build_test_data/
[DEBUG] build_paths[1]:
[DEBUG] build_paths[2]:
[DEBUG] build_paths[3]: C:/Program Files (x86)/Windows Kits/10/Lib/10.0.22000.0/
[DEBUG] build_paths[4]: C:/Program Files (x86)/Windows Kits/10/Lib/10.0.22000.0/um/x64/
[DEBUG] build_paths[5]: C:/Program Files (x86)/Windows Kits/10/Lib/10.0.22000.0/ucrt/x64/
[DEBUG] build_paths[6]: F:/VS2022/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/
[DEBUG] build_paths[7]: F:/VS2022/VC/Tools/MSVC/14.32.31326/lib/x64/
[DEBUG] build_paths[8]: F:/webgl2/src/build_test_data/.exe
[DEBUG] build_paths[9]:
```
```
        Odin: dev-2022-07
        OS:   Windows 10 Home Basic (version: 21H2), build 19044.1826
        CPU:  Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
        RAM:  32717 MiB
```

**Comment by Kelimion** [comment]
I imagine that you're using the portable MSVC script and set it up in `F:\VS2022`?

**Comment by thePHTest** [comment]
I can repro this without `-debug` . Any directory specified besides `.` seems to reproduce this.
As another data point, I am not calling the portable MSVC script.
I call "call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64"

**Comment by Kelimion** [comment]
> I can repro this without `-debug` . Any directory specified besides `.` seems to reproduce this. As another data point, I am not calling the portable MSVC script. I call "call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64"

The thick plottens, indeed. Could be that `fight_through_microsoft_craziness_registered_trademark` gets a bit loopy with VS '22.

**Comment by thePHTest** [comment]
`odin build testing`

```
[DEBUG] build_paths[0]: C:/windrunner/testing/
[DEBUG] build_paths[1]:
[DEBUG] build_paths[2]:
[DEBUG] build_paths[3]: C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0/
[DEBUG] build_paths[4]: C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0/um/x64/
[DEBUG] build_paths[5]: C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0/ucrt/x64/
[DEBUG] build_paths[6]: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/
[DEBUG] build_paths[7]: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/lib/x64/
[DEBUG] build_paths[8]: C:/windrunner/testing/.exe
```

Odin: dev-2022-07:14074e8c
        OS:   Windows 10 Professional (version: 21H2), build 19044.1826
        CPU:  Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
        RAM:  32705 MiB

**Comment by JesseRMeyer** [comment]
> I imagine that you're using the portable MSVC script and set it up in `F:\VS2022`?

Not knowingly.  Simply installed MSVC to a different folder during standard installation.

**Comment by Kelimion** [comment]
> > I imagine that you're using the portable MSVC script and set it up in `F:\VS2022`?
> 
> Not knowingly. Simply installed MSVC to a different folder during standard installation.

Good to know, thanks. I ask because there's a slightly different detection path used for the portable installs, but it appears you're both using bog standard VS installs.

**Comment by thePHTest** [comment]
fwiw doing `odin build ../windrunner/testing/` worked just fine. It seems to be that when it's a single directory or `../testing` that it fails

**Comment by thePHTest** [comment]
Can we re-open this issue? It hasn't been resolved yet.

**Comment by DragosPopse** [comment]
https://github.com/odin-lang/Odin/pull/2280
