### ISSUE TITLE
SIMD cannot be used in functions + different failures based on types

### ISSUE THREAD

**Issue by CircArgs** [odin-lang/Odin#1906]
## Context
```odin
package test

import "core:fmt"
import "core:simd"

add_vectors :: proc(a, b: simd.u8x16) -> simd.u8x16 {
	return a + b
}

main :: proc() {
	x := add_vectors(simd.u8x16{1, 2, 3, 4}, simd.u8x16{1, 2, 3, 4})
	fmt.print(x)
}
```
## `odin report` output:
        Odin: dev-2022-07:227ee0f7
        OS:   Manjaro Linux, Linux 5.15.55-1-MANJARO
        CPU:  Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
        RAM:  15928 MiB

## Expected Behavior

Expected to print added vectors `{2, 4, 6, 8}`

## Current Behavior
src/llvm_abi.cpp(813): Panic: Unhandled integer width for vector type
Illegal instruction (core dumped)

## with `f64x4` instead of `u8x16` you get

src/array.cpp(13): Assertion Failure: `0 <= index && index < count` Index 2 is out of bounds ranges 0..<2
Illegal instruction (core dumped)

**Comment by gingerBill** [comment]
Does this happen on the latest commit?

**Comment by CircArgs** [comment]
Latest report
	Odin: dev-2022-07:f174c805
	OS:   Manjaro Linux, Linux 5.15.55-1-MANJARO
	CPU:  Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
	RAM:  15928 MiB
> Does this happen on the latest commit?
Nope. had old commit. my bad
