### ISSUE TITLE
math.log2 returns truncated result

### ISSUE THREAD

**Issue by slembcke** [odin-lang/Odin#1924]
## Context
	Odin: dev-2022-08-nightly:73beed04
	OS:   Pop!_OS 22.04 LTS, Linux 5.18.10-76051810-generic
	CPU:  AMD Ryzen 7 3700X 8-Core Processor             
	RAM:  15927 MiB

## Expected Behavior

`math.log2()` should compute the base 2 logarithm of a number. Ex: `math.log2(f32(10))` should return approximately 3.32.

## Current Behavior

Calling `math.log2()` always returns a truncated integral result. Ex: `math.log2(f32(10))` returns 3.00.
[In the source](https://github.com/odin-lang/Odin/blob/master/core/math/math.odin#L188) it's an alias for `logb()` which is very unexpected since that's a distinct function in C. I believe this was made in error, since in every other language I know of (including C), `log2()` returns the full result.

**Comment by blakeb211** [comment]
request to close issue
