### ISSUE TITLE
min(type) max(type)

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#193]
Proposal:
```c
min(i8) = -128
max(u8) = 255
min(uint) = 0
// etc.
```

**Comment by ThisDrunkDane** [comment]
would this be implemented in `core:math.odin` or as a compiler-level function?

**Comment by gingerBill** [comment]
Compiler-level function, like `min` and `max` are currently.

**Comment by bpunsky** [comment]
this should potentially be a separate thing from `max(foo, bar)` etc

**Comment by ThisDrunkDane** [comment]
I don't see the need for it to be separate. And for justification, this could work with a `T : type` (if that's allowed ofc) to allow for better checking in a para-poly proc.

**Comment by bpunsky** [comment]
that seems like a good use case. however having overloaded builtins (for completely different usages) still seems somehow wrong. maybe `upper` and `lower` would be better? but then you're stealing a lot of identifiers. not sure which is better

**Comment by bpunsky** [comment]
I *almost* want to say fair enough except that `max(-int, int)` doesn't make sense as `int` isn't a value

**Comment by Tetralux** [comment]
> `max(int)` could just be described as `max(-int, int)`

@bpunsky I think they meant it like, `max(lowest_int_value, highest_int_value)`. 😉

**Comment by ThisDrunkDane** [comment]
@gingerBill Did you ever decide on this?

**Comment by gingerBill** [comment]
@ThisDrunkDane I never did decide. I could add it if people really really wanted it.

**Comment by gingerBill** [comment]
Not worth the confusion with regards to `min(f32)` and `min(f64)`

**Comment by bpunsky** [comment]
@Tetralux that actually makes *more* sense haha

And the Dane made a good point, it would be useful for parapoly. Although I agree that this should not be built in. Proposed compromise: limits constants, and simple procs that switch on the basic types (`max_value :: proc(T : type) -> int`, `min_value :: proc(T : type) -> int`)
