### ISSUE TITLE
Raylib Gesture.TAP behaves as Gesture.NONE

### ISSUE THREAD

**Issue by samstorment** [odin-lang/Odin#1934]
## Context

Odin: dev-2022-08:edba99d6
OS:   Windows 10 Home Basic (version: 21H2), build 19044.1826
CPU:  Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
RAM:  8154 MiB

## Expected Behavior

Raylib's `IsGestureDetected(Gesture.TAP)` should only return true during a TAP Gesture.

## Current Behavior

Raylib's `IsGestureDetected(Gesture.TAP)` returns true at all times unless a Gesture is happening.

## Extra Information

It seems that the Gesture enum is missing the `NONE` value like the one that exists in the [raylib repo](https://github.com/raysan5/raylib/blob/63a23a6b744a0a4cd79698eeec0db531a8c3fd40/src/rgestures.h#L83). The [Odin implementation](https://github.com/odin-lang/Odin/blob/7b539e3025907ab5b40762f90ca4f613cee7eab5/vendor/raylib/raylib.odin#L841) sets the `TAP` value to 0 in the `Gesture` enum, the same as raylib's `NONE` value.

When I update my own vendor raylib file to include `NONE` in the `Gesture` enum, this problem seems to be resolved, but I lack the skill to verify the correctness of this.

### Steps to Reproduce

```odin
package main

import rl "vendor:raylib"

WIDTH :: 800
HEIGHT :: 450

main :: proc() {

    rl.InitWindow(WIDTH, HEIGHT, "Gesture.TAP Bug")
    defer rl.CloseWindow()

    rl.SetTargetFPS(60)

    for !rl.WindowShouldClose() {

        rl.BeginDrawing()

        rl.ClearBackground(rl.RAYWHITE)

        // these are inverted from my expectation
        if (rl.IsGestureDetected(rl.Gesture.TAP)) {
            rl.DrawText("TAP DETECTED", 100, 100, 32, rl.BLACK)
        } else {
            rl.DrawText("NO TAP DETECTED", 100, 100, 32, rl.BLACK)
        }

        rl.EndDrawing()
    }
}
```

**Comment by joyousblunder** [comment]
Oh, I just stumbled on this error too.

GESTURE_NONE is mapped to TAP.
GESTURE_TAP is mapped to DOUBLE_TAP
and the others are not correctly mapped.

I tried to fix locally but couldn't. There is some arcane logic in the original enum cause in jumps by 2^n increments and when I tried to mimic it in Odin I got some error about a 512bit int allocation, so I guess it's a no no. Sorry.

**Comment by gingerBill** [comment]
If this is still an error, I will fix it pronto.
