### ISSUE TITLE
make() doesn't allocate on WASM

### ISSUE THREAD

**Issue by inkeliz** [odin-lang/Odin#1947]
## Context

Currently, compiling to WASM (`-target:wasi_wasm32`), I'm unable to use `make` function and it fails when try to access some value in the index.

* Please paste `odin report` output:
        Odin: dev-2022-08-nightly:73beed04
        OS:   Windows 11 Professional (version: 21H2), build 22000.795
        CPU:  AMD Ryzen 9 3900X 12-Core Processor
        RAM:  65448 MiB

## Expected Behavior

The `make` and `append` should allocate and, maybe, grow the WASM memory.

## Current Behavior

The `make` doesn't do anything, and accessing some value `say: array[0]` crashes due to "Index 0 is out of range 0..<0".

## Failure Information (for bugs)

```
main.odin(17:13) Index 0 is out of range 0..<0
error: failed to run `testdata/wasi/odin.wasi`
│   1: RuntimeError: unreachable
           at runtime.bounds_trap (odin.wasi[17]:0x1187)
           at runtime.bounds_check_error.handle_error-0 (odin.wasi[19]:0x1321)
           at runtime.bounds_check_error (odin.wasi[18]:0x11e0)
           at main.main (odin.wasi[29]:0x1cd5)
           at _start (odin.wasi[106]:0xb16a)
╰─▶ 2: unreachable
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create some code which uses `make`:

```
package main

main :: proc () {
    array := make([dynamic]u8, 8_000_000)
    first := array[0]
}
```

2. Compile to WASM:

```
odin build . -target:wasi_wasm32 -extra-linker-flags:"--lto-O3"
```

3. Run the WASM (with any runtime, such as Wasmer):

```
wasmer main.wasm
```

4. It will crash.

**Comment by gingerBill** [comment]
Not a bug. wasm uses a nil allocator by default on purpose.

**Comment by inkeliz** [comment]
There's any other allocator available on WASM, which works as I expected?

**Comment by gingerBill** [comment]
You need to explicitly specify and assign the `context.allocator`. This is because Wasm has a weird memory system which doesn't really map the same as modern systems with an operating system. There are ways to specify more 64KiB pages but none of those pages can ever be decommitted because they are not "virtualized".

So a general purpose allocator would have to be very specific to wasm and is probably not a good idea to default to for most people either.

**Comment by inkeliz** [comment]
That is my first time using Odin. So, I need to create and provide one custom `allocator`? How can I call the `grow` assembly function, from Odin? 

I'm not if `nil_allocator` is right. At least, that doesn't seems documented. However, all other language (say Zig, Golang, Swiftwasm and even Emscripten) have options to use "`malloc`/`make`" (and equivalent) and "works out-of-box". I expect Odin to work in somewhat similar. 😬

**Comment by gingerBill** [comment]
We will have to document this more, even more so than the little we have for the semi-experimental wasm stuff.

But just because they have a "works out of the box" doesn't really mean it "works as expected and assumed" which it cannot.

**Comment by inkeliz** [comment]
I think they "works as expected and assumed", assuming that WASM only have one linear memory.

Following the documentation, it says:

> By default, the context.allocator is a OS heap allocator and the context.temp_allocator is assigned to a scratch allocator (a ring-buffer based allocator).

I think that is fine to have `context.allocator` undefined, since WASM doesn't have OS. However, why not have one "scratch allocator", which may call `grow` when required? I mean, that is something that "works", maybe not the best implementation and sure it's not the same of `context.allocator` from others OSes.

---------------

I "fix" my code with one ugly code, which creates `HeapMemory := [65_536_000]u8{}` and uses it as one `mem.Arena` and `mem.Allocator`. That simply uses alot of memory upfront. So, I think that is worse than anything that  doesn't "works as expected and assumed":

```
HeapMemory := [65_536_000]u8{}
HeapArena : mem.Arena
HeapAllocator : mem.Allocator

main :: proc () {
    mem.init_arena(&HeapArena, HeapMemory[:])
    HeapAllocator = mem.arena_allocator(&HeapArena)

    context.allocator = HeapAllocator

    x := make([]u8, 8_000_000)
    y := x[0]
}
```` 

Now, that works, _but is terrible._

--------------

To create a better allocator (because the current one is really trash), I have two issues:

1. I don't know how to call `grow` (the assembly function which grows the memory).
2. I don't know if Odin can grow their stack and, maybe, overwrite my memory (since we share the same memory, and Odin is unaware that the memory is already in use).

I take some look into the existent code, but sounds like most of them only uses syscall functions, which doesn't apply here. I'm not sure about the stack internals (some languages like Golang can grow their stack, at certain point, in order to prevent stackoverflow, I'm not sure if the same happens on Odin).

-----------

I know that this issue was closed. But, I hope that some basic allocator lands to wasm, at some point. 😍

**Comment by gingerBill** [comment]
This issue was closed because your problem is technically not a bug other than poor documentation.

------

To call the wasm intrinsics:
```odin
package intrinsics

// index is always 0, but kept here for future extension of multiple memories
wasm_memory_grow :: proc(index, delta: uintptr) -> int ---
wasm_memory_size :: proc(index: uintptr)        -> int ---
```

If you are using the `js_wasm32` target (which is specifically for web browsers), then I recommend looking around in the `vendor:wasm` packages specifically under `vendor:wasm/js` which will show you how can allocate more pages if necessary. The `js.page_allocator()` ONLY allocates pages and is meant to be used as a foundation for other allocators.

------

We will add other allocators in the future, especially for `-target:js_wasm32` use, probably something inspired by Rust's `wee_alloc`.
