### ISSUE TITLE
Constants defined through the command-line aren't being recognised

### ISSUE THREAD

**Issue by fendevel** [odin-lang/Odin#1948]
## Context

Defining constants with the compiler option `-define:NAME=VALUE` does not result in a constant of that name recognisable to the build.

* Please paste `odin report` output:
Odin: dev-2022-08:081e36c9
OS:   Windows 11 Professional (version: 22H2), build 25174.1000
CPU:  AMD Ryzen 5 5600X 6-Core Processor
RAM:  32655 MiB

## Expected Behavior

Using the `define` compiler option should introduce a constant of that name.

## Current Behavior

The constant is not being recognised.

## Failure Information (for bugs)

`main.odin(5:17) Undeclared name: CONSTANT_VALUE`

### Steps to Reproduce

1. Create a new folder and Odin source file
2. Write something that consumes your constant, like:
```odin
package main
import "core:fmt"

main :: proc() {
    fmt.println(CONSTANT_VALUE)
}
```
3. Compile with:
```
odin build . -define:CONSTANT_VALUE="hello!"
```

**Comment by DaseinPhaos** [comment]
this is not a bug. identifiers defined by command line are to be accessed like this:
`fmt.println(#config(CONSTANT_VALUE, "default_value"))`, see [`#config`](https://odin-lang.org/docs/overview/#built-in-procedures)

**Comment by Kelimion** [comment]
`odin build -help` also mentions the following:

```
        -define:<name>=<expression>
                Defines a global constant with a value
                Example: -define:SPAM=123
                To use:  #config(SPAM, default_value)
```

**Comment by fendevel** [comment]
Ah, I wasn't under the impression this was a required step from the documentation but the -help message does absolutely make it clear. Thank you.
