### ISSUE TITLE
Compiler assert when casting matrix variable

### ISSUE THREAD

**Issue by IanLilleyT** [odin-lang/Odin#1960]
Casting a matrix that's stored in a variable results in an error

Error: `llvm_backend_general.cpp(920): Assertion Failure: are_types_identical(ca, core_type(value.type)) f32 != f64`
```
m := matrix[4,4]f64{}
v := cast(matrix[4,4]f32)m
```
If the matrix is an rvalue it does not crash
```
v := cast(matrix[4,4]f32)matrix[4,4]f64{}
```

Report:
```
Odin: dev-2022-08:afec321d
OS:   Windows 11 Professional (version: 21H2), build 22000.856
CPU:  Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
```

**Comment by laytan** [comment]
Looks like this has been fixed at some point.
