### ISSUE TITLE
@llvm.dbg.value used on procedure parameter pointer type instead of @llvm.dbg.declare

### ISSUE THREAD

**Issue by JesseRMeyer** [odin-lang/Odin#1964]
```odin
package main

bob_sally :: struct {
	bob, sally: int,
}

debug_param_test :: proc (b_s :bob_sally) -> int {
	return b_s.bob + b_s.sally
}

main :: proc() {
	test := bob_sally{
		1,
		2,
	}
	res := debug_param_test(test)
}
```
`b_s.bob` should equal 1, and `b_s.sally` should equal 2.  However, their values are garbage as seen below.
![huh](https://user-images.githubusercontent.com/5846309/185684882-aaaba7a6-94f2-4640-b7a6-58a4373359d7.JPG)

But consider the value of `b_s.bob` as it relates to the address of `b_s`.  It looks like the value is reporting a stack address.  And indeed, it is.

![huh2](https://user-images.githubusercontent.com/5846309/185684853-226c05bd-6d48-4270-8653-38827b39013c.JPG)

It's reporting the stack address of `test`.

I suspect the basic reason here is that Odin will encode the debug info of a parameter which was passed as a pointer as a value via `llvm.dbg.value`.  But debug info for pointers are supposed to treated with `llvm.dbg.declare`.

```llvm
define internal i64 @main.debug_param_test(%main.bob_sally* %0, i8* noalias nocapture nonnull %__.context_ptr) #0 !dbg !1109 {
decls:
~BUG HERE~  call void @llvm.dbg.value(metadata %main.bob_sally* %0, metadata !1117, metadata !DIExpression()), !dbg !1119
  call void @llvm.dbg.declare(metadata i8* %__.context_ptr, metadata !1118, metadata !DIExpression()), !dbg !1120
  br label %entry, !dbg !1120

entry:                                            ; preds = %decls
  %1 = getelementptr inbounds %main.bob_sally, %main.bob_sally* %0, i32 0, i32 0, !dbg !1121
  %2 = load i64, i64* %1, align 8, !dbg !1121
  %3 = getelementptr inbounds %main.bob_sally, %main.bob_sally* %0, i32 0, i32 1, !dbg !1121
  %4 = load i64, i64* %3, align 8, !dbg !1121
  %5 = add i64 %2, %4, !dbg !1121
  ret i64 %5, !dbg !1121
}
```

**Comment by gingerBill** [comment]
I hope this improves things: https://github.com/odin-lang/Odin/pull/2034

**Comment by JesseRMeyer** [comment]
`@llvm.dbg.value` needs to be emitted for parameters passed by value and `llvm.dbg.declare` otherwise.

**Comment by JesseRMeyer** [comment]
The fix (tested locally) should resemble.

```c++
// NOTE(bill, 2022-02-01): For parameter values, you must insert them at the end of the decl block
// The reason is that if the parameter is at index 0 and a pointer, there is not such things as an
// instruction "before" it.
// NOTE(Jesse, 2022-09-09): Use DgbValue for parameters passed by value and Declare for those passed by pointer / conf ref (implicit in Odin's calling convention)
i64 type_size = type_size_of(type);
if (type_size <= 8) { // TODO(Jesse, 2022-09-09): Assumes 8 byte pointers.
	LLVMDIBuilderInsertDbgValueAtEnd(m->debug_builder, storage, var_info, llvm_expr, llvm_debug_loc, block->block);
} else {
	LLVMDIBuilderInsertDeclareAtEnd(m->debug_builder, storage, var_info, llvm_expr, llvm_debug_loc, block->block);
}
```

This procedure does not have the higher level context of whether it was called with lbArg_Direct or lbArg_Indirect arguments, so that understanding has to be either recreated by checking the type size, or by some other means.

**Comment by JesseRMeyer** [comment]
Fixed in https://github.com/odin-lang/Odin/commit/913e8b2e02ea278235cade2c02c2ddae40e8470d.
