### ISSUE TITLE
Dynamic arrays, in fields at the end of some large structs, using arena allocation, on WASM, have broken allocators

### ISSUE THREAD

**Issue by bvisness** [odin-lang/Odin#1966]
## Context

        Odin: dev-2022-08:afec321d
        OS:   Windows 10 Professional (version: 21H2), build 19044.1889
        CPU:  Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
        RAM:  16335 MiB

## Expected Behavior

Using a dynamic array in any field of a struct of any size, with an arena allocator, should get a good arena allocator that does not corrupt memory.

## Current Behavior

On WASM, some dynamic array fields end up with arena allocators whose `data` field is inexplicably `0`. Moving the offending field to the top of the struct fixes the issue.

### Steps to Reproduce

Open the attached zip, run `python -m http.server 8000`, and view `localhost:8000` in your browser. Observe that the allocator in the second entry under "After struct literals:" has `data = 0x0`.

[allocbug.zip](https://github.com/odin-lang/Odin/files/9385905/allocbug.zip)

**Comment by colrdavidson** [comment]
Managed to shrink this repro dramatically. 900B struct -> ~56. It seems to be contingent on having u64/ints in the struct
[repro.zip](https://github.com/odin-lang/Odin/files/9396015/repro.zip)

**Comment by colrdavidson** [comment]
[expanded_repro.zip](https://github.com/odin-lang/Odin/files/9396198/expanded_repro.zip)

**Comment by colrdavidson** [comment]
Ok, squashed this one down even more, can now fit it comfortably in a comment. 
It only seems to happen only when doing struct decl, and only if the field has more than 40 bytes and uses a u64 before the log type, and only on WASM

```Odin
FakeType :: distinct [20]u16
LogsAtEnd :: struct {
    _t00: [41]u8,
    _t51: u64,
    logs: FakeType,
}
new_fake_type :: proc() -> FakeType {
    ft := FakeType{}
    for i := 0; i < len(ft); i += 1 {
        ft[i] = u16(i)
    }

    return ft
}

main :: proc() {
    a := LogsAtEnd{ logs = new_fake_type(), }

    fmt.println("Field offsets:")
    fmt.printf("a .logs:     %d\n", uintptr(&a.logs)-uintptr(&a))

    fmt.println("Init state:")
    fmt.printf("a %v\n", a.logs)

    fmt.println("After reassigning:")
    a.logs = new_fake_type()
    fmt.printf("a %v\n", a.logs)
}
```
```
Got
a [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1, 0]
Expected
a [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```
