### ISSUE TITLE
Using a debugger on a mac

### ISSUE THREAD

**Issue by clankill3r** [odin-lang/Odin#1967]
Is it possible to use a debugger on a mac?
And if so can someone help me of how to set this up?

I know there is Visual Studio for mac, but not sure if this is possible to use for debugging on a mac.

Any help is welcome.

**Comment by Lperlind** [comment]
You can use xcode to debug on apple platforms.

**Comment by clankill3r** [comment]
Can someone help me how to set it up. I used Xcode before, but not for something like this.
I can't figure out the steps.

**Comment by JesseRMeyer** [comment]
Please visit us on the discord server for more assistance.  The issues page here is for problems with the Odin project.

**Comment by bmaxa** [comment]
lldb is on mac. I don't know if it supports Odin source code...
