### ISSUE TITLE
BSD: unable to build due to WIFEXITED and WEXITSTATUS

### ISSUE THREAD

**Issue by ashemedai** [odin-lang/Odin#1968]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System & Odin Version: FreeBSD 12.3-STABLE, but also applies to NetBSD and OpenBSD
Tree at b3e3b6c6

## Expected Behavior

Successful Odin build.

## Current Behavior

Failed Odin build.

### Failure Logs

```
./build_odin.sh debug
+ clang++ src/main.cpp src/libtommath.cpp -Wno-switch -Wno-macro-redefined -Wno-unused-value '-DODIN_VERSION_RAW="dev-2022
-08"' '-DGIT_SHA="b3e3b6c6"' -std=c++14 -I/usr/local/llvm11/include -std=c++14 -fno-exceptions -D__STDC_CONSTANT_MACROS -D
__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -L/usr/local/llvm11/lib -g -pthread -lm -lstdc++ -lLLVM-11 -o odin
src/main.cpp:111:6: error: use of undeclared identifier 'WIFEXITED'
        if (WIFEXITED(exit_code)) {
            ^
src/main.cpp:112:15: error: use of undeclared identifier 'WEXITSTATUS'
                exit_code = WEXITSTATUS(exit_code);
                            ^
2 errors generated.
*** Error code 1
```

FreeBSD, NetBSD or OpenBSD do not know either `WIFEXITED` or `WEXITSTATUS` for `system()` (`waitpid()`) if `<sys/wait.h>` is not included.

This allows me to build without error on FreeBSD again, unsure if this is how it should be fixed though. Also unsure at the moment if it could be collapsed with the preceding section, I don't think it can hurt since `sys/types.h` and `sys/sysctl.h` are quite common includes on all three.

```patch
diff --git a/src/build_settings.cpp b/src/build_settings.cpp
index 9d5c3e55..bed8e7c9 100644
--- a/src/build_settings.cpp
+++ b/src/build_settings.cpp
@@ -3,6 +3,10 @@
 #include <sys/sysctl.h>
 #endif

+#if defined(GB_SYSTEM_FREEBSD) || defined(GB_SYSTEM_NETBSD) || defined(GB_SYSTEM_OPENBSD)
+#include <sys/wait.h>
+#endif
+
 // #if defined(GB_SYSTEM_WINDOWS)
 // #define DEFAULT_TO_THREADED_CHECKER
 // #endif
```

For the collapsed route:

```patch
diff --git a/src/build_settings.cpp b/src/build_settings.cpp
index 9d5c3e55..d09b07d7 100644
--- a/src/build_settings.cpp
+++ b/src/build_settings.cpp
@@ -1,6 +1,7 @@
-#if defined(GB_SYSTEM_FREEBSD) || defined(GB_SYSTEM_OPENBSD)
+#if defined(GB_SYSTEM_FREEBSD) || defined(GB_SYSTEM_NETBSD) || defined(GB_SYSTEM_OPENBSD)
 #include <sys/types.h>
 #include <sys/sysctl.h>
+#include <sys/wait.h>
 #endif

 // #if defined(GB_SYSTEM_WINDOWS)
```

**Comment by semarie** [comment]
odin built fine on OpenBSD with b3e3b6c6565d6211ffd8ccef7a3866e03a978fee

but we already include [sys/wait.h](https://github.com/odin-lang/Odin/blob/b3e3b6c6565d6211ffd8ccef7a3866e03a978fee/src/gb/gb.h#L93-L95) for it

**Comment by ashemedai** [comment]
@semarie Thanks, hadn't checked that far yet and made an assumption since I didn't want to leave another BSD potentially broken.

Makes me wonder if those header includes should indeed not be consolidated for the BSDs in one place.

**Comment by semarie** [comment]
`WIFEXITED` is expected to be present on POSIX systems and should be visible with `sys/wait.h` include.

the calling code (at src/main.cpp) is guarded with `GB_SYSTEM_UNIX` so I wonder why Linux doesn't need `sys/wait.h` too.
It might be defined/included by some other headers.

I would add an entry in gb.h to include `sys/wait.h` for all `GB_SYSTEM_UNIX` (and remove the one for OpenBSD).
