### ISSUE TITLE
Erroneous cast for `mprotect` procedure in `virtual_linux.odin`

### ISSUE THREAD

**Issue by Daemondeal** [odin-lang/Odin#1973]
## Context

Odin: dev-2022-08:af1b3b63
OS:   Arch Linux, Linux 5.19.2-arch1-1
CPU:  AMD Ryzen 5 4600U with Radeon Graphics
RAM:  5799 MiB

I was trying to build [ols](https://github.com/DanielGavin/ols), and the compiler returned:
```
/home/daem/Odin/core/mem/virtual/virtual_linux.odin(51:79) Argument 3 must be of type 'uintptr', got uint
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Be on a Linux machine
2. Try to compile some program the calls `mem_virtual.mprotect`

### Notes

I tried just to go to the relevant source file, i.e. [the mprotect proc](https://github.com/odin-lang/Odin/blob/af1b3b6368ffe690ba7f395920fd658b575fa042/core/mem/virtual/virtual_linux.odin#L50-L53), and it seems that one of its arguments was erroneously casted to `uint` instead of `uintptr` like the `intrinsics.syscall` prototypes asks you to do. I've tried just changing that cast in the source code, and that seems to have fixed my issue.

**Comment by Kelimion** [comment]
Fixed via 3469178dc16a1ee8c4f4c21daca927f8b8d46ff7.
