### ISSUE TITLE
Created Odin lexer for CudaText

### ISSUE THREAD

**Issue by Alexey-T** [odin-lang/Odin#1983]
This is not the report. it is an announcement. The CudaText editor https://cudatext.github.io/ now has the Odin lexer. It supports the code-tree too (for 'proc' and 'enum/struct' nodes).
Install the lexer from: "Plugins / Addon Manager / Install".

**Comment by kevinsjoberg** [comment]
Wonderful! Care to add it to the [list](https://wiki.freepascal.org/CudaText#List_of_lexers)? 🙂

**Comment by gingerBill** [comment]
This is wonderful to hear! And I'll have to give CudaText a go, especially being very similar to my day-to-day editor of SublimeText.

**Comment by Alexey-T** [comment]
@gingerBill you are welcome.
please write then, your verdict to the editor, or some feedback.

**Comment by Alexey-T** [comment]
> Wonderful! Care to add it to the [list](https://wiki.freepascal.org/CudaText#List_of_lexers)? slightly_smiling_face

thanks, updated the wiki.

**Comment by Kelimion** [comment]
Thanks muchly for adding it to CudaText.
