### ISSUE TITLE
Odin compiler output, out of box support for emacs?

### ISSUE THREAD

**Issue by Inc0n** [odin-lang/Odin#1990]
**Is your feature request related to a problem? Please describe.**

The compilation error are usually formatted as follow:
```
$PATH/$odin_src_file($line_number:$col_number) Syntax Error: Expected '}', got '^'
```
This format is different from most other compilers, such as the ones I have looked into, such as: zig, gcc. They are all in the following format: 
```
$PATH/$odin_src_file:$line_number:$col_number Example error: placeholder
```
This very small difference means that in `Emacs` it recognize the latter but not the prior, which means it cannot help locate back into the exact location of where the error is.

**Describe the solution you'd like**

The easiest solution to me is to use the latter style.

**Comment by SentientCoffee** [comment]
VSCode has a similar issue, but on Unix you can work around it using the ``ODIN_ERROR_POS_STYLE` environment variable:

```sh
$ ODIN_ERROR_POS_STYLE="unix" odin build .
```
