### ISSUE TITLE
foreign import variable incorrect value in windows

### ISSUE THREAD

**Issue by dgriffie79** [odin-lang/Odin#1999]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

        Odin: dev-2022-09:4c567211
        OS:   Windows 11 Home Basic (version: 21H2), build 22000.856
        CPU:  AMD Ryzen 7 5800 8-Core Processor
        RAM:  32693 MiB
        Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31629 for x64

## Expected Behavior

Attempting to import a foreign variable from a windows dll and print the value. Expected to see "32"

## Current Behavior

Outputs "-809753089"

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. test.odin
```
package main

import "core:fmt"
import "core:c"

foreign import lib "foo.lib"

foreign lib {
    foo: c.int
}

main :: proc() {
    fmt.println(foo)
}
```

2. foo.c
```
int foo = 32;
```

3. foo.def
```
LIBRARY foo
EXPORTS
     foo
```

4. build/run
```
cl /LD foo.c foo.def
odin build .
test.exe
```

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Kelimion** [comment]
I get the wrong value as well, but if I export an accessor, it does give me the correct value.
```cpp
int foo = 32;
int foozle() {
	return foo;
}
```
```
FOO 4099810815
FOOZLE 32
```

**Comment by dgriffie79** [comment]
looks like the DLLStorageClass needs to be set for the windows/dll case. my workaround: 
```
		if (is_foreign) {
			LLVMSetLinkage(g.value, LLVMExternalLinkage);
+			LLVMSetDLLStorageClass(g.value, LLVMDLLImportStorageClass);

			LLVMSetExternallyInitialized(g.value, true);
			lb_add_foreign_library_path(m, e->Variable.foreign_library); 
```
