### ISSUE TITLE
Support ARM

### ISSUE THREAD

**Issue by dreadhello** [odin-lang/Odin#202]
Currently Odin does not work on ARM (the compiler can't even be compiled on ARM).

This is a huge issue for developing for the Raspberry Pi or also for Android.

It would be awesome if you could support ARM soon.

**Comment by GrooveStomp** [comment]
I would like to know what would be involved to help in this regard.
I'd also really like to see RISC-V support; despite not having any RISC-V hardware myself.

**Comment by ThisDrunkDane** [comment]
We sort a support ARM now because of the M1 chip, this is not totally the same but closing this anyway as there is an overall goal of supporting it already

**Comment by cognociente** [comment]
Please can you look at providing a compiler for windows arm64. This platform is becoming more prevalent.
