### ISSUE TITLE
Allow slices and arrays to be defined as constants

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#203]
Such as:
```odin
SIGMA :: [4]u32{0x61707865, 0x3320646e, 0x79622d32, 0x6b206574};
```
or:
```odin
SIGMA :: []u32{0x61707865, 0x3320646e, 0x79622d32, 0x6b206574};
```

**Comment by gingerBill** [comment]
There is a reason as to why I do no allow this. This is because constants in Odin are copied on use. This is akin to `#define` in C. Please prefer storing these as variables instead.
