### ISSUE TITLE
Differing behaviors with defer statements for single vs. multiple return values

### ISSUE THREAD

**Issue by elusivePorpoise** [odin-lang/Odin#2054]
## Context	
Odin: dev-2022-09-nightly:74458ab0
OS:   Windows 10 Home Basic (version: 21H2), build 19044.1889
CPU:  11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
RAM:  7771 MiB

## Expected Behavior
Defer statements should either affect or not affect results for both single and multiple-return values. Having different behaviors is unintuitive (and unnecessary?).

## Current Behavior
Single-return procedure result is not affected by a defer. Multiple-return is affected.

### Steps to Reproduce
```
single_return :: proc()->(i: int){
        defer i = 42
        return
}
multi_return :: proc()->(i: int, b: bool){
        defer i = 42
        return
}

main :: proc(){
        fmt.println(single_return())
        fmt.println(multi_return())
}
```
```
0
42 false
exited with code 0
```

**Comment by gingerBill** [comment]
This is caused by an ABI optimization bug. Should be pretty simple to fix.
