### ISSUE TITLE
Pascal-like `set` type

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#206]
```
Char_Set :: set['0'...'9']; // 10 bits of data -> 2 bytes
#assert(size_of(Char_Set) == 2);

Flag :: enum {A, B, C, D}; // 4 different states e.g. 2 bits of data
Flag_Set :: set[Flag]; // 2^2 == 4 bits of data -> 1 byte
x := Flag_Set{A, C};
if C in x {}
y := x & Flag_Set{C};
z := x | Flag_Set{A, B};
w := ~x;
```

**Comment by Tetralux** [comment]
Considering the similarity with `bit_field`, maybe it should just be
```
Flag_Set :: bit_field Flag;
Char_Set :: bit_field '0'...'9';
```
Less keywords/types to understand, etc. Especially if the point is that it's represented as a bit field! >D

Plus, sets are generally about being an array where the elements are unique. Seems different enough.

**Comment by gingerBill** [comment]
`bit_field` is a completely different concept. That allows the mapping of certain bits to act as integers. A `set` would be for flags/bit sets/packed bit array.

I do think that reducing the number of keywords is a good idea but these are different concepts so it's probably better to have a separate one for the time being.

**Comment by Tetralux** [comment]
Hmmm. Well, since this `set` is about using one bit for each possible value that is specified, perhaps it should be `bit_set`, since a set is usually a more generic construct than that.

**Comment by gingerBill** [comment]
Now implemented with `bit_set`
