### ISSUE TITLE
`core/c/libc.complex.odin` `pow` bindings are incorrect

### ISSUE THREAD

**Issue by 13419596** [odin-lang/Odin#2069]
## Context

The power functions cpow  and cpowf should take in two arguments, the base and the power. However the declarations/bindings in  c/libc/complex.odin only have a single argument. The end result is that the unspecified second argument is set to zero and all calls just raise whatever is passed in to the 0 power (z^0).

## Suggested Fix
The current declarations in `complex.odin` look like
```
cpow    :: proc(z: complex_double) -> complex_double ---
cpowf   :: proc(z: complex_float) -> complex_float ---
```

Instead they should look something like the following: (matching the documentation at https://en.cppreference.com/w/c/numeric/complex/cpow)
```
cpow    :: proc(x: complex_double, y: complex_double) -> complex_double ---
cpowf   :: proc(x: complex_float, y: complex_float) -> complex_float ---
```

## Issue Workaround

I wrote a function to evaluate the complex power using odin native functions.
```
pow_complex :: proc(z:$C, power:$T) -> C where 
  intrinsics.type_is_complex(C) &&
  intrinsics.type_is_numeric(T) {
  if z==0 {
    return 0.
  }
  zr := real(z)
  zi := imag(z)
  r2 := zr*zr + zi*zi 
  th := math.atan2(zi, zr)
  when !intrinsics.type_is_complex(T) {
    // when power is a real number things are simple
    // z^power
    // |z|^power * exp(1i*th*power)
    power := type_of(r2)(power)  // cast power as r2 type so that multiplication is valid,
    // sometimes power comes in as unspecified float or int and this fixes the type so it can be multiplied
    r_out := pow(r2, power * .5)  // (r2^.5)^p = (r2)^(p*.5) - save a sqrt
    th_out := th * power
    out : C = complex(r_out * math.cos(th_out), r_out * math.sin(th_out))
    return out
  } else {
    // z^power
    // = (r*exp(1i*th))^(a+ib)
    //   r^(a+ib)*exp(1i*th*(a+ib))
    //   r^a * r^(ib) * exp(1i*th*a) * exp(1i*th+ib)
    //   (r^a*exp(-th*b)) * r^(ib)*exp(1i*th*a)
    //   (r^a*exp(-th*b)) * r^(ib)*exp(1i*th*a)
    //
    // Magnitude portion:
    // r_out = r^a * exp(-th*b)
    //
    // Angle portion:
    // r^(ib) * exp(1i*th*a)
    // (exp(ln(r))^(ib) * exp(1i*th*a)
    // (exp(1i*ln(r)*b) * exp(1i*th*a)
    // exp(1i*ln(r)*b + 1i*th*a)
    // exp(1i*(ln(r)*b + th*a))
    // th_out = ln(r)*b + th*a
    power : C = power
    a := real(power)
    b := imag(power)
    r_out := pow(r2, a * .5) * exp(-th * b) // - saves a sqrt
    th_out := (.5 * ln(r2) * b) + (th * a)  // ln(r2^.5) = .5*ln(r2) - saves a sqrt
    out : C = complex(r_out * cos(th_out), r_out * sin(th_out))
    return out
  }
}
```

**Comment by Kelimion** [comment]
If you want to make a pull request with the binding fix and proposed native `pow_complex`, we can get this added in no time.

**Comment by 13419596** [comment]
> If you want to make a pull request with the binding fix and proposed native `pow_complex`, we can get this added in no time.

I'll try making a PR for the binding fixes. 

As for the native power function. I haven't written unit tests for it, so I really wouldn't feel comfortable putting in core odin code. In addition, I wouldn't know where it would belong anyways. What package and file would I put it in hypothetically?

**Comment by 13419596** [comment]
Also when writing unit tests, is it okay to assume that -collection:test=Odin/tests will be supplied, or do I need to supply the `when ODIN_TEST { ...`  blah stuff at the beginning of every unit test file?

**Comment by Kelimion** [comment]
`core:math` has `pow` in `math.odin`. That `pow` procedure group could be extended with support for complex types.

As for tests, one possible avenue could be to test your implementation against the fixed bindings to gain some confidence in its correctness.

**Comment by Kelimion** [comment]
(It's fine if those are two separate PRs, if you prefer. One for the bindings, one for better complex support in `core:math`.)

**Comment by graphitemaster** [comment]
This should be closed now. The bindings were fixed and merged.
