### ISSUE TITLE
Importing "core:path" causes compile time panic

### ISSUE THREAD

**Issue by 13419596** [odin-lang/Odin#2086]
## Context

I should be able to import "core:path" without crashing the compiler. Right now it causes a compile time panic in `core:path/slashpath`.

#### Odin Report

I'm on the most recent odin as of 2022/09/26
```
	Odin: dev-2022-09:83ffb68b
	OS:   macOS Monterey 12.5 (build: 21G115, kernel: 21.6.0)
	CPU:  ARM64
	RAM:  16384 MiB
```

### Steps to Reproduce

Attempt to compile the following code, and the compiler will crash:
```
package main

import "core:fmt"
import "core:path"

main :: proc() {
  fmt.printf("hello\n")
}
```

### Failure Logs

```
core/path/path_error.odin(3:1) Compile time panic: core:path/slashpath - for paths separated by forward slashes, e.g. paths in URLs, this does not deal with OS-specific paths
core:path/filepath - uses either forward slashes or backslashes depending on the operating system, deals with Windows/NT paths with volume letters or backslashes (on the related platforms)
```

**Comment by Kelimion** [comment]
You're misreading the error message. What is says is that `core:path` is not actually a package, and you should use either  `core:path/slashpath`, or `core:path/filepath`. If you're dealing with URLs, you'll want `slashpath`, when dealing with files you'll want `core:path/filepath`.
