### ISSUE TITLE
raylib.odin needs to have Model :: struct #align 4 {

### ISSUE THREAD

**Issue by ross-a** [odin-lang/Odin#2089]
## Context

raylib.odin needs to have Model :: struct **#align 4** {

* Operating System & Odin Version:
* Please paste `odin report` output:

## Expected Behavior

UpdateModelAnimation() should work

## Current Behavior

raylib functions like UpdateModelAnimation(Model, ModelAnimation, frame)
will misbehave without Model being aligned

**Comment by laytan** [comment]
This was fixed recently, not with the suggested solution but with correcting the use of row major matrices in raylib, so this can be closed
