### ISSUE TITLE
`type_info_of` returning incorrect value when called from DLL compiled with `-no-crt` flag

### ISSUE THREAD

**Issue by englerj** [odin-lang/Odin#2097]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System & Odin Version:
        Odin: dev-2022-09-nightly:74458ab0
        OS:   Windows 11 Professional (version: 21H2), build 22000.978
        CPU:  Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
        RAM:  32702 MiB

## Expected Behavior

`type_info_of` should return the same value from a DLL as it does from the EXE.

## Current Behavior

`type_info_of` returns an empty/zero'd `Type_Info` struct. However, `typeid_of` does seem to return the correct value in that the value returned in both the exe and dll are identifical. Removing the `-no-crt` flag appears to alleviate the issue.

_Note: I uncovered this issue by noticing that the `fmt.*printf` family of procedures weren't formatting any of their arguments when called within a DLL. I am led to believe that this bug is the root cause of that issue._

### Steps to Reproduce

The following is the code used to reproduce the issue. The `assert` in the `procedure` proc should fail.

```odin
// Compiled as 'example.exe'.
package exe

import "core:sys/windows"

main :: proc()
{
    string_type_id := typeid_of(string)
    string_type    := type_info_of(string)

    assert(string_type.id == string_type_id)

    module := windows.LoadLibraryW(windows.utf8_to_wstring("example_lib.dll", context.allocator))
    procedure := cast(proc())windows.GetProcAddress(module, "procedure")

    procedure()
}


// Compiled as 'example_lib.dll' with '-no-crt' and '-extra-linker-flags:/noentry' flags.
package dll

@export
procedure :: proc()
{
    string_type_id := typeid_of(string)
    string_type    := type_info_of(string)

    assert(string_type.id == string_type_id)
}
```

**Comment by gingerBill** [comment]
This isn't a bug but a fundamental limitation of runtime type information in Odin. You CANNOT pass RTTI across a DLL boundary whatsoever and expect it to work as expected.

**Comment by englerj** [comment]
Understood. That makes sense. Thank you for the clarity.
