### ISSUE TITLE
Declaring arrays using brace delimited lists broken

### ISSUE THREAD

**Issue by vassvik** [odin-lang/Odin#210]
The following code:
```	
main :: proc() {
	arr1 := [?]int{1, 2, 3};
	arr2 := [?]int{1, 2, 3, 4};
}
```
results in the error 
```
Index 3 is out of bounds (>= 3) for array literal
```
As if the size of the first assignment is used for the second one as well.

Another example:

foo.odin:
```
foo :: proc() {
	arr2 := [?]int{77, 141, 279, 834, 1296, 1675, 1861, 2734, 3094, 2734, 3817, 5828, 8178};
}
```
and
```
import "foo.odin"

main :: proc() {
	arr1 := [?]int{72, 68, 64, 60, 56, 52, 48, 44, 40, 36, 32, 28, 24, 20, 16, 12};
}
```
results in the error
```
test.ll:6023:19: error: constant expression type mismatch
        store [13 x i64] [i64 72, i64 68, i64 64, i64 60, i64 56, i64 52, i64 48, i64 44, i64 40, i64 36, i64 32, i64 28, i64 24, i64 20, i64 16, i64 12], [13 x i64]* %0
                         ^
```

On commit 30f5a3bb9358ded6a48e8d8ba6f5eb0b3743a807, 23rd of March.

**Comment by lunaticLipid** [comment]
@gingerBill Issue still exists after this fix. It causes a similar error if the shorter array comes later.

Same code as in the example, except the order is swapped:

`
main :: proc() {
	arr2 := [?]int{1, 2, 3, 4};
	arr1 := [?]int{1, 2, 3};
}
`

`
main.ll:6015:18: error: constant expression type mismatch
        store [3 x i64] [i64 1, i64 2, i64 3, i64 4], [3 x i64]* %0
`
