### ISSUE TITLE
Compiler does not name outputs when subdirectory is specified 

### ISSUE THREAD

**Issue by jon-lipstate** [odin-lang/Odin#2112]
## Context

When using a subdirectory to build the outputs are unnamed (eg `.exe` instead `foo.exe`). i only tested a subdirectory, possible it is any non `.` path..?

* Operating System & Odin Version:
        Odin: dev-2022-10:ee070c9b
        OS:   Windows 10 Professional (version: 21H2), build 19044.2006
        CPU:  AMD Ryzen 9 3950X 16-Core Processor
        RAM:  32686 MiB

## Expected Behavior

`odin build ./platform` produces `platform.exe` inside `./platform`

## Current Behavior

`odin build ./platform` produces `.exe` inside `./platform` (same for `.pdb` and `.obj`. did not test `dll`, suspect the same)
![image](https://user-images.githubusercontent.com/52809771/194646398-531f9df7-7bfd-42bb-bdc7-553bdc4898c5.png)

`odin build ./platform -out:target/platform.exe --debug` produces `platform.exe` inside `./platform`

### Steps to Reproduce

use relative build path to subdirectory

**Comment by Kelimion** [comment]
Cheers. I'll look into it tomorrow. I have an idea of what it might be.

**Comment by Kelimion** [comment]
The patch affected `-file`. Will take a different approach tomorrow.

**Comment by jrfondren** [comment]
@Kelimion the original bug is back:

```
$ find . -type f
./name/hello.odin
$ odin build name  # or ./name or name/ or $PWD/name/
$ find . -type f
./name/.bin
./name/hello.odin
$ rm name/.bin
$ odin build name -file  # this probably shouldn't be accepted
$ find . -type f
./name/.bin
./name/hello.odin
$ rm name/.bin
$ odin build name/hello.odin -file  # this result is fine
$ find . -type f
./name/hello.odin
./hello.bin
```

**Comment by Kelimion** [comment]
> @Kelimion the original bug is back:
> 
> ```
> $ find . -type f
> ./name/hello.odin
> $ odin build name  # or ./name or name/ or $PWD/name/
> $ find . -type f
> ./name/.bin
> ./name/hello.odin
> $ rm name/.bin
> $ odin build name -file  # this probably shouldn't be accepted
> $ find . -type f
> ./name/.bin
> ./name/hello.odin
> $ rm name/.bin
> $ odin build name/hello.odin -file  # this result is fine
> $ find . -type f
> ./name/hello.odin
> ./hello.bin
> ```

I know. I had to revert the file because it broke something else worse. I'm working on a more complete fix.

**Comment by Kelimion** [comment]
Github mistakenly closed this because of the patch reverting the partial fix named the issue. 🙄

**Comment by Feoramund** [comment]
I'm unable to reproduce this on Linux as of the latest commit.
