### ISSUE TITLE
Casting a float literal to an int issues an error

### ISSUE THREAD

**Issue by shuaDev** [odin-lang/Odin#213]
```
x := 1.5;
y := cast(int)x;
```

works fine but

```
y := cast(int)1.5;
```

causes a compiler error that says `Cannot cast '1.5' as 'int' from 'untyped float'`

**Comment by thebirk** [comment]
Also errors with typed floats
```
a := cast(int) f32(1.5);
```

**Comment by gingerBill** [comment]
This is not an bug. This is by design.
`1.5` cannot be represented by `int`. However, `1.0` can be represented by `int`. This is how the constant system should work.

**Comment by Tetralux** [comment]
If you want to have somewhat strict conversion rules, then for `cast` that makes some sense--for `transmute` too though? Which also doesn't work here.

If `cast` does not allow you to do this, then shouldn't `transmute` allow you to do this and have the error when using `cast`, suggest the use of `transmute` to you?

**Comment by gingerBill** [comment]
`transmute` is just a bit cast. As long as the sizes of the source and destination types are equation, there should be no issue.
