### ISSUE TITLE
strconv.parse_f64 accuracy issue?

### ISSUE THREAD

**Issue by chancyk** [odin-lang/Odin#2131]
## Context

I was actually just playing around trying to write my own float parser, but I noticed Odin gives slightly different results than I expected. I'm certainly no expert in this area.

System:
        Odin: dev-2022-09-nightly:74458ab0
        OS:   Windows 11 Professional (version: 22H2), build 22621.674
        CPU:  Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

## Expected Behavior

Base on: https://www.geeksforgeeks.org/ieee-standard-754-floating-point-numbers/
85.125 has an exact float64 binary representation of: 
```
0 10000000101 0101010010000000000000000000000000000000000000000000
```

## Current Behavior

Odin produces:

```odin
package testparsef64
import "core:fmt"
import "core:strconv"
main :: proc () {
    val, ok := strconv.parse_f64("85.125")
    if (ok) {
        fmt.printf("Result: %.15f\n", val)
        fmt.printf("Binary: %b\n", transmute(u64)val)
    }
}

// Result: 85.124999999999986
// Binary: 100000001010101010001111111111111111111111111111111111111111111
```

**Comment by 13419596** [comment]
Just so you know, Odin's float printing is broken for semi-large float numbers, so don't rely on it for it for comparison.

https://github.com/odin-lang/Odin/issues/2068

**Comment by gingerBill** [comment]
`strconv.parse_f64` has been improved in the latest commit
