### ISSUE TITLE
strange runtime errors if ^testing.T is assigned to a global and reused

### ISSUE THREAD

**Issue by jrfondren** [odin-lang/Odin#2132]
## Context

with latest odin:

        Odin: dev-2022-10:412ca362
        OS:   Manjaro Linux, Linux 5.10.147-1-MANJARO
        CPU:  Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
        RAM:  15953 MiB

and this complete program:

```odin
package testptr

import "core:fmt"
import "core:testing"

works :: proc(t: ^testing.T) {
	testing.expect(t, 1 == 1)
}

p: ^testing.T
breaks :: proc() {
	testing.expect(p, 1 == 1)
}

@(test)
testptr :: proc(t: ^testing.T) {
	testing.expect(t, 1 == 1)
	works(t)
	//p = t
	//breaks()
}
```

## Current Behavior

As written, the above tests successfully:

```
$ odin test testptr.odin -file
[Package: testptr]
[Test: testptr]
[testptr : SUCCESS]
----------------------------------------
1/1 SUCCESSFUL
```

When the two commented lines are uncommented, the above produces garbage output:

```
$ odin test testptr.odin -file|od -c
0000000 340 340 340 340 340 340
0000006
$ odin test testptr.odin -file|od -c
0000000   p   p   p   p   p   p
0000006
```

## Expected Behavior

For mere pointer assignments to not break the tester like this, for `breaks()` to be equivalent to `works(t)`. It feels like I'm accidentally invoking a C++ copy constructor or something, which is not what I expect from a pointer type in Odin.

Code like this might have a harder time with a threaded test runner, but threads don't seem to be involved here.

## Why would you ever do that?

I suspected that contract programming could be possible to an extent, and reproduced an example of it from Programming in Ada 2012:

```odin
when ODIN_TEST {
	// why not user context.user_ptr ?  Because if other tests elsewhere 
	// incidentally involve stacks, it won't be as expected.
	stack_testing_ptr: ^testing.T
	expect :: proc(ok: bool, msg: string = "", loc := #caller_location) -> bool {
		if stack_testing_ptr == nil do return ok
		testing.expect(stack_testing_ptr, ok, msg, loc)
		return ok
	}
}

...

push :: proc(st: ^Stack($T), obj: T) {
	when ODIN_TEST do expect(!is_full(st^)) // precondition
	defer when ODIN_TEST do expect(!is_empty(st^)) // postcondition
	append(&st.stack, obj)
}

pop :: proc(st: ^Stack($T)) -> T {
	when ODIN_TEST do expect(!is_empty(st^)) // precondition
	return builtin.pop(&st.stack)
}
```

### Mitigation

Just discovered, the problem goes away completely if the global has type `rawptr`. So probably this is some rewriting of `testing.T` types.

```odin
package testptr

import "core:fmt"
import "core:testing"

works :: proc(t: ^testing.T) {
	testing.expect(t, 1 == 1)
}

p: rawptr
also_works :: proc() {
	// bad test to confirm line
	testing.expect(transmute(^testing.T)p, 1 == 2)
}

@(test)
testptr :: proc(t: ^testing.T) {
	testing.expect(t, 1 == 1)
	works(t)
	p = t
	also_works()
}
```

**Comment by gingerBill** [comment]
This is not a bug, per se. This is because tests are ran in parallel and each `testing.T` parameter is unique to that test. So this global variable is being overwritten by another thread, and thus why it breaks.
