### ISSUE TITLE
Expressions with transmute should be constant when the thing they are transmuting is also constant.

### ISSUE THREAD

**Issue by Sanian-Creations** [odin-lang/Odin#2140]
## Suggestion
Expressions with `transmute` should be constant when the thing they are transmuting is also constant.

## Context
Values that are in theory constant, cannot be assigned to constants if they use `transmute` in their definition.

For example, this snippet from the Overview page which explains how transmute works:
```odin
f := f32(123)
u := transmute(u32)f
```
All values involved are known at compile time and do not call to any procedures. So, making both constant should work in theory.
```odin
f :: f32(123)
u :: transmute(u32)f
```
We can't however, because `'transmute(u32)f' is not a constant`.

`u` should by all means be constant, because `f` is constant, and `transmute` by definition does not change the bits of `f`, it only assigns them a different type (quote: _"The transmute operator is a bit cast conversion between two types of the same size"_).

Another example it should work for, is to assign hex values to signed integers, even if those hex values write to the sign bit
```odin
// store 0x80000000 as a constant i32
x80000000 ::                i32(0x80000000);  // X  - Cannot cast '0x80000000' as 'i32' from 'untyped integer'
x80000000 ::      cast(i32) u32(0x80000000);  // X  - Cannot cast 'u32(0x80000000)' as 'i32' from 'u32'
x80000000 :: transmute(i32) u32(0x80000000);  // X  - 'transmute(i32)u32(0x80000000)' is not a constant
x80000000 ::              ~ i32(0x7FFFFFFF);  // OK - Forced to write this, completely changing the hex,
x80000000 ::          ~i32(~u32(0x80000000)); // OK - or this, both making the expression more convoluted and hard to read,
                                              // all just to make sure the sign bit isn't 1 when casting
```

**Comment by gingerBill** [comment]
We now support this for integers but not for floats _yet_.

**Comment by chrisdavies** [comment]
I just ran into this with strings, though I'm a total Odin n00b, so I could be doing it wrong. I'm going through [this](https://viewsourcecode.org/snaptoken/kilo/03.rawInputAndOutput.html#reposition-the-cursor), but with Odin.

Doesn't work:

```odin
os.write(os.stdout, transmute([]u8)"\x1b[2J")
```

Does work:

```odin
s := "\x1b[2J"
os.write(os.stdout, transmute([]u8)s)
```

**Comment by jasonKercher** [comment]
@chrisdavies String literals are constants that do not have an address.  Therefore, it doesn't make sense to be able to take a pointer and a length from it.  Here is an example that shows this better:
```odin
package main
import "core:fmt"

S :: "hello"                                                                                                                                                              
main :: proc() {
    fmt.println(&S)
}
```
yields:
```none
/home/jason/a.odin(7:14) Error: Cannot take the pointer address of 'S' which is a constant
        fmt.println(&S)
                    ^
```

**Comment by gingerBill** [comment]
I am closing this issue now because the latter 3 examples in the original issue now work.
