### ISSUE TITLE
null-terminated odin string

### ISSUE THREAD

**Issue by lunaticLipid** [odin-lang/Odin#215]
https://github.com/odin-lang/Odin/blob/49dd299999d9daa550151a0338f0c770212ab57b/core/strings.odin#L4-L9

Not sure if this is a bug because maybe odin strings are supposed to be null terminated for some reason but this looks like a copy-and-forget bug based on the function below this one.

**Comment by zhiayang** [comment]
I think it makes sense for C interoperability to have null-terminated strings even if you store a length. This way you can just pass the pointer directly to C functions.

**Comment by lunaticLipid** [comment]
I thought it could be something like that, but now we have the cstring type that we can pass to bindings and whatever, and the new_cstring proc adds a nul terminator for us. Also, we can make a string from a slice taken out of another string, which isn't nul-terminated.

**Comment by gingerBill** [comment]
This is not a bug but by design. It's mostly a safety feature.
