### ISSUE TITLE
Build-time Assertion in `src/llvm_backend_general.cpp` when assigning ptr through multiple `using`s

### ISSUE THREAD

**Issue by jceipek** [odin-lang/Odin#2160]
## Context

```
        Odin: dev-2022-10
        OS:   macOS Monterey 12.5 (build: 21G115, kernel: 21.6.0)
        CPU:  Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
        RAM:  32768 MiB
```

```odin
package main

A :: struct {}
B :: struct{using _: A}
C :: struct{using _: B}

main :: proc () {
    c: ^C = nil // Silently works if this is `^B` instead
    a: ^A = c
}
```

I encountered this error in the context of `@objc_class` `struct`s (see https://github.com/odin-lang/Odin/issues/2158), but I think this is a more concise formulation of the problem.

## Expected Behavior

I would either expect the program to compile successfully or to get an error like:
```
Cannot assign value 'c' of type '^C' to '^A' in variable declaration
```

I'm not sure which is more appropriate.

## Current Behavior

Attempting to build results in:
```
src/llvm_backend_general.cpp(960): Assertion Failure: `are_types_identical(a, value.type)` ^A != ^B
Illegal instruction: 4
```

### Steps to Reproduce

1. Build the above program with odin `build .`

**Comment by gingerBill** [comment]
Your expected behaviour is not correct. This should work because of the double `using`. This is backend bug that needs correcting.
