### ISSUE TITLE
Cannot compile if #optional_ok tag is on new line

### ISSUE THREAD

**Issue by 13419596** [odin-lang/Odin#2163]
## Context

It is expected that the whitespace around tag `#optional_ok` (or any tag for that matter), should not matter. Instead if a newline precedes the optional_ok tag, then the compiler fails to recognize it as legitimate and does fails to compile.

There  is an obvious work-around is to not put the tag on a newline, or to not use the tag at all. However `ols` will, if the line is long enough, put the tag on a new line and thus cause the error. 

#### Odin Report
```
	Odin: dev-2022-10:a5f8c3f6
	OS:   macOS Monterey 12.5 (build: 21G115, kernel: 21.6.0)
	CPU:  ARM64
	RAM:  16384 MiB
```

## Expected Behavior

It is expected that the following snippet compiles without error
```odin
package main

foo :: proc() -> (out:int, ok:bool)
#optional_ok {
  return
}

main :: proc() {
}
```

## Current Behavior

The code snippet fails to compile with the following compiler errors:
```
main.odin(4:1) Syntax Error: Unknown tag directive used: 'optional_ok'
main.odin(5:9) Syntax Error: You cannot use a return statement in the file scope
main.odin(6:1) Syntax Error: Expected a statement, got '}'
```

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Attempt to compile the code snippet.

**Comment by gingerBill** [comment]
Not a bug, per se. If you want it on a separate line, use `\` to consume the newline character.

**Comment by 13419596** [comment]
> Not a bug, per se. If you want it on a separate line, use `\` to consume the newline character.

I thought white space wasn’t significant in Odin. Is there a reason the return type be on a newline but not the tag directive here?

**Comment by gingerBill** [comment]
> I thought white space wasn’t significant in Odin within a statement / declaration.

That is incorrect. In order to have optional semicolons, there has to be special tokenization and syntax rules, meaning there is a minor form of significant whitespace (i.e. newlines). This is the case in pretty much EVERY language with optional semicolons. Odin just has a few more to make it feel like it doesn't have many.
