### ISSUE TITLE
Use of `d3d11.WKPDID_D3DDebugObjectNameW` causes link error

### ISSUE THREAD

**Issue by cshenton** [odin-lang/Odin#2174]
## Context

```
        Odin: dev-2022-11-nightly:df19c48d
        OS:   Windows 11 Home Basic (version: 21H2), build 22000.1098
        CPU:  AMD Ryzen 9 5900X 12-Core Processor
        RAM:  32671 MiB
```

## Expected Behavior

`"vendor:directx/d3d11"` should link system libraries for all symbols it exports. 

## Current Behavior

Attempts to use `WKPDID_D3DDebugObjectNameW` (which is used in `SetPrivateData` calls to expose readable names to external graphics debuggers like RenderDoc) causes link errors.

```
odin build .
.obj : error LNK2019: unresolved external symbol __imp_WKPDID_D3DDebugObjectNameW referenced in function app.main
app.exe: fatal error LNK1120: 1 unresolved externals
```

This [gamedev.net thread](https://gamedev.net/forums/topic/604418-wkpdid_d3ddebugobjectname-link-error/4833386/) suggests the solution is to link `dxguid.lib`. My naive attempts to do that in `d3d11.odin` didn't work but I'm not super savvy with the foreign import system in odin.

### Steps to Reproduce

`odin run .` the following:

```odin
package main

import "vendor:directx/d3d11"
import "core:fmt"

main :: proc() {
    fmt.println(d3d11.WKPDID_D3DDebugObjectNameW)
}
```

**Comment by elusivePorpoise** [comment]
The packages are wrong, GUIDs should be defined and not imported:

```
WKPDID_D3DDebugObjectNameW :: GUID{0x4cca5fd8, 0x921f, 0x42c8, 0x85, 0x66, {0x70, 0xca, 0xf2, 0xa9, 0xb7, 0x41}}
```

and you can use a helper function like this:

```
@(deferred_out=free_refiid)
as_refiid :: proc(guid: GUID)->(refiid: ^GUID){
	refiid = new(GUID)
	refiid^ = guid
	return
}
free_refiid :: proc(refiid: ^GUID){free(refiid)}


SetPrivateData(as_refiid(WKPDID_D3DDebugObjectNameW), ...)
```

I think it has to do with C's usage of macros to define these things which causes problems.
