### ISSUE TITLE
Fix core:math inverse trig functions

### ISSUE THREAD

**Issue by JesseRMeyer** [odin-lang/Odin#2175]
https://github.com/odin-lang/Odin/blob/503b8976771362be757966eb5f54653dae005e21/core/math/math.odin#L1391-L1410

https://wikimedia.org/api/rest_v1/media/math/render/svg/7dd6a9370a877ca5e198e28b7582bd06b377bdc3

**Comment by JesseRMeyer** [comment]
As of: https://github.com/odin-lang/Odin/commit/ff36b754cb626f9250794e94d89b429f84e95c29

```odin
	should_be_one := math.sin(math.asin(f32(1)))
	fmt.println(should_be_one)

	should_be_one = math.cos(math.acos(f32(1)))
	fmt.println(should_be_one)
```
0.000
-1.000

**Comment by gingerBill** [comment]
These should fixed now.
