### ISSUE TITLE
Missing import line in demo program on Odin home page

### ISSUE THREAD

**Issue by wfdoran** [odin-lang/Odin#2182]
## Context

	Odin: dev-2022-11-nightly:382bd876
	OS:   Ubuntu 20.04.5 LTS, Linux 5.15.0-52-generic
	CPU:  Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	RAM:  11866 MiB

## Expected Behavior

Compile without error.

## Current Behavior

```
../ubuntu_artifacts/odin build context.odin -file
.../context.odin(45:25) Undeclared name: mem
.../context.odin(45:2) Invalid declaration type 'mem.nil_allocator'
```

## Failure Information (for bugs)

Missing import line. 

```
package main

import "core:mem"

main :: proc() {
```

Adding import line fixes bug.

### Steps to Reproduce

1) Go to https://odin-lang.org/
2) In pull down menu select `Context System`
3) Copy code to file context.odin
4) Attempt to build.

**Comment by Kelimion** [comment]
Fixed via https://github.com/odin-lang/odin-lang.org/commit/6dc08429d35ce77d56e5c9be3b3556f888b88e35
