### ISSUE TITLE
Writing to pipe freezes program? is this correct behavior?

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2187]
Hello, I have to following code:

cmds_r, cmds_w, cmd_err := os.pipe();
fmt.fprintln(cmds_w, "gnuplot -persistent\n");

This will freeze the program, is this correct behavior?
I want to open gnuplot from my program, how would I do this?

**Comment by Kelimion** [comment]
https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-createpipe

> When a process uses [WriteFile](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-writefile) to write to an anonymous pipe, the write operation is not completed until all bytes are written. If the pipe buffer is full before all bytes are written, WriteFile does not return until another process or thread uses [ReadFile](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile) to make more buffer space available.

It will not return until something reads from that pipe, so this is indeed expected behavior.

If you want to start a program, you can use the following:
```odin
package main

import "core:c/libc"

main :: proc() {
	libc.system("calc.exe")
}
```

A planned `process` package will in the future allow you to start a process and communicate with it using stdin and stdout.

**Comment by xzores** [comment]
I need to do more then just call gnuplot, i need to talk with it after it has opened gnuplot.

How would I do this in Odin?

**Comment by Kelimion** [comment]
> A planned process package will in the future allow you to start a process and communicate with it using stdin and stdout.

**Comment by xzores** [comment]
So it is not possiable atm?

**Comment by Kelimion** [comment]
It's entirely possible if you call the requisite OS APIs yourself, but there's no user-friendly wrapper in `core` that does this for you, yet. The odds are decent that we'll have a `process` package in December or January, one that lets you start up and communicate with other executables. Until then you'd have to write your own implementation.
