### ISSUE TITLE
Erroneous "illegal type declaration cycle" error for the matrix type

### ISSUE THREAD

**Issue by frightster** [odin-lang/Odin#2188]
## Context

* Operating System & Odin Version: WIndows 10, master
* Please paste `odin report` output: 
*  Odin: dev-2022-11:79baddc1
        OS:   Windows 10 Professional (version: 21H2), build 19044.2251
        CPU:  Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
        RAM:  24504 MiB

## Expected Behavior

Matrices should work with distinct numbers.

## Current Behavior

The original distinct number is reported as being an illegal type declaration.

### Steps to Reproduce

```
// a.odin
package testa
sometype :: distinct i32

// b.odin
package testa
mattype :: distinct matrix[4, 4]sometype
```
### Failure Logs

a.odin(3:1) Illegal type declaration cycle of `sometype`

**Comment by Kelimion** [comment]
I'd like to add that it would be lovely if these declaration cycles produce an error message similar to this one:
```odin
package main

main :: proc() {
    i32 :: distinct a32
    a32 :: distinct b32
    b32 :: distinct i32
}

W:/Odin-other/Odin-test/foozle/foozle.odin(4:2) Illegal declaration cycle of `i32`
W:/Odin-other/Odin-test/foozle/foozle.odin(5:2)     a32 refers to
W:/Odin-other/Odin-test/foozle/foozle.odin(6:2)     b32 refers to
W:/Odin-other/Odin-test/foozle/foozle.odin(4:2)     i32
```
