### ISSUE TITLE
Compiler panic when printing imported function group

### ISSUE THREAD

**Issue by frightster** [odin-lang/Odin#2201]
## Context

Odin: dev-2022-11:79baddc1
        OS:   Windows 10 Professional (version: 21H2), build 19044.2251
        CPU:  Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
        RAM:  24504 MiB

## Expected Behavior

Using `println` on a function group prints the function group address.

## Current Behavior

The compiler panics when this is used on an imported function group.

### Steps to Reproduce

```go
//bug.odin
package test

func1 :: proc() {}
func2 :: proc(v: int) {}

func :: proc {
	func1, func2,
}

//main.odin
package main

import "core:fmt"
import "core:math"
import b "bug"

func1 :: proc() {}
func2 :: proc(v: int) {}

func :: proc {
	func1, func2,
}

main :: proc() {
	fmt.println(func) // proc() @ 7FF6064CC5F0
	fmt.println(b.func) // Odin\src\llvm_backend_type.cpp(914): Panic: UNHANDLED ENTRY 2 (148)
	fmt.println(math.modf) // Odin\src\llvm_backend_type.cpp(914): Panic: UNHANDLED ENTRY 1 (150)
}
```

**Comment by gingerBill** [comment]
This is a frontend bug as there is no runtime location of the procedure groups.
