### ISSUE TITLE
Error build from source in MacOS, headers problem

### ISSUE THREAD

**Issue by reducio** [odin-lang/Odin#2209]
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/6662917/203875959-e1b415b6-6f1f-44d1-bc4a-b66491be3993.png">

OS: MacOS Ventura 13.0.1 (22A400)

But I haven't Packages folder by it path, so this step is skipped.
> On newer versions of macOS, some headers are not installed by default. Open macOS_SDK_headers_for_macOS_*.pkg in /Library/Developer/CommandLineTools/Packages/.

I use build from source that last commit d6cb105d5f29506fc64abbccf8767a79539de1ae in master branch.

Thank for help!

**Comment by reducio** [comment]
Solved.

After update to MacOS Ventura 13.0.1 (22A400) - `Xcode` is fail.
I downloaded `Command Line Tools for Xcode 14.1` here:  https://developer.apple.com/download/all/

**Comment by Kelimion** [comment]
Thanks for the update. Glad you got it solved. I had to update xcode as well after the update to Ventura.
