### ISSUE TITLE
New Maps and Allocators

### ISSUE THREAD

**Issue by krixano** [odin-lang/Odin#2214]
## Context

There's an odd bug that I've found that involves the interaction between an allocator (Arena specifically) and the map. For some reason that is y'alls job to have found and fixed, when an allocator is set, only the first 47 elements are added to the map (regardless of Arena size). Otherwise, when no allocator is set, all elements are added. It doesn't work with the regular Arena or the virtual Arena, which would have been found had this been tested before the new maps PR was merged.

* Operating System & Odin Version: commit c663566, Windows 11

## Expected Behavior

It to work, obviously.

## Current Behavior

It doesn't work.

### Steps to Reproduce

```odin
package main

import "core:fmt"
import "core:mem"

B :: 1;
KB :: 1024 * B;
MB :: 1024 * KB;
GB :: 1024 * MB;
TB :: 1024 * GB;

Key :: struct {
    x: int,
    y: int,
    z: int,
}
Blah :: struct {
    test: int,
}
blah: map[Key]^Blah;

main :: proc() {
    guiArena: mem.Arena;
    allocator_data := make([]byte, 5 * MB); // Same error when 5 or 500 MB.
    mem.arena_init(&guiArena, allocator_data);
    guiAllocator := mem.arena_allocator(&guiArena);

    context.allocator = guiAllocator;
    blah = make(map[Key]^Blah);

    for i in 0..<5000 {
        blahV := new(Blah, guiAllocator);
        blah[Key { i, -1, -1 }] = blahV;
        test := blah[Key { i, -1, -1 }];
        fmt.printf("%d: %s\n", i, test);
        if test == nil {
            // Breaks when got to first nil
            break;
        }
    }
}
```

**Comment by gingerBill** [comment]
This is now fixed
