### ISSUE TITLE
os.open() fails to open directory on Darwin arm64

### ISSUE THREAD

**Issue by samloeschen** [odin-lang/Odin#2217]
`odin report` output:
```
        Odin: dev-2022-11:a27c0086
        OS:   macOS Monterey 12.4 (build: 21F2081, kernel: 21.5.0)
        CPU:  ARM64
        RAM:  24576 MiB
```

## Expected Behavior

`os.open()` should be able to open directories with correct permissions.

## Current Behavior

`os.open()` fails with error code 1, regardless of `mode` or `perm` arguments. however, using `os.open()` on individual files works correctly, and it works as expected on Windows.
### Steps to Reproduce

1. Download and extract attached example
2. `odin run .` in containing folder 

### Failure Logs

On darwin arm64 the output should be:
```
os is Darwin, arch is arm64
Exists? true
Is dir? true
<repro folder>/main.odin(16:13) Panic: Unable to open folder dir. Error 1
```
[odin-os-open-repro.zip](https://github.com/odin-lang/Odin/files/10097696/odin-os-open-repro.zip)

**Comment by MrStevns** [comment]
In order to use open() on a directory on darwin, you'd have to use the O_DIRECTORY mode which works when inputted manually (0x00100000)

It's true however that the case doesn't exist as of right now.

**Comment by Platin21** [comment]
So it's an easy fix then just adding that flag. Btw. in sys/darwin there are some wrappers for this stuff already just not as integrated..

**Comment by Platin21** [comment]
Hmm seems to not be open that doesn't like the dir but something else..
