### ISSUE TITLE
math.remap fails with integers, may trap on overflow

### ISSUE THREAD

**Issue by frightster** [odin-lang/Odin#2235]
## Context
Odin: dev-2022-11:79baddc1
        OS:   Windows 10 Professional (version: 21H2), build 19044.2251
        CPU:  Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
        RAM:  24504 MiB

## Expected Behavior

`math.remap` is marked to work with all numerics, and should work with floats and integers.

## Current Behavior

`math.remap` only works with floats; it will return incorrect values for integers, and may even trap on overflow in some edge cases.

## Failure Information (for bugs)
`math.remap(input, min(i16), max(i16), 0, 127)` resulted in a trap on overflow, shown below.

`math.remap(i64(input), -100_000, 100_000, -100, 100)` yields results like the following:
```
Input: -16573
Result: -100
Input: -9356
Result: -100
Input: -8542
Result: -100
Input: -1647
Result: -100
Input: -1194
Result: -100
Input: 536
Result: -100
Input: 1312
Result: -100
Input: 1520
Result: -100
Input: 1728
Result: -100
```

### Failure Logs
![image](https://user-images.githubusercontent.com/118065824/206339397-c25f25a3-2c3e-4e01-b0fd-fbbe68f7820b.png)

**Comment by Kelimion** [comment]
For sane, real world inputs like remapping a value in range 0..1 to 0..255, this procedure works as expected. It's up to the user to not supply contrived inputs that overflow, upcasting to a bigger type as necessary..
