### ISSUE TITLE
Compiler gets confused by array/struct literal in if statement

### ISSUE THREAD

**Issue by kururen** [odin-lang/Odin#2243]
## Context
 
* Operating System & Odin Version:
        Odin: dev-2022-12-nightly:521ed286
        OS:   Windows 11 Professional (version: 22H2), build 22621.900
        CPU:  Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
        RAM:  16301 MiB

## Expected Behavior

An array or struct literal can be defined inside an if condition to compare against.

## Current Behavior

An array or struct literal inside an if conditional causes to compiler to emit an error.

### Steps to Reproduce
Repro code:

```
package bug

import "core:fmt"

Point :: [2]int
Vec2 :: struct { x, y: int }

main :: proc() {
    p := Point{1, 2}
    if p == Point{1, 2} do fmt.println("array equal") // <-- error

    v := Vec2{2, 3}
    if v == Vec2{2, 3} { // <-- error
        fmt.println("struct equals")
    }

    equal := p == Point{2, 3} // works fine
}
```

### Failure Logs
`Syntax Error: Expected 1 expression`

If using `if ... do ...`
`Syntax Error: Expected a statement, go 'do'`

**Comment by Kelimion** [comment]
You don't need the type on the literal:
```odin
    p := Point{1, 2}
    if p == {1, 2} do fmt.println("array equal") // <-- works

    v := Vec2{2, 3}
    if v == {2, 3} { // <-- also works
        fmt.println("struct equals")
    }
```

**Comment by Kelimion** [comment]
That said, I do feel like it's a bug you're not allowed to specify the type for clarity in these cases, even though they're redundant.

**Comment by kururen** [comment]
Thank you for the info!

I forgot to mention that putting parenthesis around the condition actually fixes the problem:

`if (p == Point{1, 2}) do fmt.println("array equal")`

works just fine, so that part does work. It seems more likely that the type trips up the parser and makes it think the condition is over before parsing to the end.

**Comment by gingerBill** [comment]
This isn't a bug but just an intrinsic ambiguity in the syntax because if statements don't require parentheses. The two solutions to this problem are:

```odin
if p == {1, 2} {...}
```
or
```odin
if (p == Vec2{1, 2}) {...}
```
