### ISSUE TITLE
Allow spreading fixed arrays into non-vararg arguments

### ISSUE THREAD

**Issue by Beefster09** [odin-lang/Odin#2258]
# PLEASE POST THIS IN THE DISCUSSION TAB UNDER "PROPOSALS" OR "IDEAS/REQUESTS"

**Is your feature request related to a problem? Please describe.**
When working with certain apis such as OpenGL, often xyz or rgba values are specified in multiple arguments. If your source is a fixed array, you're forced to do this:

```
// bg_color is a [4]f32
gl.ClearColor(bg_color[0], bg_color[1], bg_color[2], bg_color[3])
```

**Describe the solution you'd like**
It should be possible to do this:

```
gl.ClearColor(..bg_color)
```

**Additional context**
It's understandable that it wouldn't be possible to spread *slices* into non-vararg positions since slices do not have a length known at compile time, but that is not the case for fixed arrays, and it should be relatively simple to spread the array across several same-typed arguments since the spread can essentially be translated into a fixed number of array indexes.

**Comment by gingerBill** [comment]
This is already possible with the built in procedure `expand_to_tuple`
