### ISSUE TITLE
LLVM error message on indexing of a constant matrix

### ISSUE THREAD

**Issue by ftphikari** [odin-lang/Odin#2267]
## Context

        Odin: dev-2022-12:56e050fb
        OS:   Windows 10 Unknown Edition (0000007d) (version: 21H2), build 19044.2364
        CPU:  Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
        RAM:  16263 MiB

## Example code
```odin
package bug

import "core:fmt"

main :: proc() {
	a: matrix[2, 2]int : {
		0, 1,
		1, 0,
	}
	for i in 0..<2 {
		fmt.println(a[i, 0])
	}
}
```

## Expected
A proper error message

## Got
```
LLVM Error:
Use of instruction is not an instruction!
  %7 = add i64 %.0, 0, !dbg !9903
```

**Comment by Skytrias** [comment]
should probably be not allowed, as constant arrays are also not able to be indexed into :thinking:
