### ISSUE TITLE
`linalg.transpose` segfaults for `Matrix3f64`

### ISSUE THREAD

**Issue by drbassett** [odin-lang/Odin#2274]
## Context

Odin: dev-2022-12-nightly:521ed286
OS: Windows 10 Home Basic (version: 21H2), build 19044.2364
CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
RAM: 16285 MiB

## Expected Behavior

`linalg.transpose` doesn't cause a segfault

## Current Behavior

`linalg.transpose` segfaults with a  `Matrix3f64`

## Failure Information (for bugs)

I also tested some adjacent functions, and these do not cause a segfault. The other functions I tested include:

* `linalg.transpose` with `linalg.Matrix3f32`
* `linalg.transpose` with `linalg.Matrix4f64`
* `linalg.matrix3_inverse_transpose` with `linalg.Matrix3f64`

The problem seems to be unique to `linalg.transpose` with `linalg.Matrix3f64`.

I recall reading that Odin uses SIMD operations to implement matrix operations, so I'm guessing this segfault is related to that. If this is the case, this issue may be unique to `x86`.

### Steps to Reproduce

Run this Odin program:

```odin
package transpose_crash

import "core:math/linalg"

main :: proc() {
	_ = linalg.transpose(linalg.Matrix3f64(0))
}
```

## Other Information

For anyone else running into this bug, I wrote my own transpose function as a workaround:

```odin
swap :: proc(a: ^$T, b: ^T) {
	tmp := a^
	a^ = b^
	b^ = tmp
}

transpose_matrix3_f64 :: proc(m: linalg.Matrix3f64) -> linalg.Matrix3f64 {
	mt := m
	swap(&mt[0,1], &mt[1,0])
	swap(&mt[0,2], &mt[2,0])
	swap(&mt[1,2], &mt[2,1])
	return mt
}
```

**Comment by Platin21** [comment]
Yes this bug is unique to the Abi e.g doesn't happen on arm64..
