### ISSUE TITLE
json unmarshal fails on some float inputs

### ISSUE THREAD

**Issue by ftphikari** [odin-lang/Odin#2277]
## Context

        Odin: dev-2022-12:56e050fb
        OS:   Windows 10 Unknown Edition (0000007d) (version: 21H2), build 19044.2364
        CPU:  Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
        RAM:  16263 MiB

## Code
```odin
package bug

import "core:fmt"
import "core:encoding/json"

Data :: struct {
	a: f32,
}

main :: proc() {
	data: Data
	str := `{"a":0.011111111111111111111}`
	bytes := transmute([]u8)str
	json.unmarshal(bytes, &data)
	fmt.println(data)
}
```

## Expected behavior
The program parses the number truncated.

## Ouput
The program hangs.

**Comment by DragosPopse** [comment]
tracked it down to the parsing of floats. Looking into it further. It's not exactly a json marshalling error, it's `strconv`

**Comment by DragosPopse** [comment]
The bug goes further, because  `str := {"a":0.81111111111111111}` will output `data = 0.0`

**Comment by nico-bb** [comment]
I also had to do some digging recently and it indeed is `strconv.float64()` that doesn't handle high number of digit places (around 15-17+). It is very unexpected because the json parser silently ignores the error value from `float64()` and as a user you don't even realize that it may have failed.

**Comment by ftphikari** [comment]
Seems this bug was fixed by commit ea9fe397e572b33f4db70a878ef7c5fc6b8c5d43, can people here confirm?

**Comment by MarenFayre** [comment]
So, I wrote a script to brute force all the f32,
I wanted to test the "float-to-string" part against my [bindings to fastfloat](https://github.com/MarenFayre/odin-fastfloat), then validate every value for `parse_f32`.

But the first test was actually tripped during ftoa, this value:
```odin
import "core:fmt"
main :: proc() {
    buf: [4096]u8
    fmt.bprintf(buf[:], "%.170f", f32(16777216.0))

    fmt.println(16777216.0)   // 16777216.000
    fmt.printf("%s\n", buf)   // 16777210.0000000000000000000000000000000.......
}                             //        ^ Error
```

And here is the complete test I was doing:
```odin
package test_all

import "core:strconv"
import "core:fmt"
import "../fastfloat"

is_nan :: proc(f: f32) -> bool {  // I think this is correct?
    bits := transmute(u32)(f)
    exponent_mask :u32 = 0b01111111_10000000_00000000_00000000
    mantissa_mask :u32 = 0b00000000_01111111_11111111_11111111

    return ((bits & exponent_mask) == exponent_mask) && ((bits & mantissa_mask) != 0)
}

main :: proc() {
    start := u32(0b01001011011001100101111001000000) // It tripped after here, no point in waiting 20min...
    for i in u32(start)..=0xFFFF_FFFF {
        backing: [4096]u8
        buf := backing[:]

        f := transmute(f32)(i)
        fmt.bprintf(buf, "%.170f", f)

        a, b := fastfloat.parse_f32(string(buf))  // 1rst test that tripped ftoa.
        //a, b := strconv.parse_f32(string(buf))  // What I want to test afterwards

        /* Print where we're at every ~second */
        if i % 5_000_000 == 0 do fmt.printf("%32b | %32b\n", i, transmute(u32)(a))

        if !b {
            fmt.printf("=========== Parsing error.")
            fmt.printf("BUFFER=%s\n", buf)
            fmt.printf("%32b | https://float.exposed/0x%8x\n", i, i)
            assert(false)
        }

        if !(i == transmute(u32)(a) || (is_nan(f) && is_nan(a))) {
            fmt.println("=========== Error:")
            fmt.printf("BUFFER=%s\n", buf)
            fmt.printf("bits   = %32b | https://float.exposed/0x%8x\n", i, i)
            fmt.printf("parsed = %32b | https://float.exposed/0x%8x\n", transmute(u32)(a), transmute(u32)(a))
            assert(false)
        }
    }
}
```

**Comment by gingerBill** [comment]
@MarenFayre Your code doesn't test what you think it tests.

```odin
fmt.println(16777216.0)      // 16777216.000
fmt.println(f32(16777216.0)) // 16777210.000
fmt.println(f32(0h4b800000)) // 16777216.000
```

This shows an issue with the Odin compiler itself not the Odin core library. The Odin core library parses it correctly. I think the bug lies with LLVM not representing the float correctly as it treats `f32` and `f16` as just a truncated `f64`. LLVM is bizzare.

**Comment by gingerBill** [comment]
`LLVMConstReal` seems to be the blame for everything.
