### ISSUE TITLE
Inconsistent compilation of `sync.atomic_load`

### ISSUE THREAD

**Issue by ftphikari** [odin-lang/Odin#2290]
## Context

        Odin: dev-2023-01:782f1b47
        OS:   Windows 10 Unknown Edition (0000007d) (version: 21H2), build 19044.2364
        CPU:  Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
        RAM:  16263 MiB

## Code

```odin
package bug12

import "core:fmt"
import "core:sync"

main :: proc() {
	a: [2]i32 = {2, 10}
	fmt.println(sync.atomic_load(&a))
}
```

## Expected:

To compile/not compile consistently.

## Got:

When compiled with -debug: works

When compiled without -debug:
> LLVM CODE GEN FAILED FOR PROCEDURE: bug12.main
define internal void @bug12.main(i8* noalias nocapture nonnull %__.context_ptr) {
decls:
  %0 = alloca [2 x i64], align 8
  %1 = alloca %..any, align 8
  %2 = alloca { %..any*, i64 }, align 8
  %3 = alloca [1 x %..any], align 8
  %4 = alloca %..string, align 8
  br label %entry
...
atomic load operand must have integer, pointer, or floating point type!
 [2 x i64]  %6 = load atomic [2 x i64], [2 x i64]* %0 seq_cst, align 8

**Comment by gingerBill** [comment]
Fixed in c819c350
