### ISSUE TITLE
register_user_formatter cause Panic: Invalid type conversion

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2305]
## Context
I am running version dev-2023-01-nightly:86511d44 on windows 11

I get the following error:
PS D:\GitHub\Hadl\Odin> odin build . -out:my_program.exe
main.main
lb_emit_conv: src -> dst
Not Identical Matrix_xy(f32) != typeid
Not Identical struct {rows: int, columns: int, data: [dynamic]f32} != typeid
Not Identical 26ab228ec60 != 7ff6a9ef3ff8
Not Identical 26ab228ed20 != 7ff6a9ef3ff8
D:\a\Odin\Odin\src\llvm_backend_expr.cpp(2200): Panic: Invalid type conversion: 'Matrix_xy(f32)' to 'typeid' for procedure 'main.main'

I would expect it to compile.

The bug should be reproduceable with the following code:

```
Matrix_xy :: struct(Data_type : typeid) {
    rows : int,
    columns : int,
    data : [dynamic]Data_type,
}

foo_formatter :: proc(fi: ^fmt.Info, arg: any, verb: rune) -> bool {
foo := arg.(Matrix_xy(f32))
io.write_string(fi.writer, "something")
return true;
}

formatters: map[typeid]fmt.User_Formatter;
fmt.set_user_formatters(&formatters);
fmt.register_user_formatter(Matrix_xy(f32), foo_formatter); //issue caused by this line
```

**Comment by spindlebink** [comment]
This bug still occurs for me with variadic typeid arguments.
```go
package main

import "core:fmt"

Poly :: struct(T: typeid) {
	mode: T,
}

test_proc :: proc(t: ..typeid) {
	for type in t {
		fmt.println(type, "is a typeid")
	}
}

main :: proc() {
	test_proc(int)
	test_proc(bool)
	test_proc(Poly(int))
}
```

**Comment by mtarik34b** [comment]
Neither code crashes with dev-2023-07:551c379f for me.
