### ISSUE TITLE
Wrong value in global map initialized from literal

### ISSUE THREAD

**Issue by lunaticLipid** [odin-lang/Odin#231]
```
using println in import "core:fmt.odin"

m := map[string]any {
    "one" = 5,
};

main :: proc() {
    println(m["one"]);
}
```

Output:
```
16
```

**Comment by gingerBill** [comment]
That is because the data is junk. Please try not do use `any` (within a map) unless you know what you are doing. When initializing that map, it is done on the stack and that `any` variable will use stack memory is has now gone out of scope, thus it is rubbish memory.
