### ISSUE TITLE
Stream read returns No_Progress, instead of EOF

### ISSUE THREAD

**Issue by bmaxa** [odin-lang/Odin#2311]
bmaxa@Branimirs-Air odinprograms % odin version
odin version dev-2023-01:1064bcd0

While reading with csv.read_all i noticed that it returns nil for results and err No_Progress, same with bufio.read....
No I even relly on this behavior to exit loop 📦 
[code]
parseTSV:: proc (filename: string)->map[string][]string {
  f,err := os.open(filename)
  defer os.close(f)
  if err != os.ERROR_NONE {
    fmt.println("cannot open",filename)
    return nil
  }
  reader := io.Reader{stream = os.stream_from_handle(f) }
  defer io.destroy(reader.stream)
  csvParser: csv.Reader
  csv.reader_init(&csvParser,reader)
  csvParser.comma = '\t'
  csvParser.lazy_quotes = true
  defer csv.reader_destroy(&csvParser)
  err1 : csv.Error
  records: [dynamic][]string = make([dynamic][]string,0)
  record : []string
  defer delete(records)
  for {
    record,err1 = csv.read(&csvParser)
    if err1 != nil {
      delete(record)
      break
    }
    append(&records,record)
  }
  if err1 != nil && err1 != io.Error.No_Progress{
    fmt.println("error parsing", err1)
  }
  rc := make(map[string][]string)
  delete(records[0])
  recordsiter := records[1:] // first is header
  for record in recordsiter {
    rc[record[3]]=record
  }

  return rc
}
[/code]

**Comment by laytan** [comment]
Fixed in #2998
