### ISSUE TITLE
[feature request] make os_wasi support get_env, stdin, for cgi support  in wasm

### ISSUE THREAD

**Issue by shynome** [odin-lang/Odin#2318]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I want to use  `os.get_env` instead of `wasi.environ_get`, add those interface make cgi can run native and wasm
- `os.args`
- `os.get_env`

**Additional context**

**Comment by shynome** [comment]
Does wasi support `os.stdin`? It seems does not work
```odin
package main

import "core:os"
import "core:fmt"

main :: proc() {
	buf := make([]byte, 1024)
	defer delete(buf)

	n, err := os.read(os.stdin, buf)
	if err < 0 {
		return
	}

	fmt.println("len", n, "err", err)
	str := string(buf[:n])
	fmt.println("input", str)
}
```
```sh
odin build . -target:wasi_wasm32 -o:size
echo inputtext | wazero run main.wasm
#output
len 0 err 0
input
```

**Comment by shynome** [comment]
anyone can help me? I want to use odin in my program in wasi part, but I can't read os.stdin correctly

**Comment by gingerBill** [comment]
If you are using wasi, we recommend not touching `package os` at all the moment and just stick with the "raw" wasi calls themselves.

**Comment by shynome** [comment]
Thanks your reply. I'm so sad to hear that, I am a curd boy from golang, so I don't know too much about C, I need to learn more about wasm or os.stdin has support on wasi, after those I can try odin lang again.

at latest, odin lang is great, if I can I will try again
