### ISSUE TITLE
Deadlock on linux when calling mem_virtual.arena_free_all

### ISSUE THREAD

**Issue by SamuelDeboni** [odin-lang/Odin#2321]
## Context

When I call the function `mem_virtual.arena_free_all` a deadlock happens.

Odin: dev-2023-02:fcc920ed
OS:   Artix Linux, Linux 6.1.8-artix1-1
CPU:  Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
RAM:  15856 MiB

## Expected Behavior

The function `mem_virtual.arena_free_all` should not cause a deadlock 

## Current Behavior

The function `mem_virtual.arena_free_all`  causes a deadlock 

### Steps to Reproduce

This is a test program that will reproduce the bug: 

```odin
package main

import memv "core:mem/virtual"
import fmt "core:fmt"

main :: proc() {
	arena: memv.Arena
	err := memv.arena_init_growing(&arena)
	
	if err == .None {
		fmt.println("Before Free All")
		memv.arena_free_all(&arena)
		fmt.println("After Free All")
	}
}
```

After the line with `memv.arena_free_all(&arena)` a deadlock will occur

### Failure Logs

Only this is the output of the test program, deadlock after the `arena_free_all` function
![image](https://user-images.githubusercontent.com/23066049/216604555-943eefe6-8ad1-4505-a187-fc0df1e4d772.png)

**Comment by gingerBill** [comment]
Fixed in 802333e4
