### ISSUE TITLE
where should the pthread bindings be located?

### ISSUE THREAD

**Issue by ReneHSZ** [odin-lang/Odin#234]
I'm currently working on implementing `core:thread` and `core:sync` for Linux. In order to provide multithreading support on Unix, the `pthread` library is required.

Where should the bindings to `libpthread` be in the standard library? I was thinking about putting them into the thread package, however sync also requires the library for semaphores and mutexes.

**Comment by ThisDrunkDane** [comment]
I would say in both and import the relevant pthread functions in each, or completely seperate pthread.odin thing which then `core:thread` and `core:sync` then uses.

**Comment by ReneHSZ** [comment]
Ok, I guess this question is answered.

**Comment by gingerBill** [comment]
@ReneHSZ The layout of the standard library is far from done and will change.

**Comment by bpunsky** [comment]
`core:sys/linux/pthread.odin` seems reasonable, and then like @ThisDrunkDane said it could be referenced elsewhere, and if the layout of `core` is changed, it would be easier to refactor that way (seems like it's sort of equivalent to the kind of functionality in `core:sys/win32`)
