### ISSUE TITLE
Large arrays are inlined in the llvm output

### ISSUE THREAD

**Issue by vassvik** [odin-lang/Odin#235]
resulting in massive files and long times spent in `opt` and `llc`. Should probably be looped for N > large_value arrays.

**Comment by gingerBill** [comment]
Should N=16 be the cut-off?

**Comment by ThisDrunkDane** [comment]
Perhaps try and make an example in clang and look at what it's cutoff is?

**Comment by bpunsky** [comment]
IIRC this was resolved
