### ISSUE TITLE
suboptimal memcpy to extract bytes

### ISSUE THREAD

**Issue by jhunsaker** [odin-lang/Odin#2351]
## Context

clang version 15.0.7 (Fedora 15.0.7-1.fc37)

$ odin report
Where to find more information and get into contact when you encounter a bug:

        Website: https://odin-lang.org
        GitHub:  https://github.com/odin-lang/Odin/issues

Useful information to add to a bug report:

        Odin: dev-2023-02:a2f02b8b
        OS:   Fedora CoreOS 37, Linux 6.1.10-200.fc37.x86_64
        CPU:  Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
        RAM:  773891 MiB

## Expected Behavior

```C++
typedef struct off48_t
{
    alignas(2) unsigned char a[6];
} off48_t;

static_assert(sizeof(off48_t) == 6);
static_assert(alignof(off48_t) == 2);

static inline off48_t off48_from_int(int64_t const offset)
{
    off48_t result;
    memcpy(&result, &offset, 6);
    return result;
}
```

generates assembly

```
  10:   48 89 f8                mov    %rdi,%rax
  13:   c3                      ret
```

## Current Behavior

while for Odin:

```
off48_t :: distinct [6]u8;
@export
from_int :: proc "system" (offset : i64) -> off48_t {
    offset_copy := offset
    result: off48_t = 0
    mem.copy_non_overlapping(&result, &offset_copy, 6)
    return result
}
```

generates

```
0000000000001c30 <from_int>:
    1c30:       48 89 7c 24 f8          mov    %rdi,-0x8(%rsp)
    1c35:       89 7c 24 f0             mov    %edi,-0x10(%rsp)
    1c39:       0f b7 44 24 fc          movzwl -0x4(%rsp),%eax
    1c3e:       66 89 44 24 f4          mov    %ax,-0xc(%rsp)
    1c43:       48 8b 44 24 f0          mov    -0x10(%rsp),%rax
    1c48:       c3                      ret
```

which is suboptimal

### Steps to Reproduce

1. paste above code into offset.odin
2. execute `odin build offset.odin -file -o:speed -build-mode:dll`

**Comment by jhunsaker** [comment]
a number of variations were tried:
1. `transmute` to new 8 byte array and then copy 6 bytes in loop
2. `raw_union` with 8 byte array and copy in loop
3. 16-bit words similar to above

**Comment by jhunsaker** [comment]
a ptr-to-ptr version in C would generate:

```
   0:   48 8b 06                mov    (%rsi),%rax
   3:   89 07                   mov    %eax,(%rdi)
   5:   48 c1 e8 20             shr    $0x20,%rax
   9:   66 89 47 04             mov    %ax,0x4(%rdi)
}
   d:   c3                      ret
```

**Comment by gingerBill** [comment]
Your translation from C to Odin is not 1-to-1:

```odin
off48_t :: struct #align 2 {
    a: [6]byte,
}

#assert(size_of(off48_t) == 6)
#assert(align_of(off48_t) == 2)

off48_from_int :: #force_inline proc "c" (offset: i64) -> (result: off48_t) {
    offset := offset
    intrinsics.mem_copy_non_overlapping(&result, &offset, 6)
    return
}
```

But it does produce the same thing on Linux AMD64 with `-o:speed`:
```
off48_from_int:
	movq	%rdi, -8(%rsp)
	movl	%edi, -16(%rsp)
	movzwl	-4(%rsp), %eax
	movw	%ax, -12(%rsp)
	movq	-16(%rsp), %rax
	retq
```

The "sub-optimal" optimization is effectively the best we can do with how LLVM works for Odin. This is has very little to do with Odin itself and more to do with LLVM.

**Comment by gingerBill** [comment]
The IR that Odin generates looks like this:

```llvm
%bug.off48_t = type { [6 x i8] }

define i64 @off48_from_int(i64 %0) #2 {
decls:
  %1 = alloca %bug.off48_t, align 8
  %2 = alloca i64, align 8
  store i64 %0, i64* %2, align 8
  %3 = bitcast %bug.off48_t* %1 to i8*
  %4 = bitcast i64* %2 to i8*
  call void @llvm.memcpy.inline.p0i8.p0i8.i64(i8* %3, i8* %4, i64 6, i1 false)
  %5 = bitcast %bug.off48_t* %1 to i64*
  %6 = load i64, i64* %5, align 8
  ret i64 %6
}
```

The IR that Clang produces looks like this before optimizations:

```llvm
%struct.off48_t = type { [6 x i8] }

define dso_local i48 @_Z14off48_from_intl(i64 %0) #0 {
  %2 = alloca %struct.off48_t, align 2
  %3 = alloca i64, align 8
  %4 = alloca i48, align 8
  store i64 %0, i64* %3, align 8
  %5 = bitcast %struct.off48_t* %2 to i8*
  %6 = bitcast i64* %3 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 2 %5, i8* align 8 %6, i64 6, i1 false)
  %7 = getelementptr inbounds %struct.off48_t, %struct.off48_t* %2, i32 0, i32 0
  %8 = bitcast i48* %4 to i8*
  %9 = bitcast [6 x i8]* %7 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 %8, i8* align 2 %9, i64 6, i1 false)
  %10 = load i48, i48* %4, align 8
  ret i48 %10
}
```


Note the difference is that `i48` is being used as the return type rather than an `i64` as in Odin. Clang does loads of things which are undocumented and not technically ABI correct, but because you marked it `static inline`, it doesn't matter.

**Comment by Kelimion** [comment]
You might also be able to use `intrinsics.unaligned_load`:
```odin
off48_from_int_v2 :: #force_inline proc "c" (offset: i64) -> (result: off48_t) {
	offset := offset
	result = intrinsics.unaligned_load((^off48_t)(&offset))
	return
}
```

**Comment by gingerBill** [comment]
@Kelimion That produces the same result.

**Comment by jhunsaker** [comment]
sorry, just to understand, are you asserting that llvm should better optimize the LLVM IR that is generated by Odin to produce the same result as the LLVM IR generated by Clang? what makes the difference here? why doesn't Odin use i48 as Clang does?

**Comment by gingerBill** [comment]
@jhunsaker To clarify what I am saying:

* This GitHub issue is not a bug, just not a great optimization
* The optimization passes that we use from LLVM do not catch this thing, mainly because the passes we don't use usually assume C-like semantics and thus introduce UB based "optimizations" (these are not optimizations in any strict sense of that word)
* We don't use arbitrary bit width integers in the code generation we only use 8, 16, 32, 64, and 128 bit integers
* `i48` is being used as the return type in Clang for this procedure even if the actual ABI will put it in a 64-bit wide register
    * LLVM is giving itself a bigger hint as to converting it to a `trunc` (LLVM IR), and then a `mov` (AMD64)

**Comment by jhunsaker** [comment]
any plans to include arbitrary bit width support as being added to C/C++ soon?

https://blog.llvm.org/2020/04/the-new-clang-extint-feature-provides.html
BitInt in C23

**Comment by gingerBill** [comment]
@jhunsaker Never.
