### ISSUE TITLE
`make_bound_udp_socket` hits unreachable with empty struct address

### ISSUE THREAD

**Issue by Skytrias** [odin-lang/Odin#2386]
## Context

* Operating System & Odin Version: `dev-2023-03:5bbdbadc`
* Please paste `odin report` output: 
```
        Odin: dev-2023-03:5bbdbadc
        OS:   Windows 10 Home Basic (version: 22H2), build 19045.2604
        CPU:  AMD Ryzen 5 3600 6-Core Processor
        RAM:  16310 MiB
```

## Expected Behavior

Allow an empty struct address to not silently crash or report an error to the user.

## Current Behavior

Silently crashes at unreachable in `family_from_address` and potentially other places where this could be the case.

### Steps to Reproduce

`skt, skt_err := net.make_bound_udp_socket({}, 1234)`

**Comment by Kelimion** [comment]
The problem isn't that this behaves this way, but that `unreachable()` is silent. It should complain that it hit unreachable code and used to do so.
```odin
main :: proc() {
	if true {
		unreachable()
	}
	fmt.println("Hellope!")
}
```
