### ISSUE TITLE
imports enclosed in when are type checked

### ISSUE THREAD

**Issue by DragosPopse** [odin-lang/Odin#2388]
## Context

When trying to separate an import unavailable on a certain platform through a `when` statement, the compiler does type checking on the import, and obviously fails. I feel this is a big issue, because this makes a lot of cross platform setups nearly impossible to achieve (example below), especially desktop <-> wasm
![image](https://user-images.githubusercontent.com/31741257/225557492-95b8669a-2601-48b4-928c-c29b0ed952e7.png)
![image](https://user-images.githubusercontent.com/31741257/225557575-d95faf38-b8eb-4513-921b-f595cc5306c3.png)

* Operating System & Odin Version:
Odin: dev-2023-03:ca15eb26
        OS:   Windows 10 Professional (version: 21H2), build 19044.2728
        CPU:  AMD Ryzen 9 3900X 12-Core Processor
        RAM:  32716 MiB

## Expected Behavior

The import should be completely ignored if inclosed in a `when` that doesn't evaluate to true. 

## Current Behavior

`#panic` is being invoked from `os_js.odin`, which shows that the import is type checked. It also follows up with a bunch of undefined type errors.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `when ODIN_OS != .JS do import "core:os`
2. Compiler with `-target:js_wasm32`
3. Pain 

### Failure Logs

![image](https://user-images.githubusercontent.com/31741257/225558523-6734577d-1248-4dab-b3b8-11d406bb30c3.png)

**Comment by Feoramund** [comment]
It is not possible anymore to import packages from within when statements, making this issue no longer applicable. The following error will arise:
```
Cannot use 'import' within a 'when' statement.
Prefer using the file suffixes (e.g. foo_windows.odin) or '//+build' tags
```

**Comment by DragosPopse** [comment]
this is quite a stale and "false" issue at this point, bill clarified the situation many times. i'll close it.
