### ISSUE TITLE
using import shadows functions, structs etc

### ISSUE THREAD

**Issue by nergethic** [odin-lang/Odin#243]
When "using import" imported modules contain structs or functions with the same name as those in local file scope, the local ones get completely shadowed.

**Comment by gingerBill** [comment]
This is not a bug but rather an implicit warning to not use `using import`. All imports are local to that file whilst normal declarations are package wide. 

This is a design decision I made as I want people to think more locally about something. It is clearer when reading the code where the thing is imported if it is done on a per file basis.
