### ISSUE TITLE
Vulkan wrapper for Wayland platform

### ISSUE THREAD

**Issue by CuteMath** [odin-lang/Odin#2442]
Please, consider adding vulkan_wayland.h to the binding generator.
Thank you

**Comment by Kelimion** [comment]
There is no official binding generator for Odin, nor is there one in this repository.

**Comment by CuteMath** [comment]
Then I might be misunderstanding. What is this? https://github.com/odin-lang/Odin/blob/master/vendor/vulkan/_gen/create_vulkan_odin_wrapper.py

**Comment by Kelimion** [comment]
You make a good point. Because you said binding generator, I was thinking about a tool that would take any .h file and turn it into bindings. We don't have an official one of those.

Added `vulkan_wayland.h` in the aforementioned commit.

**Comment by Kelimion** [comment]
Sorry, but that had to be reverted as the generator spits out invalid code once you add that file.

You're welcome to add `vulkan_wayland.h` to that generator yourself and run `odin check examples/all` to figure out why it doesn't like those bindings.

**Comment by CuteMath** [comment]
I was actually about to point out the problem. I've already tried adding it myself. The python script does not handle correctly "struct wl_display*" and "struct wl_surface*".

**Comment by Kelimion** [comment]
> I was actually about to point out the problem. I've already tried adding it myself. The python script does not handle correctly "struct wl_display*" and "struct wl_surface*".

I hope this works for you. I've added them as opaque structs, as they're defined in the Wayland headers external to Vulkan.
