### ISSUE TITLE
Allow set_user_formatters to be called more than once

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2447]
I used a previous version of Odin and just upgraded only to get a runtime assertion.

Before I would set all my formatters in an init function like so:

```
init :: proc (){

	matrix_set_formatter(f64);
	matrix_set_formatter(bool);
	stacked_array_set_formatter(Terminal);
	stacked_array_set_formatter(Wire);
	stacked_array_set_formatter(^Terminal);
	stacked_array_set_formatter(^Wire);
}
```

But now I get the error "runtime assertion: set_user_formatters must not be called more than once."
I get it a little bit, but why not allow this?

How will this work with different libraries all wanting to set their own formatters.

**Comment by Kelimion** [comment]
You must have been using it wrong previously, if that's the case?

`set_user_formatters :: proc(m: ^map[typeid]User_Formatter)` takes a pointer to the map in which all formatters are registered. `fmt` can only use one such map, so there's no need for your program to register the map more with `fmt` than once.

After that you can call `register_user_formatter(typeid, custom_formatter_proc)` to register the individual formatters for each type.

Meaning you can still do what you want to do.
```odin
my_formatters: map[typeid]fmt.User_Formatter

init :: proc() {
    fmt.set_user_formatters(&my_formatters)
    fmt.register_user_formatter(f64, matrix_formatter_proc)
    fmt.register_user_formatter(bool, matrix_formatter_proc)
    ...
}
```

**Comment by Kelimion** [comment]
The assert only makes clear that `fmt` keeps track of a single map only, and that to call `set_user_formatters` more than once previously would just have overriden the previous pointer to it with the new one, not kept track of both.
