### ISSUE TITLE
Compiler Segfault & Double Free

### ISSUE THREAD

**Issue by jon-lipstate** [odin-lang/Odin#2454]
## Context

In the process of porting a library, I allowed a good number of errors to accrue before bothering to address them. I noticed that >20 errors (guessing) the compiler starts giving `Segmentation fault` and occasionally `Double Free or corruption (out)\n Aborted` .
I was using `odin build .` to chase errors and clean them. An additional observation (unrelated (?) ) is that errors were ping ponging locations in the file, eg error on 343, error on 1052, next on 128, next on 744 and so forth.

Operating System & Odin Version:  
- Odin: dev-2023-04:0234f50d *( i think i have pulled since i had the errors, but likely exact build is within the last week)*
- OS:   Windows 10 Professional (version: 22H2), build 19045.2728
- CPU:  AMD Ryzen 9 3950X 16-Core Processor
- RAM:  32686 MiB

## Failure Information (for bugs)

![image](https://user-images.githubusercontent.com/52809771/231345213-39864fab-0d78-4ab1-ba7a-9989ab50ee64.png)
![image](https://user-images.githubusercontent.com/52809771/231345256-4b3c9b28-e253-48fb-aa30-fd3d6dc8d0a6.png)
![image](https://user-images.githubusercontent.com/52809771/231345271-2ba26a5e-a702-45ff-9ef7-0e0d1eafda5f.png)

Please provide detailed steps for reproducing the issue.

I retained a copy of the files that still contains a good number of errors and was producing the error state for me here:

https://gist.github.com/jon-lipstate/4635994a86ff18863e3d0311353906aa

**Comment by laytan** [comment]
Similar issue as this one: https://github.com/odin-lang/Odin/issues/3169 and should also be fixed by the latest error system overhaul
