### ISSUE TITLE
LLVM 14 support not yet enabled for make

### ISSUE THREAD

**Issue by BitPusher16** [odin-lang/Odin#2460]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* OS: Linux Mint Vera (Ubuntu Jammy)
* Odin version: 073f51e284e50d324cc71c4d3e80fe56b79005a7
* Please paste `odin report` output:

```
Where to find more information and get into contact when you encounter a bug:

	Website: https://odin-lang.org
	GitHub:  https://github.com/odin-lang/Odin/issues


Useful information to add to a bug report:

	Odin: dev-2023-04:b7b5043a
	OS:   Linux Mint 21.1, Linux 5.15.0-69-generic
	CPU:  12th Gen Intel(R) Core(TM) i5-1240P
	RAM:  31813 MiB
```

## Expected Behavior

Cloning Odin and running make builds Odin.

## Current Behavior

Build fails because LLVM 14 has moved/removed atomic.h

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clone repo
3. Navigate into repo
4. Call `make`

### Failure Logs

```
./build_odin.sh debug
+ clang++ src/main.cpp src/libtommath.cpp -Wno-switch -Wno-macro-redefined -Wno-unused-value '-DODIN_VERSION_RAW="dev-2023-04"' '-DGIT_SHA="b7b5043a"' -std=c++14 -I/usr/lib/llvm-14/include -std=c++14 -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -L/usr/lib/llvm-14/lib -g -pthread -lm -lstdc++ -ldl /usr/lib/llvm-14/lib/libLLVM-14.so '-Wl,-rpath=$ORIGIN' -o odin
In file included from src/main.cpp:3:
src/common.cpp:30:10: fatal error: 'atomic' file not found
#include <atomic> // Because I wanted the C++11 memory order semantics, of which gb.h does not offer (because it was a C89 library)
         ^~~~~~~~
1 error generated.
make: *** [Makefile:10: debug] Error 1
```

### Workaround
Installed clang 13, llvm 13. Make works after that.

```
$ gcc --version
gcc (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ clang --version
Ubuntu clang version 13.0.1-2ubuntu2.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ llvm-config --version
13.0.1

```

**Comment by ThaCuber** [comment]
what are the packages' names? I'm trying to download the ones I think are but none work

**Comment by 7ombie** [comment]
I'm not sure this is helpful, but on macOS, I just installed Odin with LLVM 14 (14.0.6), and `make` ran without any issues (outputting the quick test results).

**Comment by feelingkrummy** [comment]
I was having this same issue, and I was able to fix it.

System Info:
- OS : Linux Mint 21
- Odin Version : 19ea0906
- Odin Report : N/A

I don't have an Odin Report this was my first time attempting to build the repo.
I was getting the same error described above.

> In file included from src/main.cpp:3:
> src/common.cpp:30:10: fatal error: 'atomic' file not found
> #include <atomic> // Because I wanted the C++11 memory order semantics, of which gb.h does not offer (because it was a C89 library)

I found [this page](https://gatowololo.github.io/blog/clangmissingheaders/) about missing clang headers. I learned that clang basically borrows headers from other projects, like GCC. So I ran the command running `make` produced but with `-v` option to get the verbose output. 

> 
> > [kameron](~/odin) > clang++ src/main.cpp src/libtommath.cpp -Wno-switch -Wno-macro-redefined -Wno-unused-value '-DODIN_VERSION_RAW="dev-2023-06"' '-DGIT_SHA="19ea0906"' -std=c++14 -I/usr/lib/llvm-14/include -std=c++14 -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -L/usr/lib/llvm-14/lib -g -pthread -lm -lstdc++ -ldl /usr/lib/llvm-14/lib/libLLVM-14.so '-Wl,-rpath=$ORIGIN' -o odin -v
> Ubuntu clang version 14.0.0-1ubuntu1
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
> Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12

Clang 14 is selecting gcc-12 for it's include files. However, I don't have the g++-12 headers:

> [kameron](~/odin) > find /usr -name atomic
> /usr/include/c++/11/atomic  
> /usr/src/linux-headers-5.15.0-69-generic/scripts/atomic
> /usr/src/linux-headers-5.15.0-73/include/linux/atomic
> /usr/src/linux-headers-5.15.0-73/scripts/atomic
> /usr/src/linux-headers-5.15.0-73-generic/scripts/atomic
> /usr/src/linux-headers-5.15.0-69/include/linux/atomic
> /usr/src/linux-headers-5.15.0-69/scripts/atomic

After installing g++-12, I know have the header files, and running `make` works. 

I don't know if this counts as a solution or if it's a work around. I don't know if there's a way to account for this in `./build_odin.sh` because clang seems to just do pick that latest gcc version installed. 

Maybe it would be wise to add a sentence to the install directions about ensuring the user has the latest g++ version installed so that clang has the correct header files.

**Comment by laytan** [comment]
This can be closed, llvm 14 works and the installation page explains the possible atomic.h error on some linux
