### ISSUE TITLE
Unicode does not show up in `odin run .` output, when unicode otherwise shows up

### ISSUE THREAD

**Issue by lesleyrs** [odin-lang/Odin#2482]
## Context

Odin: dev-2023-04:341ba347
OS:   Windows 10 Home Basic (version: 22H2), build 19045.2846

## Expected Behavior

Expected to see the emoji from this example https://github.com/odin-lang/Odin#the-odin-programming-language

## Current Behavior

`The program "+ + * ­ƒÿâ - /" calculates the value 7`

Running the type command does show the emojis.

Happens on both windows terminal and wezterm.

### Steps to Reproduce

1. Try the example code on the odin lang github linked above
2. See output when ran

**Comment by gingerBill** [comment]
This isn't a bug with Odin but rather your terminal has not be configured to use UTF-8.

**Comment by Kelimion** [comment]
Try the command `chcp 65001`.

**Comment by lesleyrs** [comment]
I managed to fix the problem by following the 4th step here: https://akr.am/blog/posts/using-utf-8-in-the-windows-terminal. After restarting the unicode output of an odin binary shows up correctly, but it's behind a beta feature of windows.

`chcp 65001` didn't work correctly for some reason even though the above should be doing the same under the hood, it only showed question marks (in cmd, no effect otherwise).

I just don't understand why utf-8 already works in windows terminal when manually typing or the output of a rust binary for example. But with Odin you have to enable this.

**Comment by tuket** [comment]
I had the same problem.

`chcp 65001` did nothing.

The solution that worked for me is the 4th step mentioned by @lesleyrs.

I'm not sure why this is needed for Odin. I could print Unicode strings in python without any configuration required.

**Comment by blob1807** [comment]
It's needed in Odin because its runtime, unlike Python or Rust, doesn't modify the environment it's run in. It's up to you, or your terminal, decided that.

Your terminal will decide its default code page. For cmd & pwsh it's either 437 or 1252, both extended ASCII.
If your application will emit UTF-8 you need to tell it as such. Whether through `SetConsoleOutputCP` or by adding a manifest/resource file to the exe.
