### ISSUE TITLE
Silent crash when assigning into field of null pointer

### ISSUE THREAD

**Issue by Trolobezka** [odin-lang/Odin#2484]
## Context

Win10, built with x64 Native Tools Command Prompt for VS2017, odin.exe and link.exe locations added into PATH.

Odin: dev-2023-04:be0a5430
OS:   Windows 10 Professional (version: 22H2), build 19045.2846
CPU:  Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
RAM:  16236 MiB

## Expected Behavior

Print some sort of error to the console.

## Current Behavior

Silent crash.

## Failure Information (for bugs)

I don't see any.

### Steps to Reproduce

```odin
package main

import "core:fmt"

main :: proc() {
    Point :: struct {
        x: f32,
        y: f32,
    }
    // this or p: ^Point = nil
    p: ^Point

    fmt.println("A")
    // this or p^.x = 10
    p.x = 10
    fmt.println("B")
}
```

Run with `odin run .`

A is printed, then it crashes, no message/error in the console, only VSCode is telling me the program exited with code 1.

### Failure Logs

I don't see any.

**Comment by matias-eduardo** [comment]
Yeah, that should probably show a warning at build-time. I think that's what C compilers do, e.g. Warning C6011.

Obligatory: https://www.youtube.com/watch?v=bLHL75H_VEM

**Comment by Lperlind** [comment]
This would require a check on every pointer access everywhere.
A better solution would be for you to use a debugger to determine the location of the segfault.

**Comment by matias-eduardo** [comment]
I feel like there’s a subset of this compile-time check that can be done very cheaply. If it’s too expensive, there’s always the alternative of placing it behind a compiler flag.

That said, I’m fine either way since I’m always running through RemedyBG.

**Comment by Trolobezka** [comment]
I tried debugging with gdb, could not load the debug symbols, so I tried Visual Studio Debugger and it showed me the line of code that caused the crash with somehow understandable message. Should this issue be closed?

**Comment by matias-eduardo** [comment]
Yeah, I would close it. Solving it would involve doing redundant work since the debugger is already catching it for you. As far as I can tell, Odin is a language that assumes you have a debugger on-hand.

That said, it's a common problem to stumble upon and I do wonder if there's a middle ground that could cover at least 50% of these null dereferences. UNIX-side debuggers are a bit lacking after all, so it might be worth exploring in the future.

**Comment by Tetralux** [comment]
There's an idea that Odin will eventually have a segfault handler that will either be enabled by default or manually enabled by calling a procedure in main.

That, however, requires being able to read debug info at runtime, which is a nontrivial amount of work if that info is DWARF/PE/COFF.

Another possibility is that Odin gains the ability to emit a custom stacktrace information thing of some sort that is vastly simpler, but that hasn't been fleshed out much as of yet.

I think someone was writing some Odin packages that manipulate DWARF for their own project, but nothing for the corelib has come to fruition as yet.

**Comment by matias-eduardo** [comment]
@Tetralux Couldn't this particular case be caught by looking at the AST? If Odin (or user) ZIIs the pointer, then can it know it is still set to zero when it's dereferenced immediately after? So if it hasn't been touched or passed as a param we could warn the user that they're dereferencing a null pointer?

I imagine adding an `else if` somewhere in here that would check:
https://github.com/odin-lang/Odin/blob/88f6b5f16be37887667f52d1849c62209266d9b0/src/check_expr.cpp#L9821-L9860
