### ISSUE TITLE
Compiler error when indexing constant slices using a variable

### ISSUE THREAD

**Issue by rhulzing** [odin-lang/Odin#2495]
## Context
Operating System: Win 10x 64
Odin version/Commit: dev-2023-04:be0a5430

## Expected Behavior

I expect this code to compile:
```
package main

const_test :: []u32{123, 456}
non_const_test:= []u32{123, 456}


main :: proc() 
{
    // works
    a:= const_test[0]

    direction: int = 0
    // also works
    b := non_const_test[direction]
    // fails
    c := const_test[direction]

}
```

## Current Behavior

The compiler will fail with "Cannot index constant 'const_test'" when trying to index the constant slice using a variable for an index. Indexing the normal slice with or without using a variable works as expected.

I found the following issue: https://github.com/odin-lang/Odin/issues/659
which helped me narrow down the issue being specific to using a variable to index a constant slice.

**Comment by Lperlind** [comment]
This is the expected behavior. The variable isn't known at compile time thus the slice must exist during runtime to be indexed.

**Comment by rhulzing** [comment]
I understand what you are saying. I am a little new to the language, but I totally get that const things are compile time, and non-const things can be runtime. Thank you for the clarification.
