### ISSUE TITLE
Odin does not build on fedora 37 with LLVM 13 and LLVM 15 installed.

### ISSUE THREAD

**Issue by hypatia-of-sva** [odin-lang/Odin#2506]
## Context

I'm using Fedora 37 (planning to move to 38 but probably as a reinstall which will take some time), and because I had previously installed LLVM 15, Odin wouldn't build. I installed the LLVM 13 packages because that is the newest supported version as explained by the website setup guide.

## Expected Behavior

After LLVM 13 was installed, I would have expected the Makefile to work.

## Current Behavior

Currently, it fails by looking for "llvm-config" without a version number, which is still linked to LLVM 15. Also, "llvm-config-13" isn't even in the list. I had to change the build_odin.sh in line 96/97 to

```sh
		if [ -x "$(command -v llvm-config-13)" ]; then
			LLVM_CONFIG=llvm-config-13
```

to make it work.

**Comment by gingerBill** [comment]
Odin does not support LLVM 15 whatsoever. This is because LLVM 15 changed a lot of things which we cannot guarantee anything will work correctly.

One thing you can do is just override the `LLVM_CONFIG` yourself to the specific your llvm-config.

**Comment by hypatia-of-sva** [comment]
Yes, that's exactly what I did. I would maybe suggest checking if "llvm-config" is too new, so to have something like 

```sh
		if [ -x "$(command -v llvm-config)" and check_config_version  ]; then
			LLVM_CONFIG=llvm-config
```
where check_config_version would check if it's in the supported range, so that, if it isn't, it could check if a specific version is installed.

It's ultimately a relative trivial thing to fix, and the install works fine now, I just wanted to give a heads up in case this was not the way the build script was intended to work.
