### ISSUE TITLE
Named return values produce side effects with 128-bit integer types

### ISSUE THREAD

**Issue by gluyas** [odin-lang/Odin#2517]
## Context

First time Odin user, found this while trying out "hello fibonacci" with large integers. Wasn't sure if this was expected behaviour but upon experimentation found that it is inconsistent.
 
The following code gives incorrect results for 128-bit integers.

```odin
good :: proc() -> (x: int, dummy: int) {
    x = 0
    return 1, x
}
// returns 1, 0

bad :: proc() -> (x: i128, dummy: i128) {  // i128 or u128
    x = 0
    return 1, x
}
// returns 1, 1
```
In the latter case, the value of the first returned value is leaked into `x`, effectively desugaring to `x = 1; dummy = x; return` instead of creating temporaries. Here is the recursive Fibonacci function where I encountered the issue:

```odin
fib2 :: proc(i: u128) -> (f: u128, pred: u128) {
    if i == 0 { return 1, 0 }

    f, pred = fib2(i - 1)
    return f + pred, f
}
```

This instead produces the sequence 1, 1, 2, 4, 8 etc. as the `f` return value is also assigned to `pred`. I tested with several different types including 64-bit and smaller integers, float, complex, quaternion, and 128-bit integer arrays and only found `i128` and `u128` to produce the issue.

* Operating System & Odin Version:

        Odin: dev-2023-05:9f392097
        OS:   Windows 10 Home Basic (version: 21H2), build 19044.2846
        CPU:  Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
        RAM:  7919 MiB

## Expected Behavior

All expressions in multiple return statement should be evaluated without producing side effects on the named return variable (in procedure scope).

## Current Behavior

Returning an `i128` or `u128` evaluates and assigns the value to the procedure's named return variable if it exists, creating side effects that are visible in other expressions in the return statement.

**Comment by inbelic** [comment]
Do you still experience this behaviour? I am unable to reproduce when taking a look now.

Odin: dev-2023-06:105dca01
OS:   Linux Mint 21, Linux 5.15.0-73-generic
CPU:  AMD Ryzen 7 5800U with Radeon Graphics         
RAM:  13832 MiB

**Comment by gluyas** [comment]
Hi! Yes, I tested again on the latest commit and this is still an error on my end. 
```
Odin: dev-2023-06:4c17e2e9
OS:   Windows 10 Home Basic (version: 22H2), build 19045.2965
CPU:  Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
RAM:  7919 MiB
```

Unfortunately I don't have a Linux or AMD machine to test on, but if it's not an error on Linux then I suppose it must be platform specific. If anyone else could try reproducing on their machine then that would be helpful.

I had a look at the assembly output of the `bad` code from OP for both backends and it seems to verify that this is an issue on Windows. I'm not exactly sure how the Windows calling convention works but it looks like it it's storing `i128` 1 into both return addresses, where Linux clearly returns 1 and 0.
```asm
; windows_amd64
main.bad:
	subq	$40, %rsp
	movq	%rcx, 8(%rsp)
	movq	8(%rsp), %rax
	movq	$0, 24(%rsp)    ; high qword 0 
	movq	$1, 16(%rsp)    ; low  qword 1
	movq	$0, 8(%rax)     ; high qword 0
	movq	$1, (%rax)      ; low  qword 1
	movdqa	16(%rsp), %xmm0 ; also return first val in xmm0?
	addq	$40, %rsp       
	retq                    ; {1 0} at (%rsp) and {1 0} at (%rax) seems bad

; linux_amd64
main.bad:
	movq	%rdi, -16(%rsp)
	movq	%rdi, -8(%rsp)
	jmp	.LBB119_1
.LBB119_1:
	movq	-8(%rsp), %rax
	movq	-16(%rsp), %rcx
	movq	$0, 8(%rcx)     ; high qword 0
	movq	$1, (%rcx)      ; low  qword 1
	movq	$0, 24(%rcx)    ; high qword 0
	movq	$0, 16(%rcx)    ; low  qword 0
	retq                    ; {1 0 0 0} at (%rcx) seems ok
```
I'll try taking a look at the LLVM IR output for both targets to rule out an issue with LLVM translation, but this is a bit outside of my wheelhouse at this point so any help would be appreciated!

**Comment by gluyas** [comment]
Just quickly checked the LLVM IR and it's clearly the same issue:
```llvm
;
; windows_amd64
;
define internal <2 x i64> @main.bad(i128* noalias nonnull %0, i8* noalias nocapture nonnull %__.context_ptr) #0 {
decls:
  %1 = alloca i128, align 16
  br label %entry

entry:                                            ; preds = %decls
  store i128 1, i128* %1, align 8                 ; store 1 %1
  store i128 1, i128* %0, align 8                 ; store 1 %0: sadness :(
  %2 = bitcast i128* %1 to <2 x i64>*
  %3 = load <2 x i64>, <2 x i64>* %2, align 16
  ret <2 x i64> %3
}

;
; linux_amd64
;
define internal void @main.bad({ i128, i128 }* noalias sret({ i128, i128 }) %agg.result, i8* noalias nocapture nonnull %__.context_ptr) #0 {
decls:
  br label %entry

entry:                                            ; preds = %decls
  %0 = getelementptr inbounds { i128, i128 }, { i128, i128 }* %agg.result, i32 0, i32 0
  %1 = getelementptr inbounds { i128, i128 }, { i128, i128 }* %agg.result, i32 0, i32 1
  store i128 1, i128* %0, align 8                 ; store 1 %0
  store i128 0, i128* %1, align 8                 ; store 0 %1: ok :)
  ret void
}
```
So must be an issue with platform translation. Very bizarre that the language semantics would be interpreted differently like this.

**Comment by inbelic** [comment]
Hm, very curious. Unfortunately, a bit out of my depth now as well, but I agree with your points

**Comment by Feoramund** [comment]
For what it's worth, I am also unable to reproduce this as of the latest commit on a Linux machine.

`odin report`:

	Odin:    dev-2024-06:1f4cfd52f
	OS:      Arch Linux, Linux 6.9.3-arch1-1
	CPU:     12th Gen Intel(R) Core(TM) i7-12700K
	RAM:     31913 MiB
	Backend: LLVM 17.0.6

**Comment by gluyas** [comment]
Unfortunately this still presents as an error on Windows.

The LLVM codegen has changed from last year but the issue persists and is still visible at this stage of compilation. Someone familiar with the compiler internals and LLVM will need to verify whether this platform-specific issue is caused by Odin's or LLVM's platform translation. From a cursory look however it seems that Odin implements the platform's calling conventions itself and emits this directly to LLVM.

I'm unable to investigate this issue further, but I have provided a test program containing the original example code and identified the error in its LLVM output for target `windows_amd64`. The LLVM output should be reproducible by all Odin installations.

Test Program
---
`test.odin`:
```odin
package main
import "core:fmt"

// example function working as expected
good :: proc() -> (x: int, dummy: int) {
    x = 0
    return 1, x // returns 1, 0
}

// identical code, changing only the size of the integer type
bad :: proc() -> (x: i128, dummy: i128) {  // i128 or u128
    x = 0
    return 1, x // returns 1, 1
}

main :: proc() {
    fmt.print("good: ");
    fmt.println(good());

    fmt.print("bad:  ");
    fmt.println(bad());
}
```
Execution output, showing the error:
```
C:\Users\Marc\Desktop>odin run test.odin -file
good: 1 0
bad:  1 1
```

LLVM Output
---
See inline comments for code analysis also showing the error. Both `main.good` and `main.bad` use the same convention to return multiple values, where the first return value (named `x` in the program source) is returned through a pointer and the second (named `dummy`) through LLVM's return instruction.

 `odin build test.odin -file -build-mode:llvm -target:windows_amd64`:

```llvm
;
; main.good
; 1st return value (`x`) written to caller-provided address in %0
; 2nd return value (`dummy`) passed via ret instruction
;
define internal i64 @main.good(ptr noalias nonnull %0, ptr noalias nocapture nonnull %__.context_ptr) {
decls:
  %x = alloca i64, align 8
  %dummy = alloca i64, align 8
  br label %entry

entry:                                            ; preds = %decls
  store i64 0, ptr %x, align 8
  store i64 0, ptr %dummy, align 8
  store i64 0, ptr %x, align 8                    ; %x <- 0
  %1 = load i64, ptr %x, align 8                  ; %1 <- %x (= 0)
  store i64 1, ptr %x, align 8                    ; %x <- 1
  store i64 %1, ptr %dummy, align 8
  store i64 1, ptr %0, align 8                    ; 1st return `x` <- 1            ; correct
  ret i64 %1                                      ; 2nd return `dummy` <- %1 (= 0) ; correct
}

;
; main.bad
; 1st return value (`x`) written to caller-provided address in %0
; 2nd return value (`dummy`) passed via ret instruction
;
define internal <2 x i64> @main.bad(ptr noalias nonnull %0, ptr noalias nocapture nonnull %__.context_ptr) {
decls:
  %x = alloca i128, align 16
  %dummy = alloca i128, align 8
  br label %entry

entry:                                            ; preds = %decls
  store i128 0, ptr %x, align 8
  store i128 0, ptr %dummy, align 8
  store i128 0, ptr %x, align 8                   ; %x <- 0
  %1 = load i128, ptr %x, align 8                 ; %1 <- %x (= 0)
  store i128 1, ptr %x, align 8                   ; %x <- 1
  store i128 %1, ptr %dummy, align 8              ; %dummy <- %1 (= 0)             ; this variable is not subsequently accessed
  store i128 1, ptr %0, align 8                   ; 1st return `x` <- 1            ; correct
  %2 = load <2 x i64>, ptr %x, align 16           ; %2 <- %x (= 1)                 ; implements a cast from 128 to <2 x i64>
  ret <2 x i64> %2                                ; 2nd return `dummy` <- %2 (= 1) ; incorrect, instead should have loaded either %1 or %dummy into %2
}
```

`odin report`
---
```
        Odin:    dev-2024-06:0d698c7b5
        OS:      Windows 10 Home Basic (version: 22H2), build 19045.4412
        CPU:     Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
        RAM:     16318 MiB
        Backend: LLVM 17.0.1
```
