### ISSUE TITLE
mem.alloc leads to segmentation fault if there is not enough memory

### ISSUE THREAD

**Issue by woodoocrap** [odin-lang/Odin#2530]
## Context
   odin report output:
   Odin: dev-2023-04:f0ba5d38
   OS:   Arch Linux, Linux 6.2.13-arch1-1
   CPU:  AMD FX-9800P RADEON R7, 12 COMPUTE CORES 4C+8G 
   RAM:  7399 MiB

```Odin
package main

import "core:fmt"
import "core:mem"

main :: proc() 
{  
   ptr := mem.alloc(1073741824);
}
```

### Steps to Reproduce
   - start new shell
   - limit shell memory by 'ulimit -v 1000000'
   - run compiled program
  
## Expected Behavior
   program executes and exits despite alloc failure  

## Current Behavior
    Segmentation fault (core dumped)

Note: when memory is not limited compiled program runs just fine

**Comment by jasonKercher** [comment]
It would seem the `heap_allocator_proc` in...

core/os/os.odin
core/runtime/os_specific_windows.odin
core/os/os2/heap_windows.odin
core/os/os2/heap_linux.odin 

...do not check for a `nil` return.
