### ISSUE TITLE
panic leads to 'Illegal instruction (core dumped)' 

### ISSUE THREAD

**Issue by woodoocrap** [odin-lang/Odin#2540]
## Context
   Odin: dev-2023-05:e6c8d3d1
   OS:   Arch Linux, Linux 6.2.13-arch1-1
   CPU:  AMD FX-9800P RADEON R7, 12 COMPUTE CORES 4C+8G 
   RAM:  7399 MiB

```Odin
package main

main :: proc() 
{
   panic("panic message");
}
```
executable compiled from this code produces following output :
file.odin(6:4) panic: panic message
Illegal instruction (core dumped)

Note: it does not occur on 'odin run .' but when i run compiled executable

**Comment by Kelimion** [comment]
Works as intended on both Windows and Ubuntu. It prints the panic message and then calls `trap()`, which emits `ud2`.
I don't know what you means by "does not occur on `odin  run`". There too it prints the panic message and issues the illegal instruction.
```
W:\Odin-other\Odin-test>odin run panic.odin -file -debug
W:/Odin-other/Odin-test/panic.odin(5:2) panic: panic message
```
```
/mnt/w/Odin-other/Odin-test $ odin run panic.odin -file
/mnt/w/Odin-other/Odin-test/panic.odin(5:2) panic: panic message
Illegal instruction
```
![image](https://github.com/odin-lang/Odin/assets/194614/9b7f7f12-d350-4e67-a33b-3f358c6c6533)
![image](https://github.com/odin-lang/Odin/assets/194614/1923b0ed-7f27-4ee1-bcc4-510f8216c589)

**Comment by woodoocrap** [comment]
so this is expected behaviour got it
