### ISSUE TITLE
Any build fails on macOS

### ISSUE THREAD

**Issue by zangent** [odin-lang/Odin#255]
Any program that I attempt to build produces this error:
```
~/Programming/odin(master) » ./build.sh
odin(45800,0x7fffa1d85380) malloc: *** mach_vm_map(size=8980810975678464) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
./build.sh: line 28: 45800 Segmentation fault: 11  ./odin run examples/demo/demo.odin
```

**Comment by gingerBill** [comment]
Well, that's a nice error...

**Comment by hasenj** [comment]
something seems to be allocating a huge amount of memory
running it through lldb reveals this in the call stack:

    frame #5: 0x000000010006bd03 odin`parse_packages(Parser*, String) [inlined] Array<gbThread> array_make<gbThread>(a=0x00007ffeefbfd150, count=4294967300) at array.cpp:106
    frame #6: 0x000000010006bc7c odin`parse_packages(p=0x00007ffeefbfe848, init_filename=(text = "examples/demo/demo.odin", len = 23)) at parser.cpp:4612

The count is supposed to be the thread count but somehow it seems to be set to some large value.

Value seems to change randomly across runs.

Could it be uninitialized memory?
