### ISSUE TITLE
GLFW window hints not working on M1 Mac

### ISSUE THREAD

**Issue by SamHaskell** [odin-lang/Odin#2556]
## Context

I'm on macOS Ventura 13.4, M1 Macbook Pro, using Odin installed by cloning this repo and building according to the quickstart guide.

Odin Report Output:
	Odin: dev-2023-05:93713252
	OS:   macOS Unknown (build: 22F66, kernel: 22.5.0)
	CPU:  ARM64
	RAM:  16384 MiB

## Expected Behavior

In GLFW, I should be able to use window hints to choose a version of OpenGL, as well as choose the CORE profile, and also (necessary on macOS) set forward compatibility.

## Current Behavior

Currently the Window Hints are being ignored, and printing the version of OpenGL being used gives the default v2.1. I have minimal examples using both GLFW and SDL. In SDL everything works fine and I can load GL 4.1, so I can only assume the issue is with the GLFW bindings.

The OpenGL load_up_to procedure seems to work fine, as the compiler does not complain about me using things like gl.GenVertexArrays, however these function calls fail at runtime, and fmt.println(string(gl.GetString(gl.VERSION))) shows 2.1 as the GL version in use.

### Steps to Reproduce

1. Install Odin according to the quickstart guide.
2. Start a minimal GLFW and OpenGL application as follows

```
package main

  import "core:fmt"
  import glfw "vendor:glfw"
  import gl "vendor:opengl"

  main :: proc() {
    glfw.WindowHint(glfw.CONTEXT_VERSION_MAJOR, 4)
    glfw.WindowHint(glfw.CONTEXT_VERSION_MINOR, 1)
    glfw.WindowHint(glfw.OPENGL_PROFILE, glfw.OPENGL_CORE_PROFILE)
    glfw.WindowHint(glfw.OPENGL_FORWARD_COMPAT, 1)

    glfw.Init()
    window := glfw.CreateWindow(800, 600, "Test", nil, nil)
    glfw.MakeContextCurrent(window)

    gl.load_up_to(4, 1, glfw.gl_set_proc_address)

    fmt.println(string(gl.GetString(gl.VERSION)))
  }
```

my output here reads "2.1 Metal - 83.1", where I would expect "4.1 Metal - 83.1"

As mentioned previously, an analagous example using SDL instead of GLFW works perfectly fine.

**Comment by SamHaskell** [comment]
Moving glfw.Init() to be called before setting Window Hints seems to fix this, I am not sure if this is expected behaviour. In this case, maybe the GLFW OpenGL example provided in examples should be updated to reflect this?

**Comment by SamHaskell** [comment]
Moving glfw.Init() to be called before setting Window Hints seems to fix this, I am not sure if this is expected behaviour. In this case, maybe the GLFW OpenGL example provided in examples should be updated to reflect this?

**Comment by gingerBill** [comment]
This is very expected behaviour. You need to initialize GLFW before you can do anything with it.

**Comment by SamHaskell** [comment]
Yeah I see now, thanks. I had been doing so before but was having what I now know are unrelated runtime issues, so I consulted the GLFW example here and followed that, where the initialisation is done after setting window hints for some reason.

**Comment by Kelimion** [comment]
> Moving glfw.Init() to be called before setting Window Hints seems to fix this, I am not sure if this is expected behaviour. In this case, maybe the GLFW OpenGL example provided in examples should be updated to reflect this?

Which example are you talking about? I'd like to update it, but [the example I'm thinking of](https://github.com/odin-lang/examples/blob/master/glfw/window/simple_window.odin#L16) does `init` at the start of `main()`.

**Comment by SamHaskell** [comment]
I was getting myself confused, I think the official odin example is correct. I was mixed up between that one and another that I was referencing which seems to be incorrect, so that's my bad.
