### ISSUE TITLE
macOS - raylib Camera2D does not render

### ISSUE THREAD

**Issue by brunodeangelis** [odin-lang/Odin#2561]
## Context

* Operating System & Odin Version: macOS Ventura 13.4 - M1 Max
* Please paste `odin report` output:

```
Odin: dev-2023-05:508d7c33
OS:   macOS Unknown (build: 22F66, kernel: 22.5.0)
CPU:  ARM64
RAM:  65536 MiB
```

## Expected Behavior

Draw calls inside the `BeginMode2D` and `EndMode2D` calls should render properly.

## Current Behavior

Draw calls inside the `BeginMode2D` and `EndMode2D` calls are not being rendered.

## Failure Information (for bugs)

I wonder if my issue is related to #1020 
Or to [this as well](https://powerc9000.itch.io/cute-asset-pipeline/devlog/199537/working-with-odin-on-macos).

A literal copy of [raylib's Camera2D examples](https://www.raylib.com/examples.html) into Odin do not work. The C versions of those examples do work.

[A Linux user tested](https://discord.com/channels/568138951836172421/939891986322825246/1112719303234555956) my same exact code and it worked for him. [Another macOS user tested](https://discord.com/channels/568138951836172421/1112732842565316618/1112739698088104096) and it didn't work for him. So definitely a Mac issue.

Please see [this thread](https://discord.com/channels/568138951836172421/1112732842565316618/1112732842565316618) in the Odin's discord server for more information.

Also do have a look at [this message](https://discord.com/channels/568138951836172421/939891986322825246/1112137968862380122) for a similar issue that could be related to this one.

### Steps to Reproduce

This code is enough to see the issue.
```c
package main

import rl "vendor:raylib"

main :: proc() {
    rl.InitWindow(800, 600, "wth am i doing 😵‍💫")
    defer rl.CloseWindow()

    for !rl.WindowShouldClose() {
        camera := rl.Camera2D {
            zoom = 1.0,
        }

        {
            rl.BeginDrawing()
            defer rl.EndDrawing()

            rl.ClearBackground(rl.DARKGRAY)

            {
                rl.BeginMode2D(camera)
                defer rl.EndMode2D()
                rl.DrawCircle(0, 0, 250, rl.YELLOW)
            } // Ends 2D mode
        } // Ends drawing
    }
}
```

**Comment by gingerBill** [comment]
It is an ABI bug specifically for ARM64.

The `BeginMode2D` procedure is being produced incorrectly:

```llvm
declare void @BeginMode2D([6 x float])
```
It should be passed by pointer rather than as 6 floats (i.e. in registers)
