### ISSUE TITLE
compiler crash: Assertion Failure: `args.count >= pt->params->Tuple.variables.count` 

### ISSUE THREAD

**Issue by ryuukk** [odin-lang/Odin#2606]
## Context

OS: Arch Linux x64

llvm: 14.0.6-3

Odin: built from master, latest commit: ``19ea0906332e6185cd0eefe873179b9058ccd725``

(i had to do: ``export PATH="/usr/lib/llvm14/bin:$PATH"``

```
	Odin: dev-2023-06:19ea090
	OS:   Unknown Linux Distro, Linux 6.3.8-arch1-1
	CPU:  Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	RAM:  15867 MiB
```

## Expected Behavior

It should compile

## Current Behavior

Compiler crashes

## Failure Information (for bugs)

```
src/llvm_backend_proc.cpp(3344): Assertion Failure: `args.count >= pt->params->Tuple.variables.count` 
./build.sh: line 4: 431507 Illegal instruction     (core dumped) ../odin/odin build src/main_game.odin -file -collection:rt=src/rt -collection:game=src/game -collection:dawn=src/dawn -out:bin/game -use-separate-modules -debug
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. ``git clone https://github.com/ryuukk/kdomo.git``
2. ``cd kdomo``
3. ``./build.sh debug``

### Note

It compile with: Odin: dev-2023-06

**Comment by gingerBill** [comment]
Also, why the heck are you using `libc.printf` rather than `fmt.printf`?
