### ISSUE TITLE
Debug build on Windows fails due to missing dlls

### ISSUE THREAD

**Issue by ftphikari** [odin-lang/Odin#2613]
## Current Behavior

Doing `build` fails with error message that it is missing `vcruntime140d.dll` and `vcruntime140_1d.dll`. However the SDK has `vcruntime140d.dll_amd64` and `vcruntime140_1d.dll_amd64` present, which are those libraries, just specific to my architecture.

## Expected Behavior

Compiler should automatically recognize the `_amd64` dlls.

**Comment by Kelimion** [comment]
I can't replicate this. There are no replication steps or any information about the environment in which this supposedly happened.

Furthermore, it's missing vital information about the environment in which you encountered this:
- Odin version, and whether it was a release build, built from git
- VS/cl.exe version and whether installed it using Microsoft's installer, Martin's, some variation of it.
- OS + version

**Comment by ftphikari** [comment]
I'm sorry, I assumed this happens with a normal VS installation, but seems that it only happens with Martin's installation. It is present on all Odin versions, latest master and latest release. Here is Odin report:

        Odin: dev-2023-06:
        OS:   Windows 11 Professional (version: 22H2), build 22621.1702
        CPU:  Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
        RAM:  9938 MiB

**Comment by ftphikari** [comment]
Actually it doesn't fail the build itself, but it fails to do `odin run examples/demo`

**Comment by Kelimion** [comment]
Debug builds work just fine when you install VS properly.

I suggest you work out how the VS environment differs when installed via Martin's script and offer him a bug fix for it. An Odin bug it's clearly not.

**Comment by Kelimion** [comment]
> Actually it doesn't fail the build itself, but it fails to do `odin run examples/demo`

That's what I tried on a proper VS install with the latest Odin. ;-)

**Comment by ftphikari** [comment]
Okay, I'll bug Martins about it and see if it can be fixed on our end.
