### ISSUE TITLE
-debug build times can dramatically increase in 3ab01db 

### ISSUE THREAD

**Issue by JesseRMeyer** [odin-lang/Odin#2618]
`Fix type switch debug information on -o:none `

This commit caused my application's compilation time with `-debug` to explode by 8x.  The commit prevents the `lb_run_remove_dead_instruction_pass` function from running in that mode.  But the IR generation portion of the compiler apparently generates so many dead instructions that we actually do want to cull most of them for reasonable debug compilation performance.

I haven't been able to isolate which kinds of Odin code hits this catastrophic case for LLVM.

**Comment by gingerBill** [comment]
Please try this now on the latest commit
