### ISSUE TITLE
`core:mem/virtual` `Arena` is slow at committing memory on Windows

### ISSUE THREAD

**Issue by ftphikari** [odin-lang/Odin#2644]
## Context

* Operating System & Odin Version:

        Odin: dev-2023-07-nightly:3072479c
        OS:   Windows 11 Professional (version: 22H2), build 22621.1702
        CPU:  Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
        RAM:  9938 MiB

## Example code

```odin
package main

import "core:os"
import "core:fmt"
import "core:time"
import "core:mem"
import "core:mem/virtual"
import "core:encoding/json"

Manifest :: struct {
	channel_items: []struct {
		id: string `json:"id"`,

		payloads: []struct {
			file_name: string `json:"fileName"`,
			sha256: string `json:"sha256"`,
			size: int `json:"size"`,
			url: string `json:"url"`,
		} `json:"payloads"`,

		localized_resources: []struct {
			language: string,
			license: string,
		} `json:"localizedResources"`,
	} `json:"channelItems"`,
}

VIRTUAL :: false

main :: proc() {
	when VIRTUAL {
		arena: virtual.Arena
		_ = virtual.arena_init_static(&arena, mem.Gigabyte, 64 * mem.Megabyte)
		defer virtual.arena_destroy(&arena)
		context.allocator = virtual.arena_allocator(&arena)
	} else {
		pool: mem.Dynamic_Pool
		mem.dynamic_pool_init(pool = &pool, alignment = 64, block_size = 64 * mem.Megabyte)
		defer mem.dynamic_pool_destroy(&pool)
		context.allocator = mem.dynamic_pool_allocator(&pool)
	}

	data, ok := os.read_entire_file("VisualStudio.vsman")
	assert(ok)

	start := time.tick_now()

	manifest: Manifest
	err := json.unmarshal(data, &manifest)
	assert(err == nil)

	fmt.println("took", time.tick_since(start))
}
```
(Download [VisualStudio.vsman](https://cdn.discordapp.com/attachments/851931108764549131/1127911698980929666/VisualStudio.vsman))

## Issue

When `VIRTUAL` is set to false, it finishes parsing in 1.5s on my machine. When `VIRTUAL` is true it takes several minutes, and in the task manager it commits memory very very slowly, like 1 MB a second or slower.

**Comment by JesseRMeyer** [comment]
The reason is because the commit size for the arena allocators is usually at allocation granularity, as opposed to a multiple of the page size.  This is a design flaw and needs to be improved / fixed.

**Comment by JesseRMeyer** [comment]
The growable arena doesn't suffer from the extreme performance issues as the static one, but also tends to issue small allocation sizes.  The big difference is that it reserves memory in independent, large blocks as opposed to 1 contiguous block.

**Comment by gingerBill** [comment]
This should be completely fixed now. This was due to the arena only commit a page at a time when the allocations were smaller than a page. I've added a heuristic now to grow by about 1.5x of the previous the commit size or the size of the requested allocation (whichever is larger).
