### ISSUE TITLE
transmuting an array to an integer (or other array) is not constant

### ISSUE THREAD

**Issue by Beefster09** [odin-lang/Odin#2660]
## Context

```
Odin: dev-2023-07:204c0fa4
        OS:   Windows 10 Home Basic (version: 22H2), build 19045.3208
        CPU:  Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
        RAM:  65343 MiB
```

## Expected Behavior

```
BLACK :: transmute(u32) [4]u8 { 0, 0, 0, 255 }
```

should be equivalent to

```
BLACK :: 0xff000000
```

(assuming little-endian byte order; it would be `0x000000ff` on big-endian architecture)

## Current Behavior

Compiler error:

```
Error: 'transmute(u32)[4]u8{0, 0, 0, 255}' is not a constant
```

The same error happens with `transmute([1]u32)`

**Comment by gingerBill** [comment]
This is not a bug. We do not want to allow this for many reasons, but a better error message might be needed.

**Comment by Beefster09** [comment]
I'm curious what the rationale is for not allowing this. I expected that might be the case, but I can't exactly pinpoint specifics on why this isn't allowed.

**Comment by gingerBill** [comment]
@Beefster09 Think about how it would be implemented in the compiler's frontend, and the complications it would involve for something is not at all needed in practice.
