### ISSUE TITLE
Assertion failed in odin compiler

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2671]
## Context

I got this assertion:`
:\a\Odin\Odin\src\llvm_backend_expr.cpp(4167): Assertion Failure: union_variant_index(ft, fet) > 0 Rect
`

Odin: dev-2023-07-nightly:1ecb4aa9
OS:   Windows 10 Home Basic (version: 22H2), build 19045.3208
CPU:  AMD Ryzen 5 3400G with Radeon Vega Graphics
RAM:  8128 MiB

## Expected Behavior
It would not assert
## Current Behavior
It asserts
## Failure Information (for bugs)
I was in the middel of a refactor.
### Steps to Reproduce
I am sadly unable recreate the bug.

**Comment by gingerBill** [comment]
This should have already been fixed.

**Comment by xzores** [comment]
Ok, we will update then
