### ISSUE TITLE
Compiler does compile invalid code

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2674]
## Context

Odin: dev-2023-07-nightly:3072479c
OS:   Windows 11 Home Basic (version: 22H2), build 22621.1992
CPU:  13th Gen Intel(R) Core(TM) i9-13900HX
RAM:  32507 MiB

## Expected Behavior

The following code should not compile:

```
texcoords_dyn    : [dynamic][2]f32 = make([dynamic][2]f32);
append(&texcoords_dyn, );
```

## Current Behavior

The code compiles with no error.

### Steps to Reproduce

Copy the code into a project and compile.

**Comment by laytan** [comment]
Technically not a bug, as `append` resolves to `append_elems` https://github.com/odin-lang/Odin/blob/1b3657122cb69b96ec54dd878e4fbdbb00641bcc/core/runtime/core_builtin.odin#L438 which is a variadic procedure, which means any amount of arguments is ok.

Could be changed to a signature like `append_elems :: proc(array: ^$T/[dynamic]$E, arg: E, args: ..E, loc := #caller_location) -> (n: int, err: Allocator_Error) #optional_allocator_error {`

I don't think it is worth it though, it would add instructions + the code will run normally the way it is now.

**Comment by laytan** [comment]
Not that I know of, would be nice yeah.

**Comment by StevenClifford** [comment]
Will such a condition not break code like this:
`append(&errors, ..new_errors)`
where `new_errors` is a slice that can have zero elements?

I say this because I am currently using it exactly like that, and more people might be.

**Comment by JesseRMeyer** [comment]
I agree that we should avoid breaking changes like that (even if the general feature would still be useful).  

I wonder if this should be classified as a syntax error as opposed to a semantic error.

**Comment by xzores** [comment]
I personally think `append(&texcoords_dyn, );` Should not compile.
But that `append(&errors, ..new_errors)` should compile even when new_errors holds nothing.

The compiler just has to check if there is a token (I think they call it token) at the postion, and give error if there is nothing there.
That does not break `append(&errors, ..new_errors)`.

**Comment by xzores** [comment]
I will close, this as it is not a bug, but a discussion.
