### ISSUE TITLE
Labeled #partial switch crashes the compiler

### ISSUE THREAD

**Issue by ChuuniMage** [odin-lang/Odin#2677]
## Context

Labelled partial switch statement works when written like this:

`#partial THE_LABEL: switch val {`

but crashes the compiler when written like this

`THE_LABEL: #partial switch val {`

* Operating System & Odin Version: 
* Please paste `odin report` output:

        Odin: dev-2023-07:0a897e2f
        OS:   Windows 10 Professional (version: 20H2), build 19042.1706
        CPU:  Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz
        RAM:  32637 MiB

**Comment by programandala-net** [comment]
Currently it does not _crashes_ de compiler anymore, if that's what you actually meant, but just issues the following error:

> Syntax error: Incorrect use of directive, use '#partial label: switch'

```
Odin:    dev-2024-05
OS:      Debian GNU/Linux 12 (bookworm), Linux 6.1.0-21-amd64
CPU:     Intel(R) Atom(TM) CPU N455   @ 1.66GHz
RAM:     1956 MiB
Backend: LLVM 14.0.6
```
