### ISSUE TITLE
Floating point exception when affecting hexadecimal litteral to int

### ISSUE THREAD

**Issue by Breush** [odin-lang/Odin#268]
This small code produces a compiler crash (core dumped) (on master branch 1a4e25f14149428ff19f2da239abe54ff0083632):

```c++
package main

main :: proc() {
    // Compiler crash when the negative bit is on
    value : i32 = 0xFFFFFFFF;
}
```

**Comment by gingerBill** [comment]
What operating system/platform is this happening on?

**Comment by Breush** [comment]
Linux (Debian 9.5)

**Comment by gingerBill** [comment]
Please make a PR for that fix. 

Also that error message is absolutely correct. That value does overflow `i32`. If you want do what you would expect in C, I recommend the following:
```
value := ~i32(0);
```
