### ISSUE TITLE
"odin version" should reflect release version

### ISSUE THREAD

**Issue by mtarik34b** [odin-lang/Odin#2688]
## Context

	Odin: dev-2023-07:551c379f
	OS:   Ubuntu 22.04.2 LTS, Linux 5.19.0-50-generic
	CPU:  Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	RAM:  15751 MiB

## Expected Behavior

I expect the `odin version` command to reflect the release version I'm currently at, being `dev-2023-07` for the master and `dev-2022-12` after the checkout.

## Current Behavior

`odin version` shows the correct commit, but the wrong release version after the checkout (see last line).
### Steps to Reproduce

```
/usr/local/bin/Odin >sudo git checkout master
[...]
/usr/local/bin/Odin >odin version
odin version dev-2023-07:551c379f
/usr/local/bin/Odin >sudo git checkout dev-2022-12
[...]
/usr/local/bin/Odin >sudo make
[...]
/usr/local/bin/Odin >odin version
odin version dev-2023-07:521ed286
```

**Comment by eliaspekkala** [comment]
It seems the Odin version is set through the `build_odin.sh` script to be the year and month when the command is run: https://github.com/odin-lang/Odin/blob/0de7df9eab9b256e0d1c8da7c9fc8c422c5ac1a7/build_odin.sh#L8
This may be the cause of this issue.

**Comment by Kelimion** [comment]
We would have to use `git describe --tags` to get the current version. That would not remedy this bug retroactively, of course.
