### ISSUE TITLE
Passing dynamic buffer to strconv.itoa results in "illegal hardware instruction"

### ISSUE THREAD

**Issue by KieranP** [odin-lang/Odin#2695]
## Context

I have an integer of unknown size that I need to convert into a string.

```
x := 100000000
buf1: [dynamic]byte
xs := strconv.itoa(buf1[:], x)
```

This results in:

```
/usr/local/Cellar/odin/2023-07/libexec/core/strconv/integers.odin(104:19) Invalid slice indices 0:1 is out of range 0..<0
zsh: illegal hardware instruction
```

odin report:

```
Odin: dev-2023-07:3072479c
OS:   macOS Unknown (build: 22F82, kernel: 22.5.0)
CPU:  Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
RAM:  32768 MiB
```

## Expected Behavior

Should return string

## Current Behavior

illegal hardware instruction

**Comment by KieranP** [comment]
@gingerBill @z64 Even if this is not intended syntax, shouldn't the compiler pick it up rather than allowing a runtime crash?

**Comment by KieranP** [comment]
@z64 Fair enough. I guess what is tripping me up is the inconsistency between dyanmic and fixed length.

For example, based on your comment about empty array, I would expect this also to fail, but it doesn't:

```odin
package main

main :: proc() {
  buf1: [5]byte
  buf1[0] = 0
}
```

Why should [5]byte work, but [dynamic]byte fail? It seems to me, for consistency, either both should work or both fail :-/

**Comment by Lperlind** [comment]
Ideally an error would be returned as we could check the len of the slice in the function

**Comment by KieranP** [comment]
@z64 Thanks for the explanation. Much appreciated. I agree with @Lperlind that an error would be ideal, "cannot alter uninitialised dynamic array" or something similar, to better indicate the cause, rather than "illegal hardware instruction".

Either way, I was able to complete the project I was working on (https://github.com/KieranP/Game-Of-Life-Implementations/tree/master/odin).

As a side point, a built in itoa that dynamically assigns a buffer, like Golang, would be nice and reduce boilerplate, otherwise I find myself creating buffers numerous times.

Odin:
```odin
buf1: [3]byte
xs := strconv.itoa(buf1[:], x)
```

v.s.

Golang:
```go
xs := strconv.Itoa(x)
```
