### ISSUE TITLE
Compiler panic using slice.sort on wasm32

### ISSUE THREAD

**Issue by stan680** [odin-lang/Odin#2698]
## Context

        Odin: dev-2023-08:4a71603a
        OS:   Windows 10 Home Basic (version: 22H2), build 19045.3208
        CPU:  Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
        RAM:  16283 MiB

## Expected Behavior

Compiler should not panic when using slice.sort on wasm32 target

## Current Behavior

Compiler panics when using slice.sort on wasm32 target

### Steps to Reproduce

Compiling this with `odin build main.odin -file -target=js_wasm32` (or `freestanding_wasm32`) should work
```Odin
package main
import "core:slice"

main :: proc() {
	array :[5]int
	slice.sort(array[:])
}
```

### Failure Logs

```
A:\projects\Odin\src\llvm_backend_general.cpp(2886): Panic: 
	Error in: A:/projects/Odin/core/slice/sort_private.odin(15:66), missing value 'call'
```

**Comment by Kelimion** [comment]
Confirmed. It's peculiar.
