### ISSUE TITLE
Using struct pointers leads to multiple bizarre behaviour

### ISSUE THREAD

**Issue by KieranP** [odin-lang/Odin#2704]
## Context

```
	Odin: dev-2023-08:9453b238
	OS:   macOS Unknown (build: 22F82, kernel: 22.5.0)
	CPU:  Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
	RAM:  32768 MiB
```

I'm making a conways game of life implementation (see my many implementations here: https://github.com/KieranP/Game-Of-Life-Implementations). The idea is that there is a world and a world has width and height, and it has many cells stored in a map with keys as their x,y coords. Because later on cells can references one another and get updated, I'm creating the cell and then using references/pointers to them. Except within Odin, this is leading to some very unusual output.

Here is my script, nothing complex at this stage:

```odin
package main

import "core:fmt"

World :: struct {
  width: int,
  height: int,
  cells: map[[2]int]^Cell,
}

Cell :: struct {
  x: int,
  y: int
}

newWorld :: proc(width: int, height: int) -> ^World {
  world := &World {
    width=width,
    height=height
  }

  world_populate_cells(world)

  return world
}

newCell :: proc(x: int, y: int) -> ^Cell {
  cell := &Cell {
    x=x,
    y=y,
  }

  return cell
}

world_populate_cells :: proc(world: ^World) {
  fmt.println(world)
  fmt.println("width")
  fmt.println(world.width)
  fmt.println("height")
  fmt.println(world.height)

  for y in 0..<world.height {
    for x in 0..<world.width {
      cell := newCell(x, y)
      key := [2]int{x,y}
      world.cells[key] = cell
    }
  }
}

world_render :: proc(world: ^World) {
  fmt.println(world)
  fmt.println("width")
  fmt.println(world.width)
  fmt.println("height")
  fmt.println(world.height)
}

main :: proc() {
  world := newWorld(150, 40)

  world_render(world)
}
```

If you run this, this is the output (have trimmed the cells map result)

```
&World{width = 150, height = 40, cells = map[]}
width
150
height
40

&World{width = 150, height = 40, cells = map[[91, 9]=0x7FF7B6A01068, [100, 20]=0x7FF7B6A01068, [20, 3]=0x7FF7B6A01068, [37, 16]=0x7FF7B6A01068, [83, 9]=0x7FF7B6A01068, [76, 21]=0x7FF7B6A01068, [124, 4]=0x7FF7B6A01068, [93, 34]=0x7FF7B6A01068, [13, 19]=0x7FF7B6A01068, ................... [105, 36]=0x7FF7B6A01068, [74, 6]=0x7FF7B6A01068]}
width
432345564227567627
height
140701897593568
```

Note the odd behaviour:

1) When `world_populate_cells` runs (the first part of the output), calling `world.width` and `world.height` returns the correct values (150 and 40 respectively), but the same `world` passed into `world_render` (the second part of the output), though the struct itself shows the correct width/height, calling `world.width` and `world.height` returns excessively large numbers (in my case 432345564227567627 and 140701897593568). That is weird right? Is the struct right above it is showing the right width/height, why would calling the width/height properties of the struct return something different?

2) All the cell memory references are the same, `0x7FF7B6A01068`. Why would this be the case? I'm creating a new Cell struct instance for each x/y coord set, fetching it's memory reference, and storing that. So shouldn't all the memory references point to different locations where that particular instance of the Cell resides?

3) Finally, if you add a final `fmt.println(world)` at the end of world_render, with nothing else changing, now the program segfaults.

**Comment by KieranP** [comment]
@z64 Thank you. That makes sense and helped a lot. I was able to complete the project I was working on (https://github.com/KieranP/Game-Of-Life-Implementations/tree/master/odin), so thank you :-)

Is being able to return references to function locals intended? Seems like the compiler should try to catch it, because evidently that memory space could become corrupted fairly quickly. Maybe disallow such behaviour unless an #unsafe_pointers declaration is provided?

**Comment by Kelimion** [comment]
> @z64 Thank you. That makes sense and helped a lot. I was able to complete the project I was working on (https://github.com/KieranP/Game-Of-Life-Implementations/tree/master/odin), so thank you :-)
> 
> Is being able to return references to function locals intended? Seems like the compiler should try to catch it, because evidently that memory space could become corrupted fairly quickly. Maybe disallow such behaviour unless an #unsafe_pointers declaration is provided?

That's the kind of thing you can't catch without static analysis, which would complicate the compiler. You may want to pass it to a callee in a child stack frame, and it'll be valid until that callee returns and the parent stack frame exits, so there's no problem with taking the address of a stack variable in itself.

**Comment by gingerBill** [comment]
I do want to add loads of good escape analysis with the Tilde backend. It's just not currently possible with the Odin frontend (for loads of complex reasons, beyond the trivial cases), and better handled in the middleend/backend.
