### ISSUE TITLE
math.round is wrong on some values

### ISSUE THREAD

**Issue by ryhor-spivak** [odin-lang/Odin#2705]
## Context

* Operating System & Odin Version:
* 
        Odin: dev-2023-08-nightly:9453b238
        OS:   Windows 10 Unknown Edition (00000064) (version: 22H2), build 19045.3208
        CPU:  AMD Ryzen 7 5800HS with Radeon Graphics
        RAM:  15775 MiB

## Expected Behavior

I expect this program:

	package main

	import "core:fmt"
	import "core:math"

	round_test :: proc(x: $FP)
	{
		rx := math.round(x)
		fmt.printf("%.17f(%h) rounds to %f(%h)\n", x, x, rx, rx )
	}

	main :: proc()
	{
		round_test(f16(0.4998))
		round_test(f16(1025))
		round_test(f16(-0.4998))
		round_test(f16(-1025))

		round_test(f32(0.49999997))
		round_test(f32(8388611))
		round_test(f32(-0.49999997))
		round_test(f32(-8388611))

		round_test(f64(0.49999999999999994))
		round_test(f64(4503599627370497))
		round_test(f64(-0.49999999999999994))
		round_test(f64(-4503599627370497))
	}

to produce this output:

	0.49975585937500000(0h37ff) rounds to 0.000(0h0)
	1025.00000000000000000(0h6401) rounds to 1025.000(0h6401)
	-0.49975585937500000(0hb7ff) rounds to -0.000(0h8000)
	-1025.00000000000000000(0he401) rounds to -1025.000(0he401)
	0.49999997019767761(0h3effffff) rounds to 0.000(0h0)
	8388611.00000000000000000(0h4b000003) rounds to 8388611.000(0h4b000003)
	-0.49999997019767761(0hbeffffff) rounds to -0.000(0h80000000)
	-8388611.00000000000000000(0hcb000003) rounds to -8388611.000(0hcb000003)
	0.49999999999999994(0h3fdfffffffffffff) rounds to 0.000(0h0)
	4503599627370497.00000000000000000(0h4330000000000001) rounds to 4503599627370497.000(0h4330000000000001)
	-0.49999999999999994(0hbfdfffffffffffff) rounds to -0.000(0h8000000000000000)
	-4503599627370497.00000000000000000(0hc330000000000001) rounds to -4503599627370497.000(0hc330000000000001)

## Current Behavior

But currently, it produces this:

	0.49975585937500000(0h37ff) rounds to 1.000(0h3c00)
	1025.00000000000000000(0h6401) rounds to 1026.000(0h6402)
	-0.49975585937500000(0hb7ff) rounds to -1.000(0hbc00)
	-1025.00000000000000000(0he401) rounds to -1026.000(0he402)
	0.49999997019767761(0h3effffff) rounds to 1.000(0h3f800000)
	8388611.00000000000000000(0h4b000003) rounds to 8388612.000(0h4b000004)
	-0.49999997019767761(0hbeffffff) rounds to -1.000(0hbf800000)
	-8388611.00000000000000000(0hcb000003) rounds to -8388612.000(0hcb000004)
	0.49999999999999994(0h3fdfffffffffffff) rounds to 1.000(0h3ff0000000000000)
	4503599627370497.00000000000000000(0h4330000000000001) rounds to 4503599627370498.000(0h4330000000000002)
	-0.49999999999999994(0hbfdfffffffffffff) rounds to -1.000(0hbff0000000000000)
	-4503599627370497.00000000000000000(0hc330000000000001) rounds to -4503599627370498.000(0hc330000000000002)

My attempt to fix this (https://github.com/odin-lang/Odin/pull/2675) was closed as incorrect, so this should be fixed is some other way.

**Comment by listeriaceae** [comment]
[Here's](https://github.com/llvm/llvm-project/blob/main/libc/src/__support/FPUtil/NearestIntegerOperations.h#L103) how llvm does it. What follows is a port for `f16`, it's my first time using odin so I don't know if any of it is bad style or anything:

```odin
package math

import "fpbits"

@(require_results)
round_f16 :: proc "contextless" (x: f16) -> f16 {
	bits := transmute(u16)x

	if fp.is_inf_or_nan(bits) || fp.is_zero(bits) {
		return x
	}

	is_neg := fp.signbit(bits)
	exponent := fp.exponent(bits)

	if exponent >= int(fp.mantissa_width(f16)) {
		return x
	}

	if exponent == -1 {
		if is_neg {
			return -1.0
		} else {
			return +1.0
		}
	}

	if exponent <= -2 {
		if is_neg {
			return -0.0
		} else {
			return +0.0
		}
	}

	trim_size := fp.mantissa_width(f16) - uint(exponent)
	mantissa := fp.mantissa(bits)
	half_bit := mantissa & (1 << (trim_size - 1))
	bits &~= fp.mantissa_mask(f16)
	bits |= mantissa >> trim_size << trim_size
	trunc_value := transmute(f16)bits

	if trunc_value == x {
		return x
	}

	if half_bit == 0 {
		return trunc_value
	} else if is_neg {
		return trunc_value - 1
	} else {
		return trunc_value + 1
	}
}

round :: proc{
	round_f16,
}
```

```odin
package fpbits

@(require_results)
signbit_f16 :: proc "contextless" (bits: u16) -> bool {
	return (bits & sign_mask(f16)) != 0
}

signbit :: proc{
	signbit_f16,
}

@(require_results)
exponent_f16 :: proc "contextless" (bits: u16) -> int {
	return int(unbiased_exponent(bits)) - exponent_bias(f16)
}

exponent :: proc{
	exponent_f16,
}

@(require_results)
mantissa_f16 :: proc "contextless" (bits: u16) -> u16 {
	return bits & mantissa_mask(f16)
}

mantissa :: proc{
	mantissa_f16,
}

@(require_results)
sign_mask_f16 :: proc "contextless" ($FP: typeid) -> u16
	where FP == f16 {
	return 1 << (exponent_width(f16) + mantissa_width(f16))
}

sign_mask :: proc{
	sign_mask_f16,
}

@(require_results)
exponent_mask_f16 :: proc "contextless" ($FP: typeid) -> u16 
	where FP == f16 {
	return ~(sign_mask(f16) | mantissa_mask(f16))
}

exponent_mask :: proc{
	exponent_mask_f16,
}

@(require_results)
mantissa_mask_f16 :: proc "contextless" ($FP: typeid) -> u16 
	where FP == f16 {
	return (1 << mantissa_width(f16)) - 1
}

mantissa_mask :: proc{
	mantissa_mask_f16,
}

@(require_results)
exponent_width_f16 :: proc "contextless" ($FP: typeid) -> uint 
	where FP == f16 {
	return 5
}

exponent_width :: proc{
	exponent_width_f16,
}

@(require_results)
mantissa_width_f16 :: proc "contextless" ($FP: typeid) -> uint 
	where FP == f16 {
	return 10
}

mantissa_width :: proc{
	mantissa_width_f16,
}

@(require_results)
is_zero_f16 :: proc "contextless" (bits: u16) -> bool {
	return (bits << 1) == 0
}

is_zero :: proc{
	is_zero_f16,
}

@(require_results)
is_inf_or_nan_f16 :: proc "contextless" (bits: u16) -> bool {
	return (bits & exponent_mask(f16)) == exponent_mask(f16)
}

is_inf_or_nan :: proc{
	is_inf_or_nan_f16,
}

@(require_results)
exponent_bias :: proc "contextless" ($FP: typeid) -> int {
	return (1 << (exponent_width(FP) - 1)) - 1
}

@(require_results)
unbiased_exponent_f16 :: proc "contextless" (bits: u16) -> u16 {
	return (bits & exponent_mask(f16)) >> mantissa_width(f16)
}

unbiased_exponent :: proc{
	unbiased_exponent_f16,
}
```

**Comment by listeriaceae** [comment]
After having read some of the standard library, I imagine something like this is more idiomatic:

```odin
package main

import "core:math"

@(require_results)
round_f16 :: proc "contextless" (x: f16) -> f16 {
	mask  :: math.F16_MASK
	shift :: math.F16_SHIFT
	bias  :: math.F16_BIAS

	if x == 0 || math.is_nan(x) || math.is_inf(x) {
		return x
	}

	bits := transmute(u16)x
	e := int((bits >> shift) & mask) - bias

	switch {
	case e >= shift:
		return x
	case e == -1:
		return math.copy_sign_f16(1, x)
	case e <= -2:
		return math.copy_sign_f16(0, x)
	}

	trim_size := shift - uint(e)
	half_bit := bits & (1 << (trim_size - 1))
	bits &~= (1 << trim_size) - 1
	trunc_value := transmute(f16)bits

	switch {
	case trunc_value == x:
		return x
	case half_bit == 0:
		return trunc_value
	case x < 0:
		return trunc_value - 1
	case:
		return trunc_value + 1
	}
}

round :: proc{
	round_f16,
}
```

**Comment by ryhor-spivak** [comment]
I still don't know what is wrong with my fix. You can just loop through all bit patterns of f16 and f32 and check it works as expected:

	package main

	import "core:fmt"
	import "core:math"

	@(require_results)
	round_f16_fix :: proc "contextless" (x: f16)   -> f16 {
		return math.ceil(x - 0.4998) if x < 0 else math.floor(x + 0.4998)
	}

	@(require_results)
	round_f32_fix :: proc "contextless" (x: f32)   -> f32 {
		return math.ceil(x - 0.49999997) if x < 0 else math.floor(x + 0.49999997)
	}

	@(require_results)
	round_f64_fix :: proc "contextless" (x: f64)   -> f64 {
		return math.ceil(x - 0.49999999999999994) if x < 0 else math.floor(x + 0.49999999999999994)
	}

	round_fix :: proc{
		round_f16_fix,
		round_f32_fix,
		round_f64_fix,
	}

	round_check :: proc(x: $FP)
	{
		rx := round_fix(x)
		//rx := math.round(x) // this will show all bad cases of current math.round version

		if math.is_nan(x) && !math.is_nan(rx)
		{
			fmt.printf("fail on %.9f(%h): rounds to %f(%h)\n", x, x, rx, rx )
			return
		}

		f := math.floor(x)
		c := math.ceil(x)

		if x > 0
		{
			if x - f < c - x
			{
				if rx != f do fmt.printf("fail on %.9f(%h): rounds to %f(%h)\n", x, x, rx, rx )
			}
			else
			{
				if rx != c do fmt.printf("fail on %.9f(%h): rounds to %f(%h)\n", x, x, rx, rx )	
			}
		}
		else
		{
			if x - f <= c - x
			{
				if rx != f do fmt.printf("fail on %.9f(%h): rounds to %f(%h)\n", x, x, rx, rx )
			}
			else
			{
				if rx != c do fmt.printf("fail on %.9f(%h): rounds to %f(%h)\n", x, x, rx, rx )	
			}
		}
	}

	main :: proc()
	{
		fmt.printf("checking all f16:\n")
		{
			u : u16 = 0
			for
			{
				round_check(transmute(f16)u)
				u += 1
				if u == 0 do break
			}
		}

		fmt.printf("checking all f32:\n")
		{
			u : u32 = 0
			for
			{
				round_check(transmute(f32)u)
				u += 1
				if u == 0 do break
			}
		}
	}

**Comment by listeriaceae** [comment]
`round(-0.0)` should return `-0.0`, also I don't know if you can rely on `0.5 + 0.499... == 1`

**Comment by ryhor-spivak** [comment]
-0 can be handled by

	@(require_results)
	round_f16_fix :: proc "contextless" (x: f16)   -> f16 {
		return math.copy_sign(math.floor(abs(x) + 0.4998), x)
	}

	@(require_results)
	round_f32_fix :: proc "contextless" (x: f32)   -> f32 {
		return math.copy_sign(math.floor(abs(x) + 0.49999997), x)
	}

	@(require_results)
	round_f64_fix :: proc "contextless" (x: f64)   -> f64 {
		return math.copy_sign(math.floor(abs(x) + 0.49999999999999994), x)	
	}

And this probably will be faster too.

For relying on fp addition: in all other places we already rely on it rounding to nearest representable float with ties to even.
