### ISSUE TITLE
Compiler compiles invalid code

### ISSUE THREAD

**Issue by albe194e** [odin-lang/Odin#2709]
## Context
The compiler compiles code that it shouldnt compile and gives no error message. 
The given arguments are not suitable for the procedure.
procedure arguments are invalid but still compiles.

Odin: dev-2023-07-nightly:0a897e2f
        OS:   Windows 11 Home Basic (version: 22H2), build 22621.1992
        CPU:  AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
        RAM:  6081 MiB

## Expected Behavior
Expected the compiler to give error message when calling a procedure. 

## Current Behavior
Compiler gives no error message and still runs. 

## Failure Information (for bugs)

Here is the code: 
```
//Procedure call with invalid arguments
 rectangle_inner := get_screen_space_position_rect(inner_rect,              // [4]f32
                                                                    container.anchor,      // Anchor_point
                                                                    container.self_anchor, // Anchor_point
                                                                    screen_width,          // f32
                                                                    screen_height,         // f32
                                                                    unit_size);            // f32

//Procedure definition
get_screen_space_position_rect :: proc(rect : [4]f32,
                                                              anchor : Anchor_point, 
                                                              self_anchor : Anchor_point,
                                  	                      anchor_rect_pixel : [4]f32, 
                                                              screen_size : [2]f32, 
                                                              unit_size : f32) -> [4]f32 {}
```

**Comment by Kelimion** [comment]
This may be an intersection with the array programming system, i.e.
```odin
Vec4: [4]f32
v: Vec4 = 4
```

**Comment by xzores** [comment]
It still recives too few arguments (and they do not have a default value) so I don't think that is the issue.

**Comment by karl-zylinski** [comment]
Unless I misread your repro, this is not a bug.

I think @Kelimion, this is just array programming. `screen_width` and `screen_height` are getting splatted out into the parameters `anchor_rect_pixel: [4]f32` and `screen_size : [2]f32`.

You are passing 6 arguments to a proc with 6 parameters.
