### ISSUE TITLE
I get LLVM ERROR in switch statement

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2715]
## Context

I get an LLVM error.

      Odin: dev-2023-07-nightly:5ac7fe45
      OS:   Windows 11 Home Basic (version: 22H2), build 22621.1992
      CPU:  13th Gen Intel(R) Core(TM) i9-13900HX
      RAM:  32507 MiB

## Expected Behavior

I would get an error from Odin.

## Current Behavior

I get LLVM error:

### Steps to Reproduce

Make a switch with 2 of the same conditions:
Like this:
```
switch command.id {
        case Mes_chat_say:
        case Mes_chat_say:
        case:
}
```

### Failure Logs

```
LLVM Error:
Duplicate integer as switch case
  switch i64 %38, label %switch.default.body [
    i64 3602879701896397334, label %switch.case.body
    i64 3602879701896397334, label %switch.case.body1
  ], !dbg !20857
i64 3602879701896397334
```

**Comment by Feoramund** [comment]
This appears to have been fixed at some point.

```odin
package main

E :: enum {
	A,
}

main :: proc() {
	e := E.A
	switch e {
		case .A:
		case .A:
		case:
	}
}
```
```
/tmp/odin/a.odin(11:9) Error: Duplicate case '.A'
	previous case at /tmp/odin/a.odin(10:9)
	case .A:
	      ^
```
