### ISSUE TITLE
How to install Odin on openSuse Linux?

### ISSUE THREAD

**Issue by joaocarvalhoopen** [odin-lang/Odin#2724]
## Context

Hello, I have a OpenSuse Tumbleweed Linux with llvm16, that some program installed, maybe Rust, when I try to compile the sources from 2023-08-03 they simply say that I have to have llvm15, I already installed llvm15 but i don't now how to change version of llvm that is active, and the internet seems to also don't have a question for this.

How can I compile Odin on openSuse?

**Comment by laytan** [comment]
Hello, you can use the environment variable called `LLVM_CONFIG`, you can point this to the `llvm-config` of version 15.

If it is on your path it should be something like this: `LLVM_CONFIG=llvm15-config make` but it could also be `llvm-15-config` for example.

**Comment by joaocarvalhoopen** [comment]
Thank you, for openSuse Tumbleweed I made the following:
```
sudo zypper install llvm14
sudo zypper install llvm-dev
```
And then made you command:

```LLVM_CONFIG=llvm-config make``` 

and it worked!

Many thanks to you @laytan  :-)
