### ISSUE TITLE
Please, is there a way to see the documentation of Odin without all the page be white, like a Dark mode?

### ISSUE THREAD

**Issue by joaocarvalhoopen** [odin-lang/Odin#2725]
Please, is there a way to see the documentation of Odin without all the page be white, like a Dark mode?

If a dark mode doesn't exist, it would be really nice to the eyes.

Best regards,
João Carvalho

**Comment by joaocarvalhoopen** [comment]
Thank you very much z64, for your suggestion, I will see it, because for a person that is long days and night in front off the computer all that white light, with blue component in RGB messes the eyes :-)

Best regards,
João Carvalho

**Comment by eleriaqueen** [comment]
Hi, I just made a quick-and dirty custom css to avoid being flashbang-ed by the Odin documentation. It's shoddy but gets the job done !
If you don't know how to use it, search google with keywords like "how to userContent.css".
```
@-moz-document domain(odin-lang.org){
  body {
    color: rgb(160,160,160) !important;
    background-color: rgb(10,10,10) !important;
    font-weight: 700 !important;  /* text needs bolding for readability */
  }
  a {
    color:  rgb(200,200,200) !important;
  }
  table tr:nth-child(even) {
    background: rgb(15,15,35) !important;
  }
  li:nth-child(odd) {
	background: rgb(15,15,35) !important;
  }
  textarea, input {
    font-weight: 700 !important;  /* text needs bolding for readability */
  }
  img {
    background-color: rgb(10,10,25)
  }
  footer, nav, section, input {
    background-color: rgb(15,15,35) !important;
    color: rgb(160,160,160) !important;
  }
  nav {
    border: none !important;
  }
  code {
    background-color: rgb(20,20,20) !important;
  }
  pre.doc-code {
    background-color: rgb(20,20,20) !important;
    color: rgb(160,160,160) !important;
  }
}
```
