### ISSUE TITLE
thread.pool_destroy halt if no task was added

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2746]
## Context

I used the thread pool in the threads lib.

Odin: dev-2023-08-nightly:49b24471
OS:   Windows 11 Home Basic (version: 22H2), build 22621.2134
CPU:  13th Gen Intel(R) Core(TM) i9-13900HX
RAM:  32507 MiB

## Expected Behavior

I would expect thread.pool_destroy to not halt

## Current Behavior
thread.pool_destroy halt if no task was added

## Failure Information (for bugs)

There was 1 thread in the thread pool.

### Steps to Reproduce

Make a thread pool,
destroy it

**Comment by Feoramund** [comment]
This looks to be caused by non-started threads being joined to the main thread. You can cause it to happen with plain threads too.
