### ISSUE TITLE
Strong request to remove the proc keyword!!!! Be a most advanced language!!

### ISSUE THREAD

**Issue by karriszou** [odin-lang/Odin#2749]
Odin is so amazing language,  but i don't know why it need the **proc** keyword?

Except for C/C++ language, many other languages ​​need keywords(like func, fn, proc..) to declare functions, but is it really necessary? Why not keep it simple and concise?

I think the **proc** keyword is cumbersome and unnecessary, at this point, only **Jai** has done so that it is the most advanced language out there!

Odin can refer to this, removing the **proc** keyword will make Odin more conciser and advanced!! Why not try it??

**Comment by gingerBill** [comment]
Troll better next time. 

But if you are serious, here's a table showing why Odin's syntax is superior compared to the other alternatives: 

https://gist.github.com/gingerBill/27aec0cd434f2be58d024dccef6e8d13

**Comment by karriszou** [comment]
> Troll better next time.
> 
> But if you are serious, here's a table showing why Odin's syntax is superior compared to the other alternatives:
> 
> https://gist.github.com/gingerBill/27aec0cd434f2be58d024dccef6e8d13

Sorry, I didn't mean to offend and start a meaningless argument,  If this issue is inappropriate I will delete this post. I respect Odin's philosophy, I'm just talking about my opinion seriously.

If remove the **proc** keyword, Odin need introduce the concept of **void** to avoid ambiguity, but actually it's not true.
Jai through a different anonymous function syntax to avoid ambiguity.

I know this is a complicated issue, I am also Blow's fan, so I really wish Odin could use Jai's function syntax.
```
particle_left := view_left * it.particle_size;
particle_up := view_up * it.particle_size;
origin := it.origin;

() [m, origin, particle_left, particle_up] {
    m.Position3fv(origin - particle_left - particle_up);
    m.Position3fv(origin + particle_left - particle_up);
    m.Position3fv(origin + particle_left + particle_up);
    m.Position3fv(origin - particle_left + particle_up);
} (); // Call the function
```
- Jai’s function syntax
```
                                 { ... } // Anonymous code block
                       [capture] { ... } // Captured code block
     (i: int) -> float [capture] { ... } // Anonymous function
f :: (i: int) -> float [capture] { ... } // Named local function
f :: (i: int) -> float [capture] { ... } // Named global function
``` 
Jai's scheme is practical and elegant, detail to see [JaiPrimer](https://github.com/BSVino/JaiPrimer/blob/master/JaiPrimer.md#code-refactoring).

Also, we can declaration function by preprocessor **directive** or other ways.
- Universal declaration syntax
```
// compile-time constants use ::
my_func :: (v: int) -> int { return v + 5; }
my_enum :: enum { Foo; Bar; Baz; }
my_struct :: struct { v: int; }
my_const_float :: 13.37;
my_const_string :: "hello world";
my_func_type :: #type (int) -> int;

// variables use  :=
// the type can be explicit or deduced
a_func_ptr : my_func_type = my_func;
a_float : float = my_const_float;
an_int : int = 42;
another_int := a_func_ptr(an_int);
a_type : Type = string;
another_type := type_of(an_int);
```
We can discard **keyword** and **void** concept to declaration and definition function safely.

**In a word, If Odin has the same function syntax as Jai, that would be great!**

**Comment by gingerBill** [comment]
Jai's syntax is ambiguous to parse. That table I posted is actually a proof of that. 

Your capture syntax examples are not even valid in Jai. If I remember correctly, they were hypothetical proposals from nearly a decade ago, and were never actually implemented.

Please understand that you wanting to remove `proc` means that so many other features that the keyword allows for will not be possible without ambiguity. Please (re-)read that gist I sent.
