### ISSUE TITLE
There is a small typo error in the documentation Overview in the switch statement:

### ISSUE THREAD

**Issue by joaocarvalhoopen** [odin-lang/Odin#2752]
Hello,

in the documentation Overview in the switch statement,

in the code is written 2 times  ```switch in f {``` and it should have been ```switch _ in f {```  the following is the original code :

``` odin
Foo :: union {int, bool}
f: Foo = 123
switch in f {
case int:  fmt.println("int")
case bool: fmt.println("bool")
case:
}

#partial switch in f {
case bool: fmt.println("bool")
}
```

Thank you,

Best regards,
João Carvalho

**Comment by gingerBill** [comment]
All changes to the website can be done at https://github.com/odin-lang/odin-lang.org
