### ISSUE TITLE
bytes.Buffer does not allocate with the given allocator if the initial capacity is 0

### ISSUE THREAD

**Issue by laytan** [odin-lang/Odin#2756]
## Context

* Operating System & Odin Version:
* Please paste `odin report` output:
```
Useful information to add to a bug report:

	Odin: dev-2023-08:58982063
	OS:   Pop!_OS 22.04 LTS, Linux 6.2.6-76060206-generic
	CPU:  AMD Ryzen 7 5800X 8-Core Processor
	RAM:  32008 MiB
```

## Expected Behavior

Any writes to be allocated on the given allocator in `bytes.buffer_init_allocator`.

## Current Behavior

During the first write, the backing buffer is allocated on the context.allocator, instead of the allocator given in `bytes.buffer_init_allocator`. 

## Steps to reproduce

The following program prints that there is a leakage, meaning the context.allocator was used during the `bytes.buffer_write_string` call.

Output: `/home/laytan/third-party/Odin/core/bytes/buffer.odin(117:11) leaked 64 bytes`

```odin
package main

import "core:mem"
import "core:fmt"
import "core:bytes"

main :: proc() {
	track: mem.Tracking_Allocator
	mem.tracking_allocator_init(&track, context.allocator)
	context.allocator = mem.tracking_allocator(&track)

	{
		defer free_all(context.temp_allocator)

		buf: bytes.Buffer

		// This does not register the usage of the temp allocator.
		bytes.buffer_init_allocator(&buf, 0, 0, context.temp_allocator)

		// This allocates the string on the context.allocator instead.
		bytes.buffer_write_string(&buf, "Hello, world!")
	}

	for _, leak in track.allocation_map {
		fmt.printf("%v leaked %v bytes\n", leak.location, leak.size)
	}
	for bad_free in track.bad_free_array {
		fmt.printf("%v allocation %p was freed badly\n", bad_free.location, bad_free.memory)
	}
}
```

**Comment by Kelimion** [comment]
I would consider this a user error because you're initializing it with a cap of `0`, and `resize` only registers the allocator the first time it's given a reservation larger than `0`. We could add a comment to `buffer_init_allocator` that says the allocator won't be assigned if you're not actually giving it an allocation to init the buffer with.

**Comment by laytan** [comment]
That's unfortunate, my use case is having the buffer in my struct, and only wanting it to eventually allocate when it is actually used, but set the allocator upfront.

I would say it should be an assertion, `assert(cap > 0)` instead because this is pretty dangerous and took me a while to figure out.

**Comment by Kelimion** [comment]
That's fine. I think we could accept a PR that adds a cap > 0 check to that init.

**Comment by Kelimion** [comment]
Unless... let me ponder this for a bit, Laytan. I'll make the PR one way or another. I may have a solution for this that without a performance implication.

**Comment by Kelimion** [comment]
It does actually register the temp allocator. Try adding `assert(buf.buf.allocator == context.temp_allocator)` after the `init`. It doesn't fire, i.e. the Bytes buffer does have the correct allocator registered to it. It's then just overridden when the first resize is made for some reason.

**Comment by Kelimion** [comment]
Patch that fixes it soon. Thanks @Tetralux for the rubber ducking.

**Comment by laytan** [comment]
Great stuff!

**Comment by Kelimion** [comment]
Good find. Was indeed actually a bug after all. `_buffer_grow` forgot to respect an existing allocator.
