### ISSUE TITLE
Support Arduino

### ISSUE THREAD

**Issue by clankill3r** [odin-lang/Odin#277]
It would be really cool if Odin could run on micro controllers like the Arduino.
I would not mind to do it myself but I don't know where to get started.
Is it just creating a different backend like there is x64 / llvm?

**Comment by ratchetfreak** [comment]
and a new stdlib implementation that includes globals that refer to the ports.

**Comment by gingerBill** [comment]
Odin was design with regards to 32 bit and 64 bit platforms and platforms with higher level capabilities. 

So Odin was never designed around microcontrollers such as an Arduino _specifically_.

I have wanted to design a language specifically for those types of platforms as they require slightly different constructs that Odin does not have, nor should have.
