### ISSUE TITLE
Feature Request: Compile-time warning for potential use of deallocated memory

### ISSUE THREAD

**Issue by semolex** [odin-lang/Odin#2798]
**Is your feature request related to a problem? Please describe.**
Hello,

I've been working with Odin and noticed a scenario where it's easy to accidentally access deallocated memory without any warnings or errors. I understand that with manual memory management comes the responsibility of managing memory properly, but I believe a compile-time warning for potential misuses can be beneficial for the Odin community.

```odin
main :: proc() {
    dyn := make([dynamic]int, 5, 5)
    append(&dyn, 1)
    delete(dyn)
    append(&dyn, 2) // Accessing deallocated memory here
    fmt.println(dyn)  // Accessing deallocated memory here too
}
```
In the above example, even after calling `delete(dyn)`, it's still possible to access the `dyn` slice, leading to undefined behaviour. While experienced developers might recognise this and avoid it, newcomers (like me, true) or even seasoned developers in a hurry might overlook such scenarios.

**Describe the solution you'd like**
Would it be possible to introduce a compile-time warning mechanism that identifies potential accesses to deallocated memory? This can be based on static analysis, heuristics, or any other mechanism that fits Odin's design philosophy. Such a feature would greatly improve the safety of the language without compromising its performance characteristics.

Thank you for considering this request. I truly appreciate all the work that's been put into Odin, and I believe this feature can make the language even more robust and user-friendly.

**Additional context**
`context.allocator == Allocator{procedure = proc(rawptr, Allocator_Mode, int, int, rawptr, int, Source_Code_Location) -> ([]u8, Allocator_Error) @ 1044BDAB8, data = 0x0}`

**Comment by gingerBill** [comment]
This **cannot** be known at compile time because that could be absolutely valid behaviour still depending on the allocator. 

It should also be noted that `delete` and `append` are implemented in user-space too so the compiler itself has no idea about its semantic meaning beyond that.
