### ISSUE TITLE
Code gen fail for defer panic

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2800]
## Context

writing `defer panic("Unimplemented");` will cause a code gen fail.

        Odin: dev-2023-08-nightly:49b24471
        OS:   Windows 11 Home Basic (version: 22H2), build 22621.2283
        CPU:  13th Gen Intel(R) Core(TM) i9-13900HX
        RAM:  32507 MiB

## Expected Behavior

It should give an error or compile

## Current Behavior

It fails in code gen

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduc

defer panic("Something");

### Failure Logs

LLVM CODE GEN FAILED FOR PROCEDURE: render.load_texture_from_file
define internal void @render.load_texture_from_file(%render.Texture2D* noalias sret(%render.Texture2D) %agg.result, %..string* %0, %runtime.Source_Code_Location* %1, i8* noalias nocapture nonnull %__.context_ptr) {
decls:
  %2 = alloca { i8*, i64 }, align 8
  %3 = alloca { { i8*, i64 }, i8 }, align 8
  %data = alloca { i8*, i64 }, align 8
  %ok = alloca i8, align 1
  %4 = alloca { %..any*, i64 }, align 8
  %5 = alloca [1 x %..any], align 8
  %6 = alloca %..any, align 8
  %7 = alloca %render.Texture2D, align 4
  br label %entry

entry:                                            ; preds = %decls
  %8 = bitcast i8* %__.context_ptr to %runtime.Context*
  %9 = load %..string, %..string* %0, align 8
  %10 = getelementptr inbounds %runtime.Context, %runtime.Context* %8, i32 0, i32 0
  %11 = load %runtime.Allocator, %runtime.Allocator* %10, align 8
  %12 = load %runtime.Source_Code_Location, %runtime.Source_Code_Location* @"ggv$4cc", align 8
  %13 = bitcast { i8*, i64 }* %2 to i8*
  call void @llvm.memset.p0i8.i64(i8* %13, i8 0, i64 16, i1 false)
  %14 = bitcast %runtime.Context* %8 to i8*
  %15 = call i8 @os.read_entire_file_from_filename(%..string* %0, %runtime.Allocator* %10, %runtime.Source_Code_Location* @"ggv$4cc", { i8*, i64 }* %2, i8* %14)
  %16 = load { i8*, i64 }, { i8*, i64 }* %2, align 8
  %17 = load { { i8*, i64 }, i8 }, { { i8*, i64 }, i8 }* %3, align 8
  store { i8*, i64 } %16, { i8*, i64 }* %data, align 8
  store i8 %15, i8* %ok, align 1
  %18 = load i8, i8* %ok, align 1
  %19 = load %..string, %..string* %0, align 8
  %20 = bitcast { %..any*, i64 }* %4 to i8*
  call void @llvm.memset.p0i8.i64(i8* %20, i8 0, i64 16, i1 false)
  %21 = bitcast [1 x %..any]* %5 to i8*
  call void @llvm.memset.p0i8.i64(i8* %21, i8 0, i64 16, i1 false)
  %22 = getelementptr [1 x %..any], [1 x %..any]* %5, i64 0, i64 0
  %23 = bitcast %..any* %6 to i8*
  call void @llvm.memset.p0i8.i64(i8* %23, i8 0, i64 16, i1 false)
  %24 = bitcast %..string* %0 to i8*
  %25 = getelementptr inbounds %..any, %..any* %6, i32 0, i32 0
  %26 = getelementptr inbounds %..any, %..any* %6, i32 0, i32 1
  store i8* %24, i8** %25, align 8
  store i64 432345564227567632, i64* %26, align 8
  %27 = load %..any, %..any* %6, align 8
  store %..any %27, %..any* %22, align 8
  %28 = getelementptr [1 x %..any], [1 x %..any]* %5, i64 0, i64 0
  %29 = getelementptr inbounds { %..any*, i64 }, { %..any*, i64 }* %4, i32 0, i32 0
  store %..any* %28, %..any** %29, align 8
  %30 = getelementptr inbounds { %..any*, i64 }, { %..any*, i64 }* %4, i32 0, i32 1
  store i64 1, i64* %30, align 8
  %31 = load { %..any*, i64 }, { %..any*, i64 }* %4, align 8
  %32 = load %runtime.Source_Code_Location, %runtime.Source_Code_Location* %1, align 8
  %33 = icmp ne i8 %18, 0
  %34 = bitcast %runtime.Context* %8 to i8*
  %35 = call i8 @fmt.assertf(i1 zeroext %33, %..string* @"ggv$4cd", { %..any*, i64 }* %4, %runtime.Source_Code_Location* %1, i8* %34)
  %36 = load { i8*, i64 }, { i8*, i64 }* %data, align 8
  %37 = load %..string, %..string* %0, align 8
  %38 = load %runtime.Source_Code_Location, %runtime.Source_Code_Location* %1, align 8
  %39 = bitcast %render.Texture2D* %7 to i8*
  call void @llvm.memset.p0i8.i64(i8* %39, i8 0, i64 20, i1 false)
  %40 = bitcast %runtime.Context* %8 to i8*
  call void @render.load_texture_from_bytes(%render.Texture2D* sret(%render.Texture2D*) %7, { i8*, i64 }* %data, %..string* %0, %runtime.Source_Code_Location* %1, i8* %40)
  %41 = load %render.Texture2D, %render.Texture2D* %7, align 4
  %42 = bitcast %render.Texture2D* %agg.result to i8*
  %43 = bitcast %render.Texture2D* %7 to i8*
  call void @llvm.memcpy.inline.p0i8.p0i8.i64(i8* %42, i8* %43, i64 20, i1 false)
  br label %defer

defer:                                            ; preds = %entry
  %44 = load %runtime.Source_Code_Location, %runtime.Source_Code_Location* @"ggv$4ce", align 8
  %45 = bitcast %runtime.Context* %8 to i8*
  call void @runtime.panic(%..string* @"ggv$4cf", %runtime.Source_Code_Location* @"ggv$4ce", i8* %45)
  unreachable
  ret void
}

**Comment by laytan** [comment]
Fixed in #3219
