### ISSUE TITLE
Compiler produces bad code

### ISSUE THREAD

**Issue by simonwashere** [odin-lang/Odin#2806]
## Context

* Operating System & Odin Version:
	Odin: dev-2023-09:c23b5825
	OS:   macOS Unknown (build: 22G91, kernel: 22.6.0)
	CPU:  ARM64
	RAM:  32768 MiB

## Current Behavior

On a debug build the compiler produces bad output which is corrected with a change to the source code which should make no difference, release build has the correct output though.

See attached screenshots where:
aPoint, bPoint := region_viewPoint(region, from), region_viewPoint(region, to) 
gives correct output

<img width="929" alt="Screenshot 2023-09-21 at 15 54 47" src="https://github.com/odin-lang/Odin/assets/4092587/59deed06-275d-4885-83e5-592916b40282">

but with:
aPoint := region_viewPoint(region, from)
bPoint := region_viewPoint(region, to)

the output is clearly wrong as one of the values is lost (becomes 0 or 1) on return from the proc

<img width="929" alt="Screenshot 2023-09-21 at 15 54 18" src="https://github.com/odin-lang/Odin/assets/4092587/c0dea8e9-8222-48c9-8187-47fa6577daa3">

data types are:

ViewPoint :: struct {
	angle: Angle,
	offset: Coord32,
}

Fix32 :: distinct i32 // 16.16
Angle :: distinct i32 // 16.16
Coord32 :: struct { x, y: Fix32 }

**Comment by simonwashere** [comment]
Simple test case producing bad result with debug build:
'''
package main
import "core:fmt"

Fix32 :: distinct i32 // 16.16
Angle :: distinct i32 // 16.16
Coord32 :: struct { x, y: Fix32 }

ViewPoint :: struct {
	angle: Angle,
	offset: Coord32,
}

ViewRegion :: struct {
	position: Coord32,
}

minus :: proc(a, b: Coord32) -> Coord32 {
	return {a.x - b.x, a.y - b.y}
}

region_viewPoint :: proc(region: ^ViewRegion, point: Coord32) -> ViewPoint {
	offset := minus(point, region.position)
	return {27, offset}
}

region_compareSpan :: proc(region: ^ViewRegion, from, to: Coord32) {
	aPoint := region_viewPoint(region, from)
	bPoint := region_viewPoint(region, to)
	fmt.printf("aAngle %v, bAngle %v\n", aPoint.angle, bPoint.angle)
}

main :: proc() {
	region: ViewRegion
	region_compareSpan(&region, {10, 10}, {40, 20})
}
'''

**Comment by simonwashere** [comment]
Output:

Desktop/test % odin build . -debug
Desktop/test % ./test             
aAngle 0, bAngle 27

**Comment by laytan** [comment]
We did a few ABI fixes in the last few weeks which has fixed this for me, could you confirm/close the issue?
