### ISSUE TITLE
Odin files with _ cannot define main

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2809]
## Context

I make a single file called "my_test.odin" and get the error "(1:1) Error: Undefined entry point procedure 'main'".
Renaming the file "test.odin" and everything works.

Odin: dev-2023-08-nightly:49b24471
        OS:   Windows 11 Home Basic (version: 22H2), build 22621.2283
        CPU:  13th Gen Intel(R) Core(TM) i9-13900HX
        RAM:  32507 MiB

## Expected Behavior
It should compile

## Current Behavior

It does not load files with _ correctly.

### Steps to Reproduce

Make a file with _ in name, try to define main.

**Comment by oskarnp** [comment]
The reason is that Odin defines some special keywords as part of the file name. "_test" is one of them which means it will only be built under `odin test` which causes your main procedure to disappear. Other keywords would be "_linux", "_arm64", etc.

**Comment by xzores** [comment]
Ahh, so I was really unlucky to hit that keyword, rip.

**Comment by oskarnp** [comment]
Compiler could still do better though. One solution might be that it prints all the files used during compilation and highlights those that are ignored and why.

**Comment by xzores** [comment]
I mean, disallowing main to be defined in a _test would be a good idea.
Should I reopen?

**Comment by Kelimion** [comment]
> I mean, disallowing main to be defined in a _test would be a good idea. Should I reopen?

Done. We could do a better job defining the special handling of filenames and communicating that in the overview and during compilation, so let's leave open the issue as a reminder to do that.
