### ISSUE TITLE
Frequent compile error with parapoly and/or test file

### ISSUE THREAD

**Issue by mtarik34b** [odin-lang/Odin#2814]
## Context

I have just these two files together in a package: `pkg/main.odin`, `pkg/test.odin`

```odin
/* main.odin */
package main

A :: struct {}
B :: struct {}
C :: struct {}
D :: struct {}
E :: struct {}
F :: struct {}
G :: struct {}

ZZZ :: struct($Key, $Value: typeid) {}

Big_Struct :: struct($T: typeid) {
	field_A: ZZZ(int, A),
	field_B: ZZZ(int, B),
	field_C: ZZZ(int, C),
	field_D: ZZZ(int, D),
	field_E: ZZZ(int, E),
	field_F: ZZZ(int, F),
	field_G: ZZZ(int, G),
}

create :: proc($T: typeid) -> Big_Struct(T) {
	bs: Big_Struct(T)

	zzz: ZZZ(int, A)
	bs.field_A = zzz

	return bs
}

main :: proc() {
	T :: [3]f32
	obj := create(T)
}
```

```odin
/* test.odin */
package main
 
import "core:testing"

@(test)
test :: proc(t: ^testing.T) {
	T :: [3]f32
	obj := create(T)
}
```

* Operating System & Odin Version:
```
Odin: dev-2023-09:c23b5825
OS:   Ubuntu 22.04.3 LTS, Linux 6.2.0-33-generic
CPU:  Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
RAM:  15747 MiB
```
## Expected Behavior

I expect the code to compile successfully always(!).

## Current Behavior

When using `odin run .` or `odin test .` I oftentimes get one of these three compile errors randomly:

```
.../pkg/main.odin(27:2) Error: 'bs' of type 'Big_Struct(T)' has no field 'field_A'
        bs.field_A = zzz
        ^^
```
```
.../pkg/main.odin(27:2) Error: 'bs' of type 'Big_Struct(T)' has no field 'field_A'
        bs.field_A = zzz
        ^^
        Suggestion: Did you mean?
                field_A
                field_B
                field_C
                field_D
                field_E
                field_F
                field_G
```
```
.../pkg/main.odin(27:15) Error: Cannot assign value 'zzz' of type 'ZZZ($Key=int, $Value=A) (package main)' to 'ZZZ($Key=int, $Value=A) (package main)' in assignment
        bs.field_A = zzz
                     ^~^
        Suggestion: the expression may be directly casted to type ZZZ($Key=int, $Value=A)

        Suggestion: the expression may be directly casted to type ZZZ($Key=int, $Value=A)
```

Also see failure logs attached, where I ran `odin run .` many times in a row.

## Failure Information (for bugs)
**Observations**

1\) The more of the `field_B`, `field_C`, ..., `field_G` are removed, the rarer the errors occur.

The issue seems to disappear, when

2\) `test.odin` is removed,
3\) the `create` proc doesn't return anything.

### Steps to Reproduce

1\. Have `main.odin` and `test.odin` in a common package.    
2\. Inside that directory, run `odin run .` or `odin test .` several times, until you hit an error.

3\. To make observation 1), repeat steps 1 and 2 by removing more and more of the `field_*`s.
4\. To make observation 2), repeat steps 1 and 2 after deleting or commenting out `test.odin`.
5\. To make observation 3), repeat steps 1 and 2 after modifying the `create` proc to not return anything.

### Failure Logs

[error_log.txt](https://github.com/odin-lang/Odin/files/12708088/error_log.txt)

**Comment by Lperlind** [comment]
Same bug as https://github.com/odin-lang/Odin/issues/2463

**Comment by Lperlind** [comment]
It's a race condition, I've traced the compiler and you can see it quite clearly.
![image-6.png](https://github.com/odin-lang/Odin/assets/16159123/0d370889-b57e-42f8-af15-c4f6dd93317a)

**Comment by gingerBill** [comment]
This should be relatively simple to fix, but hard to replicate.

**Comment by gingerBill** [comment]
I have just added a potential fix for this race condition. I have just used a RwMutex so that when it is writing, it blocks readers.

**Comment by gingerBill** [comment]
Is this still a problem on the latest commit?

**Comment by mtarik34b** [comment]
I tested with some yesterday's commit and hit the errors frequently. Now after updating to latest commit there were no errors for 100+ tries.
