### ISSUE TITLE
Compiler crashes when #partial switch is used after a named block

### ISSUE THREAD

**Issue by ntn9995** [odin-lang/Odin#2818]
## Context

Minimal repro:

```odin
package main

Foo :: enum {
    NONE,
    BAR,
    BAZ
}

main :: proc() {
    f: Foo
    switch_block: #partial switch f {
    case .BAR:
    case .BAZ:
    }
}
```

Odin report output:
```
Odin: dev-2023-09:0ed2d8b1
OS:   Windows 10 Professional (version: 22H2), build 19045.3448
CPU:  11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
RAM:  32551 MiB
```

Odin build command: `odin build main.odin -file`

Also tested on odin version `dev-2023-09:adcaace0`

## Expected Behavior

Compiler compiles and reports error if any. 

## Current Behavior

Segmentation faults. However, compiler doesn't crash if the `#partial` is put before the named block.

**Comment by gingerBill** [comment]
This is due to a parsing bug not expecting this behaviour.
