### ISSUE TITLE
Failed to execute command

### ISSUE THREAD

**Issue by boagz57** [odin-lang/Odin#282]
After trying to build latest release I get this error:

Failed to execute command:
"C:\Users\UserName\Desktop\Odin-master\bin/opt" "C:\Users\UserName\Desktop\Odin-master\demo.ll" -o "C:\Users\Jason\Desktop\Odin-master\demo.bc" -memcpyopt -die

The compiler still builds but anytime I try and use it to build the same error will pop up.

**Comment by vassvik** [comment]
Do you have the LLVM binaries in Odin/bin?

**Comment by gingerBill** [comment]
https://github.com/odin-lang/Odin/wiki#getting-started-with-odin

**Comment by boagz57** [comment]
Yes, still get the error. What I've done:

1.) downloaded latest master branch as zip
2.) unzipped into "Odin" folder on desktop
3.) Copied over latest release of LLVM bin folder (version 7.0) to Odin folder
4.) navigated to vcvarsall.bat and ran 'vcvarsall.bat x64' command
5.) navigated back to Odin folder in cmd prompt and ran build.bat

**Comment by boagz57** [comment]
Trying to think of things. Should this line:

"C:\Users\UserName\Desktop\Odin-master\bin/opt"

say this instead:

"C:\Users\UserName\Desktop\Odin-master\bin" /opt

**Comment by boagz57** [comment]
Have tried with both VS 2017 and VS 2015 as well.

**Comment by gingerBill** [comment]
Sorry to be a pain but could you state what you are doing very precisely?

Are you calling `vcvarsall.bat x64` in the same command window as the Odin call?
Are you sure you have the `bin` directory in the same directory as `odin.exe`?

**Comment by boagz57** [comment]
No, not at all. And yes. I've attached an image to try and show the process with the command window

![odin_issue](https://user-images.githubusercontent.com/11085826/48912871-c7ad2480-ee44-11e8-903c-12d1d79c55c2.jpg)

**Comment by gingerBill** [comment]
And what is contained inside of `bin`?

**Comment by boagz57** [comment]
I copied it straight from LLVM folder:

![bandicam 2018-11-22 10-55-22-334](https://user-images.githubusercontent.com/11085826/48913007-37231400-ee45-11e8-85e6-c106d462f7cd.jpg)

**Comment by gingerBill** [comment]
Ah... That is not what you are meant to do as `opt` is not always included with LLVM. I provide the required LLVM binaries here: https://github.com/odin-lang/Odin/archive/llvm-windows.zip

**Comment by boagz57** [comment]
Okay. So I downloaded that zip file and current have this unzipped and opened on my desktop:

![bandicam 2018-11-22 11-06-39-426](https://user-images.githubusercontent.com/11085826/48913571-c67cf700-ee46-11e8-9c0f-ec2533c6745b.jpg)

Where do I go from here to build the project? Where are the llvm binaries within this folder structure?

**Comment by boagz57** [comment]
Ah, I see. If anyone else has this issue make sure you download his llvm binaries from this link:

https://github.com/odin-lang/Odin/releases/tag/llvm-windows
