### ISSUE TITLE
string literals cannot be assigned to [?]u8

### ISSUE THREAD

**Issue by Beefster09** [odin-lang/Odin#2821]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
```
	Odin: dev-2023-09:aaaff9b6
	OS:   Linux Mint 21, Linux 5.15.0-79-generic
	CPU:  Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
	RAM:  7745 MiB
```

## Expected Behavior

```
MAGIC_BYTES: [?]u8 : "MyBinaryFiletypeMagicHeader"
```

Should accept the string literal without having to specify the length of the literal

## Current Behavior

This currently causes a compiler error:

```
Error: ? can only be used in conjuction with compound literals
	MAGIC_BYTES: [?]u8: "MyBinaryFiletypeMagicHeader"
```

The same error applies to `[?]u8` variables when initialized

*However* you can work around this with:

```
MAGIC_BYTES: [27]u8 : "MyBinaryFiletypeMagicHeader"
```

and it will compile just fine. This isn't great since you need to know the exact length of the literal, which could be error-prone when the string is changed. (though the compiler will complain if the length does not match)

**Comment by gingerBill** [comment]
This is not a bug.

`[?]T` only exists for compound literals and is not considered a type.

**Comment by Beefster09** [comment]
It just seems a bit surprising to me because it works fine when you specify the length of the u8 array.

The error message vaguely implies that this behavior is intentional, and I get that it's not a type. Perhaps it can offer a suggestion like the following:

```
Hint: change the type to [<length of string>]u8 to allow this assignment
```

Though at that point, I don't see why the compiler wouldn't just allow `[?]u8`. The semantics are unambiguous for the basic case, and it feels intuitive as a developer to be able to use it like this. I can fathom a few possible cases when this wouldn't be sensible or reasonable, such as making the string defined by a compiler define, and I can imagine this might be made a lot more complex if it only supported singular string literals.
