### ISSUE TITLE
New, different error (than #2817 was generating) using -target:wasi_wasm32 or -target:wasi_wasm64p32

### ISSUE THREAD

**Issue by mahSource** [odin-lang/Odin#2823]
## Context
Setup: Windows 11 Pro 64-bit PC; odin version dev-2023-09-nightly:fc93ea7a
Downloaded 9/26/2023 nightly: odin-windows-amd64-nightly+2023-09-26.zip	56.2MB
SHA-1: 54001c58046edfb2e539c05f17b0a178fd1bf127
## Expected Behavior
Successful compilations, esp. after nightly build that had supposedly fixed: https://github.com/odin-lang/Odin/issues/2817
With this commit: https://github.com/odin-lang/Odin/commit/4c328d83ba31e867a51668a3f91348a5e80b737c
## Current Behavior
Using a modest .odin file as such:
```go
//main.odin
package main
import "core:fmt"
main :: proc() {
    fmt.println("\nHellope!")
}
```
I tried the following build commands that failed with these errors:
Note that a main.wasm.o file is created, but get this error for all four build commands below:
```text
Failed to execute command: "C:\odin\nightly_build\\bin\wasm-ld"
"C:/Users/home/Documents/GitHub/odin/working/main.wasm.o"
-o "C:/Users/home/Documents/GitHub/odin/working/main.wasm"  --allow-undefined
```
**Build Commands from Terminal - all get same error above**
(1) odin build main.odin -file -target:wasi_wasm64p32
(2) odin build main.odin -file -target:wasi_wasm32
(3) odin build main.odin -file -no-thread-local -target:wasi_wasm64p32
(4) odin build main.odin -file -no-thread-local -target:wasi_wasm32
### Steps to Reproduce
Attempt compilation with the information above.

**Comment by laytan** [comment]
Do you have wasm-ld in that location?
If you do, are you sure there isn't more output given with the failure? You can also try running the command yourself on the .o file that was created.
