### ISSUE TITLE
Passing inline-created struct larger than registry size to C code that modifies it causes crash if struct initializer constains only literals & constants

### ISSUE THREAD

**Issue by karl-zylinski** [odin-lang/Odin#2837]
## Context

* Operating System & Odin Version: Windows, 
* Please paste `odin report` output:
        Odin: dev-2023-09:ba61cf27
        OS:   Windows 10 Professional (version: 22H2), build 19045.3448
        CPU:  Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz
        RAM:  32674 MiB

## Failure Information (for bugs)

Calling a C function and passing an inline-created larger-than-registry-size struct that is initialized from only constants & literals, and then having the C code modify the struct, will make the program crash.

Here's a repro:

Odin code:
```
package bug_test

import "core:fmt"

foreign import lib {
	"mini_lib.lib",
}

@(default_calling_convention="c")
foreign lib {
	test_func :: proc(s: TestStruct) ---
}

TestStruct :: struct {
	x: f32,
	y: f32,
	z: f32,
}

main :: proc() {
	constant :: 7
	var: f32 = 9

	test_func({constant, 0, 0})
	fmt.println("Got here")
}
```

Tiny C lib, save as `mini_lib.c` and compile using `cl.exe /LD mini_lib.c`
```
typedef struct TestStruct {
    float x;
    float y;
    float z;
} TestStruct;

__declspec(dllexport) void test_func(TestStruct s) {
    s.x = 123;
}
```

When you have both the Odin program and C DLL in place, you can run the odin program. It'll crash with an access violation when the C code tries to modify the struct. You'll notice that the program never prints "Got here".

If you change `test_func({constant, 0, 0})` to `test_func({var, 0, 0})` so that it passes a local var instead of a constant into the inline-created struct, then it doesn't crash. It also crashes if you just put literals or literals + constants in the struct. However, if the struct is initialized using at least one non-literal or non-constant, such as a local variable, then it no longer crashes.

This only happens if you create the struct inline like that, i.e. if you put the struct in a local variable instead of inline, then it does not crash.

It only happens if the struct passed is larger than registry size. I.e. if the struct only has two floats in it instead of three, then it does not crash.

How I found this bug: It happened to me while working with Raylib. Raylib will sometimes modify the source Rectangle passed to `DrawTexturePro` if the height of the Rectangle is negative (that's how you 'flip' texture when drawing). In my case I happened to pass an inline-created struct that contained constant `-ScreenHeight` as height, since I wanted to flip my render texture.

**Comment by laytan** [comment]
Can't reproduce on:
```
	Odin:    dev-2024-03:01569fc05
	OS:      macOS Sonoma 14.2.1 (build: 23D56, kernel: 23.2.0)
	CPU:     ARM64
	RAM:     8192 MiB
	Backend: LLVM 17.0.6
```

**Comment by karl-zylinski** [comment]
I will try it on my end in a few days, I'll let you know if it is fixed here too.

**Comment by laytan** [comment]
Thanks for confirming, will have to look at it on Windows in that case!

**Comment by cstrachan88** [comment]
Examples are working for me with this fix. Thanks @laytan !

**Comment by karl-zylinski** [comment]
Great! Thank you @laytan! We can close this when the PR gets merged.
