### ISSUE TITLE
A comment between if and else 

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2840]
## Context

A comment between if and else  will result in the error : `'else' unattached to an 'if' statement`

        Odin: dev-2023-08-nightly:9453b238
        OS:   Windows 11 Home Basic (version: 22H2), build 22621.2283
        CPU:  13th Gen Intel(R) Core(TM) i9-13900HX
        RAM:  32507 MiB

## Expected Behavior
it should just work

## Current Behavior

`'else' unattached to an 'if' statement`

### Steps to Reproduce
```
	if (...)
		...
	}
	/*my_comment*/
	else {
		...
	}
```

**Comment by gingerBill** [comment]
This is not a bug but how the automatic-semicolon system works. It cannot allow for an empty line between `}` and `else`, of which that comment effectively is.

**Comment by xzores** [comment]
So I can't comment out a case for in if statement?
	
```
if ... {
}
/*if identifiers, ok := &mesh.implementation.(Mesh_identifiers); ok {
	panic("You have already uploaded this mesh", loc = loc);
}*/
else {
	panic("You have already uploaded this mesh", loc = loc);
}
```

**Comment by gingerBill** [comment]
You can do this as it does not produce a newline
```odin
if true {

} /*

*/ else {

}
```
