### ISSUE TITLE
Union not being copied into map or new_clone()

### ISSUE THREAD

**Issue by JoshuaManton** [odin-lang/Odin#285]
https://i.imgur.com/FThQhd4.png

results in this

https://i.imgur.com/XdgIYsU.png

Collider struct:
https://i.imgur.com/XXBquiO.png

if I change `user_handle` to an i32 it works, but then if I change another unrelated var to i32 then it breaks again so I'm not sure if that's related

**Comment by gingerBill** [comment]
I cannot replicate this. Could you produce a minimal amount of code please? 

My guess is it is an alignment bug, but I am not so sure.

**Comment by JoshuaManton** [comment]
Managed to narrow it down
```
package test

import "core:fmt"
using import "core:math"

Handle :: i32;

Bar :: struct {
	x: i32, // switch to i64 to fix `kind = nil`
}

Foo :: struct {
	position: Vec3,
	user_handle: int,
	kind: union {
		Bar,
	},
}

foos: [10]Foo;

main :: proc() {
	foos[0] = Foo{{1, 2, 3}, 24, Bar{22}};
	fmt.println(foos[0]);
}
```
Run this and you will see `nil` printed out where we would expect `Bar{x = 22}`. If you change Bar.x to be an `i64` the problem goes away and it prints `Bar{x = 22}` as expected.

**Comment by gingerBill** [comment]
This appears to be a "doesn't happen on my machine" issue. I cannot replicate this whatsoever... 🤔

**Comment by bpunsky** [comment]
Just documenting the on-stream discovery that it only happens with `-opt=0` without `-debug`, and that `-debug` or any other opt level cancels out this bug.

LLVM :heart:

**Comment by gingerBill** [comment]
Is this bug still replicated? @JoshuaManton @bpunsky

**Comment by JoshuaManton** [comment]
@gingerBill yup I can confirm that this is fixed!
