### ISSUE TITLE
Compilation error without error message

### ISSUE THREAD

**Issue by bigidea-kz** [odin-lang/Odin#2851]
Hi guys. I know I shouldn't write code like this, but I expected to get a compilation error or something like that!

```
package main
import "core:fmt"
main :: proc() {
  p: ^int
  p^ = 1337
  fmt.println("POINTER", p)
  fmt.println("AFTER!!!")
}
```

* Operating System & Odin Version: Arch linux & dev-2023-10:2cca005

**Comment by jasonKercher** [comment]
I don't think that should be an error.  It's perfectly valid code.  C wouldn't give you an error or warning on this either

**Comment by bigidea-kz** [comment]
Ok. I close this issue.
Thank you.
