### ISSUE TITLE
defining a matrix as a product of a non-constant scalar, a constant matrix, and a literal matrix causes a crash

### ISSUE THREAD

**Issue by bg-thompson** [odin-lang/Odin#2852]
## Context

* Operating System & Odin Version:
```
Odin: dev-2023-10:96778c69
OS:   Windows 11 Home Basic (version: 22H2), build 22621.2283
CPU:  Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
RAM:  32689 MiB
````

## Expected Behavior

The code below should print `matrix[1, 0; 0, 1]` when the command `odin run bug3.odin -file` is run but there is a crash instead.

```
package bug
import "core:fmt"

ROT0 :: matrix[2,2]int{0,1,1,0}

main :: proc() {
    a   := 1
    mat := a * ROT0 * matrix[2,2]int{0,1,1,0}
    fmt.println(mat)
    // Expected to print "matrix[1, 0; 0, 1]"
    // but instead a silent crash occurs.
}
```

### RemedyDB debugging screenshot

![bug3](https://github.com/odin-lang/Odin/assets/62212228/f9f4bc76-1537-48ae-91a5-632f3b5d9a82)

**Comment by Feoramund** [comment]
I'm unable to reproduce this on Linux as of the latest commit.
