### ISSUE TITLE
Compiler produces bad code on `"stdcall"`

### ISSUE THREAD

**Issue by seventh-chord** [odin-lang/Odin#2854]
```
OS:   Windows 10 Professional (version: 22H2), build 19045.3448
CPU:  AMD Ryzen 7 PRO 5850U with Radeon Graphics
RAM:  15182 MiB
```
I've only tested on this machine.

Happens with `dev-2023-10-nightly:2cca0050` (from github releases), and with custom release build of `0c10b951`.
Does not happen with `dev-2023-08-nightly:9453b238` (from github releases).

## Steps to reproduce

Run the following code:

```odin
package main
import "core:runtime"

foo :: proc "stdcall" () {
}

main :: proc() {
  runtime.print_string("Hello\n")
  foo()
  runtime.print_string("Goodbye\n")
}
```

Compiler command line I used:
```
C:\Dev\tools\Odin\odin.exe run main.odin -file -o:speed
```

## Expected Behavior

Program should print `Hello` and then `Goodbye`.

## Current behavior

Program prints `Hello` and then crashes because an `int3` instruction is generated directly after the first call to `print_string`.

## Failure Information (for bugs)

Only happens if I pass `-o:speed`.

I noticed this bug because I was using `CreateWindowW`, and my code stopped working when I enabled `-o:speed` after I updated the compiler.

**Comment by seventh-chord** [comment]
Ran `git bisect`, which shows this:

```
f0ab58dfbb4be6103fb7340ec570d218e2137a4b is the first bad commit
commit f0ab58dfbb4be6103fb7340ec570d218e2137a4b
Author: gingerBill <bill@gingerbill.org>
Date:   Wed Sep 20 10:39:48 2023 +0100

    Begin work with adding the new pass system

 src/llvm_backend.cpp | 54 ++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 54 insertions(+)
```

**Comment by seventh-chord** [comment]
*I'm seeing if I can solve this bug. Let me know if you'd rather not have me post progress updates :)*

Looks like some optimization pass that is part of `default<O2>` in clang is causing this.

If I run the following commands (with odin built from 0c10b951a9):
```
odin build bug.odin -file -no-crt -keep-temp-files -show-system-calls
clang bug.ll -O2 -S -emit-llvm -o bug_opt.ll
```

I see this in `bug.ll`:
```
define internal x86_stdcallcc void @main.foo() {
decls:
  br label %entry

entry:                                            ; preds = %decls
  ret void
}

define internal void @main.main(ptr noalias nocapture nonnull %__.context_ptr) {
decls:
  br label %entry

entry:                                            ; preds = %decls
  %0 = call i64 @runtime.print_string(ptr @"ggv$e")
  %1 = call i64 @runtime.print_string(ptr @"ggv$f")
  call void @main.foo()
  %2 = call i64 @runtime.print_string(ptr @"ggv$10")
  ret void
}
```


...and then this in `bug_opt.ll`:
```
; Function Attrs: noreturn
define internal fastcc void @main.main() unnamed_addr #3 {
decls:
  tail call fastcc void @runtime.print_string(ptr nonnull @"ggv$e")
  tail call fastcc void @runtime.print_string(ptr nonnull @"ggv$f")
  unreachable
}
```

Either there is a bug in some LLVM optimization pass. Or the llvm-ir output by the odin compiler is incorrect somehow, and it's triggering seemingly nonsensical behavior from LLVM.

My next idea would be to try seeing what specific optimization pass in LLVM causes `unreachable` to be generated instead of `call void @main.foo()`, maybe that gives some insight into what is going on.

**Comment by seventh-chord** [comment]
Austensibly simpler example which also shows the bug without needing an `import`:

```odin
// https://github.com/odin-lang/Odin/issues/2854

package main

foreign import kernel32 "system:kernel32.lib"

foreign kernel32 {
  GetLastError :: proc "stdcall" () -> u32 ---
}

bar :: proc() {
  GetLastError()
}

foo :: proc "stdcall" () { // Any of these calling conventions make LLVM generate `int3`: win64, stdcall, fastcall, sysv
}

main :: proc() {
  bar()
  foo()
}
```

I also think I found a fix, will submit PR.

**Comment by Kelimion** [comment]
Good sleuthing.
