### ISSUE TITLE
js_wasm32 fmt.println doesn't work

### ISSUE THREAD

**Issue by RehkitzDev** [odin-lang/Odin#2855]
Recently updated the compiler from  `dev-2023-07`  to version `dev-2023-10`. It seems like the fmt package doesn't work properly on the js_wasm32 target. The resulting wasm file can't be compiled.

wasm_ld.exe: 17.0.1.0

### Steps to Reproduce

main.odin:

```
package bug
import "core:fmt"
main :: proc() {
    fmt.println("Hello, world!")
}
```

index.html:

```
<script type="module" type="text/javascript">
    import "./runtime.js"; // https://raw.githubusercontent.com/odin-lang/Odin/master/vendor/wasm/js/runtime.js

    odin.runWasm("bug.wasm");
</script>

```
`odin build . -target:js_wasm32`

Output in chrome:

`CompileError: WebAssembly.instantiate(): Compiling function #43:"strconv.generic_ftoa" failed: local.set[0] expected type i32, found call of type f32 @+28887`

**Comment by Mavigno42** [comment]
I'm getting a similar error with basically the same setup. The error message from chrome:
`CompileError: WebAssembly.instantiate(): Compiling function #56:"fmt.fmt_arg" failed: call[0] expected type f32, found local.get of type i32 @+123164`

Inspecting the commit history I managed to find the commit in which the error first appeared, the hash for it is `bc401fa392c937a8935adeaacab11b1d6525ca00`. There a is gap of commits that can not be built between the mentioned commit and the last one that I could build, of hash `c23b5825bb88e0cdfccc652138cf76b49a530490`, this commit seems to be the last commit in which the error doesn't show up.
I first tested with `wasm-ld.exe 16.0.0` and then I did the update to `wasm-ld.exe 17.0.3` and got the same error in both tests.

**Comment by mothfuzz** [comment]
I just started getting this issue recently, is there a solution or workaround? 

I tried with LLVM (and thus wasm-ld.exe) versions 17, 16, and 14, no luck. I scanned through the commits and didn't see any changes to fmt, so I'm not sure why wasm builds would have been broken at those particular commits.

I only have Windows to test on at the moment, but is the issue reproducible when compiling to wasm32 on Linux or MacOS?

**Comment by mothfuzz** [comment]
Alright, so I've inspected the textual webassembly for the project I'm trying to run. I traced every `call` inside the `$fmt.fmt_arg` function, and found that the first one to take an `f32` arg is this:
`  (func $__extendhfsf2 (type $t31) (param $p0 f32) (result f32)`
and `$t31` in this case is:
`  (type $t31 (func (param f32) (result f32)))`
I'm not sure what this `$__extendhfsf2` function is, but it seems to be the one causing problems - it is in fact being called with an i32 in fmt_arg:
`(call $__extendhfsf2 (local.get $l417)))`
where there is, inside the fmt_arg definition:
`(local $l417 i32)`

All this wasm probably isn't too meaningful on its own, so I've attached the wasm compile + conversion to textual format of my project here if any reference is needed:
[odings.wat.txt](https://github.com/odin-lang/Odin/files/13801912/odings.wat.txt)

Other than that, it seems this call to the $__extendhfsf2 function is the culprit.

I've looked inside the fmt_arg source code in Odin itself, and there was no call to extendhfsf2 (underscores or not), so I'm not sure why it's present in the wasm output - likely an LLVM backend issue.

**Comment by thetarnav** [comment]
I have the same issue. Problem compiling `fmt.fmt_float`, `fmt.fmt_arg`, and `__extendhfsf2` when using any of the procs in `fmt` package.

For me it only appears when using `llvm-17` to compile Odin, switching "back" to `llvm-14` fixes the issue.
It's just important to remove llvm-17 from `build_odin.sh`, as [it doens't use what in PATH, but checks from highest to lowest version using `llvm-config-<version>` command](https://github.com/odin-lang/Odin/blob/master/build_odin.sh#L29).

@mothfuzz I don't think there is some particular commit that broke it. Support for llvm-17 was only added recently and it's probably not polished yet.

**Comment by leecommamichael** [comment]
Tonight I pulled master and compiled the following with `odin build . -target:js_wasm32 `

```odin
package main

import "core:fmt"

main :: proc()  {
    fmt.println("Hello!")
}
```
Which results in: `CompileError: WebAssembly.instantiate(): Compiling function #58:"strconv.generic_ftoa" failed: local.set[0] expected type i32, found call of type f32 @+97817` from `runtime.js`

I run Windows 11 Pro with no versions of LLVM installed.
