### ISSUE TITLE
[feature request] Allow struct re-declaration

### ISSUE THREAD

**Issue by flysand7** [odin-lang/Odin#2866]
## Context

I'm currently working on replacing `sys/` package's syscall bindings on linux to bind more stuff and introduce Odin's types early in the pipeline. I'm writing the bindings with full documentation, but the issue is that the structs that syscalls return are sometimes platform-dependent. For now I'm keeping all type definitions in the same file and my struct declarations look like this:

```
when ODIN_ARCH == .arm64 {
   Stat :: struct{/*...*/} // New cross-platform version of `struct stat`
} else when ODIN_ARCH == .amd64 {
   Stat :: struct{/*...*/} // Old platform-specific version of `struct stat`
} else {
   Stat :: struct{/*...*/} // Somewhat cross-platform `struct stat64`
}
```

I would like to document this structure, just for the context the fields are largely the same, what differs is their order, padding and alignment.

Currently your only option to document this struct in a way compatible with odin-doc is to copy-paste the documentation three times, once into each `when/else` block.

## Proposal

If Odin allowed re-declaration of struct, in the same way it allows re-declaring primitive types, the documentation can be put outside of the `when` block, without the needing to duplicate the documentation.

```
/// *stat documentation here*
Stat :: Stat
```

## Future directions

I haven't interacted much with `odin doc`, so I don't quite know the extent of its abilities. The pattern of declaring the platform-dependent types in functions separately and putting the documentation on a re-declaration statement can probably allow for better documentation, where it would describe the struct first, and then list platform-dependent declarations and/or define flags that expose one or the other structure declaration.

**Comment by jakubtomsu** [comment]
If I understand you problem correctly, maybe you could do something like this..?

```odin
/// *stat documentation here*
Stat :: struct {
    impl: _Stat, // maybe use `using`?
    // other cross-platform fields could be here
}

when ODIN_ARCH == .arm64 {
   _Stat :: struct{/*...*/} // New cross-platform version of `struct stat`
} else when ODIN_ARCH == .amd64 {
   _Stat :: struct{/*...*/} // Old platform-specific version of `struct stat`
} else {
   _Stat :: struct{/*...*/} // Somewhat cross-platform `struct stat64`
}
```

I've seen code like this in core lib, e.g. `core:sync` `Mutex` and platform-specific `_Mutex`.

**Comment by flysand7** [comment]
I guess

```odin
Stat :: struct {
    using impl: _Stat, // maybe use `using`?
}
```

In my case works better, since the user won't have to do hoops accessing the `impl` field of the stat struct every time they retrieve information about a file.

But yes, this actually works for me. I'm closing this issue.
