### ISSUE TITLE
Access to the struct fields during initialization

### ISSUE THREAD

**Issue by sshikaree** [odin-lang/Odin#2872]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

*  `odin report` output:
        Odin: dev-2023-10:2783461e
	OS:   Manjaro Linux, Linux 6.1.53-1-MANJARO
	CPU:  12th Gen Intel(R) Core(TM) i5-12500
	RAM:  31808 MiB

## Failure Information (for bugs)

Can't access to existing struct fields during initialization. Wasn't able to find any information about this so reporting a bug.

### Steps to Reproduce

```
Vector2 :: struct {
    x: f32,
    y: f32,
}

// Doesn't work
vector2_new :: proc() -> Vector2 {
    return Vector2 {
        x = 42,
        // y = x,
        y = .x,
    }
}
```

```
Error: Invalid type 'f32' for implicit selector expression '.x'
```
```
// Doesn't work
vector2_new2 :: proc() -> Vector2 {
    v: Vector2 = {
        x = 42,
        y = v.x,
    }
    return v
}
```

```
Error: Undeclared name: v
```
Workaround

```
vector2_new3 :: proc() -> Vector2 {
    v : Vector2 = {
        x = 42,
    }
    v.y = v.x
    return v
}
```

**Comment by laytan** [comment]
This is not a feature in Odin, which is why you can't find any information about it.

**Comment by flysand7** [comment]
In case you desire more clarification, the reason this won't (or rather cannot be implemented) is because whatever syntax is used, it's going to be ambiguous.

If it's made to be `field = .Other`, then it can also refer to an implicit enum field, and if it's made to be `field = other`, then it could be a constant assignment
