### ISSUE TITLE
Bit-shifting Float causes LLVM to error/crash

### ISSUE THREAD

**Issue by blob1807** [odin-lang/Odin#2913]
## Context

When doing a bit-shift on a hard coded float, LLVM errors/crashes in code gen but only when a non constant is used.

Odin: dev-2023-11:4d498b66
OS:   Windows 11 Home Basic (version: 22H2), build 22621.2428
CPU:  AMD Ryzen 7 6800HS with Radeon Graphics
RAM:  15608 MiB

Also happens on dev-2023-10-nightly:2cca0050

## Expected Behavior

To return the same if with a const or odin errors out. IDK what's the proper one

## Current Behavior

LLVM errors out / crashes with:
```
Both operands to ICmp instruction are not of the same type!
  %11 = icmp ult double %10, i0 0
Shifts only work with integral types!
  %12 = shl double 1.000000e+00, %10
```

### Steps to Reproduce

Run with any of the commented out sections uncommented
```odin
main :: proc() {
    s := "2"
    a := [3]uint{1,2,3}
    sl := []uint{1,2,3}
    c :: 2
    i: uint = 2
    
    n := 1.0<<c        //-> works
    // n := 1.0<<i     //-> LLVM build crash
    // n := 1.0<<a[1]  //-> LLVM build crash
    // n := 1.0<<sl[1] //-> LLVM build crash
    // n := 1.0<<uint(strconv.atoi(s)) //-> LLVM build crash

    fmt.println(n)
}
```

### Failure Logs

Full LLVM output for `1.0<<i `:
[LLVM out.txt](https://github.com/odin-lang/Odin/files/13227329/LLVM.out.txt)

**Comment by flysand7** [comment]
Should bitshift on floats even be allowed by the type checker in the first place?

That said, the error message is curious. What happens if you bitshift not by integer but by another float?

**Comment by gingerBill** [comment]
@flysand7 The bug is here is that `1.0` is representable by an integer, and the internal "exact value" constant is not being updated to an integer.
