### ISSUE TITLE
import errors despite `when`

### ISSUE THREAD

**Issue by dotbmp** [odin-lang/Odin#292]
This has been brought up before, just making an official issue out of it. `import` statements placed inside file-scope `when` statements the conditions of which evaluate to `false` still result in name resolution errors if the `import`ed package is not supported on the host platform.

For example, I have a package `bp:process` that uses `CreateProcessA` to spawn Windows child processes. Using it my code like this:
```
when os.OS == "windows" {
    import "bp:process"
}

...

// inside a procedure
when os.OS == "windows" {
    process.create("cl %s /OUT:%s", input, output);
}
```
While the `process.create` call does not trigger any errors due to being `when`'d out, I get errors stating that `win32` is an undeclared name from `bp:process/process.odin`. `core:sys/win32` is imported by `bp:process/process_windows.odin`, so it seems that imports inside false `when` conditions are being lexed, parsed, and reaching at least the name resolution stage of checking if not the typechecking stage.

I hope this has been clear, it's a bit of a weird bug to describe so I opted for over-describing 😛 

If you have any pointers as to where to start looking, I'd be happy to take a look at the compiler myself, but I have a feeling this bug is a little out of my depth in regards to intimate knowledge of the compiler's internals.

**Comment by bpunsky** [comment]
So `ODIN_OS` is still a thing? Hmm

What makes it better than os.OS here? Not being in a package?
