### ISSUE TITLE
Compiler Error: Exit Code -1073740940 "All nodes should be resolved" "Broken module found, compilation aborted"

### ISSUE THREAD

**Issue by Sarund9** [odin-lang/Odin#2922]
## Context
I was experimenting with a assigned global, allocations, and value/reference syntax.

```
Odin: dev-2023-11:5edb2c568
OS:   Windows 10 Home Basic (version: 22H2), build 19045.3570       
CPU:  AMD Ryzen 7 5800X 8-Core Processor
RAM:  32712 MiB
```

## Expected Behavior
A consistent build success.

## Current Behavior
Build sometimes fails with an exit code, sometimes prints an error.
Rarely, it builds successfully and runs fine, the provided example produces the following output:
```
Program: 
         Modules (1):
                 Module: &Module{name = ""}
```

## Failure Information (for bugs)

Build sometimes fails with error code (-1073740940)

Sometimes prints:
```
All nodes should be resolved!
!400 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64, align: 64, dwarfAddressSpace: 0)
LLVM ERROR: Broken module found, compilation aborted!
```
Before exiting with the same error code.
NOTE: this is sometimes never printed (but the build still fails) if all fields are removed from the `Module` struct (see below)

Build sometimes succeeds, however it Always succeeds if one of the offending lines is removed

### Steps to Reproduce
I boiled down a minimal setup

#### Files:
```py
shader/shader.odin
main.odin
bug.bat
```

#### main.odin
```go
package main

import "shader"

main :: proc() {
    shader.printTree(&shader.basicShader)
}
```

#### shader.odin
```go
package shader

import "core:fmt"

Program :: struct {
    modules: [dynamic]^Module,
    subprograms: map[string][]^Module,
}

// removing fields leads to an incosistent result
Module :: struct {
    name: string,
}

printTree :: proc(using program: ^Program) {
    using fmt
    printf("Program: \n")
    printf("\t Modules ({}):\n", len(modules))
    for mod in modules { // 'offending' line
        printf("\t\t Module: {}\n", mod)
    }
}

basicShader := Program {
    modules = {
        set(Module {}, "vert"),
    },
    subprograms = {
        "default" = {
            ref(Module, "vert"), // 'offending' line
        },
    },
}

@private
allocs: map[string]rawptr

set :: proc(pass: $T, id := "") -> ^T {
    ptr := new(T)
    ptr^ = pass
    if id != "" do allocs[id] = ptr
    return ptr
}

// Offending function? Calling from main does not cause the error
ref :: proc($T: typeid, id: string) -> ^T {
    ptr, ok := allocs[id]
    if ok {
        return cast(^T) ptr
    }
    return nil
}
```

#### bug.bat (Simple build script)
```bat
echo off
cls

odin build . -debug -out:bug.exe

if %ERRORLEVEL% NEQ 0 (
    echo Failed to Build %ERRORLEVEL%
    exit %ERRORLEVEL%
)
echo Build Success
```

### Failure Logs
Possible outputs from `bug.bat`
- ```
  Build Success
  ```
- ```c
  Failed to Build -1073740940
  ```
- ```d
  All nodes should be resolved!
  !400 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64, align: 64, dwarfAddressSpace: 0)
  LLVM ERROR: Broken module found, compilation aborted!
  ```

**Comment by laytan** [comment]
I am pretty sure this has been fixed in https://github.com/odin-lang/Odin/commit/d8bb93accc3793b82609f2b14881272f3e19af27, could you verify?

**Comment by Sarund9** [comment]
Instead of the last error (All nodes ...), it now outputs:
```c
invalid base type
!398 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !399, size: 64, align: 64, dwarfAddressSpace: 0)
!399 = !{!400, !168, !423, !279, !120, !435}
LLVM ERROR: Broken module found, compilation aborted!
Failed to Build -1073740791
```
It still has a chance to do `Failed to Build -1073740940`, or Success
