### ISSUE TITLE
 Intermittent missing value 'args' compiler bug

### ISSUE THREAD

**Issue by hitchh1k3r** [odin-lang/Odin#2943]
## Context

This is an intermittent compiler bug, it happens on my computer about 1 in 10 times.

Odin: dev-2023-11:ef5eb4b6
OS:   Windows 10 Professional (version: 22H2), build 19045.3570
CPU:  Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
RAM:  16311 MiB

## Expected Behavior

The compiler should not crash.

## Current Behavior

The compiler occasionally crashes with the message:
```
[...]\Odin\src\llvm_backend_general.cpp(2908): Panic:
        Error in: [...]/core/os/os_windows.odin(64:1), missing value 'args'
```

## Failure Information

This seems to only happen when calling a global procedure with a parapoly parameter that accesses os.args via an explicit overload. Here is a minimal reproduction:

```odin
package main

import "core:os"

main :: proc() {
  proc_override :: proc{ unused, global_proc_using_args }
  unused :: proc() {}

  proc_override(0)
}

global_proc_using_args :: proc(parapoly_param : $T) {
  a := os.args
}
```

**Comment by jakubtomsu** [comment]
This might be related to #2968, there seem to be some threading issues in the checker. The problem goes away when I use `-no-threaded-checker`

**Comment by laytan** [comment]
The linked issue has been fixed, can you verify it also fixed this one?

**Comment by jakubtomsu** [comment]
I tested the repro it and it doesn't seem to crash anymore
