### ISSUE TITLE
Weird Pointer Autocasting Bug

### ISSUE THREAD

**Issue by bpunsky** [odin-lang/Odin#295]
So it seems that pointers to a struct autocasting to pointers to `using` members of that same struct. Behold the weirdness that that entails: https://i.imgur.com/e0lPJvs.png

Code:
```
main :: proc() {
    Bar :: struct {
        x: int,
    }

    Foo :: struct {
        y: int,
        using bar: Bar,
    }

    op :: proc(b: ^Bar) {
        println(b.x); // 321 rather than 123
    }

    f: Foo = {321, {123}};
    op(&f);
}
```

An obvious fix would be to only allow it if the `using` member is the first member, and no struct reordering takes place. My personal opinion is that this shouldn't be allowed at all 😛, `&f.bar` never hurt a soul.

**Comment by gingerBill** [comment]
Where is the bug? `using` on a struct field enabled subtype polymorphism. This is a feature.

**Comment by gingerBill** [comment]
Fixed in latest commit
