### ISSUE TITLE
Case for Goto

### ISSUE THREAD

**Issue by bpunsky** [odin-lang/Odin#296]
It would be very useful to be able to use `goto` within switches to access other cases, and the implications with regard to `defer` are the same as with `fallthrough`.
```
switch kind {
case Foo:
    return 1;
case Bar:
    return 2;
case Foo_Bar:
    when os.OS == "windows" {
        goto Foo;
    }
    else {
        goto Bar;
    }
}
```

**Comment by gingerBill** [comment]
`goto` is complicates things a lot when it interacts with `defer`. In order to get them to mesh correctly would not be intuitive for the programmer nor would it be intuitive for the reader. I have not implemented `goto` for this exact reason -- it complicates the language a lot.

Your use case is pretty interesting but too specific to warrant the concept of `goto` for a single use case.

**Comment by Kelimion** [comment]
```cpp
for (kind) {
    switch kind {
    case Foo:
        return 1;
    case Bar:
        return 2;
    case Foo_Bar:
       when os.OS == "windows" do kind=Foo; else kind=Bar;
    }
}

**Comment by gingerBill** [comment]
```go
other: for {
    if cond {
        continue other;
    }
    break other;
}
```

**Comment by bpunsky** [comment]
Abusing loops that way is a sign that something is wrong in my opinion 😛

It becomes unclear what you're doing very fast, especially if it's part of a large proc.

My take on this would be to implement `goto` and just disallow any interaction with `defer`s, by ensuring that `goto`s in deferred blocks aren't accessing labels outside of the deferred block and vice versa, but I take it you've thought about this more than I have, so I'll grudgingly `defer` to your judgement 😛 

Of course there's the "let them break things" approach too!

**Comment by gingerBill** [comment]
@bpunsky There is now a better feature!
```c
label: {
    break label;
}
```

**Comment by bpunsky** [comment]
Neat! I'll have to play around with it
