### ISSUE TITLE
Aliasing issues when value is passed by reference

### ISSUE THREAD

**Issue by jakubtomsu** [odin-lang/Odin#2971]
## Context
Odin can pass values by reference if they are large (>16 bytes on x64 IIRC) and it's more efficient to do so. This works because parameters are immutable.
However this can cause a problem when you alias a value with a pointer. I discovered this specific issue because it's also happending in Zig.

I haven't ran into this issue while writing code, but it's a footgun people should be aware of.

## Expected Behavior
I'm not exactly sure what is the best way to tackle this problem. Odin can't really reason about aliasing like something like Rust.

But there should definitely be better docs on the automatic references. Many people on the discord were very surprised by this behavior. Aliasing rules could also use some docs.

There could also be checking for aliased values in local scope. We can't guarantee anything globally, but I think lot of the errors could be caught in the checker.

Another idea I had is to say all aliasing is disallowed. ISPC does this, and it works for the high-performance focesed code really well. I'm not sure if it's applicable to a general-purpose language like Odin though.
More info here: https://ispc.github.io/ispc.html#data-alignment-and-aliasing

## Current Behavior
Currently if you alias a pointer with a value passed automatically by reference, you can modify the value indirectly using the pointer.

### Steps to Reproduce
This is a simple example of the problem:
```odin
package main
import "core:fmt"

Data :: struct {
	a: [1000]i64,
}

foo :: proc(a: Data, b: ^Data) {
	// Uncommenting this line fixes it by copying the value:
	// a := a
	b.a[5] = 123
	fmt.println(a.a[5]) // prints 123
}

main :: proc() {
	d: Data
	// Aliased value with pointer. The value is passed by reference automatically.
	foo(d, &d)
}
```

**Comment by laytan** [comment]
See https://twitter.com/TheGingerBill/status/1727744336673030145

**Comment by jakubtomsu** [comment]
Oh cool, I missed that. I agree with Bill, I think it's a good idea to pass by reference automatically, and it's not a problem in _vast_ majority of cases.

But I still think this issue is kinda relevant, because most of these issues happen when people don't understand aliasing, or that the value could be implicitly passed by ref. I think improving the overview docs is probably the most beneficial thing to do.

**Comment by gingerBill** [comment]
We just need to document this clearer. That's all.
