### ISSUE TITLE
SDL2 fourcc codes are in the wrong order

### ISSUE THREAD

**Issue by numbers-zz** [odin-lang/Odin#2990]
In the sdl2 bindings, the fourcc codes for pixel formats in sdl2_pixels are in the wrong order. E.g. 

'Y'<<24 | 'V'<<16 | '1'<<8 | '2'<<0,

should be 

'Y'<<0 | 'V'<<8 | '1'<<16 | '2'<<24,

This is what the SDL source code is doing (in most recent code, [here](https://github.com/libsdl-org/SDL/blob/e4582e6edc13649668111aea4e9c04cf840bdfb8/include/SDL3/SDL_stdinc.h#L120)) and is as far as I know the typical calculation of fourcc codes.

When I grab available texture formats with GetRendererInfo and loop through its texture_formats array, enum conversion sees several entries that are recorded as bad enum values. On inspection these are the reversals of Odin's attempted fourcc code calculation.

**Comment by flysand7** [comment]
Odin's SDL2 bindings follow the [exact same procedure](https://github.com/odin-lang/Odin/blob/master/vendor/sdl2/sdl_stdinc.odin#L18) for computing the Four CC codes as SDL2.

However the actual definition of pixel formats is flipped..
