### ISSUE TITLE
thread local storage support

### ISSUE THREAD

**Issue by benoitjacquier** [odin-lang/Odin#300]
Hi, 

I created an allocator with a simple leaktracker
( https://gist.github.com/benoitjacquier/62299cb6ab923641c52d71ae8efa06eb )
It's not thread safe, i'd like to test it with TLS.
Is thread_local still supported ?

Thanks!

**Comment by gingerBill** [comment]
Thread local storage is supported at the file scope:
```
@(thread_local)
x: int;
```
It can have any of the following _string_ parameters
```
@(thread_local="default")
@(thread_local="localdynamic")
@(thread_local="initialexec")
@(thread_local="localexec")
```
