### ISSUE TITLE
Large performance difference, maybe bug

### ISSUE THREAD

**Issue by iansimonson** [odin-lang/Odin#3023]
## Context

I've been hitting a performance issue quite often during Advent of Code problems where storing a temporary calc into a variable in a loop leads to a 50% performance penalty for the loop (and ~20-40% hit overall depending on how hot the loop is in the code)

Affects Windows and MacOS (probably linux too but I haven't been able to confirm)
This is all when compiling with:
`odin build . -o:aggressive -no-bounds-check -disable-assert -microarch:native`

The windows machine this was generated for is a Ryzen 5800X
The mac is a 2017 3.1 GHz Dual-Core Intel Core i5

I've attached a small benchmark which shows the difference. The llvm-ir of this benchmark and relevant asm sections are also attached. They were generated from the windows build. I also was able to run the benchmark via vtune (recompiling each time to only run one workload) to narrow down the asm instructions that were hot.

The code is essentially a loop over a 2D grid with three access patterns
1. `aocloop_do_work_1` -> loop over the 1D slice and calc row/col at the start of the loop, use that in the switch statement
2. `aocloop_do_work_2` -> loop over the 1D slice and (mulitple times) calc row and col at each access / use
3. `aocloop_do_work_3` -> loop `0..<grid_height` and `0..<grid_width` and calc index i into the 1D slice

2 and 3 above run roughly equivalent times
1 is the problem and takes twice as much time to run

Interestingly, building with `-o:speed` rather than `-o:aggressive` actually makes 2 the slowest by quite a bit

This does _not_ appear to be related to SROA as reverting the Odin compiler and/or manually adding that step back in does not appear to change the benchmark

~~I'm not super familiar with llvm-ir but this line in do_work_1_llvm_ir.txt caught my eye and might be the culprit (line 83):~~
edit: was unrelated

## Expected Behavior

The three loops above should translate to roughly the same code when compiled with `-o:aggresssive`

## Current Behavior

The llvm-ir is very similar, as is the asm, however the asm has a few key divergences which show up in the vtune hotspot profiling.

## Logs

[do_work_1_llvm_ir.txt](https://github.com/odin-lang/Odin/files/13679583/do_work_1_llvm_ir.txt)
[do_work_2_llvm_ir.txt](https://github.com/odin-lang/Odin/files/13679587/do_work_2_llvm_ir.txt)
[optimization_example_llvm_ir.txt](https://github.com/odin-lang/Odin/files/13679588/optimization_example_llvm_ir.txt)
[do_work_1_dump_asm.txt](https://github.com/odin-lang/Odin/files/13679600/do_work_1_dump_asm.txt)
[do_work_2_dump_asm.txt](https://github.com/odin-lang/Odin/files/13679602/do_work_2_dump_asm.txt)
[for_loop_temporaries.txt](https://github.com/odin-lang/Odin/files/13679615/for_loop_temporaries.txt)
[runner.txt](https://github.com/odin-lang/Odin/files/13679618/runner.txt)

**Comment by iansimonson** [comment]
If you'd like to try the example yourself more easily you can download it from here:
https://github.com/iansimonson/AoC_2023/tree/main/optimization_example

**Comment by iansimonson** [comment]
Update:

It appears to be related to temporaries existing in different scopes. A version (1c) was added to the benchmark that has the same (on windows) or better (on mac) performance than (2). The only difference between 1c and 1 is the temporaries for `row` and `col` are defined in each switch block vs at the top of the for loop

**Comment by JesseRMeyer** [comment]
This is likely because the SROA pass was removed recently as it was discovered to be generating bad code.  Unfortunately it's an important baseline optimization, so we'd like to understand how to enable it without the problems.

You can test if this is the case for you by re-running the tests as compiled with Odin built with 034aead9301305d41756ef3b5b9b60a88c95d825, which I think is the commit before the SROA pass was removed..

**Comment by iansimonson** [comment]
Hey Jesse, I'll run it again with that specific commit but note above I did run with an older version of the compiler that has SROA enabled as well as HEAD with those passes added back in (though admittedly I just manually added those passes in that were removed. I don't know llvm enough to know how they play with the new passes added in since the removal).

I've got some more to dive into also because, at least running on my 2017 intel mac, a C++ equivalent benchmark is actually displaying a similar result with clang 17. MSVC doesn't like how I've written my benchmark currently so:

So next few steps:
1. Re-run odin benchmark with the commit you provided
2. Fixup the c++ benchmark so I can run on my windows ryzen 5800x system
3. Grab a clang 14/15 compiler to see if there's maybe regression

I've been browsing through the llvm issues page and there are a number of optimization regressions listed that _could_ be related to this issue mentioned.

**Comment by JesseRMeyer** [comment]
My bad.  I somehow missed that you tested this (I'll blame the fact that I haven't finished my morning coffee yet!).

**Comment by iansimonson** [comment]
No worries at all. Esp because that is the answer to most perf problems in odin recently haha

**Comment by iansimonson** [comment]
Update:
I'm chatting in llvm discord and will probably end up opening a ticket. This appears to be the same behavior as C++ going back as far as godbolt has compiler versions for. At the very least there's a clang/llvm bug I'm going to open an issue for about not respecting `[[likely]]` / `intrinsics.expect` values. At best someone there agrees this optimization should happen in general

going to close this issue
