### ISSUE TITLE
TCP Dialing Error on NixOS (core:net)

### ISSUE THREAD

**Issue by greenm01** [odin-lang/Odin#3042]
Hello,

I have a simple TCP server/client command-line set of apps in Odin (using the core:net package) that compiles and runs successfully on both Windows and Ubuntu Linux. The client basically dials the server and transmits some serialized data that is decoded and displayed on the server side.

Serving on localhost 127.0.0.1, port 10000

However, under NixOS I'm getting **_Dial_Error.Not_Socket_** error when calling the **_net.dial_tcp_** procedure in my client code. As mentioned above, this same code runs successfully under both Windows and Ubuntu.

The server seems to be running correctly on NixOS, as I can successfully ping it with [tcping](https://github.com/cloverstd/tcping). TCP port 10000 is open in my firewall configuration. 

Anyone have an idea what the problem might be?

**Comment by flysand7** [comment]
What is the version of Odin you're running? I remember there was a bug like that that got fixed recently

**Comment by greenm01** [comment]
> What is the version of Odin you're running? I remember there was a bug like that that got fixed recently

I using dev-2023-12

**Comment by flysand7** [comment]
Okay, seems like it is probably a bug then. Can you post the code that dials the server?

**Comment by greenm01** [comment]
> Okay, seems like it is probably a bug then. Can you post the code that dials the server?

Here's the code that fails on NixOS:

	endpoint := net.Endpoint {
		address = net.IP4_Address([4]u8{127, 0, 0, 1}),
		port    = 10000,
	}

	dial_socket, ok := net.dial_tcp(endpoint)
	if ok != nil {
		fmt.printf("error dialing port %d: %v", endpoint.port, ok)
		os.exit(1)
	}

Error message:

error dialing port 10000: Not_Socket

**Comment by flysand7** [comment]
I tried doing the same with one of my servers, ran the server listening on port 10000, and used the following test:

```odin
package test

import "core:os"
import "core:fmt"
import "core:net"
import "core:testing"

@(test)
test_net :: proc(t: ^testing.T) {
    endpoint := net.Endpoint {
        address = net.IP4_Address([4]u8{127, 0, 0, 1}),
        port    = 10000,
    }
    dial_socket, ok := net.dial_tcp(endpoint)
    testing.expect_value(t, ok, nil)
    if ok != nil {
        fmt.printf("Error dialing port %d: %v", endpoint.port, ok)
        os.exit(1)
    }
}
```

It doesn't seem like I can reproduce it on my machine (Arch Linux btw), maybe it's due to OS difference which I would want to doubt but have no way of confirming unless you are on the latest nightly version of Odin.

What would happen to the issue if you updated your Odin's core library to the latest version?

Since this bug is irreproducible like that, you might assist the debugging if you printed the socket value from `net:_dial_tcp_from_endpoint` function:

```diff
+import "core:fmt"

@(private)
_dial_tcp_from_endpoint :: proc(endpoint: Endpoint, options := default_tcp_options) -> (TCP_Socket, Network_Error) {
	errno: linux.Errno
	if endpoint.port == 0 {
		return 0, .Port_Required
	}
	// Create new TCP socket
	os_sock: linux.Fd
	os_sock, errno = linux.socket(_unwrap_os_family(family_from_endpoint(endpoint)), .STREAM, {}, .TCP)
	if errno != .NONE {
		// TODO(flysand): should return invalid file descriptor here casted as TCP_Socket
		return {}, Create_Socket_Error(errno)
	}
+	fmt.println(os_sock, errno)
	// NOTE(tetra): This is so that if we crash while the socket is open, we can
	// bypass the cooldown period, and allow the next run of the program to
	// use the same address immediately.
	reuse_addr: b32 = true
	_ = linux.setsockopt(os_sock, linux.SOL_SOCKET, linux.Socket_Option.REUSEADDR, &reuse_addr)
	addr := _unwrap_os_addr(endpoint)
	errno = linux.connect(linux.Fd(os_sock), &addr)
	if errno != .NONE {
		return cast(TCP_Socket) os_sock, Dial_Error(errno)
	}
	// NOTE(tetra): Not vital to succeed; error ignored
	no_delay: b32 = cast(b32) options.no_delay
	_ = linux.setsockopt(os_sock, linux.SOL_TCP, linux.Socket_TCP_Option.NODELAY, &no_delay)
	return cast(TCP_Socket) os_sock, nil
}

```

**Comment by greenm01** [comment]
> I tried doing the same with one of my servers, ran the server listening on port 10000, and used the following test:

Appreciate the help! I finally got it working on NixOS.

Turns out the "unstable" NixOS Odin package wasn't up to date, even though the version was dev-2023-12.

Instead I cloned the Odin master branch and built it locally on my machine. Problem solved!

Merry Xmas and Happy New Year. Cheers to 2024!

**Comment by greenm01** [comment]
problem solved
