### ISSUE TITLE
`-lld` CLI Argument Ignored on Non-Windows Machine

### ISSUE THREAD

**Issue by pcleavelin** [odin-lang/Odin#3044]
## Context

Just to be clear up-front, I'm using the nix package manager to install Odin (which is currently broken, but with workarounds I am able to run the compiler). However, when linking any libraries (in my case the `vendor:raylib` package), it uses `ld` and fails to link some Objective-C symbols. I imagine this works fine through the normal & supported installation method of `brew`, but the issue isn't `ld` not working in my strange environment, its when running the build with the `-lld` argument:
```console
$ odin build <dir> -lld
```

The above command seems to ignore the argument on MacOS (and I think it will on linux as well). Looking at the source, in [src/linker.cpp:L103](https://github.com/odin-lang/Odin/blob/dev-2023-12/src/linker.cpp#L103), a check is made for the `-lld` arg, but only in the branch where the system in compiling on windows, further down in the non-windows systems branch, there is no check made for this argument, and thus `ld` is always the chosen linker when compiling with `clang`.

Since on my machine `lld` links correctly, I've currently made changes locally to make the check for the argument and pass `-fuse-ld=ld64.lld` to `clang` as a workaround.

Please forgive me if I'm missing something, as I'm not familiar with the codebase at all.

## System
```
Odin: dev-2023-12
OS:   macOS Sonoma (build: 23B74, kernel: 23.1.0) (M1 Pro)
CPU:  ARM64
RAM:  16384 MiB
```
## Expected Behavior

Passing `-lld` to `odin build` on MacOS uses `lld` as the linker.

## Current Behavior

On MacOS, `ld` is always used as the linker.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run `odin build src/ -lld -v`

See that `ld` is used as the linker.

**Comment by Platin21** [comment]
Actually we pass our flags just to clang for linking. But yeah this is not taken into account.
