### ISSUE TITLE
Refuses to run tests marked as `@(private="file")`

### ISSUE THREAD

**Issue by flysand7** [odin-lang/Odin#3047]
## Context

```
Odin: dev-2023-12:ee504aa5
OS:   Arch Linux, Linux 6.6.7-arch1-1
CPU:  Intel(R) Core(TM) i5-4460T CPU @ 1.90GHz
RAM:  5373 MiB
```

## Expected Behavior

Given the following test:

```
@(test, private="file")
test_dump :: proc(t: ^testing.T) {
    for arg in os.args[1:] {
        fmt.println()
        fmt.println(arg, ":", sep="")
        fmt.println("----------")
        file_bytes, file_bytes_ok := os.read_entire_file(arg)
        testing.expect_value(t, file_bytes_ok, true)
        dump_bytes(file_bytes)
    }
}
```

I would assume a test that can not be called outside the package in normal code, i.e. can not be used as a standalone function that does meaningful things, yet can be executed by `odin test` runtime to perform the testing.

## Current Behavior

Odin is unable to find the test with the given name in the package.

```
odin test src -test-name:test_dump -- temp/temp.out
/home/bumbread/x86disasm/src/dump.odin(1:2) Error: Unable to find the test 'test_dump' in 'package disasm' 

         ^
error: Recipe `test` failed on line 5 with exit code 1
```

If `@(private="file")` is removed, the test is able to execute properly.

**Comment by gingerBill** [comment]
I think this just needs to be disallowed entirely.
