### ISSUE TITLE
`#partial` doesn't work on 2d Enumerated Arrays

### ISSUE THREAD

**Issue by jakubtomsu** [odin-lang/Odin#3062]
## Context
```
        Odin: dev-2023-12-nightly:31b1aef4
        OS:   Windows 10 Professional (version: 22H2), build 19045.3803
        CPU:  Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
        RAM:  32681 MiB
```

## Expected Behavior
I'd expect 2d enumerated arrays (`#partial[E1]#partial[E2]T`, where E1 and E2 are contiguous enums) to work like the 1d case.

## Current Behavior
Currently the second dimension enumerated array triggers an error when you use the `#partial` tag. It suggests to use `#sparse`, which doesn't make sense since both enums are contiguous.

### Steps to Reproduce
The following code doesn't compile, and prints this error:
```
Syntax Error: #partial has been replaced with #sparse for non-contiguous enumerated array types
```
```odin
package foo

Foo :: enum {
    A,
    B,
    C,
}

Bar :: enum {
    Foo,
    Bar,
    Baz,
}

// (15:30) Syntax Error: #partial has been replaced with #sparse for non-contiguous enumerated array types
data := #partial[Foo]#partial[Bar]int {
    .A = {.Foo = 1, .Bar = 2},
    .B = {.Foo = 1, .Bar = 2},
}
```

**Comment by gingerBill** [comment]
This needs a better error message but the error message is now outdated.
```odin
data := #partial[Foo][Bar]int {
    .A = #partial {.Foo = 1, .Bar = 2},
    .B = #partial {.Foo = 1, .Bar = 2},
}

```
This works
