### ISSUE TITLE
Free Segfaults depending on where a struct was initialized

### ISSUE THREAD

**Issue by Simerax** [odin-lang/Odin#3101]
## Context

```
Useful information to add to a bug report:

	Odin: dev-2024-01-nightly:5961d4b3
	OS:   openSUSE Tumbleweed, Linux 6.6.10-1-default
	CPU:  11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
	RAM:  31884 MiB
```

## Expected Behavior

No Segfault

## Current Behavior

Segfault

## Failure Information (for bugs)

Freeing a reference to a struct seems to behave differently depending on where you are freeing it.

In my example below I have written two different ways to "create" a Person struct.
After I'm done with them I want to `free` them.

In the first case (creating the struct in a seperate proc `make_person`) the `free` succeeds.
In the second case (creating the struct without an intermediate proc) the `free` segfaults.

I'm new to odin so I don't fully understand its semantics. Does the creation of `p` actually create a value on the stack which escapes to the heap on function return? This would explain the segfault of `p2`.

### Steps to Reproduce

```odin
package main

import "core:fmt"


Person :: struct {
    firstName: string,
    lastName: string,
}


make_person :: proc(firstName, lastName: string) -> ^Person {
    p := &Person{
        firstName = firstName,
        lastName = lastName,
    }
    return p
}

print_person :: proc(p: Person) {
    fmt.println(p.firstName, p.lastName)
}


main :: proc() {

    p1 := make_person("Dennis", "Ritchie")
    print_person(p1^)
    free(p1) // works
    fmt.println("still alive!")



    p2 := &Person{
        firstName = "Ken",
        lastName = "Thompson",
    }
    print_person(p2^)
    free(p2) // <-- segfault here

    // never reached
    fmt.println("still alive 2!") 

}
```

**Comment by jon-lipstate** [comment]
You are allocating on the stack, so in the case of p2, you are segfaulting because you cant free something that was allocated to the stack. What i find a little bit interesting is why p1 doesn't segfault. I would have expected it should as well. 

The correct way to allocate a pointer (if you need it) is to call `new`. Stack allocated variables do not need to be freed.

```odin
p:=new(Person)
p^ = Person{"a","b"}
free(p)
```

**Comment by gingerBill** [comment]
`x := &Person{}` is equivalent to doing this:
```
temp := Person{}
x := &temp
```

You don't `free` stack values ever.

And in your first call, you were return a stack variable, which you should not do.
