### ISSUE TITLE
Parapoly should figure out types from first non-constant instead of first parameter 

### ISSUE THREAD

**Issue by karl-zylinski** [odin-lang/Odin#3118]
## Expected Behavior

```
t: f32 = 123
s := math.smoothstep(0, 1.4, t)
```
`smoothstep` has three parameters of type $T, since 0 and 1.4 are untyped constants, then I expect it to infer the type from the first non-constant, which is t (of type f32)

## Current Behavior

You get these errors:
```
'1.4' truncated to 'int', got 1.399999
	s := math.smoothstep(0, 1.4, t)
	                        ^~^
Cannot assign value 't' of type 'f32' to 'int' in procedure argument
	s := math.smoothstep(0, 1.4, t)
```

I.e. it has inferred the type T to int, even though it had the extra info it needed in the type of t. I can work around it by changing the code to

```
t: f32 = 123
s := math.smoothstep(f32(0), 1.4, t)
```

**Comment by gingerBill** [comment]
The problem is that it needs to figure out in this order. Doing it in the way you are suggesting will make it inconsistent behaviour.
