### ISSUE TITLE
`defer`'d statements aren't executing on `break`

### ISSUE THREAD

**Issue by JoshuaManton** [odin-lang/Odin#312]
This program doesn't print anything but it definitely should.
```
import "core:fmt"

main :: proc() {
	for {
		defer fmt.println("Henlo");
		break; // change to `return` to see the print
	}
}
```
I initially observed this behaviour with `@(deferred)` so be sure to test that as well

**Comment by bpunsky** [comment]
Update your compiler bruh 😛

**Comment by JoshuaManton** [comment]
D'oh! My bad, I thought I pulled before started coding :owlofshame:
