### ISSUE TITLE
Can't build on mac anymore

### ISSUE THREAD

**Issue by clankill3r** [odin-lang/Odin#313]
I was able to build before, but I didn't build in a long time.
Now I get the following when I type make:

> make
> clang src/main.cpp -Wno-switch -Wno-writable-strings -Wno-tautological-compare -Wno-macro-redefined  -std=c++11 -g -pthread -ldl -lm -lstdc++ -o odin
> Undefined symbols for architecture x86_64:
>   "_iconv", referenced from:
>       convert_multibyte_to_widechar(char*, unsigned long, wchar_t*, unsigned long) in main-73e638.o
>       convert_widechar_to_multibyte(wchar_t*, unsigned long, char*, unsigned long) in main-73e638.o
>   "_iconv_close", referenced from:
>       convert_multibyte_to_widechar(char*, unsigned long, wchar_t*, unsigned long) in main-73e638.o
>       convert_widechar_to_multibyte(wchar_t*, unsigned long, char*, unsigned long) in main-73e638.o
>   "_iconv_open", referenced from:
>       convert_multibyte_to_widechar(char*, unsigned long, wchar_t*, unsigned long) in main-73e638.o
>       convert_widechar_to_multibyte(wchar_t*, unsigned long, char*, unsigned long) in main-73e638.o
> ld: symbol(s) not found for architecture x86_64
> clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [debug] Error 1

OSX 10.12.6

**Comment by alexkelbo** [comment]
The build fails when using `make` but with `build.sh` is works fine.

**Comment by gingerBill** [comment]
Could you please see if the latest commit has fixed this issue?

**Comment by clankill3r** [comment]
make still fails:

```
clang src/main.cpp -Wno-switch -Wno-pointer-sign -Wno-tautological-constant-out-of-range-compare -Wno-tautological-compare -Wno-macro-redefined -Wno-writable-strings -std=c++11 -g -pthread -ldl -lm -lstdc++ -o odin
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      convert_multibyte_to_widechar(char*, unsigned long, wchar_t*, unsigned long) in main-3cb837.o
      convert_widechar_to_multibyte(wchar_t*, unsigned long, char*, unsigned long) in main-3cb837.o
  "_iconv_close", referenced from:
      convert_multibyte_to_widechar(char*, unsigned long, wchar_t*, unsigned long) in main-3cb837.o
      convert_widechar_to_multibyte(wchar_t*, unsigned long, char*, unsigned long) in main-3cb837.o
  "_iconv_open", referenced from:
      convert_multibyte_to_widechar(char*, unsigned long, wchar_t*, unsigned long) in main-3cb837.o
      convert_widechar_to_multibyte(wchar_t*, unsigned long, char*, unsigned long) in main-3cb837.o
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [debug] Error 1
```

**Comment by hasenj** [comment]
FWIW I can build on mac.

I did have some issue after some OS upgrade, but it was not related to this (apple is just being mean and hiding the development tools installer in weird corners), and I was able to fix it after some Googling.

**Comment by gingerBill** [comment]
@hasenj Could you please update the installation instructions to aid others please?
