### ISSUE TITLE
odin run: Unexpected parsing of verbatim command line parameters

### ISSUE THREAD

**Issue by flysand7** [odin-lang/Odin#3158]
## Context

```
Odin: dev-2024-01:67362057
OS:   Windows 10 Home Basic (version: 22H2), build 19045.3930
CPU:  12th Gen Intel(R) Core(TM) i5-12500H
RAM:  16088 MiB
```

## Expected Behavior

The program I'm writing in Odin takes command-line parameters and one of the things it does is use the verbatim parameters. Everything following `--` is meant to be passed to the "user program", so to speak, argument by argument.

I would like to be able to run my program with `odin run` with these parameters which results in an interesting command line:

```
odin run src -out:bake.exe -o:none -debug -- -- build
```

For which, I would expect `bake.exe` to be executed with the following `argv` array:

```
["bake.exe", "--", "build"]
```

However instead, the compiler fails to run the program:

```
flysand7@~/bake(main)$ odin run src -out:bake.exe -o:none -debug -- -- build
Unknown flag: ''
```

### Steps to Reproduce

Here's a small program that would demonstrate the success case. It just prints argv array on start and exits.

```
package bug

import "core:fmt"
import "core:os"

main :: proc() {
    fmt.println(os.args)
}
```

**Comment by flysand7** [comment]
Update: pretty sure verbatim is the wrong word here as it implies the command string is the same, not the argv array, however I only care about argv for this issue.

**Comment by laytan** [comment]
Can you close this?
