### ISSUE TITLE
#caller_location unique hash field

### ISSUE THREAD

**Issue by Kelimion** [odin-lang/Odin#317]
Proposal: Extend `#caller_location` with a unique hash (or counter), like so:

`Source_Code_Location{file_path = ..\solver.odin, line = 219, column = 14, procedure = iter_gs, hash = 0x0000DEADBEEFCAFE}`

This could be used as a mapping key directly for profilers, imgui elements and so on, without them having to compute - at runtime - a unique hash or otherwise distinguishing between callers at some additional cost. If the compiler provides a known unique value to each of these call sites this cost can be avoided in many cases.

For a profiler one would still store the rest of the caller location under said key, but for an imgui button where one wants to disambiguate between two buttons each having the same label, just passing the id would likely be sufficient. In both cases it obviates the need for a hashing step combining the file, line and col values.

**Comment by gingerBill** [comment]
I have added a new field to the Source_Code_Location for hashes in commit 5acea1b
