### ISSUE TITLE
[homebrew] odin 2024-02 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [odin-lang/Odin#3171]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
$ ODIN_DEBUG=true /opt/homebrew/Cellar/odin/2024-02/bin/odin build hellope.odin -file
Syntax Error: Path does not exist:
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/7773113895/job/21196437206
relates to Homebrew/homebrew-core#161768

**Comment by laytan** [comment]
Odin now has a new collection `base`.
On line 32 of that formula you can add `, "base"` to copy that folder over and it the build should work.

Keep in mind that homebrew is an unsupported installation method.

**Comment by chenrui333** [comment]
@laytan yeah, works fine for me, thanks for the pointer. 🙏
