### ISSUE TITLE
Add opaque to the list of keywords (if it is)

### ISSUE THREAD

**Issue by Breush** [odin-lang/Odin#318]
This does not parse (syntax error):

```C
package main

A :: struct {
    opaque : int,
}

main :: proc() {
}
```

What does `opaque` do? (Couldn't find documentation about it.)

If it is a keyword, add it to https://github.com/odin-lang/Odin/wiki/Keywords-and-Operators

**Comment by vassvik** [comment]
`opaque` is a recent addition that is used to create a type that is not read or writeable, which is useful to make typesafe handles,
```
Handle :: opaque i64;
```
This should indeed be added to the docs/tutorial.

**Comment by Breush** [comment]
Can we consider to change to syntax to `#opaque`?

**Comment by gingerBill** [comment]
`opaque` was experimental in the first place but I made it a keyword to make it similar to `distinct` which is also a keyword.
