### ISSUE TITLE
Hitting exception "variadic_operands.count != 0"

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#3183]
## Context

Odin: dev-2023-11-nightly:3e1791aa
        OS:   Windows 11 Home Basic (version: 23H2), build 22631.3007
        CPU:  13th Gen Intel(R) Core(TM) i9-13900HX
        RAM:  32507 MiB

## Expected Behavior

I do not hit the expection, if I am doing something wrong I expect an error.

## Current Behavior

I get the exception from:
D:\a\Odin\Odin\src\check_expr.cpp(5572): Assertion Failure: `variadic_operands.count != 0` 

### Steps to Reproduce

This is the code I use:
```
debug_helper :: proc"c"(from_loc: runtime.Source_Code_Location, num_ret: int, args: ..any, loc := #caller_location) {
		context = runtime.default_context()

		if capture_gl_callback != nil {
			capture_gl_callback(from_loc, num_ret, ..args, loc = loc);
		}
}
```

I might be because of the "c"?

**Comment by gingerBill** [comment]
I need the full minimal code to replicate this.

**Comment by xzores** [comment]
This is old, I don't remember how I made it happen. I will close the issue.
