### ISSUE TITLE
Support arrays with `in` check

### ISSUE THREAD

**Issue by ForLoveOfCats** [odin-lang/Odin#321]
Currently, testing if a value is `in` an array throws a compiler error.
> expected either a map or bitset for 'in', got []rune

This seems like something that should be implemented as `in` works with maps.
> mymap := make(map[rune]int);
mymap['t'] = 69;
fmt.println('t' in mymap);

which prints `true`

**Comment by gingerBill** [comment]
I'm not sure if this is better than this:
```
find_in_slice :: proc(s: $T/[]$E, elem: $E) -> int {
	for e, i in s {
		if e == elem do return i;
	}
	return -1;
}

is_in_slice :: proc(s: $T/[]$E, elem: $E) -> bool {
	return find_in_slice(s, elem) >= 0;
}
```

When you want to check if something is in an array, you usually want its index too. Also, this would only work for comparable types too.

`in` for arrays would be just this `for` loop in practice so it might be an okay thing to add as it's not really much of a surprise as to what code would be generated.

**Comment by ForLoveOfCats** [comment]
Yeah sorry I should have closed this a while back. Apologies

**Comment by zPhoeniqz** [comment]
Has this been implemented? I still get the error mentioned above.

**Comment by Kelimion** [comment]
No, but then the odds of a 4-year old issue that states it won't be implemented being implemented are slim to none.

**Comment by flysand7** [comment]
To clarify, part of the odin design is to not hide complexity/significant performance behind a pretty syntax. It does a loop, therefore it should be written in a loop.

**Comment by zPhoeniqz** [comment]
>No, but then the odds of a 4-year old issue that states it won't be implemented being implemented are slim to none.
Sorry, I misread the post

>To clarify, part of the odin design is to not hide complexity/significant performance behind a pretty syntax. It does a loop, therefore it should be written in a loop.
Wouldn't it be ovbious that there is a for-loop being run under the hood? Anyway. I understand, that feature won't be implemented. Thank you for responding so quickly.
