### ISSUE TITLE
defining const named "replace" causes LLVM error

### ISSUE THREAD

**Issue by ChuuniMage** [odin-lang/Odin#3225]
declare  `replace :: "SOME_STUFF"` in a project, try to compile, and receive `\Odin\src\llvm_backend_stmt.cpp(13): Assertion Failure: `e != nullptr`

**Comment by gingerBill** [comment]
I need a _lot more_ more to replicate this. I am doubting it has anything to do with the name itself, but something else.

**Comment by ChuuniMage** [comment]
I'm finding it difficult to replicate even in my own original case that it popped up... so I'm chalking it up to LLVM voodoo.
