### ISSUE TITLE
Unprivate some procedures in `core:io` and `core:bufio`

### ISSUE THREAD

**Issue by flysand7** [odin-lang/Odin#3227]
The application I'm writing uses streams as an abstraction and I would like to be able to use the following procedures directly: `core:io._multi_writer_proc` and `bufio._writer_proc` in order to be able to check whether a given stream is a buffered stream or a multi-stream and free it's memory accordingly. And not have the "user-side" store the references to multi- and buffered streams.

Therefore I would like the `@(private)` attribute to be removed from those functions.

**Comment by gingerBill** [comment]
Make a PR for it :)
