### ISSUE TITLE
.od file extension

### ISSUE THREAD

**Issue by rvi64** [odin-lang/Odin#323]
pros:
* shorter
* simpler

cons:
* ?

**Comment by Kelimion** [comment]
cons:
- not as descriptive
- .c file extension is also named after the language
- .cpp likewise, with the substitution of pp for ++ because of filesystem limitations
- .od channels "odd" and Odin's only odd in the sense that it's one of the few sane languages

**Comment by gingerBill** [comment]
Other than defaults in MSVC, the C++ name extensions are just conventions and are not enforced.

**Comment by rvi64** [comment]
Exactly, but .odin is inforced, i can not do `odin build main.od`

**Comment by gingerBill** [comment]
And your point is? Enforcement is actually need by the package system. Why have multiple ways of doing a thing when one is all that is needed?

**Comment by rvi64** [comment]
idk it just really threw me off that i had to write 4 letters instead of 2, guess you do what you do
