### ISSUE TITLE
-target=linux_arm32 broken

### ISSUE THREAD

**Issue by wardjm** [odin-lang/Odin#3245]
## Context

	Odin:    dev-2024-03:4c35633e0
	OS:      Ubuntu 22.04.4 LTS, Linux 6.5.0-17-generic
	CPU:     AMD Ryzen 9 3950X 16-Core Processor            
	RAM:     15981 MiB
	Backend: LLVM 14.0.0

## Expected Behavior

```
package main

import "core:fmt"

main :: proc() {

    fmt.println("Hello")

}
```

odin build . -target=linux_arm32 

## Current Behavior

odin build . -target=linux_arm32 
/usr/bin/ld: /home/jeff/o-example/hello/hello.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/jeff/o-example/hello/hello.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/jeff/o-example/hello/hello.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/jeff/o-example/hello/hello.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /home/jeff/o-example/hello/hello.o: error adding symbols: file in wrong format
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by flysand7** [comment]
Are you coompiling using x86 cpu, or using an ARM cpu? The bug report information mentions an x86 cpu, but you aren't running it inside a virtual machine, are you?

If you're compiling for arm32 target using x86 cpu, you can not output executables, only relocatable object files. Odin does not support cross-linking yet.

**Comment by wardjm** [comment]
I see. Thanks!
