### ISSUE TITLE
core:math/big.Int internal_invmod() returns wrong answerodin

### ISSUE THREAD

**Issue by edyu** [odin-lang/Odin#3253]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System & Odin Version:
* Please paste `odin report` output:

        Odin:    dev-2024-03:a944aa406
        OS:      Ubuntu 22.04.4 LTS, Linux 5.15.133.1-microsoft-standard-WSL2
        CPU:     AMD Ryzen 7 5800HS with Radeon Graphics
        RAM:     11662 MiB
        Backend: LLVM 14.0.0

## Expected Behavior

Please describe the behavior you are expecting

for `internal_invmod(&ans, 17, 60)` the answer is 53, but I'm getting -54. 

## Current Behavior

What is the current behavior?

Returning wrong number. Talking @Kelimion, the code was from `libtommath` so it might have been a typo.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

    e, phi, ans: big.Int
    big.int_set_from_integer(&e, 17)
    big.int_set_from_integer(&phi, 60)
    big.internal_invmod(&ans, &e, &phi)

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Kelimion** [comment]
The C++ version gives 53 as the answer, so it does appear to be a bug in the Odin port.
```cpp
#include <time.h>
#include <string.h>
#include <stdlib.h>
#include <inttypes.h>
#include "libtommath.cpp"

int main(int argc, char* argv[]) {
    mp_int res, a, b;
    mp_err err = mp_init_multi(&a, &b, &res, NULL);
    printf("Error: %d\n", err);

    mp_set(&a, 17);
    ndraw(&a, "a");
    mp_set(&b, 60);
    ndraw(&b, "b");

    err = mp_invmod(&a, &b, &res);

    ndraw(&res, "res");
    printf("Error: %d\n", err);
}
```
