### ISSUE TITLE
core:time accurate_sleep doc needs updating for win

### ISSUE THREAD

**Issue by blob1807** [odin-lang/Odin#3259]
The current documentation for `time.accurate_sleep` points to the old `sys:win32`. https://github.com/odin-lang/Odin/blob/fc9d3ec5a7246a57bc2a5fc7ac92b4de729da9b8/core/time/time.odin#L240   
This should be changed to `windows.timeBeginPeriod(1)`.    

Additionally, as per the [MS docs](https://learn.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timebeginperiod), `timeEndPeriod` needs to be run when you're done with the same value.   
Suggesting `defer windows.timeEndPeriod(1)` should work for most people.   

I don't know the best way to write the updated doc right now, so I'm just making an issue for it.

**Comment by gingerBill** [comment]
Can you make a PR for this change please.

**Comment by blob1807** [comment]
NP will do.
