### ISSUE TITLE
`type_of` in a `struct` declaration doesn't work for variables declared in the same scope

### ISSUE THREAD

**Issue by rowbyte** [odin-lang/Odin#3287]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System & Odin Version: 
* Please paste `odin report` output: Odin:    dev-2024-03
	OS:      macOS Monterey 12.7.2 (build: 21H1015, kernel: 21.6.0)
	CPU:     Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
	RAM:     32768 MiB
	Backend: LLVM 17.0.6

## Expected Behavior

Using `type_of` in a struct declaration should work for variables in the current scope. 

## Current Behavior

`type_of` in a struct declaration only works for variables declared in a parent scope

### Steps to Reproduce

The following code fails to compile
```
        x : int = 1
	y : int = 2
	z : int = 3
        Sample :: struct {
		x : type_of(x), //compile error
		y : type_of(y), //compile error
		z : type_of(z), //compile error
        }
	sample : Sample = {9,8,7}
	fmt.println(sample.x,sample.y,sample.z)
```

But the following (just declare the struct inside a scope) compiles and runs as expected
```
        x : int = 1
	y : int = 2
	z : int = 3
	{
		Sample :: struct {
			x : type_of(x),
			y : type_of(y),
			z : type_of(z),
		}

		sample : Sample = {9,8,7}
		fmt.println(sample.x,sample.y,sample.z) //prints 9,8,7

	}
```

### Failure Logs

None

**Comment by gingerBill** [comment]
This is not a bug and part of the rules of the language.

The constant values `::` will be type checked before the variables `:=` within a scope in a procedure.
