### ISSUE TITLE
Global Variable Name Conflicts Are Not Detected

### ISSUE THREAD

**Issue by rowbyte** [odin-lang/Odin#3290]
## Context

* Operating System & Odin Version:
Odin: dev-2024-03
OS: macOS Monterey 12.7.2 (build: 21H1015, kernel: 21.6.0)
CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
RAM: 32768 MiB
Backend: LLVM 17.0.6

## Expected Behavior

The compiler should error out or atleast issue a warning if a local variable conflicts with a global variable.

## Current Behavior

The compiler compiles the program without any error or warning even if the local variable has the same name and type as a global variable. 

```
package test

S_val : int

main :: proc() {

	S_val :int = 0

	return
}
```

**Comment by karl-zylinski** [comment]
It's not really a conflict, it's called "shadowing" and it can be useful sometimes. If you compile with `-vet` or `-vet-shadowing`, then this will become an error. See `odin build --help` for what other things `-vet` includes.

**Comment by gingerBill** [comment]
This is not a bug. This is shadowing and actually a feature.
