### ISSUE TITLE
Polymorphic types sometimes mess up the compilation

### ISSUE THREAD

**Issue by Adorjani2** [odin-lang/Odin#3291]
## Context

The following code sometimes doesn't compile and gives me different errors.
https://github.com/Adorjani2/odin-bug/tree/main

* Operating System & Odin Version:
        Odin:    dev-2024-03-nightly:4c35633e0
        OS:      Windows 10 Professional (version: 22H2), build 19045.4170
        CPU:     13th Gen Intel(R) Core(TM) i7-13700K
        RAM:     16139 MiB
        Backend: LLVM 17.0.1

## Expected Behavior

The code compiles 100% of the time.

## Current Behavior

Compilation sometimes fails.

## Failure Information (for bugs)

Compilation fails randomly around 5-10% of the time. I pasted the errors I have got after compiling it 100-120 times below and also in the repository's readme. It's rare, sometimes takes 10-15 tries before any error shows up and the compilation fails.
When the code compiles then it runs correctly, no runtime errors.
It seems like the polymorphic struct is messing things up, but I'm not entirely sure since I wasn't able to shrink the code size further down. When I tried to remove more code the errors stopped showing up.
Limiting the thread count to 1 when building made the errors show up way less but I still got them very very rarely.

### Steps to Reproduce

Build the project i linked above with `odin build .` until an error shows up

### Failure Logs
Error messages I got so far:

1:
-
```
ecs.odin(193:13) Error: '_data[index]' of type 'Component_Wrapper(T)' has no field 'component'
        return &_data[index].component, .None
                ^~~~~~~~~~~^
        Suggestion: Did you mean?
                component
```

2:
-
```
ecs.odin(304:34) Error: Too many values in structure literal, expected 0, got 2
        item := Component_Wrapper(T){ed, component}
```

3:
-
```
ecs.odin(235:23) Error: 'we' of type '^ecs.Component_Wrapper(T)' has no field 'component'
        append(&ret, &we.component)
                      ^^
```

4:
-
```
ecs.odin(235:9) Error: No procedures or ambiguous call for procedure group 'append' that match with the given arguments
        append(&ret, &we.component)
        ^~~~~^
        Given argument types: (^[dynamic]^Perspective_Camera_Component, ecs/ecs.odin(304:34) ^Component_Wrapper($T=Perspective_Camera_Component))
Did you mean to use one of the following:
Error:  runtime.append_elem        :: proc(array: ^$T/[dynamic]$E, arg: E, loc := #caller_location) -> (n: int, err: Allocator_Error)            at C:/Odin/base/runtime/core_builtin.odin(450:1)
Too many values in structure literal, expected 0, got 2
        item := Component_Wrapper(T){ed, component}     runtime.append_elems       :: proc(array: ^$T/[dynamic]$E, args: ..E, loc := #caller_location) -> (n: int, err: Allocator_Error)         at C:/Odin/base/runtime/core_builtin.odin(499:1
)

                runtime.append_elem_string :: proc(array: ^$T/[dynamic]$E/u8, arg: $A/string, loc := #caller_location) -> (n: int, err: Allocator_Error) at C:/Odin/base/runtime/core_builtin.odin(519:1)
                             ^^
```

5: the first error here was from a different file in the main project where I use this code
-
```
program.odin(105:16) Error: 'c' of type 'Component_Wrapper(T)' has no field 'component'
        if c.component.primary {
           ^
        Suggestion: Did you mean?
                component

C:/Dev/odin_bugs/Telya bug/src/engine/scene/ecs/ecs.odin(304:34) Error: Too many values in structure literal, expected 0, got 2

item := Component_Wrapper(T){ed, component}
                             ^^
```

**Comment by laytan** [comment]
Issue looks solved just like the referenced issues, I ran this build a 200 times in a loop and it didn't fail.
