### ISSUE TITLE
Default arguements are allow to be placed before no-default arguments

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#3306]
## Context

        Odin: dev-2024-02-nightly:539cec74
        OS:   Windows 11 Home Basic (version: 23H2), build 22631.3296
        CPU:  13th Gen Intel(R) Core(TM) i9-13900HX
        RAM:  32507 MiB

## Expected Behavior

The thing below should not compile.

## Current Behavior

This will pass:
```
generate_sphere :: proc(offset : [3]f32 = {0,0,0}, diameter : f32, stacks : int = 10, sectors : int = 20, use_index_buffer := true, loc := #caller_location) -> (verts : []Default_vertex, indices : []u16) {
}

```

diameter does not have a default value but offset do!

### Steps to Reproduce

Compile above.

**Comment by xzores** [comment]
Maybe I am not remembering correctly, but this used to be illigal.

**Comment by gingerBill** [comment]
This is not a bug. And has technically always been allowed.
