### ISSUE TITLE
Fresh Odin install warns about duplicate libraries

### ISSUE THREAD

**Issue by sz-piotr** [odin-lang/Odin#3324]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System & Odin Version: MacOS Sonoma 14.1.1 (23B81), odin version dev-2024-03:34247b265
* Please paste `odin report` output:
```
❯ odin report
Where to find more information and get into contact when you encounter a bug:

        Website: https://odin-lang.org
        GitHub:  https://github.com/odin-lang/Odin/issues


Useful information to add to a bug report:

        Odin:    dev-2024-03:34247b265
        OS:      macOS Sonoma 14.1.1 (build: 23B81, kernel: 23.1.0)
        CPU:     ARM64
        RAM:     16384 MiB
        Backend: LLVM 14.0.6
```

## Expected Behavior

After the installation of Odin building the hellope example results in the following output:
```
❯ odin run .
Hellope!
```

The code in question
```odin
package main

import "core:fmt"

main :: proc() {
	fmt.println("Hellope!")
}
```

Note that the expected behavior actually does happen when I pass the `--lld` flag.
```
❯ odin run . --lld  
Hellope!
```

## Current Behavior

The build process warns about duplicate libraries:
```
❯ odin run .    
ld: warning: ignoring duplicate libraries: '-lSystem'
Hellope!
```

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Follow the MacOS installation guide for Odin
2. Create a folder with `main.odin` containing the source code of the hellope example.
3. Run `odin run .`

Maybe it is the case that my system has something special configured that I don't know about but I don't know where to look. I'll provide more information on request.

### Failure Logs

I don't think there are any logs that I can provide.

**Comment by laytan** [comment]
Fixed in #3316
