### ISSUE TITLE
Compiler deadlock

### ISSUE THREAD

**Issue by laytan** [odin-lang/Odin#3341]
## Context

Since https://github.com/odin-lang/Odin/commit/6d4f30de1a85fe51159808d70a342c1c915d15de there is a deadlock compiling this gist: https://gist.github.com/gingerBill/e1270f60a1739c266934599c2bee46f5 (obviously on macOS because it is a darwin program).

## Failure Information (for bugs)

Seems to be stuck waiting on a futex.

### Steps to Reproduce

1. copy gist
2. try to compile it

**Comment by gingerBill** [comment]
This is caused by any of the following lines:
```odin
color_attachment->setLoadAction(.Clear)
color_attachment->setStoreAction(.Store)
color_attachment->setTexture(drawable->texture())
```

Why? I have no idea, yet.
