### ISSUE TITLE
os.flush mising on darwin based systems

### ISSUE THREAD

**Issue by serberoth** [odin-lang/Odin#3349]
## Context

The os.flush function is missing on for darwin based systems causing compilation errors without marking the code in a `when`

* Operating System & Odin Version:
OSX
odin version dev-2024-03:4c35633e0

* Please paste `odin report` output:

## Expected Behavior
Expected the os.flush function to exist per the documentation:
https://pkg.odin-lang.org/core/os/#flush

Please describe the behavior you are expecting
The os.flush function does not exist for darwin systems:
```
xxx.odin(365:12) Error: 'flush' is not declared by 'os'
        err := os.flush(cast(os.Handle)handle)
               ^~~~~~~^
        Suggestion: Did you mean?
                EBUSY
                fstat
                ESRCH
                EAUTH
                fcntl
```

## Current Behavior

What is the current behavior?
The os.flush function does not exist for darwin based systems causing compilation errors.  There should be a function declared in os_darwin.odin named flush that invokes fsync on the provided file descriptor and returns any associated error value, similar to the other operating systems.

https://man7.org/linux/man-pages/man2/fsync.2.html

I would imagine that an implementation of this would look something similar to the following added into the os_darwin.odin file:

```
foreign libc {
    ...
    @(link_name="fsync")            _unix_fsync         :: proc(handle: Handle) -> c.int ---
    ...

...
flush :: proc(fd: Handle) -> (Errno) {
    return cast(Errno) _unix_fsync(fd)
}
...
```

**Comment by serberoth** [comment]
I have created this PR to try and address this issue:
https://github.com/odin-lang/Odin/pull/3354

**Comment by laytan** [comment]
This can be closed
