### ISSUE TITLE
Linux .a files missing from "vendor/stb/lib" (linker error)

### ISSUE THREAD

**Issue by causecause1** [odin-lang/Odin#3391]
## Context
* Operating System & Odin Version: Kubuntu 23.10
* `odin report` output:
```
        Odin:    dev-2024-04:510574aa7
        OS:      Ubuntu 23.10, Linux 6.5.0-26-generic
        CPU:     AMD FX(tm)-6300 Six-Core Processor             
        RAM:     7914 MiB
        Backend: LLVM 17.0.2
``` 

## Expected Behavior
Programs should compile.

## Current Behavior
The linker throws an error because the file is missing.

## Failure Information (for bugs)
```
/usr/bin/ld: cannot find -l:/home/user/dev/libs/Odin/vendor/stb/image//../lib/stb_image.a: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
``` 

### Steps to Reproduce

1. Create a project (on Linux)
2. `import "vendor:stb/image"`
3. Try to run it. It fails because of the missing file

(The fix: Compile it yourself and place it in the path, or install it through the package manager.)

**Comment by laytan** [comment]
On Linux we do not pre-compile some libraries, if that is the case we will either try to link to a system version, or provide a Makefile in the vendor package.

So in this case you can do `cd vendor/stb/SRC && make` and that will compile the stb libraries and put them in place.

**Comment by causecause1** [comment]
I see. I suppose that is the reason for GLFW missing it as well then ([the issue I made regarding that](https://github.com/odin-lang/Odin/issues/3378).

The linking to the system package is already being done if it fails (both for stb and GLFW), but a makefile would be a nice addition! :)
