### ISSUE TITLE
Error Message for Proc With Multiple Return Values

### ISSUE THREAD

**Issue by CaptainKraft** [odin-lang/Odin#341]
Using the incorrect syntax for a proc with multiple return values: `foo: proc() -> int, int;` gives the output: `Syntax Error: Expected ';'`

Could this error message be improved to provide a suggestion of what the user might be attempting to do?

**Comment by gingerBill** [comment]
The issue with this is that it could be perfectly valid syntax in some cases. So knowing whether you wanted `(int, int)` or not is difficult to know.
