### ISSUE TITLE
Assigning an array to a large array of arrays blows up the compile times on js_wasm32

### ISSUE THREAD

**Issue by thetarnav** [odin-lang/Odin#3410]
code

```odin
package bug

import "core:fmt"

LENGTH :: 10000 // Increasing this, increases the "LLVM API Code Gen" time a lot

main :: proc() {
	vec: [3]f32
	vecs: [LENGTH][3]f32 = vec
	fmt.println(vecs)
}
```

run with `js_wasm32` target

```bash
odin build . -target:js_wasm32 -show-timings
```

timings

```
Total Time        - 66084.860 ms - 100.00%
initialization    -     2.236 ms -   0.00%
parse files       -    21.868 ms -   0.03%
type check        -    69.487 ms -   0.10%
LLVM API Code Gen - 65803.598 ms -  99.57%
wasm-ld           -   187.658 ms -   0.28%
```

odin report
```
	Odin:    dev-2024-04:3b5e515a2
	OS:      Ubuntu 22.04.4 LTS, Linux 6.5.0-27-generic
	CPU:     Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	RAM:     7631 MiB
	Backend: LLVM 17.0.6
```

**Comment by gingerBill** [comment]
Welcome to LLVM, and you are _just_ under the size for triggering the warning too.

**Comment by laytan** [comment]
Does clang have this issue, might be worth looking at the incantation they cast ro make it work faster

**Comment by JesseRMeyer** [comment]
Based on my reading of the compiler (llvm_backend_utility.cpp), only memset with a 0 value can be "compressed" by the front end.  So I suspect this is an area that is well within our reach to improve.

**Comment by Kelimion** [comment]
This should now be fixed. If the size > max simd alignment, Odin will now issue an efficient vectorized loop instead of e.g. 10,000 stores.
