### ISSUE TITLE
Assertion failure when defining a map to a struct inside the same struct

### ISSUE THREAD

**Issue by bogrundtman** [odin-lang/Odin#3427]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 Odin:    dev-2024-04-nightly:6dc9fdb71
        OS:      Windows 10 Home Basic (version: 22H2), build 19045.4170
        CPU:     11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
        RAM:     16057 MiB
        Backend: LLVM 17.0.1

## Expected Behavior
I expect this to compile
```
A :: struct {
    a: map[string]A,
}
```

## Current Behavior
Throws error
`C:\ODIN\Odin\src\types.cpp(4075): Assertion Failure: t->Struct.fields.count == 0 || t->Struct.offsets != nullptr`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.
Step 1. Paste into an empty Odin file and try to compile
```
package bug

A :: struct {
    a: map[string]A,
}
```

**Comment by Kelimion** [comment]
Confirmed, although I feel this should raise an error about a declaration cycle, because `A` can't contain itself.

At the site of the assertion, these are the values: `fields.count: 1, Struct.offsets: 0`.

In contrast, this doesn't assert:
```odin
A :: struct {
    a: map[string]^A,
}
```

**Comment by bogrundtman** [comment]
Forgive me if I am being slow here but I thought a struct could contain a map to itself just like it can contain slices and dynamic arrays of itself. This one compiles at least.

```
A :: struct {
    a1: [dynamic]A,
    a2: []A,
}
```

**Comment by pietype** [comment]
The snippet from the OP compiled fine for me, but these:

```
S :: struct {
    m: map[int]U,
}
U :: struct {
    s: S,
}
```
```
S :: struct {
    m: map[int]U,
}
U :: union {
    S,
}
```

cause the same error:

```
src/types.cpp(4075): Assertion Failure: `t->Struct.fields.count == 0 || t->Struct.offsets != nullptr`
Illegal instruction: 4
```

**Comment by gingerBill** [comment]
This is effectively the same bug as we had with `#soa` not too long ago. But this one is simpler to fix as the internal layout is the same always for any `map`, compared to `#soa` arrays.
