### ISSUE TITLE
text/table uses bytes instead of runes for length

### ISSUE THREAD

**Issue by Feoramund** [odin-lang/Odin#3432]
## Context
The `text/table` library is using `len` where `utf8.rune_count` would probably be more appropriate. See the following program and its output.

```odin
package main

import "core:os"
import "core:text/table"

main :: proc() {
    t: table.Table
    table.init(&t)
    table.caption(&t, "Tɛst")
    table.row(&t, "Hellope!")
    table.row(&t, "Hɛllope!")

    stdout := os.stream_from_handle(os.stdout)
    table.write_ascii_table(stdout, &t)
}
```

The `ɛ` is a two-byte UTF-8 rune here.

## Result
```
+---------+
|  Tɛst  |
+---------+
|Hellope! |
|Hɛllope!|
+---------+
```

## Expected
```
+--------+
|  Tɛst  |
+--------+
|Hellope!|
|Hɛllope!|
+--------+
```

**Comment by gingerBill** [comment]
The procedure name is written very clearly in that it only supports ASCII and not UTF-8 (unicode). We just need to add a unicode one too.

**Comment by oskarnp** [comment]
> The procedure name is written very clearly in that it only supports ASCII and not UTF-8 (unicode). We just need to add a unicode one too.

It makes sense to redefine "ascii" here as the delimiter characters used (`+`, `-`, `|`) for the table itself and not for the actual strings provided by the user. Considering that the package also supports Markdown and HTML tables, user probably expects utf-8 strings there, too.

This was an oversight on my part.

**Comment by oskarnp** [comment]
@Feoramund Technically, rune count is also not correct as it assumes glyphs or graphemes are only represented by a single code point (Rune in Odin is a single code point.)

This breaks with your PR for example:

```odin
package main

import "core:os"
import "core:text/table"

main :: proc() {
	t: table.Table
	table.init(&t)
	table.caption(&t, "Tést")
	table.row(&t, "Hellope!")
	table.row(&t, "Hɛllope!")

	stdout := os.stream_from_handle(os.stdout)
	table.write_ascii_table(stdout, &t)
}
```

Output:

```
+--------+
| Tést  |
+--------+
|Hellope!|
|Hɛllope!|
+--------+
```

Because é is two code points (e + ́)

So is this really worth addressing?

**Comment by Feoramund** [comment]
> So is this really worth addressing?

Yes.
