### ISSUE TITLE
Segfault when compiling `ols` in debug mode

### ISSUE THREAD

**Issue by Feoramund** [odin-lang/Odin#3445]
## Context

As of [ols](https://github.com/DanielGavin/ols) commit `81c84f9683a40d60c0d1ae347c175d9205d186f8`, it is causing a segmentation fault when compiling with the following command: `odin build src -debug -collection:src=src`

	Odin:    dev-2024-04:a61ae7c86
	OS:      Arch Linux, Linux 6.8.5-arch1-1
	CPU:     12th Gen Intel(R) Core(TM) i7-12700K
	RAM:     31916 MiB
	Backend: LLVM 14.0.6

## lldb output
```
* thread #1, name = 'odin', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x0)
    frame #0: 0x00005555557e5cd6 odin`lb_debug_type_internal(m=0x00007fff6cae5510, type=0x00007fff6d0ea480) at llvm_backend_debug.cpp:743:3
   740 		}
   741 	
   742 		case Type_Map: {
-> 743 			Type *bt = base_type(type->Map.debug_metadata_type);
   744 			GB_ASSERT(bt->kind == Type_Struct);
   745 	
   746 			return lb_debug_struct(m, type, bt, make_string_c(type_to_string(type, temporary_allocator())), nullptr, nullptr, 0);
```

I investigated the debugger, and it seems to be consistently failing on a type whose key is a string and value is the `Symbol` struct (so `map[string]Symbol`, presumably). `debug_metadata_type` was 0 at the point of failure. I'm not familiar enough with the internals of the Odin compiler to investigate much further. Attempts to isolate `map[string]Symbol` and related structs outside of `ols` led to no issues with compilation.

**Comment by harold-b** [comment]
Was going to report this also. It is present on macOS as well.

Odin report:
```bash
        Odin:    dev-2024-04:9bbe26f80
        OS:      macOS Sonoma 14.4 (build: 23E214, kernel: 23.4.0)
        CPU:     ARM64
        RAM:     65536 MiB
        Backend: LLVM 14.0.6
```

ols commit: [81c84f9683a40d60c0d1ae347c175d9205d186f8](https://github.com/DanielGavin/ols/tree/81c84f9683a40d60c0d1ae347c175d9205d186f8)

I believe it's happened with some different commits from both ols and Odin, however.

**Comment by harold-b** [comment]
Investigated a bit more. Looks like there's situations were types with nested maps don't have their `debug_metadata_type` resolved in `init_map_internal_debug_types` before it get's accessed in `lb_debug_type_internal()`

Here's a single file repro:

`odin build map_bug.odin -file -debug`

```odin
package main

import "core:fmt"

Indexer :: struct {
	index:            []MemoryIndex,
}

indexer: Indexer

MemoryIndex :: struct {
	collection:        SymbolCollection,
}

SymbolCollection :: struct {
	packages:       map[string]SymbolPackage,
}

SymbolPackage :: struct {
	symbols:      map[string]Symbol,
}

Symbol :: struct {
	uri:       string,
}


main :: proc() {
    fmt.printfln( "%v", len(indexer.index)  )
}```

**Comment by Feoramund** [comment]
I can confirm that the single file listed above causes the same segfault.

**Comment by gingerBill** [comment]
I'm going to fix this. It's my fault.
