### ISSUE TITLE
using NOT on a bit_set type causes a cpp panic

### ISSUE THREAD

**Issue by blob1807** [odin-lang/Odin#3463]
## Context

Odin:    dev-2024-04:caa8863c9
OS:      Windows 11 Home Basic (version: 23H2), build 22631.3447
CPU:     AMD Ryzen 7 6800HS with Radeon Graphics
RAM:     15608 MiB
Backend: LLVM 17.0.1

## Current Behavior

When trying to NOT a bit_set type it'll produce a cpp panic.

### Steps to Reproduce

mini repo
```odin
import "core:fmt"
main :: proc {
    Enum :: enum{None, Some}
    BS :: bit_set[Enum]
    j := ~BS
    fmt.println(j)
}
```

### Failure Logs
```
main.main
lb_emit_conv: src -> dst
Not Identical typeid != bit_set[Enum]
Not Identical typeid != bit_set[Enum]
Not Identical 7ff7da4bb5c8 != 28f1b1434d0
Not Identical 7ff7da4bb5c8 != 28f1b1434d0
C:\odin_git\src\llvm_backend_expr.cpp(2324): Panic: Invalid type conversion: 'typeid' to 'bit_set[Enum]' for procedure 'main.main'
```

**Comment by gingerBill** [comment]
Firstly, that code was not even valid that you gave. 
Secondly, this has now been fixed.
