### ISSUE TITLE
-json-errors reports blank error message

### ISSUE THREAD

**Issue by Feoramund** [odin-lang/Odin#3481]
## Context

For the following erroneous program, Odin reports a second, blank error message on the same line.

```odin
package main

main :: proc() {
	a
}
```

```json
{
	"error_count": 2,
	"errors": [
		{
			"type": "error",
			"pos": {
				"file": "/tmp/odin-error/main.odin",
				"offset": 32,
				"line": 4,
				"column": 2,
				"end_column": 3
			},
			"msgs": [
				"Undeclared name: a"
			]
		},
		{
			"type": "error",
			"pos": {
				"file": "/tmp/odin-error/main.odin",
				"offset": 32,
				"line": 4,
				"column": 2,
				"end_column": 2
			},
			"msgs": [
			]
		}
	]
}
```

	Odin:    dev-2024-04:e3d41f0a9
	OS:      Arch Linux, Linux 6.8.7-arch1-1
	CPU:     12th Gen Intel(R) Core(TM) i7-12700K
	RAM:     31916 MiB
	Backend: LLVM 14.0.6

**Comment by gingerBill** [comment]
Latest commit?

**Comment by Feoramund** [comment]
Commit e3d41f0a9ed106a0f0342fe8b166790965beb1b2. Made sure to re-build. Still occurring.

**Comment by Feoramund** [comment]
I did some stack tracing on this one. The 2nd error is arising for the regular console output code path too, but the `len` check in the following block hides it from any form of output.

https://github.com/odin-lang/Odin/blob/8fd318ea7a76b75974c834bb9d329958c81ce652/src/error.cpp#L783-L787

It seems to be an incidental happenstance that errors with blank messages are skipped over in the regular version, and the `json_errors()` version has merely revealed the oddity of this occurring. I'm assuming the blank 2nd error is the true error here and not that the JSON version lacks a guard against this.
