### ISSUE TITLE
Invalid argument to polymorphic variadic procedure in overload group fails assertion

### ISSUE THREAD

**Issue by Feoramund** [odin-lang/Odin#3519]
## Context

I discovered this bug after making a typo with an `append` parameter. It's a regression caused by the fix I introduced in commit ebfbe4d26031bde4e91ba489102d60fe6959173f. I narrowed the reproduction case down to a few lines. Calling `x2` works; it's when you call `x` with an invalid type to `a` that it fails.

### Program
```odin
package main

x1 :: proc(a: string) {}
x2 :: proc(a: ^$T/[dynamic]$E, args: ..E) {}
x :: proc {x1, x2}

main :: proc() {
    x(0)
}
```

	Odin:    dev-2024-04:5c1201fa4
	OS:      Arch Linux, Linux 6.8.7-arch1-2
	CPU:     12th Gen Intel(R) Core(TM) i7-12700K
	RAM:     31916 MiB
	Backend: LLVM 14.0.6

### Current Behavior
```
src/error.cpp(59): Assertion Failure: `global_error_collector.curr_error_value_set.load() == true` Possible race condition in error handling system, please report this with an issue
```

### Previous Behavior
```
/tmp/error/main.odin(8:5) Error: Ambiguous call to a polymorphic variadic procedure with no variadic input proc(^$T/[dynamic]$E, ..$E)
	x(0)
	^~~^
	Given argument types: (untyped integer)
Did you mean to use one of the following:
	main.x1 :: proc(a: string)                     at /tmp/error/main.odin(3:1)
	main.x2 :: proc(a: ^$T/[dynamic]$E, args: ..E) at /tmp/error/main.odin(4:1)
```

**Comment by Feoramund** [comment]
This looks to be happening because the error reporting system treats token positions as the way to determine duplicate errors, and this test case is raising two errors on the same token position, which causes the `curr_error_value` error to clear before it's done adding lines, if I understand everything correctly.

This is because it's using `error` then `error_line`. `error` pushes the token position, which clears the current value, then `error_line` expects that value to be there via `error_out_va` and `get_error_value`.

**Comment by gingerBill** [comment]
Fixed
