### ISSUE TITLE
Compiler not using file-local shadow of procedure name

### ISSUE THREAD

**Issue by JoshuaManton** [odin-lang/Odin#352]
## Context

* Operating System: Windows 10
* Odin version/Commit: 3a31444656dcd6f24c2909e2b72a0099a066353b

## Expected Behavior

I would either expect a namespace collision or for my file-scope proc `print` to be called

## Current Behavior

It calls the `print` in `fmt`

### Steps to Reproduce

Run the following code:

```
package test

using import "core:fmt"

print :: proc(str: string) {
}

main :: proc() {
	print("Henlo, World!");
}
```

**Comment by Kelimion** [comment]
```cpp
package test

import "core:fmt"

print :: proc(str: string) {
}

main :: proc() {
	using fmt;
	print("Henlo, World!");
}
```
Same if `using` is used locally instead of at file scope, although in this case it is expected that it should do so. `-vet` says nothing of this shadowing in either version.
