### ISSUE TITLE
Improved project repository

### ISSUE THREAD

**Issue by Footmade** [odin-lang/Odin#357]
### The issue
[This repository](https://github.com/odin-lang/odin-libs) needs to be made more visible. It can't be found on the main site (**odin-lang.org**) and, while it can be found [here](https://github.com/odin-lang) it can't be found [here](https://github.com/odin-lang/Odin) which is the github page that the _main site_ links to.

### The solution
Make this repo more visible! I think it's good to show that there is already more to the language than just the language.

### Additional suggestions
Is there some way to include a wish list that can get updated and maintained, not necessarily by you? I don't mean feature requests, but things like user applications, productivity programs and other software that people would like to see made in Odin. A complement to such a list could be a list of other projects people are currently working on, or want to work on, that for some reason aren't up on the previously mentioned repository?

**Comment by ThisDrunkDane** [comment]
> Additional suggestions Is there some way to include a wish list that can get updated and  maintained, not necessarily by you? I don't mean feature requests, but  things like user applications, productivity programs and other software  that people would like to see made in Odin. A complement to such a list  could be a list of other projects people are currently working on, or  want to work on, that for some reason aren't up on the previously  mentioned repository?

This seems more like something that should be on the forum over on HMN and not in the repo.

**Comment by gingerBill** [comment]
I agree with @ThisDrunkDane that it is probably better to just add to the HMN page rather than this repo. Which is what I have now done.
