### ISSUE TITLE
Default value of enum variable is always zero instead of first enum value

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#359]
## Context

```go
main :: proc() {
  using Mode :: enum {
    FIRST = 1,
    SECOND,
    THIRD,
  }

  m: Mode;
  fmt.printf("m is %v; should be %v\n", int(m), int(Mode.FIRST));  // m is 0; should be 1.
}
```

* Operating System: Win x64
* Odin version/Commit: 1fd677b42e33cf0407e204830df656fc1a931df5

## Expected Behavior

I was expecting the default value of enums to be the first value in the enum.

## Current Behavior

The default value is always zero.

**Comment by gingerBill** [comment]
All default values are the zero value (nil) for all types. 

So this is expected behaviour, even if it seems weird.

**Comment by Tetralux** [comment]
How would you suggest I write this instead?

As a sidenote, `m := min(Mode)` also produces zero. 🤔

**Comment by gingerBill** [comment]
I have fixed `min` and `max` for enums now.

**Comment by Tetralux** [comment]
That was quick! xD

**Comment by ThisDrunkDane** [comment]
@Tetralux Generally I would define the `0` member of an enum to an 'invalid' or 'error' state. So then `0` is a known value and you could check for it downstream to know that you have not initialized the enums variable.

**Comment by hasen-mtic** [comment]
The compiler could require an enum to have something with the value 0 otherwise it refuses to compile.

Although that would only be needed if the compiler needs to ensure than an enum value is always valid.

**Comment by hasenj** [comment]
The compiler could require an enum to have something with the value 0 otherwise it refuses to compile.

Although that would only be needed if the compiler needs to ensure than an enum value is always valid.
