### ISSUE TITLE
Invalid dynamic array creation doesn't compile error

### ISSUE THREAD

**Issue by mattt-b** [odin-lang/Odin#362]
## Context

* Operating System: Linux
* Odin version/Commit: Master - 1fd677b42e33cf0407e204830df656fc1a931df5

## Expected Behavior

Compiler error

## Current Behavior

Code compiles and then errors in opt

### Steps to Reproduce

```
package main

main :: proc() {
    // opt: file-name.ll: error: expected value token
    //   %14 = getelementptr inbounds [3 x i64], [3 x i64]* @".dacl$-7f3ee79cd6\06\00", i32 0, i32 0
    foo := [dynamic]int{1, 2, 3};
    foo : [dynamic]int = {1, 2, 3};
}
```

**Comment by gingerBill** [comment]
I cannot seem to replicate this nor understand how that is possible.

**Comment by gingerBill** [comment]
This is now fixed!
