### ISSUE TITLE
Unsigned Int Overflow cannot be relied on for constant-folded literals

### ISSUE THREAD

**Issue by NHDaly** [odin-lang/Odin#3645]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System & Odin Version: MacOS 12.7.5, odin `dev-2024-05-nightly:2250eb3e7`
* Please paste `odin report` output:

        Odin:    dev-2024-05-nightly:2250eb3e7
        OS:      macOS Monterey 12.7.2 (build: 21H1222, kernel: 21.6.0)
        CPU:     Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
        RAM:     16384 MiB
        Backend: LLVM 17.0.6
 
## Expected Behavior

From this section in the documentation ([Integer overflow #](https://odin-lang.org/docs/overview/#integer-overflow)):

> For unsigned integers, the operations +, -, *, and << are computed modulo 2^n, where n is the bit width of the unsigned integer’s type. In a sense, these unsigned integer operations discard the high bits upon overflow, and programs may rely on “wrap around”.

I would expect therefore to be able to add any unsigned ints and always get a valid unsigned int, even if it has wrapped around.

## Current Behavior

Based on the above documentation, I expect that "I can rely on wrap around." However, I find that when checking this basic wrap around with literal constants, I get the following compiler error:
```odin
@(test)
test_int_angle_basic_arithmetic :: proc (t: ^testing.T) {
    v := 0x8000000000000000 + 0x8000000000000000
    testing.expect(t, v == 0x0)
}
```
```
$ odin test src
src/test.odin(20:10) Error: Cannot convert numeric value '18446744073709551616' from '0x8000000000000000 + 0x8000000000000000' to 'int' from 'untyped integer' 
        v := 0x8000000000000000 + 0x8000000000000000 
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ 
        The maximum value that can be represented by 'int' is '9223372036854775807' 
```
The compiler is currently ("helpfully") preventing me from overflowing, even though in this case this is actually what I _want._ (I am attempting to use u64 values as angles, to get automatic hardware modulos.)

## Failure Information (for bugs)

This appears to be a bug, since the constant-folding error message does not respect what the documentation says about developers being able to "rely on" the wrap around.

### Steps to Reproduce

Constant-folding causes the above error. Adding runtime values does not, as in:
```odin
test_add_const :: proc (x : u64) -> u64 {
    return x + 0x8000000000000000
}

@(test)
test_int_angle_basic_arithmetic :: proc (t: ^testing.T) {
    v := test_add_const(0x8000000000000000)
    testing.expect(t, v == 0x0)
}
```

**Comment by gingerBill** [comment]
So the compile-time constant value system operators differently than the run-time values. 
```
0x8000000000000000 + 0x8000000000000000
```
is is just a constant untyped integer. However the default integer type is `int`, which is not representable by that constant on any platform we support. 

This is not a bug.


The point about 2's complement behaviour and wrapping-on-overflow is purely about runtime operations.
