### ISSUE TITLE
parsing json fails with single digit integer keys or negative float values

### ISSUE THREAD

**Issue by kevinw** [odin-lang/Odin#366]
## Expected Behavior

Parsing JSON like this:

```
{"a": 5}
```

or this:

```
{"b": -33.0}
```

shouldn't fail or give the wrong values.

## Current Behavior

The `core/encoding/json.parse` will fail parsing.

### Steps to Reproduce

See [json_parse_bug.odin](https://github.com/kevinw/odin_bugs/blob/master/json_parse_bug.odin) for a set of test cases.

**Comment by Kelimion** [comment]
Merged.
