### ISSUE TITLE
I beleave there is a bug in the compiler when you pass a specific odin file and the file doesn't existe. 

### ISSUE THREAD

**Issue by joaocarvalhoopen** [odin-lang/Odin#3660]
## Context

Hello,

I beleave I have found a small bug in the compiler,

If I call the Odin compiler with the following line:

```
odin build ./examples_odin/ex_concatenate_matrices/concatenation_matrices.odin -file -out:./examples_odin/ex_concatenate_matrices/concatenate_matrices.exe --debug
```

It sillently do it's stuff, more specifically doesn't do nothing and don't give an error message saing that the file  concatenation_matrices.odin does not existe inside the directory 

```
./examples_odin/ex_concatenate_matrices/concatenation_matrices.odin
```

But the directory exists, 
and there is a file with a similar name but not equal name in that directory.

I believe that it should give an error that the file doesn't exist in the diretory.

The file that existes is :

concatenate_matrices.odin

The diretory tree structure is:

proj_dir
.....examples_odin
...............................ex_concatenate_matrices
...........................................................................concatenate_matrices.odin

I'm inside proj_dir and compiling a single file with the wrong name (I have mistaclangly write the wrong name)

But I beleave that it should give me an error.

-----

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System & Odin Version:
Open Suse Tumbleweed Rooling release.

odin version dev-2024-05:c091b0d06

* Please paste `odin report` output:

It does not give a output report, that the problem :-)

## Expected Behavior

 
```
The file ./examples_odin/ex_concatenate_matrices/concatenation_matrices.odin does not exist !!!
```

Please describe the behavior you are expecting

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Create the directories and execute the Odin compiler with the following command:

```
odin build ./examples_odin/ex_concatenate_matrices/concatenation_matrices.odin -file -out:./examples_odin/ex_concatenate_matrices/concatenate_matrices.exe --debug
```

### Failure Logs

There aren't any.

Thank you,

Best regards,
João Carvalho

**Comment by Feoramund** [comment]
I'm able to reproduce this with the latest commit.
