### ISSUE TITLE
The ability to load files as binary data

### ISSUE THREAD

**Issue by vassvik** [odin-lang/Odin#368]
**Is your feature request related to a problem? Please describe.**
Easily embed binary resources into the compiled executable without an explicit resource file.

Useful for embedding shaders, icons, images, text files, etc.

**Describe the solution you'd like**
Something like a `#load` directive which would map to a slice or array of bytes.

**Comment by ThisDrunkDane** [comment]
On windows we already have the ability to use the resource capabilities in the linker, is there a way to do this in the Linux linkers?

**Comment by gingerBill** [comment]
```
data: []byte = #load("path/to/file.txt");
```

Would `#load` or `#load_file` be a better term?

**Comment by baines** [comment]
@ThisDrunkDane You can transform arbitrary binary files into object files on linux with:    
`ld -r -b binary -z noexecstack input.bin -o output.o`    
and then link `output.o` with the rest of your stuff. It will contain 3 symbols for the data:
```
0000000000000000 D _binary_input_bin_start
0000000000000200 D _binary_input_bin_end
0000000000000200 A _binary_input_bin_size
```

**Comment by gingerBill** [comment]
I have added a basic `#load` directive. This is still a test.

**Comment by hasenj** [comment]
For games you might know specific files you want.

For a web application server example, you often want to embed an entire directory.

**Comment by ThisDrunkDane** [comment]
For web servers I usually don't want to embed the entire directory inside the executable, they're more often than not dynamic content from what I've experienced.

**Comment by hasenj** [comment]
I do this in my go project (using [packr](https://github.com/gobuffalo/packr))

The dynamic content stays on the server (stuff uploaded by users, etc).

**Comment by vassvik** [comment]
Should this be closed? 

The current #load is working out quite nicely for me, and makes it trivial to embed all sorts of data.
