### ISSUE TITLE
strings.make_builder not using given allocator

### ISSUE THREAD

**Issue by Zilarrezko** [odin-lang/Odin#371]
## Context

* Odin version/Commit: 0.9.2

https://github.com/odin-lang/Odin/blob/master/core/strings/builder.odin#L11
(core/strings/builder.odin line 11)

**Comment by bpunsky** [comment]
Easy fix 😄
```go
make_builder :: proc(allocator := context.allocator) -> Builder {
	return Builder{make([dynamic]byte, allocator)};
}```

**Comment by gingerBill** [comment]
Please make a PR!

**Comment by Zilarrezko** [comment]
Request staged, close if/when accepted.
