### ISSUE TITLE
[proposal] #overload directive for procedure overloading

### ISSUE THREAD

**Issue by hasenj** [odin-lang/Odin#372]
**Is your feature request related to a problem? Please describe.**
Most languages provide only one way for extending functionality: dynamic dispatch via virtual functions.

In Go, it's `interface`, in Swift, it's `protocol`.

Rust provides something called `Traits`, and while I'm not aware of its details, it seems a bit complicated.

I think it would be nice if Odin had something that could do something similar to what interfaces in Go are used for, with the condition that:

1) It should not incur _any_ runtime overhead

2) Should not introduce a new type of procedures into the language (e.g. no 'method')

Odin has parametrically polymorphic (parapoly) procedures, which I think can be a good starting point.

If Odin would allow overloading procedures defined by another package, then it would probably satisfy most use cases for virtual functions, without having virtual functions.

**Describe the solution you'd like**

I want to define a parapoly procedure that calls another 'procedure' which might not be parapoly, but can be overloaded for many types.

Take this example. The code might be broken, but bear with me and assume the logic is correct:

```odin
package byte_readers;

// based on https://golang.org/src/bytes/buffer.go?s=6885:6944#L192

MIN_READ :: 512

read_all_bytes_from_reader(reader: $T, output: ^[dynamic]byte) -> (int, os.Errno) {
    total_read := 0
    for {
        new_start := grow_buffer(output, MIN_READ); // definition left as exercise; grows capacity by length + MIN_READ without altering length
        read_count, err := reader_read(reader, output[new_start:]); // assumes procedure `reader_read(T, []byte) -> os.Errno` is defined for T
        if read_count > 0 do total_read += read_count;
        if is_eof(err) do return total_read, 0;
        if err do return total_read, err;
        output = output[:new_start+read_count];
    }
}

```

This parapoly procedure would only work if `reader_read` has an overload for type T.

Within the package that defines this procedure, this is not a problem: I can define several `reader_read_xxx` procedures and then define the overloads explicitly in one go:

    reader_read :: proc{reader_read_xxx1, reader_read_xxx2, reader_read_xxx3}

This is however not great for external users of this package.

I would like it if it was possible to provide an overload for a procedure even if it was defined in a different package.

Say I have my custom type. Again the code is probably broken, but just assume the logic works:

```odin

package virtual_fs;

Virtual_File :: struct {
    content: []byte,
    cursor: int,
}

read_from_file(file: ^Virtual_File, output: []byte) -> (int, os.Errno) {
    last := file.cursor + len(output)
    err := 0
    if file.cursor + len(output) >= len(file.content) {
        last = len(file.content);
        err = EOF;
    }
    read_count := last - file.cursor;
    copy(file.content[file.cursor:last], output);
    return read_count, err;
}
```

I want to be able to say this:

    #overload byte_readers.read_from with virtual_fs.read_from_file

This should fail to compile if there's already another overload with the same parameters.

**Additional context**

I tried to adhere to keeping procedure overloading explicit and keeping the language simple.

Although I suspect this might be complicated to implement in the compiler.

One negative point it might introduce is packages are no longer self-contained: a package can be 'extended' in a sense by another package that imports it, but in a sense, this is already the case. Because you a procedure that accepts polymorphic parameters can also accept types that come from other packages that it itself isn't aware of.

**Comment by gingerBill** [comment]
```
One negative point it might introduce is packages are no longer self-contained: a package can be 'extended' in a sense by another package that imports it, but in a sense, this is already the case. Because you a procedure that accepts polymorphic parameters can also accept types that come from other packages that it itself isn't aware of.
```

This is the biggest reason to not implement the proposal. I don't want the ability to "extend" a package with more entities. Polymorphic entities don't "extend" more entities but rather just become specializations of that entity. 

There are a little too many weird edge cases with this approach in conjunction with polymorphic procedures.

A simpler approach may be to just allow procedure groups in procedure groups.
```
foo :: proc{a, b, c};
bar :: proc(d, foo};
```

**Comment by gingerBill** [comment]
Aside: this is a really well written proposal!
