### ISSUE TITLE
Redeclaration of 'iso8601_to_time_utc' in this scope

### ISSUE THREAD

**Issue by cbouwense** [odin-lang/Odin#3763]
## Context

I downloaded the Odin Windows release build, and am running on Windows 10.
Odin version: `dev-2024-06-nightly:f745a1c47`

```
Odin:    dev-2024-06-nightly:f745a1c47
OS:      Windows 10 Home Basic (version: 22H2), build 19045.4412
CPU:     AMD Ryzen 7 5800X 8-Core Processor
RAM:     32689 MiB
Backend: LLVM 17.0.1
```

## Expected Behavior

The compiler to run without errors.

## Current Behavior

Upon attempting to compile a trivial program, I get the following errors:
```
Error: Redeclaration of 'iso8601_to_components' in this scope
        at C:/Users/bouwe/ThirdParty/Odin/core/time/iso8061.odin(43:1)
        iso8601_to_components :: proc(iso_datetime: string) -> (res: dt. ...
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Write a hello world
2. run `odin run .`

## Fix

It appears that there is an extra file called `iso8061.odin` in `core/time/iso8061.odin`. Deleting this file solves the problem.

**Comment by Feoramund** [comment]
In what way have you been updating Odin? That file was renamed from `iso8061.odin` to `iso8601.odin`, and I see no duplicate file in the master branch.

**Comment by cbouwense** [comment]
I downloaded [odin-windows-amd64-dev-2024-06.zip](https://github.com/odin-lang/Odin/releases/download/dev-2024-06/odin-windows-amd64-dev-2024-06.zip)

**Comment by Feoramund** [comment]
I see a `core/time/iso8061.odin` file in the zip but no `iso8601.odin`.

**Comment by Kelimion** [comment]
> I downloaded [odin-windows-amd64-dev-2024-06.zip](https://github.com/odin-lang/Odin/releases/download/dev-2024-06/odin-windows-amd64-dev-2024-06.zip)

The release ZIP predates the typo fix by a few days. So the issue such as it is has been fixed for 9 days now.
