### ISSUE TITLE
Randomly getting "Access violation executing location 0x0000000000000000."

### ISSUE THREAD

**Issue by cmdl-dev** [odin-lang/Odin#3802]
## Context

Today I randomly got an error using the vendor library raylib. When I try to load the image using `LoadTexture`. I feel like there is an issue with my version of odin, not sure how to resolve it. 

Repo: [https://github.com/cmdl-dev/odin_raylib_issue](https://github.com/cmdl-dev/odin_raylib_issue)
![ImageOfError](https://github.com/odin-lang/Odin/assets/11858501/7d9fbf6d-b895-48a6-bebd-329be521df2d)

I have already:
 - rebooted my PC.
 - pulled the latest version of odin and rebuilt the compiler

### Operating System & Odin Version:
 Windows 11 Pro - Odin version dev-2024-06:8eafd9eb8
### Please paste `odin report` output:
        Odin:    dev-2024-06:8eafd9eb8
        OS:      Windows 11 Professional (version: 23H2), build 22631.3737
        CPU:     AMD Ryzen 9 5950X 16-Core Processor
        RAM:     32653 MiB
        Backend: LLVM 17.0.1

## Expected Behavior
The output should display "File is  32" 32 being the width of the image.
Please describe the behavior you are expecting

## Current Behavior

What is the current behavior?
When running in debugger I am getting an excepting being throw with the text:
`Getting Unhandled exception at 0x0000000000000000 in test.exe: 0xC0000005: Access violation executing location 0x0000000000000000. `
In the console I am getting:
`INFO: FILEIO: [grass.png] File loaded successfully
INFO: IMAGE: Data loaded successfully (32x32 | R8G8B8A8 | 1 mipmaps)`

**Comment by Kelimion** [comment]
This isn't a bug in raylib or Odin.

You need to set up the Window to be able to upload a texture to the GPU, that's why it crashes after loading the image file. Raylib tries to upload it to GPU through OpenGL handles that haven't been set up yet.

**Comment by Kelimion** [comment]
No. This code didn't work last week or any other week. Don't  insult out intelligence to get help by pretending it's an Odin issue that wasn't there last week, and giving us a dead link.

I already said what's wrong with the example code: You're not initializing the window. But because you chose to bullshit us instead of asking for help honestly, that's the last help you'll get.

**Comment by Kelimion** [comment]
![image](https://github.com/odin-lang/Odin/assets/194614/e5b8b5dc-847b-4ab6-8da0-39c1550372c1)
So, deleting this as well. Consider yourself banned.
