### ISSUE TITLE
odin build segfaults on self-referencing union

### ISSUE THREAD

**Issue by jist99** [odin-lang/Odin#3803]
## Context

Operating System & Odin Version:
* MacOS (M1) 
* odin version dev-2024-05:7dc1f114b  

Please paste `odin report` output:
```
Odin:    dev-2024-05:7dc1f114b
OS:      macOS Sonoma 14.4.1 (build: 23F79, kernel: 23.4.0)
CPU:     Apple M1
RAM:     16384 MiB
Backend: LLVM 14.0.6
```

## Expected Behavior

When I define a self-referencing union the odin compiler should properly create the union or give an appropriate error.

## Current Behavior

The odin compiler segfaults

### Steps to Reproduce

1. Paste the code:
```
package main

FL_Item :: union($T: typeid) {
    T,
    ^FL_Item(T)
}

main :: proc() {}
```
2. run `odin build filename.odin -file`

### Failure Logs

N/A

**Comment by Kelimion** [comment]
Hits this assert in checker.cpp.

![image](https://github.com/odin-lang/Odin/assets/194614/dd7a77ee-af94-4485-82ca-836f0c99b96c)
