### ISSUE TITLE
'#complete' directive on switch not mentioned in new docs

### ISSUE THREAD

**Issue by hasenj** [odin-lang/Odin#381]
Odin supports tagged unions and switching on the type such that the compiler reports an error if the switch doesn't cover all the possible cases, using the `#complete` directive.

However, this is not mentioned on the new overview documentation page:

https://odin-lang.org/docs/overview/#unions

This is an important feature, and not being mentioned on the overview can easily lead people to believe Odin does not have this feature.

**Comment by ThisDrunkDane** [comment]
Since we now have a repo who odin-lang.org, please open the issue there :-) (https://github.com/odin-lang/odin-lang.org-source)
