### ISSUE TITLE
Safe access to nullable 'objects'

### ISSUE THREAD

**Issue by hasenj** [odin-lang/Odin#382]
**Is your feature request related to a problem? Please describe.**

A lot of people perceive 'nil' to be a problem. Adding separate nullable and non-nullable types is generally a bad idea that will open a deep rabbit hole for little or no benefit.

Instead, I propose that providing mechanism to easily avoiding common pitfalls might be a better solution to appease people's worries.

**Describe the solution you'd like**

Given a pointer to a struct:

    Something :: struct { ....... }

    // inside the body of some procedure:
    ref: ^Something

Generally if you're not sure whether ref is nil or not, you should check:

    if ref != nil {
        // do your thing
    }

Some languages offer a syntax sugar:

    a := ref?.field

Which is equivalent to:

    a : <type of ref.field>
    if ref != nil do a = ref.field

**Additional context**

This feature makes a lot more sense if languages where you can call 'methods' on objects, and where it's a common mistake to call a method on a null reference.

Since Odin does not have this general pattern, the feature might be less useful.

However, it can be useful when the struct has function pointers

     ref?.fnPtr(....)
     // equivalent to:
     if ref != nil do ref.fnPtr(....)

**Potential problems**

One potential problem with this syntax sugar is repeating the boolean check over and over if abused:

    a := ref?.fieldA
    ref?.fnPtr(....)
    x?.y = ref?.z

Another problem is you are silently ignoring potentially logic errors, and generally encouraging sloppiness.

**Comment by gingerBill** [comment]
I am personally not a huge fan of this for a lot of reasons, mainly because it hides a lot of branches. I don't think Odin needs this feature.
