### ISSUE TITLE
Visual Studio debugging experience

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#385]
## Context

In Visual Studio:

- [ ] VS shows the opening line instead of the closing line for the closing brace of a control block, such as a `for` loop, etc.

- [ ] VS does not highlight the correct part of the current line. It highlights the whitespace before the text on the line, or the incorrect part of the line when executing a second expression/statement on the same line, such as the `i += 1` part of a `for` loop, or condition of a `for` loop, etc.

I think there's another, but I forget what it is right now; will add if I remember.

* Operating System: Win x64 (Obviously.)
* Odin version/Commit: b0dd3ac599fedfea18a9d574620fb105a1c33f4f
* Visual Studio 2019. (Also happened in 2017 IIRC.)

## Expected Behavior

The current statement (or even just the correct line) should be highlighted correctly.

## Current Behavior

The current statement is either only partially highlighted, or it is just incorrect.
Whitespace should not be highlighted.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Compile a program with Odin and the `-debug` switch.
2. Call `devenv.exe` on the resulting executable.
3. Set a breakpoint in the Odin source file and step through it, noting the highlighting of whitespace and incorrect highlighting as you go.

**Comment by ThisDrunkDane** [comment]
This is so old by now that I'm just gonna close it, if still a problem, open new issue
