### ISSUE TITLE
Mistakes in Odin/vendor/sdl2/sdl_pixels.odin

### ISSUE THREAD

**Issue by RichardFevrier** [odin-lang/Odin#3860]
Currently implementing SDL3 I noticed some little mistakes in the current SDL2 implem (too busy to make a PR sorry).

`PIXELTYPE_ARRAYF3  :: 11` -> `PIXELTYPE_ARRAYF32  :: 11`

`ARRAYORDER_ABG  :: 6` -> `ARRAYORDER_ABGR :: 6`

Odin lang is a banger btw! 🤩

Edit:
[Here](https://github.com/libsdl-org/SDL/blob/25f9ed87ff6947d9576fc9d79dee0784e638ac58/include/SDL_pixels.h#L64) and [here](https://github.com/libsdl-org/SDL/blob/25f9ed87ff6947d9576fc9d79dee0784e638ac58/include/SDL_pixels.h#L100) are the original imple if you want to check by yourself.

**Comment by Feoramund** [comment]
Thank you for the direct source links on this. Those are always very helpful.
