### ISSUE TITLE
Procedure assignment with tenary when

### ISSUE THREAD

**Issue by JesseRMeyer** [odin-lang/Odin#3863]
As discussed in Discord.  Feature request for this to work.

```odin
empty_proc :: #force_inline proc(..any) {}
end_mark :: empty_proc when !TRACY_ENABLE else proc(ctx: zone_context) {
  zone_end(ctx)
}
```

emits the compiler error: `Error: 'empty_proc when !TRACY_ENABLE else proc(ctx: zone_context) {...}' is not a compile-time known constant`

Which is currently not considered a bug but could be made to work.  The current behavior is unintuitive and feels needlessly restrictive.

**Comment by Feoramund** [comment]
Wouldn't `@(disabled=TRACY_DISABLE)` suit your needs here?

**Comment by JesseRMeyer** [comment]
Sometimes it does but `disabled` still compiles & checks the code.  Though more important imo is how procs are handled in when statements more broadly.

**Comment by laytan** [comment]
This should work now: https://github.com/odin-lang/Odin/commits/master/
