### ISSUE TITLE
ERROR: No `llvm-config` command found.

### ISSUE THREAD

**Issue by matthewelmer** [odin-lang/Odin#3876]
## Context

- Operating System: Fedora 40
- Odin version: Unable to build
- Please paste `odin report` output: N/A

## Expected Behavior

Odin builds after running `make` from within the cloned repo.

## Current Behavior

```
matt@fedora:~/repos/Odin$ make
./build_odin.sh debug
ERROR: No llvm-config command found. Set LLVM_CONFIG to proceed.
make: *** [Makefile:10: debug] Error 1
```

## Failure Information

It seems as though Odin's build process depends on `llvm-config`, which doesn't ship with package manager versions of LLVM. Looks like you have to build LLVM from source in order to have access to that binary.

### Steps to Reproduce

1. On a Fedora machine without LLVM, install LLVM by running `sudo dnf install llvm`
2. Clone the Odin repo
3. `cd /path/to/Odin`
4. `make`

### Failure Logs

N/A

**Comment by laytan** [comment]
Fedora puts that into a separate package `llvm-devel`

**Comment by matthewelmer** [comment]
> Fedora puts that into a separate package `llvm-devel`

This fixes the original issue. Now we just need to update [the install guide](https://odin-lang.org/docs/install/) with this information.

**Comment by matthewelmer** [comment]
I opened a PR on [the website's repo](https://github.com/odin-lang/odin-lang.org/pull/219). Please let me know if I made any mistakes or if I missed anything.

**Comment by laytan** [comment]
Seems to all be resolved now and ready to close this
