### ISSUE TITLE
`using` bug

### ISSUE THREAD

**Issue by bpunsky** [odin-lang/Odin#390]
https://i.imgur.com/3ixylk5.png

Possibly linked to #62? But unlikely as that's a runtime issue.

`memory` should be defined, bug goes away if you put `vm.` or `hart.` before `memory`

I dunno why the issue template didn't come up, maybe because GitHub made me sign in before making the issue it got confused

**Comment by gingerBill** [comment]
Is this still a bug? @bpunsky

**Comment by ThisDrunkDane** [comment]
I'll close this, please re-open @bpunsky if this is still an issue
