### ISSUE TITLE
"Thread Queue Full!" seems back on macos when processing a lot of files

### ISSUE THREAD

**Issue by DamienPetrilli** [odin-lang/Odin#3906]
## Context

It seems the issue described in [Package with large amount of Objective-C wrapper procs exhibits slow compilation time](https://github.com/odin-lang/Odin/issues/3343#issuecomment-2024868685) is back.

* Operating System : `macos 14.5 (23F79)`
* Odin Version: `master`
* Please paste `odin report` output

```bash
Odin:    dev-2024-07:1770e3a
OS:      macOS Sonoma 14.5 (build: 23F79, kernel: 23.5.0)
CPU:     Apple M1 Pro
RAM:     32768 MiB
Backend: LLVM 18.1.8
```

## Expected Behavior

The darwodin project should compile when including a lot of obj-c bindings.

## Current Behavior

The compiler crashes with a threading error unless you use the `lite` option.

### Steps to Reproduce

Copy / Paste the code bellow to setup and trigger the issue on macOS.

```bash
   ROOT_FOLDER="$HOME/THREAD_QUEUE_BUG"
   ODIN_FOLDER="$ROOT_FOLDER/Odin"
   DARWODIN_FOLDER="$ROOT_FOLDER/darwodin"
   
   ODIN_URL="https://github.com/odin-lang/Odin.git"
   DARWODIN_URL="https://github.com/harold-b/darwodin.git"
   mkdir -p $ROOT_FOLDER
   git clone --depth 1 $ODIN_URL $ODIN_FOLDER
   
   cd $ODIN_FOLDER
   ./build_odin.sh
   export PATH="$ODIN_FOLDER:$PATH"
   
   git clone --depth 1 $DARWODIN_URL $DARWODIN_FOLDER
   
   cd $DARWODIN_FOLDER
   ./build
```

### Failure Logs

```bash
+ odin build samples/metal_app -collection:samples=./samples -collection:root=./darwodin-macos -out:.bin/main -o:speed -thread-count:10 -target:darwin_arm64
src/thread_pool.cpp(68): Assertion Failure: `new_head != tail` Thread Queue Full!
./build: line 93: 87452 Trace/BPT trap: 5       odin build samples/metal_app "-collection:samples=./samples" "-collection:root=${root}" "-out:${out_dir}/main" ${debug_args[@]} -thread-count:${thread_count} -target:darwin_arm64 ${extra_args[@]}
Build Time: 1.409 seconds
```

**Comment by harold-b** [comment]
I meant to submit a PR before addressing this, but didn't get around to it. In the meantime, as a workaround if you self-compile Odin, you can [increase the thread pool capacity on this line](https://github.com/odin-lang/Odin/blob/master/src/threading.cpp#L562):
~`t->capacity = 1 << 14; // must be a power of 2`~ -> `t->capacity = 1 << 16; // must be a power of 2`

**Comment by laytan** [comment]
Fixed in https://github.com/odin-lang/Odin/pull/3919 so this can be closed
