### ISSUE TITLE
Error running ./build.sh on macOS mojave

### ISSUE THREAD

**Issue by m-henderson** [odin-lang/Odin#392]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOS Mojave
* Odin version/Commit: https://github.com/odin-lang/Odin/commit/b0dd3ac599fedfea18a9d574620fb105a1c33f4f

## Expected Behavior

I should have a nice, fresh, beautiful, smart, lovely built Odin compiler. 

## Current Behavior

I am getting a fatal error that states 'elfin.h' file not found
<img width="809" alt="Screen Shot 2019-06-11 at 10 22 27 PM" src="https://user-images.githubusercontent.com/16070192/59321401-786efa00-8c97-11e9-9fbf-e12bf354efbb.png">

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. make sure you are on a machine that has macOS mojave installed. 
2. go through the getting started guide [here](https://odin-lang.org/docs/install/) for Mac. 
3. the getting started guide will make sure that you have llvm installed and that Xcode CLI tools are installed. 
4. follow through with the setup and notices that you get the error when you build.sh

### Extra
I noticed some people online talking about how macOS mojave changed their headers. This [link ](https://github.com/neovim/neovim/issues/9050)may be helpful but simply doing a google search of the error will bring up some good results that could give a lead as to what the problem is. 

<img width="714" alt="Screen Shot 2019-06-13 at 6 27 12 AM" src="https://user-images.githubusercontent.com/16070192/59428990-5c0cb380-8da4-11e9-84b9-1ea98a0dabd3.png">

**Comment by m-henderson** [comment]
Here is some more info that will help resolve the issue:
 https://github.com/neovim/neovim/issues/9050#issuecomment-424417456https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojavehttps://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes

**Comment by themeshpotato** [comment]
I ran into the same error, but it looks like it had something to do with installing llvm through homebrew.

I followed this answer and installed the command line tools with open `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

After that I was able to build Odin. Hope this helps :)

**Comment by hazeycode** [comment]
You need to install headers see https://github.com/odin-lang/odin-lang.org/pull/3

**Comment by hasenj** [comment]
$ open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

**Comment by ThisDrunkDane** [comment]
Do note, that the package you're mentioning has been removed in macOS catalina, however if you install the latest LLVM from homebrew (9.0.0) it seems to find the new headers fine.

**Comment by ThisDrunkDane** [comment]
This is not an Odin bug but rather changes something with older clang versions on new macOS
