### ISSUE TITLE
Unexpected operator precedence with cast operator

### ISSUE THREAD

**Issue by flysand7** [odin-lang/Odin#3927]
The compiler has wrong (unexpected) precedence rules for the `cast(T)E` unary operator which seems inconsistent with `(T)(E)`-style cast.

---

`$ odin report` output:

* Odin:    dev-2024-07:65dab3a3b
* OS:      Windows 10 Unknown Edition (00000064) (version: 22H2), build 19045.4651
* CPU:     12th Gen Intel(R) Core(TM) i5-12500H
* RAM:     16088 MiB
* Backend: LLVM 18.1.8

---

To reproduce the error compile the following code:

```
package bug

import "core:fmt"

B :: struct {
	field: int,
}

A :: struct {
	handle: rawptr, // Mimics the way os-specific file info works in os2 package
}

main :: proc() {
	a: A
	a.handle = &B { 3 }
	fmt.pritnln(cast(^B)(a.handle).field)
}
```

Cmpiler prints the following error:

```
flysand7@~/Odin(core-process)$ odin run examples/bug -debug
C:/Users/flysand7/Odin/examples/bug/bug.odin(17:22) Error: '(a.handle)' of type 'rawptr' has no field 'field' 
        fmt.println(cast(^B)(a.handle).field) 
                            ^~~~~~~~~^ 
```

suggesting that the compiler has created an AST structure in which the selector operator is executed before the cast operation, which would be consistent with "right-first" rule for unary operator parsing.

However in this case the cast expression is parenthesized, which leads me to expect that it should be done before the selector operator, and if the `cast` keyword is removed (Leading to `(T)(E)`-style cast operation) the compiler parses the code as expected.

**Comment by gingerBill** [comment]
This is not a bug and actually the correct behaviour AND extremely consistent.

* `cast(T)x` acts an unary operator
* `(T)(x)` acts as a call


Using `cast` means you want the thing on the right of it to be casted, using the call syntax means you want the thing in the parentheses to be casted.

**Comment by flysand7** [comment]
Makes sense now
