### ISSUE TITLE
X11 bindings broken/annoying

### ISSUE THREAD

**Issue by Lord-Hellgrim** [odin-lang/Odin#3944]
## Context

While playing with the X11 bindings I encountered a fatal bug and a couple annoyances.

* Operating System & Odin Version:

Odin:    dev-2024-07:7237f9c9f
	OS:      Linux Mint 21.3, Linux 5.15.0-113-generic
	CPU:     Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
	RAM:     7637 MiB
	Backend: LLVM 14.0.0

## Expected Behavior

I am expecting the X11.DefaultDepth() function to return an i32

## Current Behavior

It immediately segfaults my program.

## Failure Information (for bugs)

The bindings to the C function are wrong. DefaultDepth is a macro that takes two arguments in C (*Display, int).

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Just call the function. It reliably segfaults my process.

### Failure Logs

Please include any relevant log snippets or files here.
Segmentation fault (core dumped)

Additionally, some odin xlib functions return the wrong type of integer. This is annoying since you have to cast them to feed them into their respective function. The one example I encountered:

black: uint = X11.BlackPixel(display, screen) 
white: uint = X11.WhitePixel(display, screen)
but the function X11.CreateSimpleWindow() takes two "colors" as the final arguments and those colors are int, not uint. I think they should match.

**Comment by anarchydespot** [comment]
Just to add some further context to future readers about the segment at the bottom:
It's not so much that it would be preferable for them to match, but that the `X11.CreateSimpleWindow` binding **is wrong**.

```c
extern Window XCreateSimpleWindow(
    Display*		/* display */,
    Window		/* parent */,
    int			/* x */,
    int			/* y */,
    unsigned int	/* width */,
    unsigned int	/* height */,
    unsigned int	/* border_width */,
    unsigned long	/* border */,
    unsigned long	/* background */
);
```
It takes unsigned long for border and background, but the vendor api defines the procedure as
```odin
CreateSimpleWindow :: proc(
  display:   ^Display,
  parent:    Window,
  x:         i32,
  y:         i32,
  width:     u32,
  height:    u32,
  bordersz:  u32,
  border:    int,
  bg:        int,
) -> Window ---
```

**Comment by flysand7** [comment]
`int` in Odin is the same thing as `long` on linux.
Similarly `uint` is the same as `unsigned long`.

So the issue is that the signedness is wrong?

**Comment by anarchydespot** [comment]
Yes, it should be uint. It's not the width that's wrong, but it's "signedness."
