### ISSUE TITLE
Incorrect case selected in switch on Maybe(^T)

### ISSUE THREAD

**Issue by diocletiann** [odin-lang/Odin#3947]
Repro:
```
package main
import "core:fmt"

foo :: struct {
	x: int,
}

main :: proc() {
	maybe_foo: Maybe(^foo)

	switch v in maybe_foo {
	case ^foo:
		fmt.println("is foo")
	case nil:
		fmt.println("is nil")
	}
}
```
```
is foo
```

Odin:    dev-2024-07:7237f9c9f
OS:      macOS Sonoma 14.3.1 (build: 23D60, kernel: 23.3.0)
CPU:     Apple M1 Max
RAM:     32768 MiB
Backend: LLVM 18.1.8

**Comment by Kelimion** [comment]
Replicated on latest commit on Windows 10.

**Comment by laytan** [comment]
Probably has to do with `Maybe(^T)` internally not being a union at all, or at least internally doesn't have a tag. So this is probably an edge case not handled in the codegen for this switch.
