### ISSUE TITLE
@(rodata) doesn't work with slices of unions

### ISSUE THREAD

**Issue by kranasAngel** [odin-lang/Odin#3968]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System & Odin Version:
 Odin:    dev-2024-07:da80c5119                                                                                                                                 
        OS:      macOS Sonoma 14.4.1 (build: 23E224, kernel: 23.4.0)                                                                                                   
        CPU:     Apple M3                                                                                                                                              
        RAM:     8192 MiB                                                                                                                                              
        Backend: LLVM 14.0.6  

## Expected Behavior

Given a union, if you try to make a slice of that union and mark it as  @(rodata), the program should compile. This is because the constituent parts compile successfully. (Marking a slice as @(rodata) works, and marking a union as @(rodata) works, so hopefully marking a slice of a union should work as well?) 

## Current Behavior

Instead the compiler complains that the compiler complains that it must have readonly initialization. 

## Steps to Reproduce

```c++
DamageEffect :: struct { val : i32,}
ApplyStatusEffect :: struct {to_apply : enum {GUARD,FRAIL,WEAK,MIGHT}}
TargetEffect :: struct {target : enum i32 { SELF, TARGET, RANDOM }}

SkillEffect :: union { DamageEffect, ApplyStatusEffect, TargetEffect};

// WORKS -> Readonly Slice
@(rodata)
DAMAGE_EFFECT := []DamageEffect {DamageEffect{20}} 

// WORKS -> readonly union
@(rodata)
SKILL_EFFECT : SkillEffect = DamageEffect{20}

// FAILS -> readonly union slice
@(rodata)
ATTACK_EFFECT := []SkillEffect {DamageEffect{20}} 

// FAILS -> readonly union slice
@(rodata)
GUARD_EFFECT := []SkillEffect {TargetEffect{.SELF},ApplyStatusEffect{.GUARD}}  
```

### Failure Logs

```
Error: Variables declared with @(rodata) must have constant initialization                              
        ATTACK_EFFECT := []SkillEffect {DamageEffect{20}}                                                                                                              
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ 
Error: Variables declared with @(rodata) must have constant initialization                              
        ... FECT := []SkillEffect {TargetEffect{.SELF},ApplyStatusEffect{.G ...                                                                                        
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ... 
```

**Comment by kranasAngel** [comment]
```c++
SkillEffect :: struct {
    type : enum u8 {DAMAGE, APPLY_STATUS, TARGET},
    using data : struct #raw_union {
        damage_val : struct {val : i32},
        status_val : struct {status : enum u8 {GUARD,FRAIL}},
        target_val : struct {target : enum u8 {SELF, TARGET, RANDOM}},
    }
}

#assert(size_of(SkillEffect) <= size_of(u64));

//WORKS
@(rodata)
EMPTY_EFFECT := SkillEffect {type = .DAMAGE}

// DOES NOT WORK                                                                                                                                                       
@(rodata)
SINGLE_EFFECT := SkillEffect {type = .DAMAGE, data = {damage_val = {20}}}

```
Tried using a raw_union in place of a tagged union and got the same error:
```
Error: Variables declared with @(rodata) must have constant initialization                              
        ... FECT := SkillEffect {type = .DAMAGE, data = {damage_val = {20}} ...                                                                                        
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ... 
```

**Comment by gingerBill** [comment]
So this isn't a bug and more to do with unions themselves. Unions in the general case might not be able to be initialized at compile time.

**Comment by kranasAngel** [comment]
Gotcha, if it's not a bug then I'll go ahead and close the issue then. Good to know and makes sense (I'll use an enumerated struct for these sorts of cases going forward then)

Thanks!
