### ISSUE TITLE
GuiTextInputBox and GuiTextBox from vendor/raylib/raygui.odin immediately crash my program.

### ISSUE THREAD

**Issue by scheinheiser** [odin-lang/Odin#3984]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System & Odin Version:
OS: MacOS Sonoma Ver 14.5
Odin Version: dev-2024-07:23ca27f40

* Please paste `odin report` output:
```
Odin:    dev-2024-07:23ca27f40
OS:      macOS Sonoma 14.5 (build: 23F79, kernel: 23.5.0)
CPU:     Apple M2
RAM:     8192 MiB
Backend: LLVM 14.0.6
```

## Expected Behavior

I should be able to input text into the textbox and be able to extract the input so that the user can interact with the program.

## Current Behavior

My program immediately crashes with a bus error - `zsh: bus error  odin run .`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open an odin file.
2. Paste this code inside of it:
```
package main

import rl "vendor:raylib"

main :: proc() {
	rl.InitWindow(500, 500, "testing crash")
	defer rl.CloseWindow()

	temp := true
	test : cstring = ""

	for !(rl.WindowShouldClose()) {
		rl.BeginDrawing()
			rl.GuiTextInputBox(bounds=rl.Rectangle{100, 120, 300, 130},
							   title="Important",
							   message="Enter text below:",
							   buttons="#112#Enter;#113#Cancel",
							   text=test,
							   textMaxSize=10,
							   secretViewActive=&temp)
		rl.EndDrawing()
	}
}
```

3. Run the code with `odin run .`
4. Click on the text box and input any text.

**Comment by laytan** [comment]
Not a bug, the text argument needs a dynamically allocated buffer to write what you type into, `tesr : cstring = ""` is a literal in the readonly data section, additionally textMaxSixe must be the length of that data buffer, making it 10 here causes raylib to write outside the buffer and crash.

A proper buffer would be something like:
```odin
buf: [1024]byte
rl.GuiTextInputBox(..., text=cstring(&buf), textMaxSize=1024, ...)
```

**Comment by scheinheiser** [comment]
Thanks for the explanation. When I run the example code with your fixes, it doesn't compile though - I get this error:
```
Error: Cannot cast '&buf' as 'cstring' from '^[1024]u8'
	text=cstring(&buf),
	             ^~~^
```
