### ISSUE TITLE
Possibly conflicting error messages

### ISSUE THREAD

**Issue by fwgreen** [odin-lang/Odin#4005]
Is the first error in conflict with the suggested remedy to the second error?
```odin
package main

main :: proc() {
    for &idx in 0..<9 {
        for idx < 5 {
            idx += 1
        }
    }
}
```
```
/Users/francois/SoftwareProjects/Odin/Hello/main.odin(4:10) Error: The index variable 'idx' cannot be made addressable 
        for &idx in 0..<9 { 
             ^ 
 
/Users/francois/SoftwareProjects/Odin/Hello/main.odin(6:13) Error: Cannot assign to 'idx' 
        idx += 1 
        ^~^ 
        for &idx in 0..<9 { 
             ^~^ 
            'idx' is immutable, declare it as '&idx' to make it mutable 
```
Apple M1
macOS 14.5     
odin version dev-2024-07-nightly:b4ca044

**Comment by laytan** [comment]
Yes, this is basically the same underlying issue as https://github.com/odin-lang/Odin/issues/3943 where the type checker sees `&idx`, determines it is invalid so emits an error + ignores it, so it keeps going with checking as if it's `for idx in 0..<9 {`
