### ISSUE TITLE
linux llvm18 not found (even though the lib is in the folder)

### ISSUE THREAD

**Issue by skrshe** [odin-lang/Odin#4019]
## Context
after downloading and unzipping 2024-08 
and running odin inside fails

* Operating System & Odin Version:
ubuntu 24.04
odin 2024-08

* Please paste `odin report` output:

`odin: error while loading shared libraries: libLLVM-18.so.18.1: cannot open shared object file: No such file or directory`

## Expected Behavior
odin finds llvm 18 and functions

## Current Behavior
`$ odin` prints nothing.

`$ odin version` prints:
`odin: error while loading shared libraries: libLLVM-18.so.18.1: cannot open shared object file: No such file or directory`

## Failure Information (for bugs)
cant find `libLLVM-18.so.18.1`

### Steps to Reproduce
Download the 2024-08 odin release
unzip it 
cd into dist folder
run odin with ./odin

### Failure Logs
`odin: error while loading shared libraries: libLLVM-18.so.18.1: cannot open shared object file: No such file or directory`

**Comment by Kelimion** [comment]
Renaming `libLLVM-18.so.1` to `libLLVM-18.so.18.1` should work.

**Comment by skrshe** [comment]
that does yes.
thanks again @Kelimion for saving my odin codin' :joy_cat:
