### ISSUE TITLE
Enumerated Arrays

### ISSUE THREAD

**Issue by vassvik** [odin-lang/Odin#402]
## Motivation

Consider a situation where you want to read a few known files from disk. You might define an enum acting like a named indices for each file type:
```
File :: enum {
	File1,
	File2,
	File3,
}
``` 
which can then be used to create an associated array of filenames:
```
filenames := [len(File)]string{
	"File1.txt",
	"File2.txt",
	"File3.txt",
}
```
which can then be used to read the contents of each file:
```
files_data: [len(File)]string;
for file in File {
	files_data[file], _ := os.read_entire_file(filenames[file]);
}
```

Similarly, you might want to define some more data associated with each file:
```
files_desc := [len(File)]string{
	"This is File1",
	"This is File2",
	"This is File3",
}
```

There are a few pitfalls/issues here:

 - The enum values must be contiguous and start from 0 to be able to be used as indices. 
 - Any integer value can be used to index the associated data. 
 - You cannot use Implicit Selector Expressions to index, i.e. you need to write `File.File1` instead of `.File1` while indexing.

## Proposal: 

A fourth array type which acts like a specialization of arrays using an enum type for the length:
```
File :: enum {
	File1 = 1, // Skipped 0
	File2 = 2,
	File4 = 4, // Skipped 3
	File5 = 5,
}

filenames := [File]string{
	"File1.txt",
	"File2.txt",
	"File4.txt",
	"File5.txt",
}

files_data: [File]string;
for file in File {
	files_data[file], _ := os.read_entire_file(filenames[file]); // !
}

files_desc := [File]string{
	"This is File1",
	"This is File2",
	"This is File4",
	"This is File5",
}

fmt.println(files_desc[.File1]);  // Works
fmt.println(files_desc[File(1)]); // Works
fmt.println(files_desc[1]);       // Error: Not a File enum
fmt.println(files_desc[File(0)]); // Error: Cannot convert to File
```

**Comment by gingerBill** [comment]
Regarding this proposal, what ought to be the memory layout for the enumerated array?
```
size_of([File]string) == size_of([max(File) - min(File) - 1]string)
```

And why stop at enumerated arrays? Why not allow for ranged arrays too?
```
[4 .. 7]int
[4..<8]int
```

**Comment by vassvik** [comment]
I don't think the memory layout needs to be contiguous in input space since it's essentially a static map. So
```
size_of([File]T) == len(File)*size_of(T)
```
Would be what I would expect. 

Extending to ranged arrays seems useful as well, or even sparse setd, but there's no type/syntax for that right now is there.

**Comment by gingerBill** [comment]
The problem with that approach is how do you map values at runtime to the index?

**Comment by vassvik** [comment]
O(logN) if stored in array, or different if stored in a hash map internally? Perfect hash?

One of my use cases would be to use it on a subset of OpenGL constants, where I create a custom enum using the subset (for example, all the texture internal formats), where constants might be quite far apart due to historic reasons, so using min and max might be too expensive as a general case.

**Comment by gingerBill** [comment]
The difference is that this is now a static hash map rather than a enumerated _array_.

**Comment by vassvik** [comment]
Yes, but we're talking about how it's implemented behind the scenes now aren't we? Is there a difference in the front end?

**Comment by gingerBill** [comment]
I'm not a huge fan of a type requiring it look up its run-time type information for it to work. Especially if the user wants to disable run time type information.

**Comment by gingerBill** [comment]
Implemented!
