### ISSUE TITLE
Aliasing import with same name crashes compiler

### ISSUE THREAD

**Issue by karl-zylinski** [odin-lang/Odin#4026]
## Context

        Odin:    dev-2024-07:505dec7b1
        OS:      Windows 10 Professional (version: 22H2), build 19045.4651
        CPU:     Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz
        RAM:     32674 MiB
        Backend: LLVM 18.1.8

## Expected Behavior

```
import rl "vendor:raylib"

rl :: rl

// plus: make sure you use something from `rl` in some other file that does not import `rl`.
```

This code should either not compile or make `rl` globally findable in whole package

If you do this:

```
import "vendor:raylib"

rl :: raylib
```
Then it compiles and you can use `rl` everywhere in the package

## Current Behavior

```
import rl "vendor:raylib"

rl :: rl

// plus: make sure you use something from `rl` in some other file that does not import `rl`.
```

Silently crashes compiler
### Steps to Reproduce

Put this code in a file
```
import rl "vendor:raylib"

rl :: rl

// plus: make sure you use something from `rl` in some other file that does not import `rl`.
```

The compiler crashes when you build.

**Comment by Kelimion** [comment]
I can't replicate it. For me this compiles and briefly opens a window.
```odin
package fireworks

import rl "vendor:raylib"

rl :: rl

main :: proc() {
	rl.InitWindow(1, 1, "Foo")
}
```
```
        Odin:    dev-2024-08:030220eb2
        OS:      Windows 10 Professional (version: 22H2), build 19045.4529
        CPU:     AMD Ryzen 9 5950X 16-Core Processor
        RAM:     65444 MiB
        Backend: LLVM 18.1.8
```

**Comment by Kelimion** [comment]
Can you run Odin under a debugger and find out where it crashes, as well as provide a repro that crashes for you if the above doesn't?

**Comment by karl-zylinski** [comment]
@Kelimion I realized that the usage of `rl` must be in a separate file that does not import `rl`, i.e. it tries to use the global alias.

**Comment by Kelimion** [comment]
That I can replicate. 👍

**Comment by Kelimion** [comment]
![image](https://github.com/user-attachments/assets/225410ef-4e69-4eb0-bbe7-a0654783b9e8)

**Comment by Kelimion** [comment]
`import_scope` is a nullptr
![image](https://github.com/user-attachments/assets/03a7bf93-e0bc-45cc-bbef-ba1fdb1ed2c1)

**Comment by Kelimion** [comment]
Created a fix for it, but @gingerBill may want to properly fix it by letting `rl :: rl` alias the import across the package, or complaining at the `rl :: rl` site, or some such.

**Comment by karl-zylinski** [comment]
@Kelimion 

As 
```
import "vendor:raylib"
rl :: raylib
```
works fine, I think some people might use to to create "package global imports". So with that in mind maybe `rl ::  rl` would be nice if it worked the same way.

**Comment by Kelimion** [comment]
If you follow the new error message's advice and import it locally to that file, the problem does go away.
```cpp
W:/Odin/bug/foo.odin(5:2) Error: 'rl' is not imported in this file, 'InitWindow' is unavailable 
	rl.InitWindow(1, 1, "Foo") 
```

And for symmetry, @karl-zylinski, if you `foo := foo` in a procedure to alias a procedure param, it's only available *there*, so I personally don't know if it should alias it to the entire package. That said, `Error :: pkg.Error` is available package-wide, so there are two competing ways to handle it.

**Comment by Kelimion** [comment]
But anyway, I've found the proximate cause. It's up to the BDFL how he wants to handle it.

**Comment by gingerBill** [comment]
I do not want to allow `rl :: rl` because I wanted to keep imports local to the file. And also that makes very little sense too in the same scope. It's aliasing... itself?!

At least with `x := x` is just doing normal shadowing in a different scope.

**Comment by karl-zylinski** [comment]
@gingerBill 

> I do not want to allow `rl :: rl` because I wanted to keep imports local to the file. And also that makes very little sense too in the same scope. It's aliasing... itself?!

I see, keep in mind that
```
import "vendor:raylib"
rl :: raylib
```
currently works for making rl appear globally in the whole package and that I wouldn't be surprised if people are using this. It was just the redefinition with same name that crashed.
