### ISSUE TITLE
#force_inline Allowed When Passing In Procedure As Parameter

### ISSUE THREAD

**Issue by dozn** [odin-lang/Odin#4039]
## Context
Shouldn't be able to use `#force_inline` here:
```f#
package main
import "core:strings"
main :: proc() {
    strings.fields_proc("", #force_inline proc(_: rune) -> bool {return true})
}
```
Odin:    dev-2024-08:4b9ca3952
OS:      Windows 11 Professional (version: 23H2), build 22631.3958
CPU:     AMD Ryzen 7 3700X 8-Core Processor
RAM:     65489 MiB
Backend: LLVM 18.1.8

## Expected Behavior
Error received.

## Current Behavior
Compiles and runs.

**Comment by laytan** [comment]
I don't think it makes sense to not allow this. In this snippet LLVM could decide to inline `strings.fields_proc` and then it would see and use the `#force_inline` on the procedure you gave and inline that too.

You could even do `#force_inline strings.fields_proc("", #force_inline proc(_: rune) -> bool {})` and both of these will be respected.
