### ISSUE TITLE
Issue in Linux with os.write_entire_file( ), sillently capping at exactly 1 GB.

### ISSUE THREAD

**Issue by joaocarvalhoopen** [odin-lang/Odin#4042]
Issue in Linux with os.write_entire_file( ), sillently capping at exactly 1 GB.

Hello,

NOTE: The person that found this Issue was the member Yawning. Thank you Yawning!
             And other worked to help me on this issue, thank you to all.

In Odin, Linux version the max size of the file that can be written with os.write_entire_file( ) is 1 GB = 1024 * 1024 * 1024 = 1_073_741_824 bytes.

The os.read_entire_file( ) doesn't have this limitation, because it loops inside it, and read it in several big chunks.

This is specific to Linux and doesn't occur on Windows.

The source code file is the: 
https://github.com/odin-lang/Odin/blob/f328929939dfb761eaa4b087938c79f86ebe698a/core/os/os_linux.odin#L620

at line 592 of ```core/os/os_linux.odin```

```
// If you read or write more than `SSIZE_MAX` bytes, result is implementation defined (probably an error).
// `SSIZE_MAX` is also implementation defined but usually the max of a `ssize_t` which is `max(int)` in Odin.
// In practice a read/write call would probably never read/write these big buffers all at once,
// which is why the number of bytes is returned and why there are procs that will call this in a
// loop for you.
// We set a max of 1GB to keep alignment and to be safe.
@(private)
MAX_RW :: 1 << 30

```

and then in write of the file in:

```

write :: proc(fd: Handle, data: []byte) -> (int, Error) {
   if len(data) == 0 {
      return 0, nil
   }

   to_write := min(uint(len(data)), MAX_RW)  <----  HERE IT SHOULD LOOP :-)

   bytes_written := unix.sys_write(int(fd), raw_data(data), to_write)
   if bytes_written < 0 {
      return -1, _get_errno(bytes_written)
   }
   return bytes_written, nil
}

```
 
It should loop and write in big chuncks.

The read_entire_file( ) doesn't have the same problem because it loops but the write doesn't loop.
And should loop.

I tested on Linux OpenSuse Tumbleweed, with Odin compiler version:

odin version dev-2024-05:c091b0d06

And the problem exists in it and I believe that it exists in the current Linux version on the Github repository of Odin.

```
write_entire_file :: proc(name: string, data: []byte, truncate := true) -> (success: bool) {
	return write_entire_file_or_err(name, data, truncate) == nil
}

@(require_results)
write_entire_file_or_err :: proc(name: string, data: []byte, truncate := true) -> Error {
	flags: int = O_WRONLY|O_CREATE
	if truncate {
		flags |= O_TRUNC
	}

	mode: int = 0
	when OS == .Linux || OS == .Darwin {
		// NOTE(justasd): 644 (owner read, write; group read; others read)
		mode = S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH
	}

	fd := open(name, flags, mode) or_return
	defer close(fd)

	_ = write(fd, data) or_return       <------ HERE IS THE PROBLEM
	return nil
}
```

The os.read_entire_file( ) uses :

```
bytes_read := read_full(fd, data) or_return

```

and read_full( )  loops and read in chunks!

Thank you,

Best regards,
João Carvalho

**Comment by zen3ger** [comment]
This also seem to affect `core:os/os2` as the `_file_stream_proc` impl for Linux skips the iteration as well.
