### ISSUE TITLE
Compiler not erroring when modifying the elements of a @(rodata) array or slice

### ISSUE THREAD

**Issue by IllusionMan1212** [odin-lang/Odin#4048]
## Context

* Operating System & Odin Version:
 ```
        Odin:    dev-2024-08:7f17d4eb7
        OS:      Ubuntu 24.04 LTS, Linux 6.8.0-36-generic
        CPU:     12th Gen Intel(R) Core(TM) i7-12700H
        RAM:     15693 MiB
        Backend: LLVM 18.1.3
```

## Expected Behavior
~~Expected the compiler not to crash and to show a `Assignment to variable 'global' marked as @(rodata) is not allowed` error as it does when reassigning the array or slice.~~
Expected the compiler to show a `Assignment to variable 'global' marked as @(rodata) is not allowed` error

## Current Behavior
~~Compiler segfaults silently.~~
A faulty program is compiled successfully.

### Steps to Reproduce
```odin
package main

@(rodata)
global := [3]string{
    0 = "zero",
    1 = "one",
    2 = "two",
}

main :: proc() {
    global[1] = "eleven"
}
```

### Failure Logs
N/A

**Comment by laytan** [comment]
Does the compiler segfault or the program it compiled? A compiler segfault would be a bug, a segfault of the program wouldn't (may be a feature request/enhancement). Error messages for assigning to @(rodata) are best effort and not intended to cover every single case.

**Comment by IllusionMan1212** [comment]
The program segfaults and not the compiler. I must've ran `odin run` instead of `odin build`
An error to prevent changing rodata arrays would be nice if possible.
