### ISSUE TITLE
`-vet-tabs` may not work under some circumstances

### ISSUE THREAD

**Issue by Feoramund** [odin-lang/Odin#4076]
```odin
package main

import "core:fmt"

Hello :: enum {
	I_am_tabbed_out,
    I_am_spaced_out,
        I_am_way_spaced_out,
I_am_none_of_these,
}

Struct :: struct {
	tabbed_out: int,
    spaced_out: int,
        way_spaced_out: int,
none_of_it: int,
}

main :: proc() {
	fmt.println(Hello.I_am_none_of_these)
  fmt.println("But I am in violation of the law.") // <-- `-vet-tabs` catches this,
    fmt.println("Me too.")                         // <-- and this.
fmt.println("But not me.")
}
```

I found that `-vet-tabs` does not evaluate enums or structs, and it ignores lines in procedures with no identation at all.

Specific command used here: `odin check bad-vet-tabs.odin -file -vet -strict-style -vet-tabs`

**Comment by gingerBill** [comment]
So this may or may not be a bug because it cannot catch it in all cases generally. It could still be a form of alignment. I'll keep this open if it actually is an issue.

**Comment by gingerBill** [comment]
Loads of improvements have been added to 8ba87e01bd9a26ffd391d2ad69ff0eb6a023d1cf
