### ISSUE TITLE
Cannot pass map into function to be inserted into unless you insert into the map beforehand.

### ISSUE THREAD

**Issue by langmai** [odin-lang/Odin#4086]
## Context

        Odin:    dev-2024-08:d91fa162d
        OS:      Windows 11 Education (version: 23H2), build 22631.4037
        CPU:     Intel(R) Core(TM) i5-14400F
        RAM:     32478 MiB
        Backend: LLVM 18.1.8

## Expected Behavior

```
import "core:fmt"

foo :: proc(val: map[string]i32) {
	val := val
	if "bye" in val {
		fmt.println(val)
		return
	}

	val["bye"] = 2

}

main :: proc() {
	val := make(map[string]i32)
	//val["hello"] = 3
	for true {
		fmt.println("hello")
		foo(val)
	}
}
```
this should insert bye into the map the first interation of the first loop, and then just print val every iteration after that

## Current Behavior

instead we get this output:

hello
hello
hello
hello
hello
hello
hello
hello
hello
C:/Odin/base/runtime/dynamic_map_internal.odin(427:4) panic: unable to insert into a map

Oddly enough uncommenting `//val["hello"] = 3`, makes everything work.

### Steps to Reproduce
Copy and paste:
```
package odin_sublime_template

import "core:fmt"

foo :: proc(val: map[string]i32) {
	val := val
	if "bye" in val {
		fmt.println(val)
		return
	}

	val["bye"] = 2

}

main :: proc() {
	val := make(map[string]i32)
	//val["hello"] = 3
	for true {
		fmt.println("hello")
		foo(val)
	}
}
```

and run `odin run .`

**Comment by laytan** [comment]
This isn't a bug, you are passing the map by value to the procedure.

The `map[K]V` is this struct under the hood:
```odin
Raw_Map :: struct {
	data:      uintptr,
	len:       uintptr,
	allocator: Allocator,
}
``
So this is what you are passing to your procedure.

If you then insert into it this the `data` will be dereferenced and your entry is added there, then it also updates the `len` field. And additionally if the map had to grow it will update `data` to point somewhere else.

Now your outer procedure will not see any of these changes to that internal struct. So you keep printing with the same values.

At some point you will insert into the map and it has to grow, so the data is moved, and your outer procedure will keep using that old reference and crash.

To fix this you just pass the map by pointer `val: ^map[string]i32`.

We might be able to give you an error message in this case though (@gingerBill ?), because you are essentially mutating a parameter, which we do error for in other cases.

**Comment by gingerBill** [comment]
So the question is: what warning/error should we give that would work in all cases? Doing `val := val` on a `map` might have its use cases even if they are pretty much always dangerous. 

Odin isn't a "hand holding language" in certain cases and will allow you to do dangerous things.

**Comment by laytan** [comment]
Ah my bad, I didn't see `val := val` at that point you've already told the compiler to shut up. So yeah, nothing to do here.
