### ISSUE TITLE
core:flags package tries to change permissions of input files defined via os.Handle type

### ISSUE THREAD

**Issue by AllanCochrane** [odin-lang/Odin#4087]
## Context

Running the example Odin program provided by the flags package:

https://github.com/odin-lang/Odin/blob/master/core/flags/example/example.odin

* Operating System & Odin Version:
        Odin:    dev-2024-08:1a16585b1
        OS:      macOS Sonoma 14.5 (build: 23F79, kernel: 23.5.0)
        CPU:     Apple M3 Max
        RAM:     36864 MiB
        Backend: LLVM 18.1.8

## Expected Behavior

A file marked as readonly should not have other permissions changed

For example if I want to _read_  a file (e.g. `/etc/passwd`) the flags package should NOT try to change the permissions of the file

## Current Behavior

```
./argparse_test /etc/passwd -hub 4 -accuracy 6.3
[Open_File_Error#-1] Unable to open file with perms 0o444 in mode 0x0: /etc/passwd

```

## Failure Information (for bugs)

More insidious is if you _do_ have permissions to change the file then something that is marked `rwx` silently gets the permissions changed:

Before:
```
$  ls -lrt foo  
-rwxr-xr-x  1 acochrane  staff  0 Aug 16 09:32 foo
$  ./argparse_test foo -hub 4 -accuracy 6.3
[Parse_Error.Bad_Value] Unable to set `hub` of type Host_Or_Endpoint to true.
$  ls -lrt foo                             
-r--r--r--  1 acochrane  staff  0 Aug 16 09:32 foo
```
 

### Steps to Reproduce

Copy and paste the example flags code from https://github.com/odin-lang/Odin/blob/master/core/flags/example/example.odin then run it with a file that is readable, but not writable and the error above will be shown.

**Comment by Feoramund** [comment]
I am not able to reproduce this on Linux. However, looking at the code for Darwin's `os.open` shows:

https://github.com/odin-lang/Odin/blob/14e207088a3f38959cb4d297e29db691ffcdf152/core/os/os_darwin.odin#L701-L711

Looks like it's forcing a `chmod` if the permissions aren't 0, but it doesn't actually check if the open-mode is `O_CREATE`.

Secondly, the way you are using the flag arguments is incorrect:
```
$  ./argparse_test foo -hub 4 -accuracy 6.3
[Parse_Error.Bad_Value] Unable to set `hub` of type Host_Or_Endpoint to true.
```
This shows you're parsing in Odin style but trying to use Unix style. Odin style is `-hub:4`.
