### ISSUE TITLE
Loop unrolling for constant loop ranges

### ISSUE THREAD

**Issue by vassvik** [odin-lang/Odin#409]
The ability to unroll loops when the range is a constant would complement the recent compile time type check intrinsics to write very compact and specialized parapoly procedures with little overhead. Example with arbitrary syntax:
```
NUM :: 3;
for $i in 0..NUM {
    foo();
}
```
where $i would be consistent with procedure parameter declarations for value constants. `inline for` might be a possible option as well.
More complex example:
```
package main

import "core:fmt"
import "core:intrinsics"

main :: proc() {
    foo :: proc(v: $T) {
        when intrinsics.type_is_array(T) {
            for i in 0..<len(T) { // this is a runtime iteration
                fmt.printf("v[%d] = %v\n", i, v[i]);
            }
        } else {
            fmt.printf("v = %v\n", v);
        }
    }

    foo([3]f32{1,2,3});
    foo(3);
}
```

**Comment by vassvik** [comment]
Or, have this work for a type where the length is known at compile time: ```
inline for v in x {

}
```

**Comment by sci4me** [comment]
Can this be closed now?
