### ISSUE TITLE
bug: `expr != nullptr` in a wrong instantiation of a map

### ISSUE THREAD

**Issue by eightfilms** [odin-lang/Odin#4096]
## Context
```console
code/odin/map-bug
➜ odin report
Where to find more information and get into contact when you encounter a bug:

        Website: https://odin-lang.org
        GitHub:  https://github.com/odin-lang/Odin/issues


Useful information to add to a bug report:

        Odin:    dev-2024-08:b5a612202
        OS:      macOS Sonoma 14.2.1 (build: 23C71, kernel: 23.2.0)
        CPU:     Apple M2 Pro
        RAM:     32768 MiB
        Backend: LLVM 17.0.6
```

## Expected Behavior

Some useful compiler error about wrong usage of map.

## Current Behavior

was editing code midway, left my house and came back to:

```
➜ odin build .
src/checker.cpp(49): Assertion Failure: `expr != nullptr`
zsh: trace trap  odin build .
```

Turns out it was triggered by a wrong instantiation of a map. I wrote something like this before I went out and came back to this bug because i forgot about it and tried building :melting_face: 

```
Storage :: distinct map[]int
```

The fix is to write the above properly, hopefully guided by a compile error, but there was no indication that I missed that out.

### Steps to Reproduce

```console
➜ odin build .
src/checker.cpp(49): Assertion Failure: `expr != nullptr`
zsh: trace trap  odin build .

code/odin/map-bug
➜ cat main.odin
package main

Storage :: distinct map[]int

main :: proc() {
}
code/odin/map-bug
➜ ls
main.odin
```

**Comment by Kelimion** [comment]
![image](https://github.com/user-attachments/assets/137ef7fb-1572-40c6-88c5-a4b0580c07cd)

**Comment by Kelimion** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/dc9a523c-19ca-45b5-a481-c737b533fc92)

**Comment by eightfilms** [comment]
tysm, very based @Kelimion

**Comment by Kelimion** [comment]
No problem. Just pushed a commit to turn `map[]` into "missing type, got newline" instead of '\n' that puts it on the next line.
