### ISSUE TITLE
`or_else` with diverging procedures behaviour inconsistency

### ISSUE THREAD

**Issue by avanspector** [odin-lang/Odin#4099]
## Context

```go
arr := make([dynamic]int, 0) or_else panic("works")      // No error
resize(&arr, 10)             or_else panic("its joever") // Error: 'or_else' does not return a value, value is of type Allocator_Error
```

* Operating System & Odin Version:
Odin:    dev-2024-08:40b8150a2
OS:      Windows 10 Unknown Edition (00000064) (version: 22H2), build 19045.4651
CPU:     Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
RAM:     16253 MiB
Backend: LLVM 18.1.8

## Expected Behavior

No error in both cases

## Current Behavior

The second example evokes an error

**Comment by gingerBill** [comment]
There is absolutely nothing inconsistent here. `or_else` is meant to return a value as an expression. `resize` only returns a single value and thus the entire expression would have no value. That's what the error is saying. 

This is not a bug.
