### ISSUE TITLE
Self-referencing #type proc() declaration crashes compiler in debug mode

### ISSUE THREAD

**Issue by justus2510** [odin-lang/Odin#4105]
## Context
Operating System & Odin Version:
```
Odin:    dev-2024-08:bbb5593f8
OS:      Arch Linux, Linux 6.9.8-arch1-1
CPU:     11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz
RAM:     15790 MiB
Backend: LLVM 18.1.8
```

## Expected Behavior

Same behavior as if without the -debug flag.

## Current Behavior

Passing the -debug flag crashes the compiler.

### Steps to Reproduce

Repro:

```
package main

ProcType :: #type proc() -> ProcType

main :: proc() {
    x: ProcType
}
```

Build command:
```
odin build repro.odin -file -debug
```

**Comment by gingerBill** [comment]
That should be perfectly valid code and I am surprised it fails.

**Comment by Kelimion** [comment]
It passes `odin check` no problem, and you also don't see it if you compile with `-vet -strict-style`, as it complains about `x` being unused.

When building it segfaults.

**Comment by Kelimion** [comment]
![image](https://github.com/user-attachments/assets/d10a697f-5269-4f81-b1d0-9423f18b1e61)

**Comment by gingerBill** [comment]
Oh it's a backend problem. The size of a procedure should never result in an infinite loop. This should be simple enough to fix.
