### ISSUE TITLE
type -> any assignment triggers wrong error message

### ISSUE THREAD

**Issue by karl-zylinski** [odin-lang/Odin#4115]
## Context

        Odin:    dev-2024-08:c5ed7083d
        OS:      Windows 10 Professional (version: 22H2), build 19045.4780
        CPU:     Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz
        RAM:     32674 MiB
        Backend: LLVM 18.1.8

## Expected Behavior

```
generic_proc :: proc($T: typeid) {
    fmt.println(T)
}

generic_proc(f32)
```

The above should tell me that a type cannot be passed into an `any` param.

## Current Behavior

Currently I get this error message:

```
 Error: Cannot assign 'f32' which is a type in procedure argument 
	fmt.println(T) 
```

or perhaps this if @Kelimion has put in his proposed changes, then it'll show this error message:

```
Error: Cannot assign 'f32' — a type — to a procedure argument 
```

Regardless, both these are the wrong error message and makes it sound like you can never pass a type into a `typeid` parameter. There's nothing wrong with the error message, but it's the wrong error message for this situation. It's easy to see this message and learn the totally wrong thing. I had a momentary crisis where I thought it was impossible to pass a type to a `typeid` parameter because of this.

It seems like the check that you are trying to pass a type into `any` should be done earlier in the code hierarchy.

**Comment by Kelimion** [comment]
See also #4116
