### ISSUE TITLE
`bit_field` incorrect initialization without `-opt` > 0

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#413]
```
S :: bit_field {
    i: 8,
    j: 3,
}
```
When initialized like this...
```
s: S;
s.i = a;
s.j = b;
```
.. or like this:
```
s := S{};
s.i = a;
s.j = b;
```
.. the `bit_field` gets _incorrectly_ initialized to `{255, 0}` without `-opt`, and correctly with `-opt=n`
for `n > 0`.

**Comment by ThisDrunkDane** [comment]
@Tetralux is this still the case?

**Comment by ThisDrunkDane** [comment]
`bit_field` has been removed
