### ISSUE TITLE
`os2.temp_allocator_fini` does not free thread local allocators

### ISSUE THREAD

**Issue by Feoramund** [odin-lang/Odin#4131]
Currently, the temporary allocators used by `os2` may leak when used from threads, because they are stored in thread local variables, but `@fini` procs appear to run only on the main thread's closure. I discovered this through using `-sanitize:address` while running the test suite on the new `core:io` test suite I'm working on.

This is not a leak discoverable through the tracking allocator system, because a new `runtime.default_allocator()` is arranged for by `runtime.arena_alloc`.

**Comment by gingerBill** [comment]
I know of this issue, but it's hard to check for because you cannot access each instance of the thread local trivially. I am wondering what is the best approach for this is.

**Comment by Feoramund** [comment]
I had an idea. `core:thread` could have a way to register thread-specific procedures that are called at the end of a thread, as a sort of thread-specific `defer` in order to clean up `@thread_local` state, if this tends to become a more general pattern.
