### ISSUE TITLE
Mutating arrays when passing by value

### ISSUE THREAD

**Issue by eDev03** [odin-lang/Odin#4132]
## Context

* Operating System & Odin Version: Windows 10, Odin dev-2024-08-nightly:8359995
* Please paste `odin report` output:
        Odin:    dev-2024-08-nightly:8359995
        OS:      Windows 10 Home Basic (version: 22H2), build 19045.4780
        CPU:     Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
        RAM:     16318 MiB
        Backend: LLVM 18.1.8

## Expected Behavior

Same behaviour for different sized arrays

## Current Behavior

Some arrays mutate, others remain unchanged

### Steps to Reproduce

Compile and run
```

package main

import "core:fmt"

foo4 :: proc(array: [4]u8) {
	for &value in array do value = 1
}

foo16 :: proc(array: [16]u8) {
	for &value in array do value = 1
}

main :: proc() {
	{
		array: [4]u8 
		foo4(array)
		fmt.println(array) // [0, 0, 0, 0]
	}
	{
		array: [16]u8 
		foo16(array)
		fmt.println(array) // [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
	}
}

```

**Comment by gingerBill** [comment]
This should just be disallowed.
