### ISSUE TITLE
Structure field tags

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#415]
Structure field tags which can be queried at run time:
```go
User :: struct {
    name:  string "this is a tag",
    email: string `this is "another" tag`,
}
```
This will be useful (de)serialization by adding extra metadata to the fields.

Why not attribute-like tags? A constant string literal allows for a lot more versatility for the user and custom syntax. The other reason is that it simplifies the internal type information structure and reducing memory usage.

**Comment by gingerBill** [comment]
I this syntax good enough? Should the tag be separated by an `@` symbol?

**Comment by vassvik** [comment]
Does it have to be a string?
I like the idea of attribute-like tags

**Comment by gingerBill** [comment]
The reason I suggest a string is a few reasons:

* It's really simple but doesn't restrict what data could be stored there (even if it is in text)
* It reduces the size of type information required


Arbitrary attributes with parameters will be partially confusing in that user-defined ones are not really allowed for declarations. The other reason is that they would require the storage of a lot more data than a simple string.

Most of the time, a string literal as a tag is all that is needed. If you need more, you can your code through a metaprogrammer and get what you need.

**Comment by vassvik** [comment]
Got it.
What would be the syntax to get the tag?

**Comment by gingerBill** [comment]
@vassvik It would be stored in the Type Information of the struct.

```go
// Current
Type_Info_Struct :: struct {
	types:        []^Type_Info,
	names:        []string,
	offsets:      []uintptr, // offsets may not be used in tuples
	usings:       []bool,    // usings may not be used in tuples
	is_packed:    bool,
	is_raw_union: bool,
	custom_align: bool,
};

// Proposed
Type_Info_Struct :: struct {
	types:        []^Type_Info,
	names:        []string,
	offsets:      []uintptr, 
	usings:       []bool,    
	tags:         []string,    
	is_packed:    bool,
	is_raw_union: bool,
	custom_align: bool,
};
```

**Comment by vassvik** [comment]
Will all of these be more easily accessible in the future?

**Comment by vassvik** [comment]
I think separation by some symbol could be good.
What about multiple names per line? will tags be shared, or is that disallowed?

**Comment by gingerBill** [comment]
Added in commit 9c63212 using the original proposed syntax.
