### ISSUE TITLE
TrackPopupMenu function in user32.odin should return an i32

### ISSUE THREAD

**Issue by kcvinker** [odin-lang/Odin#4157]
Hi,
`TrackPopupMenu` function in user32.odin is now returns a `BOOL` which is actually a `distinct b32`. But MSDN says that if we use `TPM_RETURNCMD`(0x0100) flag in this function, it will return the selected menu's ID. But if we use a `distinct b32` for return value, we won't get the menu ID. Instead we just get either 0 or 1. So please correct the function signature. Thanks in advance.

**Comment by Kelimion** [comment]
You're right. That is a bit clumsy of Microsoft. https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-trackpopupmenu.
