### ISSUE TITLE
Compiler Segfault on previously working project.

### ISSUE THREAD

**Issue by tadeohepperle** [odin-lang/Odin#4169]
### Context
```
        Odin:    dev-2024-08:e0a2e5260
        OS:      Manjaro Linux, Linux 6.1.99-1-MANJARO
        CPU:     12th Gen Intel(R) Core(TM) i7-1260P
        RAM:     31806 MiB
        Backend: LLVM 14.0.6
```

### Current behavior

Since I updated the Odin compiler recently, I it crashes with: `Segmentation fault (core dumped)`

### Steps to Reproduce

```
git clone https://github.com/tadeohepperle/dengine.git
cd dengine
odin run example
```
The package uses the wgpu-native bindings, so the OS-specific dynamic libs (wgpu-native 22.1.0.1) need to be in Odin/vendor/wgpu/lib They can be downloaded here: https://github.com/gfx-rs/wgpu-native/releases

**Comment by laytan** [comment]
Should be fixed now
