### ISSUE TITLE
(BUG) Nested asserts crashes the compiler

### ISSUE THREAD

**Issue by galt-john** [odin-lang/Odin#4170]
Symptoms: Linux - segfault followed by core dump, Windows - silent crash, Mac - did not test

Odin Compiler: Latest Master August 2024.

Desired: Add error and prevent compiler crash.

Small code example:

```cpp
package main
import "core:fmt"
main :: proc() {
    #assert(assert()) // crashes if assert(true) or assert(false) as well
}
```

**Comment by Kelimion** [comment]
This should be disallowed, because A) `assert` doesn't return a `bool` to begin with, and B) it won't be run at compile-time to return its non-existent return value to `#assert` anyway.

**Comment by Kelimion** [comment]
Fixed. It now reports:
```
W:/Odin/bug/bug.odin(6:5) Error: 'assert(true)' is not a constant boolean 
	#assert(assert(true)) // crashes if assert(true) or ass ... 
	^~~~~~~~~~~~~~~~~~~~^ 
W:/Odin/bug/bug.odin(6:13) Error: 'assert(true)' call does not return a value and cannot be used as a value 
	#assert(assert(true)) // crashes if assert(true) or assert(fals ... 
	        ^~~~~~~~~~~^ 
```
