### ISSUE TITLE
Builtin function to get the package of a struct/procedure/etc

### ISSUE THREAD

**Issue by hasenj** [odin-lang/Odin#418]
**Is your feature request related to a problem? Please describe.**

The problem of implementing generic procedures over types not known ahead of time, without using virtual function dispatch at runtime.

See: #372 

**Describe the solution you'd like**

Builtin function, let's say, `pkg`, that can take a type and return the 'package' for the type so that declarations within that package become accessible by name, including explicitly overloaded procedures.

Given a polymorphic parameter to a procedure, the procedure may call a procedure defined in the same package as the parameter with a given name using something like this:

```
package my_lib;

my_parapoly_proc :: proc(a: ^$T) {
    pkg(T).greet(a);
    // do somethings ...
}
```

Then let's say we have two other packages, each with their own procedures and structs. They can both call `my_lib.my_parapoly_proc` on their internal types, as long as they provide a procedure called `greet` which accepts a pointer to the type.

For example:

```
package a;

X :: struct { .... }

greet :: proc(x: ^X) {
    fmt.printf("Hello there, %s\n", x.name);
}
```

and:

```
package b;
Y :: struct { .... }

greet :: proc(y: ^Y) {
    fmt.printf("This one is for b.Y, his name is %s\n", y.info.name);
}
```

**Additional context**

Imagine if you want to have auto initialization of structs along with allocation. It might be implemented in userspace using this feature:

```
alloc_and_init(T: typeid) ^T {
    t := alloc(T); // assume builtin
    pkg(T).init(t);
    return t;
}
```

Perhaps if we also have a way to check if a package declares a function with a given name:

```
when exists(pkg(T), 'init') {
    pkg(T).init(t);
}
```

**Comment by gingerBill** [comment]
I am personally not a fan of this idea, mainly because it will encourage a lot of "generic" stuff which I don't want to encourage in the language. It's relatively simple to implement but that doesn't mean I want it.

I am sorry but I do not want this as a built-in procedure.

**Comment by hasenj** [comment]
No problem, I'm nit always a fan of my own suggestions sometimes but I still pay them, for two reasons:

1) Throw ideas around and see if there's something valuable there

2) Documentation: letting other people know that this idea has already been considered.
