### ISSUE TITLE
File-private variables

### ISSUE THREAD

**Issue by vassvik** [odin-lang/Odin#420]
Variables marked as `@private` are currently exposed to the rest of the package. Some times you want more granuliary where it is only exposed to the current file. For example, there might be some global state/storage used by procedures in this file, but we only need to expose those procedures and the names of the storage. 

```
@(private="file")
_storage: struct {
    // stuff
}
```

**Comment by Tetralux** [comment]
Wouldn't the opposite be better?

`@private` is private to the file, `@(private="package")` private to the package?

**Comment by Tetralux** [comment]
For record though, just making `@private` work the same way as it does now, but also working for global variables: 💯

**Comment by Tetralux** [comment]
I feel like I've read this issue three times and each time misread it.

I was under the impression that `@private` did make things private to the file.
If not, there probably should be a way to do that.

**Comment by gingerBill** [comment]
`@private` is probably better named `@do_not_export`

**Comment by gingerBill** [comment]
Implemented in 9e9e905

`@private`
`@(private="package")`
`@(private="file")`
