### ISSUE TITLE
packages and program entry point (main proc)

### ISSUE THREAD

**Issue by hasenj** [odin-lang/Odin#422]
**Is your feature request related to a problem? Please describe.**

Since Odin uses the same packaging logic as Go, it suffers from the same problem: package 'main' is not reusable or importable from another program.

**Describe the solution you'd like**

Instead of requiring the entry point to be the procedure 'main' in package 'main', it can be designated by a special attribute and be applied to any procedure in any package.

Let's suppose the main function is designated by the special token `@main` before the procedure definition.

When you pass a file name to the odin command, it scans all procedures in the file for the `@main` tag. If it finds it, then it proceeds to load all other files in the directory (since all files in the directory are in the same package).

**Additional context**

It's ok for there to be multiple `@main` tags in a package, as long as there's no more than one such tag in the same file. This enables the programmer to have for example a test.odin file that has an entry point that only does some testing.

The implication here is that the entry procedure is not determined by the name of the procedure, but is selected by the compiler based on some criteria.

A natural extension of this idea is to make it possible to specify the desired entry point via command line arguments.

    odin run -entry=my_test_proc

in this case, odin will load all files in the current directory and treat it as a package, and it will look for the procedure `my_test_proc` in this package, and designate it as the entry point.

**Comment by vassvik** [comment]
You can use any package name and have a main function, so I'm a bit confused.

**Comment by hasenj** [comment]
interesting, I wasn't aware the file doesn't need to have a package 'main' to be the entry point. I'll have to revise the title.

That said, the current implementation still puts a strange distinction between "packages" and "the current folder".

Normally when a package is loaded, all files in the directory are loaded.

But when a file is passed to the command line, only that file is loaded.

You can put ```import "."``` to let odin load the entire package, but then only one file can every have a 'main' proc.

**Comment by mhjspiir** [comment]
Have you tried `odin build src/` instead of `odin build src/test.odin`? You don't have to do `import "."` to load the main package usually.

**Comment by ThisDrunkDane** [comment]
Have you tried `odin build src/` instead of `odin build src/test.odin`? You don't have to do `import "."` to load the main package normally.

**Comment by hasenj** [comment]
I see, I guess I misunderstood the package system.

**Comment by Tetralux** [comment]
Perhaps we should have a Wiki entry at least or something for this if we don't already.
If we do, we can also link it here.
