### ISSUE TITLE
Mac OSX 10.14,  error "dyld: cannot load 'odin' (load command 0x80000034 is unknown) Abort trap: 6"

### ISSUE THREAD

**Issue by magicmouse** [odin-lang/Odin#4221]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Mac OSX 10.14, 32GB RAM, Intel Core i5 processor. (2018 Mac Mini)

* Operating System & Odin Version:
Odin, version from Sept 7, 2024 (latest nightly build)

## Expected Behavior

i run ./odin in the folder, and gives me an error instead of running the compiler

## Current Behavior

dyld: cannot load 'odin' (load command 0x80000034 is unknown)
Abort trap: 6

## Failure Information (for bugs)

Is there a compatibility with OSX 10.14? 

### Steps to Reproduce

./odin while in the command prompt.

**Comment by laytan** [comment]
The release version probably does not support your old OS. Building from source should work though (and is very easy to do).

10.14 being from 2018 and not supported anymore, I don't know if we want to invest time in support for releases from our side. To be clear, from source should probably work.

**Comment by magicmouse** [comment]
I will try using an earlier version of LLVM; the latest one clearly doesn't work.

**Comment by laytan** [comment]
Ah looks like brew gave up on your version too, you can also try macports, they seem to have better support and may even provide precompiled binaries for your version still: https://ports.macports.org/port/llvm-18/details/

**Comment by Kelimion** [comment]
And if all else fails, a Mac Mini from 2018 ought to be able to run a more recent version of macOS, which wouldn't be a bad thing in terms of security either.

**Comment by magicmouse** [comment]
There are many people like me running OSX 10.14 because Apple has been rather ruthless about killing off older software on 10.15, and those of us who purchased Adobe Creative Suite (over $1000 when purchased), don't relish the thought of paying Adobe $80/month for the rest of our lives.... this is why we cling to OSX 10.14.

Apple could easily have continued to support running 32 bit apps, but they intentionally chose to break backwards compatibility. It's extremely galling that many of the apps that are part of of OSX run as 32 bit apps, but they only let their own software run...

This is the one aspect of Apple that is so objectionable, their abandonment of backwards compatibility, and why Windows is so much more used in Business, because i can run Win95 products in Windows 10 no problem.

Various companies seem to be phasing out support for 10.14, which is unfortunate, because the OS changed very little; in fact 99% of the new features of OSX are trivial in nature. The core OS has not moved much; nor can it without massive disruption to existing apps.

**Comment by Kelimion** [comment]
I'm entirely with you there.

**Comment by laytan** [comment]
I am going to close this, I don't think there is anything more to do here.
