### ISSUE TITLE
[Odin Test] `odin test . -all-packages` not running tests from other packages

### ISSUE THREAD

**Issue by worriedvulkan** [odin-lang/Odin#4222]
## Context

        Odin:    dev-2024-09:16c5c69a4
        OS:      Windows 10 Professional (version: 22H2), build 19045.4780
        CPU:     AMD Ryzen 7 5700X 8-Core Processor
        RAM:     32694 MiB
        Backend: LLVM 18.1.8

## Expected Behavior

All tests should run regardless of what package they are part of.

## Current Behavior

Only the tests in the main package run.

### Steps to Reproduce

1. Create a new Odin project.
2. Create a subpackage and add a test to it.
```
import "core:testing"

@(test)
equals :: proc(t: ^testing.T) {
	testing.expect(t, 1 == 1)
}
```
3. Run the tests using `odin test . -all-packages`

### Failure Logs

![odin-test-all-packages](https://github.com/user-attachments/assets/c3a78b8c-500a-46a6-8d26-e0c08b7c4a29)

**Comment by Kelimion** [comment]
This is not a bug.

If you look at `tests/core/normal.odin` and `tests/core/speed.odin`, you see that the parent package under test that's compiled with `-all-packages` imports the packages underneath to be tested. Just as you need to import a package to use it in a regular non-test program.

**Comment by worriedvulkan** [comment]
Understood, Thanks for the help
