### ISSUE TITLE
Frequent compiler crash Segmentation fault: 11 on macOS

### ISSUE THREAD

**Issue by harold-b** [odin-lang/Odin#4228]
```odin report
        Odin:    dev-2024-09:d256860db
        OS:      macOS Sonoma 14.5 (build: 23F79, kernel: 23.5.0)
        CPU:     Apple M3 Max
        RAM:     65536 MiB
        Backend: LLVM 14.0.6
```

Continuing from #4224 in case it might be a different issue.

I have started getting frequent compiler crashes on macOS since last week, though I cannot pin-point the exact commit.

It does not *appear* to be multi-threaded related as I've tested with both forcing a single threaded and also `-no-threaded-checker`. The crash continues to occur frequently, even within 2-8 tries.

I've tried both `debug` and `release-native` versions with the same result, which is simply crashing with "Segmentation fault: 11". I've ran it a few times under the debugger where I trigger asserts and panics in different locations of the llvm backend. The following have triggered under the debugger:

- https://github.com/odin-lang/Odin/blob/b442ea86012fb4d07c79bcc6debbd79bd047b63e/src/llvm_abi.cpp#L271
- https://github.com/odin-lang/Odin/blob/b442ea86012fb4d07c79bcc6debbd79bd047b63e/src/llvm_backend_const.cpp#L93

The latter also triggered in a `debug` build, yet not running under a debugger:

> src/llvm_backend_const.cpp(93): Assertion Failure: `lb_sizeof(dst) == lb_sizeof(src)` i8 vs  addrspace(24)*

I've no other leads at the moment.

**Comment by harold-b** [comment]
Note that I've also just managed to trigger `src/llvm_abi.cpp(271): Panic: Unhandled type for lb_sizeof -> ` outside the debugger.

These 2 asserts/panics seem are the only ones I've triggered so far, but most of the crashes come up as segfaults with no assert or panic triggered.

**Comment by laytan** [comment]
Does the code it happens on happen to be public? Or could you share it privately otherwise?

**Comment by harold-b** [comment]
Sadly I cannot share the code, but I'll see if I can reduce it to a repro case.

**Comment by colrdavidson** [comment]
Can you git bisect out the Odin compiler commit this started happening in?
Would go a long way to know where exactly it started cropping up

**Comment by harold-b** [comment]
> Can you git bisect out the Odin compiler commit this started happening in?
(or at least a rough "worked before here")
Would go a long way to know where exactly it started cropping up

I was planning on doing this, but had not gotten the chance to touch Odin again until today.

I updated to llvm 17 and got the latest commit and the issue stopped happening. It was happening very consistently before that. I'll close this, but if I get any info by bisecting I'll report it.
