### ISSUE TITLE
Crash when closing file dialogue from _open_file_dialog in comdlg32.odin

### ISSUE THREAD

**Issue by vassvik** [odin-lang/Odin#424]
Inside `_open_file_dialog` the filename buffer is allocated using the allocator passed as an optional argument to the procedure, which defaults to `context.temp_allocator`, and if the file dialogue fails for some reason, e.g. if you close the dialogue without selecting anything, then it will try to free it regardless of the allocator used. In other words, it will try and free the buffer even when the temp allocator is used, which will be most cases. 

You cannot compare allocators to detect if the temp allocator is used, so I don't know what the right solution is here..

Here's the procedure, for reference:
```go
_open_file_dialog :: proc(title: string, dir: string,
                          filters: []string, default_filter: u32,
                          flags: u32, default_ext: string,
                          mode: Open_Save_Mode, allocator := context.temp_allocator) -> (path: string, ok: bool = true) {
	file_buf := make([]u16, MAX_PATH_WIDE, allocator); // This might be context.temp_allocator

	// Filters need to be passed as a pair of strings (title, filter)
	filter_len := u32(len(filters));
	if filter_len % 2 != 0 do return "", false;

	filter: string;
	filter = strings.join(filters, "\u0000", context.temp_allocator);
	filter = strings.concatenate({filter, "\u0000"}, context.temp_allocator);

	ofn := Open_File_Name_W{
		struct_size  = size_of(Open_File_Name_W),
		file         = Wstring(&file_buf[0]),
		max_file     = MAX_PATH_WIDE,
		title        = utf8_to_wstring(title, context.temp_allocator),
		filter       = utf8_to_wstring(filter, context.temp_allocator),
		initial_dir  = utf8_to_wstring(dir, context.temp_allocator),
		filter_index = u32(clamp(default_filter, 1, filter_len / 2)),
		def_ext      = utf8_to_wstring(default_ext, context.temp_allocator),
		flags        = u32(flags),
	};

	switch mode {
	case .Open:
		ok = bool(get_open_file_name_w(&ofn));
	case .Save:
		ok = bool(get_save_file_name_w(&ofn));
	case:
		ok = false;
	}

	if !ok {
		delete(file_buf); // This will crash when the default argument for `allocator` is used.
		return "", false;
	}

	file_name := utf16_to_utf8(file_buf[:], allocator);
	path = strings.trim_right_null(file_name);
	return;
}
```

One possible solution would be to always use the temp allocator, and require the user to make a copy if they want the result to be persistent.

Another solution would be to just use static storage and not requiring freeing. 

A third solution would be to always return the buffer, requiring it to be freed on fail. 

None of these are really satisfactory in my eyes..

**Comment by Tetralux** [comment]
Shouldn't `delete` on temporary storage be a no-op?

**Comment by ThisDrunkDane** [comment]
Is this still a problem @vassvik?
