### ISSUE TITLE
Function Pointers nils all data from a struct contained in an array

### ISSUE THREAD

**Issue by Skytrias** [odin-lang/Odin#427]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Linux OpenSuse Tumbleweed 84.87.20180228.827b030
* Odin version/Commit: 59ab51acecd22674a7cc8607cd3af8eaeb55068a

## Expected Behavior

Function pointers should normally be copied over to other structs / arrays of whatever struct held the function pointer.

## Current Behavior

Function pointer inside of a struct gets nil when put into any other struct / array. Also nil's all other data that was inside of the struct. 

## Failure Information (for bugs)

Fails at runtime since the function pointer is nil and doesnt exist.

### Steps to Reproduce

```
package main 

import "core:fmt"

// array of different Foo
foos := [1]Foo {
    // below get nil maybe when it tries to copy itself here
    test,
};

// struct that holds the data we might want and the proc
Foo :: struct {
    data: [3]u32,
    bar: proc(),
}

// initialized struct with set data and proc
test := Foo {
    data = { 0, 1, 2 },
    bar = proc() {
        fmt.println("hi");
    },
};

main :: proc() {
    test.bar();
    fmt.println(test);
    fmt.println(foos[0]);
    foos[0].bar();
}
```

### Failure Logs

Above results in fmt output:
```
hi
Foo{data = [0, 1, 2], bar = proc() @ 0x425C10}
Foo{data = [0, 0, 0], bar = nil}
```

expected output:
```
hi
Foo{data = [0, 1, 2], bar = proc() @ 0x425C10}
Foo{data = [0, 1, 2], bar = proc() @ 0x425C10} // maybe some other pointer
hi
```

**Comment by gingerBill** [comment]
This appears to be an initialize ordering bug and the dependency sorting it not catching it correctly.

**Comment by gingerBill** [comment]
This is caused by the initial priority queue generation being incorrect. I need to correct the sorting comparison function. This is a fun but complex problem that I am amazed I didn't notice before.

**Comment by Skytrias** [comment]
on my end it still returns the faulty result on the current master commit a1d4ea7718d49cb0245a0fc77d6c781373a46238

**Comment by gingerBill** [comment]
This should be fixed now in the latest commit.

**Comment by Skytrias** [comment]
the test now works, nice work and good job  :+1:
