### ISSUE TITLE
Comma between params isnt needed for two param proc

### ISSUE THREAD

**Issue by FourteenBrush** [odin-lang/Odin#4278]
## Context

The following code compiles and runs just fine, despite a missing comma between the parameters, note that this is only reproducible with two parameters:
```go
package bug

import "core:fmt"

main :: proc() {
    something(1, 2)
}

something :: proc(x: int y: int) {
    fmt.println("works fine")
}
```

* Operating System & Odin Version:
* Please paste `odin report` output:
```
        Odin:    dev-2024-09:c1264c2a7
        OS:      Fedora Linux 40 (KDE Plasma), Linux 6.10.8-200.fc40.x86_64
        CPU:     AMD Ryzen 7 5800H with Radeon Graphics         
        RAM:     13817 MiB
        Backend: LLVM 18.1.6
```

## Expected Behavior

Compiler error stating missing comma

### Steps to Reproduce

`odin run file.odin -file`

**Comment by Kelimion** [comment]
Confirmed. `x` and `y` were even assigned the correct values.
```odin
package bug

import "core:fmt"

main :: proc() {
	something(1, 2)
}

something :: proc(x: int y: int) {
	fmt.printfln("works fine: x={} y={}", x, y)
}
```
