### ISSUE TITLE
Nested using in a with raw_union crashes the compiler.

### ISSUE THREAD

**Issue by lunaticLipid** [odin-lang/Odin#428]
* Operating System: Win 10
* Odin version/Commit: f0fa716

```
package main

S :: struct {
    using u: struct #raw_union {
        using nums: struct {
            x, y: int,
        }
        using other_nums: struct {
            z, w: int,
        }
    }
}

main :: proc() {
    s: S;
    s.x = 1;
}
```

E:\Projects\Odin\src\ir.cpp(1879): Panic: Unreachable

Compiles successfully if `s.x = 1;` is removed.

**Comment by lunaticLipid** [comment]
Nope, still doesn't compile.
Windows 10, commit f1a7b31
`E:\Projects\Odin\src\ir.cpp(1881): Panic: Unreachable 22`

**Comment by gingerBill** [comment]
This is now fixed!
