### ISSUE TITLE
core:image can't load png

### ISSUE THREAD

**Issue by karl-zylinski** [odin-lang/Odin#4286]
## Context
        Odin:    dev-2024-09:9a8fb2fb2
        OS:      Windows 10 Professional (version: 22H2), build 19045.4894
        CPU:     Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz
        RAM:     32674 MiB
        Backend: LLVM 18.1.8

## Expected Behavior

`image.load_from_file("image.png")` should work

## Current Behavior

I get error: `Unsupported_Format`

### Steps to Reproduce

1. Download this zip: [image_bug.zip](https://github.com/user-attachments/files/17084997/image_bug.zip)
2. Extract to empty folder. It contains an odin file and a PNG image.
3. Go into folder and run `odin run .`
4. It prints `Unsupported_Format`

The Odin code does this:

```
package image_bug

import "core:image"
import "core:fmt"

main :: proc()  {
	img, img_err := image.load_from_file("image.png")
	fmt.println(img_err)
}
```

If I use `core:image/png` directly it works. So I think it fails to identify this file as a PNG. The PNG comes from Aseprite.

**Comment by blob1807** [comment]
`core:image` works by also importing the sub packages, as they need register themselves with an [`@init` proc](https://github.com/odin-lang/Odin/blob/c1264c2a798b94561dd7dbfa627c5d1555258442/core/image/png/png.odin#L1616-L1619) for `core:image` to know what it supports. I imagen it's done like this to save on exe size by not unnecessarily importing formats.

**Comment by Kelimion** [comment]
This is not a bug. As @blob1807 says, you need to also import the actual image codec so it can register itself with `image.load`.

**Comment by karl-zylinski** [comment]
Aha. Is there some documentation to make sure one understand this? Could perhaps `image.load_from_file` panic if no single codec is loaded? With a message that gives and example of what to do.

**Comment by Kelimion** [comment]
> Aha. Is there some documentation to make sure one understand this? Could perhaps `image.load_from_file` panic if no single codec is loaded? With a message that gives and example of what to do.

@laytan and I have discussed just that solution. The thing is that the registered codecs are stored in an enumerated array, and it's going a bit far to iterate over it each time you want to load an image. So no `assert(registered_loader_count() > 0)` at the top of the proc. But what we could do, is that when `codecs[which(data)] == nil`, walk the array there and panic if the count is zero.

That way if you did register the codec(s), there's no unnecessary linear scan each time you try to load an image.

**Comment by karl-zylinski** [comment]
@Kelimion That sounds like a good compromise!
