### ISSUE TITLE
Allow swizzle field names in array initialization

### ISSUE THREAD

**Issue by Porem5002** [odin-lang/Odin#4288]
This feature comes from something that was previously possible using the raylib bindings.

Until around [dev-2023-11](https://github.com/odin-lang/Odin/releases/tag/dev-2023-11), the Color type from raylib was defined as a struct so we could write code like this and it was pretty obvious what it would do:
```odin
x: raylib.Color = { r = 127, g = 0, b = 127, a = 255  }
```
But since then (after [this](https://github.com/odin-lang/Odin/pull/2927) more precisely) this type is defined as a fixed array, which allows for more flexibility but also means that the previous code no longer compiles since those fields don't actually exist in an array.

My request is to allow for this kind of syntax for initializing arrays, making the language more consistent.

**Comment by gingerBill** [comment]
No. This is a rabbit hole which leads to a lot of problems which are not obvious.
