### ISSUE TITLE
Issue with implicit enum value specification for procedure groups

### ISSUE THREAD

**Issue by VladPavliuk** [odin-lang/Odin#4295]
Reproduces for Windows 10 & Odin Version: dev-2024-09:f7d74ff3a

When I try to call procedure group: `renderImageRect` Odin can't figure out enum value passed without being fully specified:
```
renderImageRect(shrinkRect(checkboxRect, 3), ctx.zIndex, .CHECK_ICON) // TextureType.CHECK_ICON works fine
```

Error: 
```
Cannot determine type for implicit selector expression '.CHECK_ICON'
```

A bit more context:
* `shrinkRect` method is defined as the following: 
```
shrinkRect :: proc(using rect: Rect, amount: i32) -> Rect
```
* `renderImageRect` is defined as the following: 
```
renderImageRect :: proc{renderImageRectVec_Float, renderImageRectVec_Int, renderImageRect_Int}
```

If try to call `renderImageRect` in this way it works fine:
```
renderImageRect(checkboxRect, ctx.zIndex, .CHECK_ICON) // works fine
```

So for some reasons even though `shrinkRect(...)` returns the same type as `checkboxRect` variable, the compiler can't resolve 3 parameter by it's implicit value.

**Comment by gingerBill** [comment]
This is not a bug and just a limitation of the type inference system not being able to determine what it should be.
