### ISSUE TITLE
Add #field_pack tag to structs

### ISSUE THREAD

**Issue by flysand7** [odin-lang/Odin#4298]
Currently in order to control struct field alignment we have two tags. One of them is  `#field_align(N)`, that will align each field to `max(align_of(field), N)` bytes. The other one is `#packed`, which disables field alignment for a struct.

In order to bind to certain WinAPI bindings[citation needed], it would be useful to have a `#field_pack(N)` tag, that will specify the minimum alignment for a field. Each field will be aligned to `min(align_of(field), N)` bytes.

To prevent misuse, an error could be made, when `#field_pack(N)` is used with N=1. The error would suggest to use `#packed` instead. This will signal that this tag is solely used for silly cases, i.e. bindings, which use weird minimum alignment requirements.

**Comment by avanspector** [comment]
Adding the current MSVC compiler specification and multiple potential bindings uses to a discussion:
![image](https://github.com/user-attachments/assets/decf87c6-32f6-48cf-a1cd-d2a112918e22)
![image](https://github.com/user-attachments/assets/b642501a-afb3-41aa-a2e1-5342fea57cca)
![image](https://github.com/user-attachments/assets/083346fc-d258-4dc3-92b6-061201306e80)
![image](https://github.com/user-attachments/assets/28624264-0a81-4c70-8156-6dd1bee6d05a)

**Comment by laytan** [comment]
These are also all pragma pack:
https://github.com/odin-lang/Odin/blob/f7d74ff3a8596efef67d151ffb758ed085e94be0/core/sys/posix/sys_msg.odin#L69
https://github.com/odin-lang/Odin/blob/f7d74ff3a8596efef67d151ffb758ed085e94be0/core/sys/posix/sys_sem.odin#L84
https://github.com/odin-lang/Odin/blob/f7d74ff3a8596efef67d151ffb758ed085e94be0/core/sys/posix/sys_shm.odin#L72

**Comment by flysand7** [comment]
@laytan what does `#align` do?

**Comment by laytan** [comment]
Bill added `#max_field_align(N)` which is the equivalent of `#pragma pack(N)` here: https://github.com/odin-lang/Odin/commit/a7d7c92a5302a9d0db503af37fe96c737a536544
