### ISSUE TITLE
Arch amd64: `ptrace_getregs` call causing the porgram stack corruption

### ISSUE THREAD

**Issue by eseft** [odin-lang/Odin#4306]
## Context

* `odin report` output:
```
	Odin:    dev-2024-09:8371ef668
	OS:      Arch Linux, Linux 6.10.10-arch1-1
	CPU:     AMD Ryzen 5 5600G with Radeon Graphics
	RAM:     31460 MiB
	Backend: LLVM 18.1.8
```

## Expected Behavior

Stack is not corrupted and program can continue work after `ptrace(.PTRACE_GETREGS,...)` call. 

## Current Behavior

After successful `ptrace(.PTRACE_GETREGS,...)` program stack getting corrupted.

## Failure Information (for bugs)

Looks like for the amd64 arch the `User_Regs` struct missing couple of fields compared with [https://github.com/bminor/glibc/blob/master/sysdeps/unix/sysv/linux/x86/sys/user.h](https://github.com/bminor/glibc/blob/master/sysdeps/unix/sysv/linux/x86/sys/user.h) which is causing the program stack corruption on `ptrace` syscall

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Compile the following program
```odin
package main

import "core:sys/linux"
import "core:os"


get_regs :: proc(pid: linux.Pid, regs: ^linux.User_Regs) -> bool {
    tmp := linux.User_Regs{}
    err := linux.ptrace(linux.PTRACE_GETREGS, pid, &tmp)
    if err != nil {
        return false
    }
    regs^ = tmp
    return true
}

main :: proc() {
    pid, err := linux.fork()
    assert(err == nil)

    if pid == 0 {
        err_ptrace := linux.ptrace(linux.PTRACE_TRACEME)
        assert(err_ptrace == nil)

        err_exec := os.execvp("/usr/bin/ls", {})
        assert(err_exec == nil)

    } else {
        status: u32
        rusage: linux.RUsage
        linux.wait4(pid, &status, {}, &rusage)
        assert(linux.WIFSTOPPED(status))

        regs: linux.User_Regs
        get_regs(pid, &regs)
    }
}
```
2. Run the program under a debugger and break at `get_regs` proc. Inspect address and value of `regs` local variable:
```
(gdb) p regs
$1 = (struct linux._Arch_User_Regs *) 0x7fffffffdf98
(gdb) p &regs
$2 = (struct linux._Arch_User_Regs **) 0x7fffffffdf68
(gdb) x/80x $sp
...
0x7fffffffdf50:	0x00000018	0x00000000	0x00408506	0x00000000
0x7fffffffdf60:	0x00408506	0x00000000	0xffffdf98	0x00007fff  <<<<<
0x7fffffffdf70:	0x0000057f	0x0000369b	0x0040220a	0x00000000
...
```
3. Step over `ptrace` call and inspect the `regs` value and the program stack one more time:
```
(gdb) p regs
$3 = (struct linux._Arch_User_Regs *) 0x0
(gdb) x/80x $sp
...
0x7fffffffdf50:	0x00000202	0x00000000	0xffffe380	0x00007fff
0x7fffffffdf60:	0x0000002b	0x00000000	0x00000000	0x00000000 <<<<<
0x7fffffffdf70:	0x00000000	0x00000000	0x00000000	0x00000000
...
```

**Comment by flysand7** [comment]
The link you have posted is a link to libc, not linux kernel, which is what sys/linux is binding against. I've become a little bit rusty navigating the linux codebase, so I'd have to spend some time on this

**Comment by eseft** [comment]
Oh, I see. Makes sense that it is binding against the kernel. I'm not familiar with the linux kernel codebase at all, not sure if I can help. Thank you for taking a look at the issue :)

**Comment by flysand7** [comment]
@gingerBill this should be closed
