### ISSUE TITLE
OS2 Linux Compiler Assertion

### ISSUE THREAD

**Issue by jpx40** [odin-lang/Odin#4317]
Latest build from master

Tested against llvm 17 and 18

  Odin:    dev-2024-09:90d024f
        OS:      Fedora Linux 40 (Forty), Linux 6.10.9-200.fc40.x86_64
        CPU:     AMD Ryzen 7 5800X 8-Core Processor
        RAM:     31990 MiB
        Backend: LLVM 18.1.1

Code:
``` 
package main
import "core:fmt"
import "core:mem"
import "core:os/os2"
import "core:strings"
main :: proc() {
    //buf: [mem.Kilobyte]byte = ---
    //arena: mem.Arena
    //mem.arena_init(&arena, buf[:])
    // allocator := mem.arena_allocator(&arena)
    //context.allocator = mem.arena_allocator(&arena)
    env := os2.environ(context.allocator)

    for e in env {

        if strings.contains(e, "ODIN") {
            fmt.println(e)
        }
    }
}
 


```

### Failure Logs
src/llvm_backend_general.cpp(3022): Assertion Failure: `LLVMIsConstant(value.value)`    = load 7s2.File_Impl-927, ptr , align 8
[1]    76292 illegal hardware instruction (core dumped)  /home/jonas/repo/Odin/odin run src/main.odin -file

**Comment by IllusionMan1212** [comment]
I can't reproduce this on Ubuntu 24.04.1 Kernel 6.8.0-45 with LLVM 18.1.3 on the same commit. Maybe it's the llvm version difference

**Comment by gingerBill** [comment]
I cannot replicate this on master.

**Comment by laytan** [comment]
Yeah this issue was already fixed a few weeks ago.
