### ISSUE TITLE
`json.marshal` should treat `using` subfields as part of the containing struct not as subfields of the inner struct

### ISSUE THREAD

**Issue by edyu** [odin-lang/Odin#4318]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

```
        Odin:    dev-2024-09:90d024fb7
        OS:      Ubuntu 24.04.1 LTS, Linux 5.15.153.1-microsoft-standard-WSL2
        CPU:     AMD Ryzen 7 5800HS with Radeon Graphics
        RAM:     11662 MiB
        Backend: LLVM 18.1.3

```

## Expected Behavior

The reason people use `using` inside a struct is in many cases a way of composition because otherwise, they can just not use `using`.
For example:

```
A :: struct {
 a: int,
}
B :: struct {
 using c: A,
 b: string,
}
```
I expected the `json` marshal code to treat B more like

```
B :: struct {
  a: int,
  b: string,
}
```

## Current Behavior

However right now `json` marshal code treats B more like the following (as an inner struct without `using`):

```
B :: struct {
  c: A,
  b: string,
}
```

## Failure Information (for bugs)

```
package main

import "core:encoding/json"
import "core:fmt"

A :: struct {
        a: int,
}

B :: struct {
        using c: A,
        b:       string,
}

main :: proc() {
        my_b: B
        my_b.a = 5
        my_b.b = "hello"

        m, e := json.marshal(my_b)
        fmt.println(string(m))
}
```

**Comment by gingerBill** [comment]
Why should they? They are not the same.

**Comment by edyu** [comment]
> Why should they? They are not the same.

They should be treated the same because one of the reason to use `using` is for composition. For example, if I want to "serialize" an Odin object to json so that the json can be read by a `go` program, I do need to treat the fields of `A` as part of `B` not as an inner object. Json sometimes convey the concept of "subtyping" and by not allowing this, there would be a lot of code duplication.

**Comment by edyu** [comment]
This is for those "HUGE" json objects that are used for example in the Docker API. Go solves the problem of those huge Docker API by "composing" larger objects using smaller objects of various aspect of concerns. For example, a container object is composed of Config object, Host-Config object, Network Setttings object, Network Config object etc. By not allowing this, the Odin code will have an extremely large data object that contains every field. But the "sub" objects such as Config, Host-Config etc are still needed.
