### ISSUE TITLE
`json.marshal` should not throw `Unsupported_Type` error when struct has a pointer; `json.unmarshal` should not return `Unsupported_Type_Error`

### ISSUE THREAD

**Issue by edyu** [odin-lang/Odin#4319]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

```
        Odin:    dev-2024-09:90d024fb7
        OS:      Ubuntu 24.04.1 LTS, Linux 5.15.153.1-microsoft-standard-WSL2
        CPU:     AMD Ryzen 7 5800HS with Radeon Graphics
        RAM:     11662 MiB
        Backend: LLVM 18.1.3
```

## Expected Behavior

I expect pointer to struct to be treated as if it's an inner struct. In the case of json, I expected the following to be equivalent:

```
A :: struct {
        a: int,
}
B :: struct {
        a: ^A,
        b: string,
}
```

and

```
A :: struct {
        a: int,
}

B :: struct {
        a: A,
        b: string,
}
```
should output same json

## Current Behavior

We now have an error `Unsupported_Type` when we have pointer in the struct when using `json.marshal`. We also have a weirld error that is not `nil` but prints out `nil` when printed when we call `json.unmarshal`. I'm guessing the `unmarshal` call expects the pointer to be pointing to a valid struct.

## Failure Information (for bugs)

For marshaling:

```
package main

import "core:encoding/json"
import "core:fmt"

A :: struct {
        a: int,
}

B :: struct {
        a: ^A,
        b: string,
}

main :: proc() {
        my_a: A
        my_a.a = 5
        my_b: B
        my_b.a = &my_a
        my_b.b = "hello"

        m, e := json.marshal(my_b)
        if e != nil {
                fmt.println("Error:", e)
        } else {
                fmt.println(string(m))
        }
}
```

For unmarshalling:

```
package main

import "core:encoding/json"
import "core:fmt"

A :: struct {
        a: int,
}

B :: struct {
        a: ^A,
        b: string,
}

C :: struct {
        a: A,
        b: string,
}

main :: proc() {
        my_a: A
        my_a.a = 5
        my_b: B
        my_b.a = &my_a
        my_b.b = "hello"
        my_c: C
        my_c.a.a = 5
        my_c.b = "hello"

        m, e := json.marshal(my_b)
        if e != nil {
                fmt.println("Error:", e)
        } else {
                fmt.println(string(m))
        }

        m, e = json.marshal(my_c)
        if e != nil {
                fmt.println("Error:", e)
        } else {
                fmt.println(string(m))
        }

        my_b2: B
        // making sure the pointer is not nil
        my_b2.a = &my_a
        e2 := json.unmarshal(m, &my_b2)
        if e2 != nil {
                fmt.println("Unmarshal.Error:", e2)
        } else {
                fmt.println(my_b2)
        }

        my_c2: C
        e2 = json.unmarshal(m, &my_c2)
        if e2 != nil {
                fmt.println("Unmarshal.Error:", e2)
        } else {
                fmt.println(my_c2)
        }
}
```

### Failure Logs

```
~ ❱ odin run main.odin -file
Error: Unsupported_Type
{"a":{"a":5},"b":"hello"}
Unmarshal.Error: Unsupported_Type_Error{id = ^A, token = Token{pos = Pos{offset = 5, line = 1, column = 5}, kind = "Open_Brace", text = "{"}}
C{a = A{a = 5}, b = "hello"}
```

**Comment by gingerBill** [comment]
> I expect pointer to struct to be treated as if it's an inner struct. In the case of json, I expected the following to be equivalent:

This is not a bug, and this is not expected by JSON. This will never be allowed because it cannot know if that chain of pointers terminates or not.

**Comment by edyu** [comment]
The point of JSON is to be used as a serialization method for `data`. 

For a language based on reference such as 'Go' it's easy to "compose" data objects using references and json does the "right thing." However in Odin, it's the equivalent is the pointer unless we use those large outer struct that contains inner struct which in turn contains inner-inner structs, we will encounter this kind of "not-a-bug" `bug`.

Therefore, I actually do think this should be supported.

**Comment by edyu** [comment]
> > I expect pointer to struct to be treated as if it's an inner struct. In the case of json, I expected the following to be equivalent:
> 
> This is not a bug, and this is not expected by JSON. This will never be allowed because it cannot know if that chain of pointers terminates or not.

Is this a concern of cyclic pointer references?
