### ISSUE TITLE
Getting compiler assert instead of compilation error

### ISSUE THREAD

**Issue by LeoBlute** [odin-lang/Odin#4330]
## Context
When i was coding, i, accidentally, assigned two types for the same variable, instead of throwing a compiler error, i got a compiler internal assertion
## Report
```
Odin:    dev-2024-09:a7d7c92a5
OS:      Ubuntu 22.04.5 LTS, Linux 6.8.8-060808-generic
CPU:     AMD Ryzen 3 2200G with Radeon Vega Graphics    
RAM:     13889 MiB
Backend: LLVM 14.0.0
```
## Expected Behavior
The compiler throw some error message like: "Syntax Error: Cannot assign multiple types to variable"
## Assertion hit

```
src/check_decl.cpp(450): Assertion Failure: e->type == nullptr
```
## Code
```
x : i32 : u32
```

**Comment by aarcex3** [comment]
Hi, I would like to work on this, where should I start?

**Comment by LeoBlute** [comment]
> Hi, I would like to work on this, where should I start?

What? This is a bug report

**Comment by aarcex3** [comment]
So I can't work on this and try to fix it? 😢
