### ISSUE TITLE
Incorrect dependency determination error when initializing an array of procs

### ISSUE THREAD

**Issue by Lunatoid** [odin-lang/Odin#436]
When creating an array of procs, it throw an error if you use the array within the procedure.
```
foo :: proc() {
    // Disallowed
    size := len(PROCS);
}

bar :: proc() {
    // Disallowed
    PROCS[0]();
}

PROCS := [?]#type proc() {
    foo,
    bar
};
```
Will result in
```
Cyclic initialization of 'PROCS'
 'foo' refers to
 'PROCS'
```
Since you're just creating an array without even calling the procedures it shouldn't catch this as cyclic initialization.

**Comment by ThisDrunkDane** [comment]
Please use our issue templates when reporting bugs https://github.com/odin-lang/Odin/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ThisDrunkDane** [comment]
Not valid syntax anymore, if still a problem please reopen issue with valid syntax
