### ISSUE TITLE
Json, float parsing error

### ISSUE THREAD

**Issue by Holub-Patrik** [odin-lang/Odin#4361]
## Context

When loading a simple json file:
```json
{
  "val": -10.0
}
```
Using a minimal program as such:
```odin
package main

import "core:encoding/json"
import "core:fmt"
import "core:os"

main :: proc() {
    data, ok := os.read_entire_file_from_filename("test.json")
    if !ok {
        fmt.println("Data read incorrectly.")
        return
    }
    defer delete(data)

    json_data, err := json.parse(data)
    if err != .None {
        fmt.println("Json couldn't be parsed")
        return
    }
    defer json.destroy_value(json_data)

    root := json_data.(json.Object)
    value := root["val"].(json.Float)

    fmt.println("Value read:", value)

    value_negative_10: f64 = 10.0 * (-1)
    fmt.println("Value real:", value_negative_10)
}
```

The output is:

Odin:        dev-2024-09:962af780a
OS:           Ubuntu 24-04-1 LTS, Linux 6.8.0-45-generic
CPU:         AMD Ryzen 7 5800H with Radeon Graphics
RAM :       15388 MiB
Backend:  LLVM18.1.8

## Expected Behavior
```
Value read: -10
Value real -10
```
## Current Behavior
```
Value read: -9.983125437429408
Value real: -10
```
## Info
I do not know enough about the json parsing odin uses and so this could be expected behaviour. I have tested parsing the same json file in python (I know, not a fair comparison) and it correctly parsed this. If this is expected, I am sorry.

**Comment by tf2spi** [comment]
This might be related to #4397

**Comment by Holub-Patrik** [comment]
Yes indeed it did.
