### ISSUE TITLE
Suspicious code in `map_total_allocation_size`

### ISSUE THREAD

**Issue by radekm** [odin-lang/Odin#4372]
## Context

I'm looking into the source code in `dynamic_map_internal.odin` where is the function `map_total_allocation_size`
which contains following code

https://github.com/odin-lang/Odin/blob/55ff1769d0591c3b26ddba746e5f6c6dba1ff286/base/runtime/dynamic_map_internal.odin#L344-L350

## Expected Behavior

I would expect that `size` is incremented by `+=` not replaced by `=`.

**Comment by mweihs** [comment]
It is incremented in the called proc (shortened here for clarity):

`map_cell_index_dynamic :: proc(base: uintptr, ...) {return `base + ...}`

**Comment by radekm** [comment]
Oh, didn't see that. Thanks for clarifying
