### ISSUE TITLE
deleting a string allocated with temp_allocator crashes the program

### ISSUE THREAD

**Issue by SrMordred** [odin-lang/Odin#4375]
## Context
Deleting a string allocated with temp_allocator crashes the program

* Operating System & Odin Version:
```       
        Odin:    dev-2024-10-nightly:af9ae48
        OS:      Windows 11 Professional (version: 22H2), build 22621.4317
        CPU:     AMD Ryzen 5 1600 Six-Core Processor
        RAM:     16313 MiB
        Backend: LLVM 18.1.8
```
## Expected Behavior
deleting temp_allocator should be a noop. 

## Current Behavior
Crashing on delete

## Failure Information (for bugs)
`terminated with exit code: -1073740940. `

### Steps to Reproduce
```odin
str := strings.clone_from( string("testing"), context.temp_allocator )
delete(str)
```

**Comment by Kelimion** [comment]
That's not a bug. Allocations need to be freed on the allocator they were made on:
```odin
str := strings.clone_from( string("testing"), context.temp_allocator )
delete(str, context.temp_allocator)
```

**Comment by Kelimion** [comment]
Alternatively you could call `free_all(context.temp_allocator)` to free the entire scratch arena:
```odin
package bug

import "core:fmt"
import "core:strings"

main :: proc() {
	str := strings.clone_from(string("testing"), context.temp_allocator)
	defer free_all(context.temp_allocator)
	fmt.println(str)
}
```
