### ISSUE TITLE
os.read_entire_file() uses cotext.temp_allocator even when specifiied not to

### ISSUE THREAD

**Issue by michaelcrichlow** [odin-lang/Odin#4383]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System & Odin Version:
* Please paste `odin report` output:

        Odin:    dev-2024-07:e7d37607e
        OS:      Windows 10 Home Basic (version: 22H2), build 19045.5011
        CPU:     Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
        RAM:     32646 MiB
        Backend: LLVM 18.1.8

## Expected Behavior

I'm learning how to open and read files with Odin. Since I'm new to memory managed languages, I have 2 tracking allocators to help me not to leak memory (one for context.allocator and the other for context.temp_allocator). When opening and reading a file as follow:

    read_file_by_lines_in_whole :: proc(filepath: string) {
	    data, ok := os.read_entire_file(filepath, context.allocator)
	    if !ok {
		    // could not read file
		    return
	    }
	    defer delete(data, context.allocator)

	    // print(data)
	    it := string(data)
	    print(it)
    }

The result in the terminal is as follows:

    The quick brown fox jumps over the lazy dog.
    === 1 allocations not freed: context.temp_allocator ===
    - 94 bytes @ C:/Users/mikec/source/repos/Odin/core/sys/windows/util.odin(41:10)

This is strange to me since I never used context.temp_allocator and wondered if this is the expected behavior. 

## Current Behavior

The file that I used for this is here:
https://github.com/michaelcrichlow/2024_10_15---odin_strange_behavior/blob/main/odin_strange.odin

A short video of my experience is here:
https://youtu.be/EVx_oxqhOn0

The reason I'm sharing this information is that it feels like Odin is allocating memory in the temp_allocator without telling me, which -- if it is the intended behavior -- would encourage me to call 
    free_all(context.temp_allocator)
periodically "just in case", which I think contradicts coding with knowledge and intention. Actions should have definite reasons for existing, not be born out of uncertainty. 

## Failure Information (for bugs)

I don't know if this is a bug. I'm asking if this is the intended behavior.

**Comment by flysand7** [comment]
On windows, package `os` uses `context.temp_allocator` to convert Odin's UTF-8 strings into UTF-16 for calls into the Windows API. It is not a bug, I think the idea was that you free all of that data together with the other temporary data.

Unfortunately this is not made explicit by the interface and it is one of the problems that the `os2` package (a rewrite of the OS package with API improvements) will be solving once it's more ready for use.

For now I suggest you free your temporary allocator on some convenient basis. Either after every time you do a series of `os` calls, or after the end of every frame, in case you're making a game or another frame-based application. For now this is the correct way to interface with the os package.

**Comment by michaelcrichlow** [comment]
Ah, okay. Thanks so much for the clarification! Indeed, the API does not make it clear that a call to the `os` package uses `context.temp_allocator` whether you specify that or not. I'll be careful with it and look forward to the `os2` package (whenever it arrives). >_<

Thanks again! :)

**Comment by laytan** [comment]
Something else to note here is that if you keep the `context.temp_allocator` as the default, you will not leak because it automatically frees the temporary memory before returning. Because you wrapped it in a custom allocator (the tracking allocator) you effectively opt-out of that functionality and are expected to handle freeing yourself.

**Comment by michaelcrichlow** [comment]
Wow, I didn't know such a thing was possible. I thought the tracking allocators just told you what happened, not possibly change the behavior because they exist. >_< Regardless, I'll still use them because they give me peace of mind that all allocations were freed.
