### ISSUE TITLE
Missing shared dir in new odin release odin-windows-amd64-dev-2024-10

### ISSUE THREAD

**Issue by kulkalkul** [odin-lang/Odin#4384]
``\shared`` was present in previous GH release ``odin-windows-amd64-dev-2024-9``, but not in the current ``odin-windows-amd64-dev-2024-10``. This broke OLS using ``odin check`` as OLS looks for that dir, here is the relevant issue: https://github.com/DanielGavin/ols/issues/527

I was told in the Discord by laytan ``\shared`` probably shouldn't be missing, so here I am.

**Comment by laytan** [comment]
I skimmed the latest changes and don't immediately know why it's not there 🤔

**Comment by laytan** [comment]
Hmm may be the recent changes where hidden files are excluded from upload-artifact (iirc), the only file there is .gitkeep, and then you'd have an empty directory, which may be excluded too?

**Comment by kulkalkul** [comment]
I have no idea on how GH actions works, so pass on me.

**Comment by laytan** [comment]
May be fixed in that commit, I will check and reopen if not
