### ISSUE TITLE
os2.is_file not working

### ISSUE THREAD

**Issue by SrMordred** [odin-lang/Odin#4389]
## Context

`os2.is_file` are not working on windows

* Operating System & Odin Version:
```
        Odin:    dev-2024-10-nightly:af9ae48
        OS:      Windows 11 Professional (version: 22H2), build 22621.4317
        CPU:     AMD Ryzen 5 1600 Six-Core Processor
        RAM:     16313 MiB
        Backend: LLVM 18.1.8
```

## Expected Behavior

Same as `os.is_file`

## Current Behavior

Unable to get the file type properly

this function gets the file type, but on 
https://github.com/odin-lang/Odin/blob/b82f8df5f5168fb7bd210d7bb99bd0a6bf176a80/core/os/os2/stat_windows.odin#L197

the file handle are nil. Causing `file_type` to return `.Undetermined`. 
https://github.com/odin-lang/Odin/blob/b82f8df5f5168fb7bd210d7bb99bd0a6bf176a80/core/os/os2/stat_windows.odin#L225

Since the file type that are compared here, it returns false for existing files. 
https://github.com/odin-lang/Odin/blob/b82f8df5f5168fb7bd210d7bb99bd0a6bf176a80/core/os/os2/file.odin#L294

**Comment by flysand7** [comment]
Uh oh, the git blame shows me as the culprit... I was messing around with type info and might have broken (did it work?) the stat. I'd have to think about this one before submitting a fix.
