### ISSUE TITLE
unmarshal does not free correctly it seems.

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#4391]
## Context

I am calling `marshall_err := json.unmarshal(data, ...);`

and I see there is a missing free at:
`D:/Program Files/Odin/core/encoding/json/unmarshal.odin(292:10)`

Odin version:
        Odin:    dev-2024-08-nightly:8359995
        OS:      Windows 11 Home Basic (version: 23H2), build 22631.4317
        CPU:     13th Gen Intel(R) Core(TM) i9-13900HX
        RAM:     32507 MiB
        Backend: LLVM 18.1.8

## Expected Behavior

I would expect it to clean up after itself.

## Current Behavior

It does not.

## Fix 

change from:
```
	case .String:
		advance_token(p)
		str := unquote_string(token, p.spec, p.allocator) or_return
		if unmarshal_string_token(p, any{v.data, ti.id}, str, ti) {
			return nil
		}
		delete(str, p.allocator)
		return UNSUPPORTED_TYPE
```

To:
```
	case .String:
		advance_token(p)
		str := unquote_string(token, p.spec, p.allocator) or_return
		defer delete(str, p.allocator)
		if unmarshal_string_token(p, any{v.data, ti.id}, str, ti) {
			return nil
		}
		return UNSUPPORTED_TYPE
```

str does not seem to be used anywhere else, so it should be deleted even when it returns nil.

**Comment by laytan** [comment]
It's been unmarshalled into your datastructure, for example:
```odin
Data :: struct { foo: string }
d: Data
err := json.unmarshal(transmute([]byte)string("{ foo: \"Hellope\" }"), &d)
assert(err == nil)
defer delete(d.foo)

fmt.println(d.foo)
```

**Comment by xzores** [comment]
This is my data structure:
```
Component_info :: struct {
	terminal_points : [][2]int, //As ints because they should always line up with the grid
	shapes : []Shape,
	trigger_key : render.Key_code,
	prefix : string,
	small_number : bool,
}
```

This is how I delete it:
```
delete_components :: proc (components : map[string]^Component_data) {
	for k, c in components {
		delete(k);
		delete(c.terminal_points);
		delete(c.shapes);
		delete(c.prefix);
		free(c);
	}
	delete(components);
}
```

Am I blind or do I not delete everything correctly?
I delete:
terminal_points, shapes and prefix which is the only heap allocated stuff...

**Comment by laytan** [comment]
If you have an actual reproduction instead of just snippets that would help, might help updating Odin too.

**Comment by laytan** [comment]
Does this fix it for you?:
```odin
	case .String:
		advance_token(p)
		str  := unquote_string(token, p.spec, p.allocator) or_return
		dest := any{v.data, ti.id}
		if !unmarshal_string_token(p, dest, str, ti) {
			delete(str, p.allocator)
			return UNSUPPORTED_TYPE
		}

		switch destv in dest {
		case string, cstring:
		case: delete(str, p.allocator)
		}
		return nil
```

**Comment by xzores** [comment]
Yes, this seems to resolve me issue.
