### ISSUE TITLE
Type assertion on a pointer to a union doesn't return a pointer.

### ISSUE THREAD

**Issue by lunaticLipid** [odin-lang/Odin#440]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Odin version/Commit: 2dc39a5

## Expected Behavior

Type assertion on a pointer to a union gives a pointer to the contained value.

## Current Behavior

Type assertion gives a copy of the value.

```
package main

main :: proc() {
    u: union{int, string} = 1;
    up := &u;
    i, ok := up.(int);
    #assert(type_of(i) == int);
    #assert(type_of(i) != ^int);
}
```

Also, asserting on a directly referenced union gives the pointer as expected, but doesn't give the `ok` value.

```
package main

main :: proc() {
   u: union{int, string} = 1;
   i, ok := &u.(int);
}
```

`main.odin(5:5) Assignment count mismatch '2' = '1'`

**Comment by gingerBill** [comment]
This is not a bug. But it is not a clear error message.
