### ISSUE TITLE
Binary equivalent arrays should be castable to each other.

### ISSUE THREAD

**Issue by JesseRMeyer** [odin-lang/Odin#4428]
I've been handed a grab bag of data in the form of a linear array of floats, but I know the actual organization is more structured.  It's rather tedious and error prone to manually condition the syntax where a cast should just do the job.

```odin
data: [1080]f32 // But I know the data is actually [2][10][6][9]f32`
```

The two array shapes are compatible, and further more, after the cast they remain binary equivalent, and thus, should be castable to each other.  However, Odin throws a "Cannot cast" error in the attempt.

**Comment by Feoramund** [comment]
Wouldn't you use `transmute` in this case?

**Comment by JesseRMeyer** [comment]
That would satisfy the type system currently, but I think of `transmute` as a way to re-interpret the binary sequence to a new base type (like f32 to int), but in this case, the only difference is the indexing.  Thus, it seems like an abuse of an existing language feature, and that my suggestion of permitting this through a cast is more conceptually coherent.  To your point, we transmute quite a bit in the SIMD packages, and some of those could be done away I think were this accepted.
