### ISSUE TITLE
Arrays unexpectedly passed by reference

### ISSUE THREAD

**Issue by Zorbn** [odin-lang/Odin#4472]
## Context

* Operating System & Odin Version:
```
        Odin:    dev-2024-11-nightly:e6475fe
        OS:      Windows 11 Home Basic (version: 22H2), build 22621.4317
        CPU:     Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
        RAM:     49084 MiB
        Backend: LLVM 18.1.8
```

## Expected Behavior

Arrays should be passed by value, eg. the function should receive a copy of the array similar to if the array was assigned to another variable.

## Current Behavior

The compiler may choose to pass the array by reference causing difficult to diagnose bugs.

## Failure Information (for bugs)

This may be intended behavior, but it doesn't seem like it.

### Steps to Reproduce

```
package upbr

import "core:fmt"

my_proc :: proc(a: [2]int, b: ^[2]int) {
    c := a
    fmt.println(a, c)
    b^ = {3, 4}
    fmt.println(a, c)
}

main :: proc() {
    a := [2]int{1, 2}
    my_proc(a, &a)
}
```

```
odin.exe run .
[1, 2] [1, 2]
[3, 4] [1, 2]
```

### Failure Logs

N/A

**Comment by tf2spi** [comment]
Interestingly, I can reproduce this issue on Windows but not on Linux

**Comment by laytan** [comment]
This is expected behaviour.

**Comment by Zorbn** [comment]
Yeah this works as expected on Linux.
```
odin run .
[1, 2] [1, 2]
[1, 2] [1, 2]
```

```
	Odin:    dev-2024-11-nightly
	OS:      Ubuntu 22.04.3 LTS, Linux 5.15.153.1-microsoft-standard-WSL2
	CPU:     Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	RAM:     24004 MiB
	Backend: LLVM 18.1.6
```

**Comment by laytan** [comment]
It works as expected everywhere. The abi is different so the rules that determine when it's done is different per abi/architecture.

**Comment by tf2spi** [comment]
> Yeah this works as expected on Linux.
> 
> ```
> odin run .
> [1, 2] [1, 2]
> [1, 2] [1, 2]
> ```
> 
> ```
> 	Odin:    dev-2024-11-nightly
> 	OS:      Ubuntu 22.04.3 LTS, Linux 5.15.153.1-microsoft-standard-WSL2
> 	CPU:     Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
> 	RAM:     24004 MiB
> 	Backend: LLVM 18.1.6
> ```
> 
> EDIT: And the same problem happens (on Windows, but again not on Linux) if you use a struct like
> 
> ```
> Vector2 :: struct {
>     x: int,
>     y: int,
> }
> ```
> 
> instead of `[2]int`, which is counter-intuitive when the docs say:
> 
> > Continuing the C family tradition, everything in Odin is passed by value (rather than by reference, e.g. FORTRAN, Java, etc).

[System V ABI document](https://refspecs.linuxbase.org/elf/x86_64-abi-0.99.pdf) and [Windows x64 Calling Convention](https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170) is helpful to explain why the value is copied and any other ABI questions. Laytan already explained the difference in this scenario so I won't beat a dead horse but these are helpful documents for learning the ABIs in general.

**Comment by Zorbn** [comment]
This only happens in Odin with the "odin"/"contextless" calling conventions, not "stdcall"/"fastcall"/"c", and not with struct types in C, so to be honest I'm not sure what the relevance of the Windows x64 calling convention is here. Anyways, it seems like this is viewed as a feature so I'll close the issue.

**Comment by tf2spi** [comment]
> This only happens in Odin with the "odin"/"contextless" calling conventions, not "stdcall"/"fastcall"/"c", and not with struct types in C, so to be honest I'm not sure what the relevance of the Windows x64 calling convention is here. Anyways, it seems like this is viewed as a feature so I'll close the issue.

It explains why Windows passes it as a pointer and why Linux passes it as 2 register values. That is surprising behavior that ``stdcall`` and friends change the behavior and perhaps this is because ``llvm`` does something special if you explicitly specify the calling convention. That's a nice TIL!
