### ISSUE TITLE
Type guards

### ISSUE THREAD

**Issue by czlowiek488** [odin-lang/Odin#4475]
# PLEASE POST THIS IN THE DISCUSSION TAB UNDER "PROPOSALS" OR "IDEAS/REQUESTS"

**Is your feature request related to a problem? Please describe.**
When I do and if that make some check, for example.
```
a: Maybe(int)
if a != nil {
// a is recognized by compiler as `Maybe(int)` rather than `int` which is what I would expect 
}
```

**Describe the solution you'd like**
I would like to have correct type recognized inside if statement, I guess this is something called as type guards.
Now afaik I need to create another variable like below to use `a` as int. Even though is not much effort to do, it's a little annoying for me to do so.
```
a: Maybe(int)
if a != nil {
aInt := a.(int)
}
```

**Additional context**
Odin is my first low level language I use, I proffesionaly work with typescript which is on the different level as a programming language.
However I create my game as a pet project in Odin.
I'm not proficient with low level languages and I'm still learning. I don't even want to persuade anyone to implement this feature.
This issue is more like a question I would want to know the answer for.
Does this future make sense, would you like to consider the idea of it?
Or maybe there are some limitations of the compilers I don't know about?
Or maybe it's how it was intended to be, or maybe there is other way of achieving what I would like?

Anyway, I wanted also thank for creating such easy to use language. I never though low level languages could be as good as Odin. Even though as a beginner in low level world I can complain a little about lack of well documented parts of Odin, it's the language I will use for years. Thank you all!

**Comment by gingerBill** [comment]
No. You can utilize shadowing if you prefer.

```odin
if a, ok := a.?; ok {
   ...
}
```
