### ISSUE TITLE
Compiler segfault on abs(no_return_value())

### ISSUE THREAD

**Issue by dayllenger** [odin-lang/Odin#4508]
## Context

	Odin:    dev-2024-11:e607cbe93
	OS:      Arch Linux, Linux 6.6.60-1-lts
	CPU:     Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
	RAM:     7686 MiB
	Backend: LLVM 18.1.8

### Steps to Reproduce

```
package main

main :: proc() {
	p :: proc() {}
	abs(p())
}
```
```
$ odin build .
segmentation fault (core dumped)
```

Also fails with `min`, `max`, and some other builtin functions.

**Comment by Kelimion** [comment]
Fixed in #4516. I'm looking over other builtins before I merge it.
