### ISSUE TITLE
Debugger can't see local proc variables inside switch statement

### ISSUE THREAD

**Issue by Tekkitslime** [odin-lang/Odin#4519]
## Context

* `odin report`:
	Odin:    dev-2024-11:be5cdd7
	OS:      EndeavourOS, Linux 6.12.1-zen1-1-zen
	CPU:     AMD Ryzen 3 4100 4-Core Processor
	RAM:     15880 MiB
	Backend: LLVM 14.0.6

## Expected Behavior

I can see and inspect local procedure variables with GDB.

## Current Behavior

GDB only shows procedure paramaters and context in case of the default calling convention.

## Failure Information (for bugs)

Placing an `intrinsics.debug_trap()` inside a switch statement's case, GDB doesn't show local procedure variables.

### Steps to Reproduce

1. Create a procedure with a local variable and a switch statement.
2. Place a debug trap in a case and open debugger
3. Run the program until it reaches the trap
4. `i locals`

```odin
package test

import "core:fmt"
import "base:intrinsics"

main :: proc() {
	foo("user")
}

foo :: proc(bar: string) {
	baz := 100

	switch {
		case true: {
			intrinsics.debug_trap()
			fmt.printf("Hello, %v; %v\n", bar, baz)
		}
	}
}
```

**Comment by laytan** [comment]
Should be good now, actually should improve the debugging of things with scopes a lot in general.
