### ISSUE TITLE
Cannot compile latest master branch

### ISSUE THREAD

**Issue by bbodi** [odin-lang/Odin#452]
## Context

Could not compile the latest master branch.

* Operating System: Ubuntu
* Odin version/Commit: 2db16d6a320c2c59bb5e932d7ed291dcc011af65

## Expected Behavior

build is successful

## Current Behavior

Error: `Odin/core/unicode/utf8/utf8.odin(172:11) Undeclared name: r`

### Steps to Reproduce

```
git clone https://github.com/gingerBill/Odin
cd Odin
./build.sh
```

**Comment by gingerBill** [comment]
@bbodi This has been fixed straight away. It was a typo.
