### ISSUE TITLE
Weird octal literal values

### ISSUE THREAD

**Issue by Waqar144** [odin-lang/Odin#4530]
## Context

I reported https://github.com/odin-lang/odin-lang.org/pull/260 and tried some more examples and found some weird things

`odin report`:
```
        Odin:    dev-2024-10-nightly
        OS:      Manjaro Linux, Linux 6.6.54-2-MANJARO
        CPU:     AMD Ryzen 7 4700U with Radeon Graphics         
        RAM:     15355 MiB
        Backend: LLVM 18.1.6
```

The following code prints `[255]`:
```odin
package main
import "core:fmt"
main::proc() {
	v := "\377"
	fmt.println("\377", transmute([]u8)v)
}
```

The following prints `253 65533`:
```odin
package main
import "core:fmt"
main::proc() {
	v :i32 = '\377'
	x :u8 = u8(v)
	fmt.println(x, v)
}
```

**Comment by laytan** [comment]
```odin
v: i32 = '\377'
fmt.println(v) // 65533
```
definitely seems wrong while the rest seems correct.

Also, I was actually wrong and you were right in my response on the docs issue it looks like the first digit for octal escape sequences doesn't have to be `0` like I thought.

**Comment by gingerBill** [comment]
It's being parsed and processed correctly too. So is it off by one?
