### ISSUE TITLE
`math.wrap` and `math.mod` don't accept `int` types.

### ISSUE THREAD

**Issue by Tekkitslime** [odin-lang/Odin#4538]
## Context
 ```
odin report
Odin:    dev-2024-11:be5cdd7
OS:      EndeavourOS, Linux 6.12.1-zen1-1-zen
CPU:     AMD Ryzen 3 4100 4-Core Processor
RAM:     15880 MiB
Backend: LLVM 14.0.6
```

## Expected Behavior

calling `math.wrap` and `math.mod` with ints should give the appropriate result.

## Current Behavior

`math.wrap` and `math.mod` accept only float types, since `math.mod` is only defined for floats; both procedures fail with integers.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. call either procedure with integer types.

```Odin
package test

import "core:fmt"
import "core:math"

main :: proc() {
	fmt.println(math.wrap(22, 10))
}
```

**Comment by gingerBill** [comment]
Because it's literally not needed for integers. Integers have actual syntax for this.
```
x % y
x %% y
```
