### ISSUE TITLE
encoding.json JSON5 failing to parse single-quote strings

### ISSUE THREAD

**Issue by andradei** [odin-lang/Odin#4549]
## Context

`enconding/json`'s `Specification.JSON5` failes to `json.unmarshal` JSON object with single-quote strings.

* Operating System & Odin Version:
  - Arch linux
  - odin version dev-2024-11:be5cdd759

* Please paste `odin report` output:

```
Where to find more information and get into contact when you encounter a bug:

        Website: https://odin-lang.org
        GitHub:  https://github.com/odin-lang/Odin/issues


Useful information to add to a bug report:

        Odin:    dev-2024-11:be5cdd759
        OS:      EndeavourOS, Linux 6.12.1-arch1-1
        CPU:     AMD Ryzen 5 2600 Six-Core Processor            
        RAM:     15901 MiB
        Backend: LLVM 18.1.8
```

## Expected Behavior

JSON5 object with single-quote string value should parse successfully (as it does with double-quote strings).

## Current Behavior

Runtime error: `Invalid_Data`
In another example (other than the one below, it returns this:
![image](https://github.com/user-attachments/assets/c3c90cc4-ec27-421b-9678-12ca80f30a73)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run the example code below
2. Feeding it a JSON5 object with single-quote string
3. Compile and run
4. Replacing single quotes with double quotes in `single_quotes: 'fails'` below fixes it

```odin
package main

import "core:encoding/json"
import "core:fmt"
import "core:strings"

main :: proc() {
	json5_data := `{
  single_quotes: 'fails'
  double_quotes: "passes"
}`


	Json5Data :: struct {
		single_quotes: string,
		double_quotes: string,
	}

	result: Json5Data
	if err := json.unmarshal(transmute([]byte)json5_data, &result, spec = .JSON5); err != nil {
		fmt.panicf("%v", err)
	}
}
```

**Comment by gingerBill** [comment]
Well that bug was simple. `==` vs `!=`
