### ISSUE TITLE
cstrings are not working correctly

### ISSUE THREAD

**Issue by JoshuaManton** [odin-lang/Odin#455]
## Context

* Operating System: Windows 10
* Odin version/Commit: 416ff149bd0f3ae1ff7d8093450cf42fc4aa3994

## Expected Behavior

The following assertion should not fail

## Current Behavior

The assertion is failing

## Failure Information

```
package main

main :: proc() {
    cstr : cstring = "Hello";
    assert(cstr == "Hello");
}
```

NOTE: This started happening in commit 7140f4291546748adf2ddb977f3605f7aab31856

The following program has strange output that may help with diagnosing the bug:
```
package main

import "core:fmt"
import "core:mem"

main :: proc() {
    cstr : cstring = "Hello";
    fmt.println(cstr);

    str := cast(string)cstr;
    fmt.println(str);

    raw_str := transmute(mem.Raw_String)str;
    fmt.println(raw_str);

    raw_str.len = 5;
    fmt.println(transmute(string)raw_str);
}
```
Output:
```


Raw_String{data = 0x7FF73F7C77ED, len = 0}
Hello
```

**Comment by gingerBill** [comment]
This should be fixed in the latest commit now.
