### ISSUE TITLE
Removing one of my `using` statements is crashing the compiler

### ISSUE THREAD

**Issue by Tkap1** [odin-lang/Odin#4552]
## Context
I have a `using` statement that I want to remove

Compilation command: `odin.exe build ..\game -build-mode:dll -debug -define:RAYLIB_SHARED=true -pdb-name:..\pdbs\game_%PDB_NUMBER%.pdb`

It still happens even with this compilation command `odin.exe build ..\game`

Odin:    dev-2024-11-nightly:e6475fe
OS:      Windows 10 Professional (version: 22H2), build 19045.5011
CPU:     Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
RAM:     16325 MiB
Backend: LLVM 18.1.8

## Expected Behavior

Compile or get a compilation error

## Current Behavior

Compiler crashes with exit code -1073741819

### Failure Logs

[odin.exe.16040.dmp](https://github.com/user-attachments/files/17987165/odin.exe.16040.dmp)

Video of it happening
https://github.com/user-attachments/assets/21f3dfef-f133-4dd0-9413-283b0334b3fa

Project
[game.zip](https://github.com/user-attachments/files/17987284/game.zip)

**Comment by wrapperup** [comment]
I've narrowed down the issue, if the LHS of a `>=` expression inside a `for` has an undefined variable, that causes the issue. Here's a minimal repro:

```c++
package main

import "core:fmt"

main :: proc() {
	x := 20 // Comment this out to cause issue
	y := 0

	for x >= y { // Issue happens here
		fmt.println(x)
		y += 1
	}
}

```

@Tkap1 In your case, the issue was on line 38, the left-hand variable `spawn_timer` is undefined.
