### ISSUE TITLE
Import failure for frameworks 

### ISSUE THREAD

**Issue by Platin21** [odin-lang/Odin#457]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOS Catalina
* Odin version/Commit: 2db16d6

## Expected Behavior

The Import works normally and gets linked with the binary.

## Current Behavior

It doesn't link with it and discards the import in the IR Stage.
Because there are no symbols linked in that i could use 
from these frameworks.

## Failure Information (for bugs)

Linkage error with lld can also be done manually but this would
Make using the osv2 on macOS useless e.g you would need to link 
Manually with every single thing yourself 

### Steps to Reproduce #
Try to compile: https://github.com/Platin21/odin-objc

**Comment by Platin21** [comment]
We discussed that @force for this foreign import would work. 
So this would be a thing to be implemented.

**Comment by gingerBill** [comment]
I have just added `@force` to `foreign import` int he latest comment 3b898r5
