### ISSUE TITLE
Floats being scrambled in arm32 abi

### ISSUE THREAD

**Issue by Pingar5** [odin-lang/Odin#4575]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
I am building for linux_arm32 (for a raspberry pi) so I am building to object files on my windows PC using this command:
`odin build . -target:linux_arm32 -build-mode:obj`

Then on the pi, I am compiling those object files in with my c code (which in the real project is raylib) using this CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.5)
set(CMAKE_C_STANDARD 99)

project(game)

add_executable(game
    game-main.o game-runtime.o game.o
    main.c
)
```

* Operating System & Odin Version:
* Please paste `odin report` output:
        Odin:    dev-2024-10-nightly:af9ae48
        OS:      Windows 10 Enterprise (version: 22H2), build 19045.5247     
        CPU:     11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz
        RAM:     32645 MiB
        Backend: LLVM 18.1.8

## Expected Behavior

f32s passed to c should maintain their values

## Current Behavior

The values are being scrambled

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

1. Build the following odin file for linux_arm32 in obj mode
```
package main

foreign _ {
    repro :: proc "c" (i: f32) ---
}

main :: proc() {
    repro(100)
}
```

2. Move the output files to an arm32 linux machine along with this c file:
```c
#include <stdio.h>

extern void repro(float x) {
    printf("%f\n", x);
}
```

3. Compile them together using the CMake file above 
4. Run the program

### Failure Logs
This has worked perfectly across the board except for one major issue: floats are getting entirely scrambled when passed to c. The above code prints 0.0000 but I have also seen floats transform like this `100 -> 1.4e-43`, `200 -> 2.8e-43`, `400 -> 4.2e-43`, `60 -> 683.0` depending on the context

**Comment by Pingar5** [comment]
I wrote the same program in C and built it the same way so I could compare the generated assembly. Here is that file:
```c
extern void repro(float a);

int main() {
    repro(100.0);
}
```

And here is the assembly that odin is generating:
![image](https://github.com/user-attachments/assets/379c07f5-f4e9-4d18-8b4a-561b5795a968)

And the assembly that c is generating:
![image](https://github.com/user-attachments/assets/b4f812e9-db99-4427-bded-05c17098b514)

**Comment by Pingar5** [comment]
I no longer think this is a bug! I just needed to set my microarch to mpcore to build for RPi!

Figured that out by comparing the LLVM ir from clang & odin compiler for the similar programs and finding the "target-cpu"="mpcore" attribute being applied to all of the functions in the clang version

**Comment by Kelimion** [comment]
Thanks for the feedback on that. Good to know in case someone else targets RPi 32-bit in the future.
