### ISSUE TITLE
Unused variable error despite not using -vet-unused etc.

### ISSUE THREAD

**Issue by mtarik34b** [odin-lang/Odin#4581]
If an unused variable is declared inside a for-loop or an if-cond, a *'declared but not used'* error occurs despite compiling without `-vet-unused` and alike. This one triggers: https://github.com/odin-lang/Odin/blob/8b1c9b0ff5b7ad392fa48e050eae460da8edb982/src/check_stmt.cpp#L1594

**Odin Version:**
Odin:    dev-2024-12:8b1c9b0ff

### Steps to Reproduce
Build below program with `odin build .`
```odin
package pkg

main :: proc() {
	for i in 0 ..< 2 {
		var: int
	}

	if true { x := 123 }
}
```
### Failure Logs
```
Error: 'var' declared but not used 
        var: int 
        ^~^ 
Error: 'x' declared but not used 
        if true { x := 123; } 
                  ^ 
```

**Comment by gingerBill** [comment]
So this isn't a bug and actually by design. It might seem like a bug, but it's fundamentally because code like this is pretty much always a bug or unintended.
