### ISSUE TITLE
Allow `{...}` syntax to coerce to `[N]T` like it does for `[]T`

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#460]
```go
package test;

f :: proc($D: int, a: [D]int) {
	assert(a[0] == 2);
	assert(a[1] == 4);
}

main :: proc() {
        // Index 0 is out of bounds (>= 0) for array literal
        // Index 1 is out of bounds (>= 0) for array literal
        // Cannot assign value '{2, 4}' of type '[0]int' to '[2]int' in argument
	f(2, {2, 4});
}
```

**Comment by gingerBill** [comment]
This is not actually a bug, per se, but how polymorphic parameters are handled. The parameters need to be evaluated beforehand, which causes this issue here. A better error message is needed instead.

**Comment by Tetralux** [comment]
You mean that `{2, 4}` cannot be evaluated before `$D` is but it tries to do that and can't?
Does this only happen with fixed-size arrays? Only I feel like even the stdlib has examples of this pattern working just fine.

Or is it more to do with it being `{2, 4}` rather than `T{2, 4}` ?

**Comment by gingerBill** [comment]
In this case, because the target is polymorphic and how I have set the rules, each parameter is determined _before_ the polymorphic parameters are determined. This means that it has no idea what it's passing to.
