### ISSUE TITLE
Polymorphic parameter declared in return type doesn't compile

### ISSUE THREAD

**Issue by sci4me** [odin-lang/Odin#464]
This code:
```
default :: proc() -> $T {
    t : T;
    return t;
}
```
Produces this compiler error: `Invalid use of a polymorphic type '$T' in variable declaration`.

**Comment by Tetralux** [comment]
I've been wondering if this should be allowed for a while. Definitely would be handy. 💯

**Comment by sci4me** [comment]
And of course, you could just do this:
```
default :: proc($T: typeid) -> T {
	t: T;
	return t;
}
```

But then you have to actually explicitly specify the type...
