### ISSUE TITLE
For loop buggy when using len

### ISSUE THREAD

**Issue by F0x1fy** [odin-lang/Odin#466]
## Context

When using `len` in the iteration count for a for loop without altering the value of the `len` will cause the compiler to output bugs.

* Operating System: Windows
* Odin version/Commit: 40546fb

## Expected Behavior

For loop should be able to use `len` without requiring an alteration to the value

## Workaround

Currently, you have to alter the value in order to inline the for loop (I used ` - 0` as per Tetralux's request and it worked)

## Failure Information (for bugs)

In the particular example I'm about to show, it gives these bugs:
`Syntax Error: Expected '}', got ':'`
`Syntax Error: Expected '{', got '='`

(Yes, in that order. I too find it odd it's trying to find a `}` before a `{`)

## Sample Code

```
broken_for :: proc(arr: []$T) {
    inline for i in 0..<len(arr) {
        j := i;
    }
}
```

### Workaround:

```
broken_for :: proc(arr: []$T) {
    inline for i in 0..<len(arr) - 0 {
        j := i;
    }
}
```

**Comment by gingerBill** [comment]
This should be fixed now. This was a parsing error.
