### ISSUE TITLE
Can't use size_of in range of inline for

### ISSUE THREAD

**Issue by sci4me** [odin-lang/Odin#468]
```
package main

import "core:fmt"

main :: proc() {
    inline for i in 0..<size_of(u32) {
    }
}
```

This fails with:

```
test.odin(8:1) Syntax Error: Expected '{', got '}'
test.odin(8:2) Syntax Error: Expected '}', got 'EOF'
```

**Comment by mhjspiir** [comment]
Please try and make your bug reports fit our issue template https://github.com/odin-lang/Odin/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ThisDrunkDane** [comment]
Please use our issue templates when reporting bugs https://github.com/odin-lang/Odin/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
