### ISSUE TITLE
Illegal compound literal type error on #raw_union tagged struct

### ISSUE THREAD

**Issue by godratio** [odin-lang/Odin#470]
## Context

OSX 10.14
odin version 0.11.0

## Expected Behavior

When defining a struct like this 

```
float2 :: struct #raw_union
{
    using _: struct { x, y: f32 },
    using _: struct { u, v: f32 },
}
```

initialize struct per the normal behavior

`a := float2{1,1};`

## Current Behavior

Compiler errors with message:
Illegal compound literal type 'float2'

**Comment by gingerBill** [comment]
@godratio A better error message is needed here. Currently, compound literals with elements are not supported for `struct #raw_union`. I recommend just using an array for this case however.

```
float2 :: distinct [2]f32;

a := float{1, 1};
a[0] = 2;
a[1] = 3;
a.x = 1; 
a.y = 3;
```

**Comment by godratio** [comment]
OK thanks.
