### ISSUE TITLE
cannot pass Vector3, Vector4 to poly proc

### ISSUE THREAD

**Issue by kevinw** [odin-lang/Odin#471]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Odin version/Commit: 2ef7bfc06

## Expected Behavior

You should be able to pass `Vector3` or `Vector4` to the procedure.

## Current Behavior

`Cannot determine polymorphic type from parameter: '^Vector3' to '^[0]f32'`

### Steps to Reproduce

```
package polytest

import "core:intrinsics"
import "core:fmt"
using import "core:math/linalg"

vector_test :: proc(v: ^[$N]f32)
    where intrinsics.type_is_integer(type_of(N)) && N > 0
{

    when N <= 4 {
        when N > 0 do fmt.println("x:", v[0]);
        when N > 1 do fmt.println("y:", v[1]);
        when N > 2 do fmt.println("z:", v[2]);
        when N > 3 do fmt.println("w:", v[3]);
    } else {
        inline for j in 0..<N {
            fmt.printf("[%d]: %f\n", j, v[j]);
        }
    }
}

main :: proc() {
    // v := [3]f32 { 4, 5, 6 }; // WORKS

    v := Vector3 { 4, 5, 6}; // does not
    vector_test(&v);
}

```

**Comment by gingerBill** [comment]
This is not a bug. As `Vector3` is a distinct type, what you will need to do is the following:
```
proc(v: ^$V/[$N]f32)
```
This means get any type `V` which is a specialization of the form `[$N]f32`

**Comment by Tetralux** [comment]
Could maybe use a compiler suggestion for this?
