### ISSUE TITLE
Aligning struct fields

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#472]
Something like this:
```
S :: struct {
	x: int,
	y: int #align 16,
}
```
And if multiple fields have conflicting alignment requirements, or if the alignment cannot be achieved: compile error.

**Comment by gingerBill** [comment]
Wrap the int in a struct with that custom alignment.

**Comment by Tetralux** [comment]
In my real example, the first field of `S` was a `struct` and it needed to be aligned, so I just could align `S` instead - but even so, being able to put this attribute on specific fields could be useful.

**Comment by gingerBill** [comment]
```
S :: struct {
    x: int,
    using wy: struct #align 16 { y: int },
}
```
This will work just as well
