### ISSUE TITLE
Incorrect LLVM cast opcode emitted for user-defined struct.

### ISSUE THREAD

**Issue by NotKyon** [odin-lang/Odin#474]
## Context

![test-odin-failure-screenshot](https://user-images.githubusercontent.com/168207/68769450-effbd900-05e9-11ea-9dc6-7eb41947b8a6.png)

* Operating System: macOS 10.15.1 (Catalina)
    * `brew info llvm`: "llvm: stable 9.0.0 (bottled), HEAD [keg-only]"
* Odin version/Commit: aa796a1032a3027c5d6d8af19e4834c4a60cb302, master, v0.11.1

## Expected Behavior

The following code should build and run, producing "(0, 0)\n(1, 1)\n" on stdout.
```go
package main

import "core:fmt"

Vec2 :: struct {
    x, y: f32
};

display_vec :: proc( vec: Vec2 ) {
    fmt.printf( "(%g, %g)\n", vec.x, vec.y );
}

set_one :: proc( vec: ^Vec2 ) {
    vec.x = 1;
    vec.y = 1;
}

main :: proc() {
    v: Vec2;
    display_vec( v );
    set_one( &v );
    display_vec( v );
}
```

## Current Behavior

The above code fails with uncompilable LLVM IR.

## Failure Information (for bugs)

The failing IR that gets emitted:
```
	%5 = bitcast <2 x float> %_.0 to %main.Vec2
```

### Steps to Reproduce

If the above code snippet is placed into a file named "test-odin.odin" then, with the latest built compiler, run the following shell snippet in the same directory as that file:

`odin run ./test-odin.odin`

### Failure Logs

Here's the source code and corresponding LLVM IR: [test-odin.zip](https://github.com/odin-lang/Odin/files/3841408/test-odin.zip)

**Comment by gingerBill** [comment]
Fixed!
