### ISSUE TITLE
Assigning and comparing Enumerations to their base type without cast

### ISSUE THREAD

**Issue by st142148** [odin-lang/Odin#477]
Currently this code:
```
Enumeration :: enum int { Zero, One, Two}
main :: proc() {
    integer0 : int = Enumeration.Zero;

    integer1 : int = 0;
    if integer1 == Enumeration.Zero do fmt.println("equal");
}
```
Gives these two errors:
> Cannot assign value 'Enumeration.Zero' of type 'Enumeration' to 'int' in variable declaration

> Cannot compare expression, mismatched types 'int' and 'Enumeration'

even though the base type is also int. 
Now, this can be resolved by explicitly casting the enum to int each time, but you should not have to do this.

**Comment by gingerBill** [comment]
This is not a bug. You must explicitly cast. The base type of an enum means it sets the backing type. An enum is a distinct type to its base type.
