### ISSUE TITLE
Using shadows parameters

### ISSUE THREAD

**Issue by sci4me** [odin-lang/Odin#480]
I'm not sure if this is a bug or should be a feature request. Basically, I ran into a case where I was using a local variable in a procedure and some of the fields in the struct I was using shadowed some of the parameters to my procedure, but the compiler let it happen.

It's easiest to demonstrate with code:

```
package main

import "core:fmt"

Vec2 :: struct {
    x, y: int
}

foo :: proc(x, y: int) {
    using r := Vec2{1, 2};
    
    fmt.println(x, y);
}

main :: proc() {
    foo(4, 2);
}
```

This program prints out: `1 2`.

I would expect it to give an error about re-declaration of `x` and `y`.

**Comment by gingerBill** [comment]
If you want shadowing to be an error, use `-vet`.
