### ISSUE TITLE
LLVM IR Generation Bug via passing a structure to a proc pointer

### ISSUE THREAD

**Issue by sci4me** [odin-lang/Odin#482]
OS: Arch Linux
Odin commit: 301ee664e9f10bb47993b9ccf395628606052a64 (Updated; my mistake; posted the wrong SHA)

So here's another small example program that causes the compiler to generate invalid LLVM IR:

```
package main

import sdl "shared:odin-sdl2"

Key_Event_Proc :: #type proc(state: u8, sym: sdl.Keysym);

key_event_proc: Key_Event_Proc;

my_key_event_proc :: proc(state: u8, sym: sdl.Keysym) {

}

main :: proc() {
    if key_event_proc != nil do key_event_proc(42, sdl.Keysym{sdl.Scancode.A, 42, 42, 0});
}
```

(Sorry that this one requires a dependency but that's the case that kept happening to me)

The compiler (LLVM, actually) outputs this when trying to compile that code:
```
opt: test.ll:2766:12: error: '%9' defined with type 'void (i8, { i64, i64 }, %runtime.Context*)*' but expected 'void (i8, i64, i64, %runtime.Context*)*'
        call void %9(i8 42, i64 %12, i64 %13, %runtime.Context* noalias nonnull nocapture %0)
                  ^
```

Obviously the expected behavior is for nothing to be printed at all; the program should just compile and run with no issues.

**Comment by ThisDrunkDane** [comment]
Please use the issue template
