### ISSUE TITLE
String causes a crash when used in a polymorphic type

### ISSUE THREAD

**Issue by CaptainKraft** [odin-lang/Odin#483]
## Context

* Operating System: Windows
* Odin version/Commit: 44e0e96612fe7f08361ee3014d1230ccd9a2e39d

## Expected Behavior

Either I should get an error that I'm using the type wrong, or it shouldn't crash.

## Current Behavior

The compiler crashes with errors from the ll file.

## Failure Information (for bugs)

I'm not sure if I should be able to use a single value in place of an array of size 1, but it allows it for numbers. It crashes when I try to do it with any string other than the empty string.

Here is the output I'm getting:

`C:\Users\Jeremiah\dev\EmberGen\Odin\bin/opt: C:/Users/Jeremiah/dev/EmberGen/jui/demo/bug.ll:3893:79: error: constant expression type mismatch
        store %"bug.TestStruct-394.TestStruct\281\2C\20int\29-6187" {[1 x %..string] c"a\00", [1 x i64] [i64 10]}, %"bug.TestStruct-394.TestStruct\281\2C\20int\29-6187"* %0`

### Steps to Reproduce

1. Run the following code to see it complete successfully.
2. Uncomment the code with the test3 struct.
3. Crash.

### Code

```go
package bug

import "core:intrinsics"

TestStruct :: struct(N: int, T: typeid)
    where N >= 0, N <= 3,
    !intrinsics.type_is_array(T),
    intrinsics.type_is_numeric(T)
{
    strs: [N]string,
    vals: [N]T,
}

proc :: main() {
	// This works, but I'm not sure if it should.
	test1 := TestStruct(1, int) {
		"",
		10,
	};

	// This also works, and it certainly should
	test2 := TestStruct(2, f32) {
		{"Hi there.", "How are you?"},
		{0, 1},
	};

	// test3 := TestStruct(1, int) {
	// 	"This doesn't work...",
	// 	100,
	// };
}
```
Edit: bad copy/paste left out some code

**Comment by gingerBill** [comment]
@CaptainKraft This should be fixed now.
