### ISSUE TITLE
macOS: 'sh: opt: command not found'

### ISSUE THREAD

**Issue by jkleiser** [odin-lang/Odin#485]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: macOS 10.14.6 Mojave, with the latest Xcode installed
* Odin version/Commit: 0.11.1 (Latest commit 45d844f)

## Expected Behavior

I would like to produce an executable by doing `./odin build examples/hms2019/basic.odin`.

## Current Behavior

I just get the message `sh: opt: command not found`, no executable.

I got a similar message at the end of the `make` process:
```
$ make
clang src/main.cpp -Wno-switch -Wno-pointer-sign -Wno-tautological-constant-out-of-range-compare -Wno-tautological-compare -Wno-macro-redefined -Wno-writable-strings -std=c++11 -g -pthread -ldl -lm -lstdc++ -liconv -o odin
./odin run examples/demo/demo.odin
sh: opt: command not found
```
### Steps to Reproduce

I installed odin on my Mac by doing the following:

1. `git clone https://github.com/gingerBill/Odin`
2. `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`
3. `cd Odin`
4. `make`

**Comment by gingerBill** [comment]
Please see the getting started guide: http://odin-lang.org/docs/install/#download-and-include-necessary-extras
```
For Mac and *Nix…
For Linux, make sure you have llvm and clang installed through your package managers. For macOS, make sure you’ve installed the Xcode command-line tools (xcode-select --install), then install LLVM. If you use Homebrew, you can run brew install llvm to do this.

Homebrew will not add LLVM to the PATH, run echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile to add LLVM to your PATH. Then run source ~/.bash_profile to update your PATH variable in the current terminal session.
```
