### ISSUE TITLE
Defer runs before the function output parameters are set

### ISSUE THREAD

**Issue by SpaceMonkey2126** [odin-lang/Odin#489]
I'm not sure if this is expected behavior or not:

```
func_1 :: proc() -> (ret: int) {
  defer if ret == 0 do fmt.println("func_1 defer:", ret);
  return 1;
}

func_2 :: proc() -> (ret: int) {
  defer if ret == 0 do fmt.println("func_2 defer:", ret);
  ret = 1;
  return;
}

main :: proc() {
  fmt.println("func_1 result:", func_1());
  fmt.println("func_2 result:", func_2());
}
```

```
$ ./main 
func_1 defer: 0
func_1 result: 1
func_2 result: 1
```

Also, see chat in the #randomizer channel for more context

**Comment by gingerBill** [comment]
This is not a bug. This is intended behaviour. The defers are executed after the return values have been evaluated.

**Comment by SpaceMonkey2126** [comment]
So the order here is: (1) return value evaluation, (2) defer execution, (3) outparam assignment

Can you help understand the rationale on why this ordering makes the most sense for Odin?

**Comment by gingerBill** [comment]
```
x := create_thing();
defer destroy_thing(x);

use_thing(x);

return x.value;
```
