### ISSUE TITLE
Can't `odin run` a file in a subdirectory

### ISSUE THREAD

**Issue by sci4me** [odin-lang/Odin#490]
Odin: e229885b2bd3b9b017f88d19a773bf989251ad51
OS: Arch Linux

Currently, trying to use the run command within Odin on a file that is in a subdirectory of the working directory will fail with the following error:

```
/usr/bin/ld: cannot open output file /home/sci4me/Projects/Odin/shared/sgl/test: Is a directory
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```

It is trying to create the executable `test` in the working directory instead of the directory the source file is in. Instead, it should attempt to create the executable in the directory of the source file from the `odin run`.

**Comment by gingerBill** [comment]
No. It should create the executable in the working directory. That is not an mistake.

However, one way around this issue is to change the output file name `-out:exe_name`
