### ISSUE TITLE
few things about assert

### ISSUE THREAD

**Issue by PavelVozenilek** [odin-lang/Odin#492]
1. Probably a bug. When I run this:

```
package main
main :: proc() {
  defer assert(false);
}
```

or even this:

```
package main
main :: proc() {
  assert(false);
}
```

it generates the expected assert error in console, and _then_ (on Win7 64 bit) OS shows system dialog "Application cannot continue". This dialog is used whenever application crashes, e.g. due to dereferencing a nil  pointer.

-------------------

2.  Bit strange syntax: the `#assert` does not need semicolon at the end (contrary to docs examples):

```
package main
#assert(true) // no semicolon here, compiler is happy
main :: proc() {
}
```

Btw, the ability to have file level `#assert`s should be really pointed out explicitly in the documentation. It was not trivial to me to notice this.

-------------

3. Since it looks that one can write his own asserts, some example in docs would help.  

If the language will support tests, it would be useful to expose runtime API, whether a test is currently running or not (plus which test it is - file/line). It would allow one to implement assert which does not fire when inside a test. This is handy to test unlikely code paths.

If the language gets ability to detect whether a function parameter is known at compile time or not, it would allow one to implement assert which fires at compilation when possible.

----------------

4. Will it be possible to write custom assert which shows desirable data?  Something like:

`assert(a < b, "a = %d, b = %d, c = %d", a, b, c);
`

The ultimate assert would allow user code to show things, something like this:

```
assert(compute_average(array) > 0)  
  { // block executed only when assert fires, no-op if asserts are disabled
    ...
    ... // compute average of array values
    assert_show("avg = %d", avg);
    ...
    ... // more things to show. e.g. the whole array
  }

```

**Comment by gingerBill** [comment]
1. Is not necessarily a bug but different platforms will behave slightly different when the debug break is hit. I am planning on making it a lot more consistent across all platforms

2. This is probably an oversight in the rules for semicolons

3. Yes. Asserts are just user-level stuff.

4. `fmt.assertf`
