### ISSUE TITLE
LLVM IR bug passing proc to quick_sort_proc()

### ISSUE THREAD

**Issue by AaronOmanMogo** [odin-lang/Odin#496]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: OSX 10.14.6 Mojave
* Odin version/Commit: 0.11.1

## Expected Behavior

Procedure passed to sort `sort.quick_sort_proc` should compile without issue.

Please describe the behavior you are expecting

See the gist: https://gist.github.com/GrooveStomp/0f38e029c4c5f0dcb7be853e3417a700
Snippet here:
```
Point :: struct {
    x: int,
    y: int,
}

distance :: proc(using p: Point) -> f32 {
    return math.sqrt(f32(x * x + y * y));
}

sort_point_local :: proc(p1, p2: Point) -> int {
    return int(distance(p1) - distance(p2));
}

sort.quick_sort_proc(points, sort_point_local);
```
## Current Behavior

What is the current behavior?

The sample code does not compile.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

```
opt: odin.ll:6075:114: error: '@main.sort_collisions' defined with type 'i64 (i64, i64, i64, i64, %runtime.Context*)*' but expected 'i64 ({ i64, i64 }, { i64, i64 }, %runtime.Context*)*'
        call void @sort.quick_sort_proc-4492(%..rawptr %151, i64 %152, i64 ({i64, i64}, {i64, i64}, %runtime.Context*)* @main.sort_collisions, %runtime.Context* noalias nonnull nocapture %10)
```

In the Discord, gingerBill wrote:
> LLVM IR bug. Yay!
> I know what might cause it.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. odin build .
2. See compilation error

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by gingerBill** [comment]
Is this still a bug? I think this should have been fixed with the ABI corrections a few commits ago.

**Comment by GrooveStomp** [comment]
I just pulled master and tried again on my work macbook.
This does, indeed, appear to be fixed now.

For reference, I've updated the program so it is easier to reproduce; forgive my poor report earlier.

```
package main

import "core:math";
import "core:sort";
import "core:fmt";

Point :: struct {
    x: int,
    y: int,
}

distance :: proc(using p: Point) -> f32 {
    return math.sqrt(f32(x * x + y * y));
}

sort_point_local :: proc(p1, p2: Point) -> int {
    return int(distance(p1) - distance(p2));
}

main :: proc() {
    points: [2]Point;
    points[0] = Point{12, 15};
    points[1] = Point{8, 18};
    sort.quick_sort_proc(points[:], sort_point_local);

    for p in points {
        fmt.printf("%v\n", p);
    }
}
```

**Comment by gingerBill** [comment]
That is wonderful to hear. Sorry I forgot to reply to this issue.
