### ISSUE TITLE
Compiler speed improvement by having separate compilations units for each package

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#497]
**Is your feature request related to a problem? Please describe.**
Compiler speed improvement by having separate compilations units for each package. 

LLVM takes too long to compile very large translation units and it is also appears to be single threaded. This approach would allow compilation per package to be multithreaded.

**Describe the solution you'd like**
Only recompile each package when it or its dependencies (other packages) have been updated.

This would remove a lot compilation time from LLVM and increase some in the linker.

**Additional Information**
For large projects with a lot of parametric polymorphism, it is causing a huge slow down because of the amount of code being generated.

**Comment by lerno** [comment]
It appears that compiling with ThinLTO might  later allow equally big optimizations as single module compilation would allow.

**Comment by gingerBill** [comment]
Experimental support with `-use-separate-modules`
