### ISSUE TITLE
"Instruction does not dominate all uses" using 

### ISSUE THREAD

**Issue by kevinw** [odin-lang/Odin#503]
## Context

* Operating System: Windows 10
* Odin version/Commit: 2d97e1dee388

## Expected Behavior

The program should print "all good"

## Current Behavior

The compiler shows an error:

```
Instruction does not dominate all uses!
  %12 = trunc i8 %11 to i1
  call void @test._END(i1 %12, %runtime.Context* noalias nocapture nonnull %1)
C:\Users\Kevin\src\odin\bin\opt.exe: C:/src/game/test.ll: error: input module is broken!
```

### Steps to Reproduce

```
package test

import "core:fmt"

@(deferred_out=_END)
BEGIN :: proc(open: ^bool = nil) -> bool do return true;
_END :: proc(did_open: bool) {}

main :: proc() {
    console_open: bool = true;
    if console_open && BEGIN(&console_open) {
        fmt.println("all good");
    }
}
```

**Comment by gingerBill** [comment]
I have solved this by disallowing it. It makes a lot of sense to disallow it mainly because logical binary expressions can short circuit which means you have conditional `defer statements now.
