### ISSUE TITLE
Crash when compiling for loop with parens around array expression

### ISSUE THREAD

**Issue by JoshuaManton** [odin-lang/Odin#506]
## Context

* Operating System: Windows 10
* Odin version/Commit: `4ba579bc25ab2bbde370231d090588c237552c76`

## Current Behavior

Parentheses around the expression you want to iterate over will cause a crash. Quick debugging of the compiler shows that there is a null pointer dereference at ir.cpp:9679, the `switch (et->kind) {`. `et` is null

### Steps to Reproduce

```
package main

import "core:fmt"

main :: proc() {
	list := [?]int{1, 2, 3, 4};
	for i in (list) {
		fmt.println(i);
	}
}
```

**Comment by gingerBill** [comment]
Without testing it, I am betting replacing line 9677 with 
```
Type *expr_type = type_of_expr(expr);
```
Should fix the issue. But I think the issue here is that the parentheses are not being assigned type information correctly.
