### ISSUE TITLE
memmove vs memcpy - possible mistake on internal.odin ?

### ISSUE THREAD

**Issue by SrMordred** [odin-lang/Odin#516]
https://github.com/odin-lang/Odin/blob/1d14b3059e0e4310ffc061ca606d2eb6a153149d/core/runtime/internal.odin#L5-L35
mem_copy_non_overlapping could/should(?) be doing a memcpy ?

**Comment by gingerBill** [comment]
Yes. That is a mistake.

**Comment by SrMordred** [comment]
Done https://github.com/odin-lang/Odin/pull/520
