### ISSUE TITLE
fmt does not print array correctly when array contains carriage returns (`\r`)

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#518]
On [current master](https://github.com/odin-lang/odin/tree/85e31e1b69ffdf20d942b07097dfe87bba9661b8), Windows x64:
```go
import "core:fmt"

main :: proc() {
    using fmt;

    s := "Hello\r\nWorld\r\nI\r\nAm\r\nA\r\nComputer.\r\n";
    parts := strings.split(s, "\n");

    printf("%v\n", parts);
    println();
    for e in parts do printf("%s\n", e);
}
```
```
, ]omputer.

Hello
World
I
Am
A
Computer.
```

**Comment by ForLoveOfCats** [comment]
I wanted to try and fix this so I took a look and I think that this is not a bug at all
```go
package main

import "core:fmt"
import "core:strings"

main :: proc() {
	using fmt;

	arr := [2]string{"hello", "world"};
	println(arr);
	println(arr[:]);

	dyn := [dynamic]string{};
	append(&dyn, "hello");
	append(&dyn, "world");
	println(dyn);
	println(dyn[:]);


	s := "hello\nworld";
	parts := strings.split(s, "\n");
	println(parts);
}
```
Outputs:
![image](https://user-images.githubusercontent.com/30666851/71418991-5dfcdc80-263b-11ea-9a8d-65e548d86bf0.png)


but this
```go
s := "hello\nworld\n";
parts := strings.split(s, "\n");
println(parts);
```
Outputs:
![image](https://user-images.githubusercontent.com/30666851/71419026-779e2400-263b-11ea-8834-af4a73a8a37e.png)
Which is not a bug as the last item is a blank string which is being printed without quotes just like the rest of the entries.


and this
```go
s := "hello\nworld\r";
parts := strings.split(s, "\n");
println(parts);
```
Outputs:
![image](https://user-images.githubusercontent.com/30666851/71419068-a2887800-263b-11ea-8975-42f29cabdc96.png)
Which makes sense as `\r` is a carriage return which goes back to the beginning of the line without going to the next line and the terminal here is respecting that in the final string resulting in the later characters overwriting the beginning of the line.


And together this
```go
s := "hello\nworld\r\n";
parts := strings.split(s, "\n");
println(parts);
```
Outputs:
![image](https://user-images.githubusercontent.com/30666851/71419088-ba5ffc00-263b-11ea-864b-9cd91f8678fa.png)
Here this is just the carriage return doing its thing plus the extra blank string from the final `\n`

**Comment by Tetralux** [comment]
It seems I just found a way to replace curses libraries! 😁 

That may well be the reason for this.
I'll note for future reference: Odin has the `%q` format specifier which prints quotes around the string and prints out control chars in their human-readable form - i.e, it prints `\r` as `\r` 😋
