### ISSUE TITLE
Straight crash when trying to set context

### ISSUE THREAD

**Issue by ThisDrunkDane** [odin-lang/Odin#522]
## Context
* Operating System: Windows 10 Version 1909
* Odin version/Commit: f308d8d73ecd30790a643d46ee22e0e153fc28c0

## Expected Behavior
Successful compile or an error message

## Current Behavior
Straight crash, no error message, just the windows popup saying the program has crashed.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try and compile one of the following code snippets;
```
package main;

import "core:log";

main :: proc() {
    context.logger = log.create_console_logger(ident = "Generator");
}
```
and
```
package main;

import "core:log";

main :: proc() {
    context = log.create_console_logger(ident = "Generator");
}
```
2. Watch crash happen

### Failure Logs
![image](https://user-images.githubusercontent.com/1834353/71493475-5f96f200-283f-11ea-965f-aa57ad06f5bd.png)

**Comment by zhibog** [comment]
I'm currently still on [https://github.com/odin-lang/Odin/commit/53cd7a3d0cb295173936a431fba667e3347b6f8b](53cd7a3d) and thus I tried it there.

Your first example compiles fine.
On the second one I get this message: 

> Cannot assign value 'log.create_console_logger(ident = Generator)' of type 'Logger' to 'Context' in assignment

So this might have been introduced in a recent commit.
