### ISSUE TITLE
when statement can´t find identifier.

### ISSUE THREAD

**Issue by SrMordred** [odin-lang/Odin#523]
## Context

`when` statement not working as expected. Looks like the identifier can´t be found in main proc.

* Operating System: Windows 10 (x64 )
* Odin version/Commit:072979c6d2522c5eb5e30e3091386f6fa76aa6ca

## Expected Behavior

`main` proc work the same as `f1` proc

### Steps to Reproduce

```
f1 :: proc (arr:$T)
{
    when intrinsics.type_is_array( type_of(arr) ) { }  //fine
}

main :: proc ()
{
    arr: [2]u64;
    f1(arr);//fine
    when intrinsics.type_is_array( type_of(arr) ) { }//boom
}
```
### Failure Logs
`main.odin(10:18) Undeclared name: arr`

**Comment by gingerBill** [comment]
This is not technically a bug but more about _when_ `when` statements are determined. They are determined before the "variable" state. That means it assumes all of its parameters are known already. It's a little weird but it's done this way on purpose.

**Comment by Tetralux** [comment]
@gingerBill 
> but it's done this way on purpose.

What is that reason?

**Comment by gingerBill** [comment]
Constants and variables technically have different determination in the same scope. Constants get determined before variables _within_ a procedure. This is to solve a few weird problems. I could make it so everything within a procedure is determined top-to-bottom, but this means you cannot have out of order declarations within a procedure any more. This particular approach is the best compromise I could come up with, with simple rules too.
