### ISSUE TITLE
Panic with runtime.type_info_base

### ISSUE THREAD

**Issue by SrMordred** [odin-lang/Odin#532]
Minimal example to crash:
```
package main
import "core:runtime"

T1 :: struct(T:typeid){}

main :: proc ()
{
	runtime.type_info_base( type_info_of( T1 ) );
}
```
`d:\odin\src\ir.cpp(5818): Panic: NOT FOUND ir_type_info_index T1 @ index -1`

**Comment by gingerBill** [comment]
This should be an error as that type is purely polymorphic.

**Comment by SrMordred** [comment]
This issue was generate from the question:
is possible to check if a struct is derived from a polymorphic one?
like
```
base_of( T1(int) ) == T1 )
```
?

**Comment by gingerBill** [comment]
This will require a new intrinsic to get it to work correctly.
