### ISSUE TITLE
Way to specify raw string newlines

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#533]
Right now, if I want a raw string with specific newlines, I have to duplicate the string in memory, split by `\n`, `trim_right_space` and then add back in `\r\n` if that's what I actually wanted, otherwise, it wouldn't work on Linux.

Whereas, if I want `\n`, I have to do the same exact thing as above - because it might be Windows I'm compiling on.

This, for instance, on works because it's being run on Windows:
```go
str := `GET / HTTP/1.1
Host: icanhazip.com
Content-Type: text/plain
Accept: text/plain
Accept-Encoding: utf-8
Connection: close

`;
```
On Linux, this will fail because HTTP needs `\r\n`.
Instead, I want:
```go
str := #newlines("\r\n") `GET / HTTP/1.1
Host: icanhazip.com
Content-Type: text/plain
Accept: text/plain
Accept-Encoding: utf-8
Connection: close

`;
```
Or something to that effect.

**Comment by ThisDrunkDane** [comment]
The quick fix is of course doing it all in a single line, but this might be worthwhile to consider

**Comment by Tetralux** [comment]
Indeed - though that is impractical for this many lines. It's unreadable 😁

**Comment by gingerBill** [comment]
Another option which is hacky but possible it to do this C-style-ish thing: 
```c
str := "GET / HTTP/1.1\n" +
"Host: icanhazip.com\n" +
"Content-Type: text/plain\n" +
"Accept: text/plain\n" +
"Accept-Encoding: utf-8\n" +
"Connection: close\n";
