### ISSUE TITLE
panic: un-gep-able type

### ISSUE THREAD

**Issue by hasenj** [odin-lang/Odin#535]
## Context

This report might be bogus or maybe I'm trying to be a bit too clever with the type system.

I'm trying to setup some way to bind to Objective-C. The main problem with calling into objective-c APIs is there's almost no type information. You just pass things to functions and hope the receiving function expects the same types of arguments you're passing to it.

The main dispatch mechanism `objc_msgSend` doesn't have any particular type signature. It's defined to take void and return void. You're supposed to cast it to some specific function pointer type at the point that you want to use it.

Behind the scenes, the API deals mostly with pointers to opaque structs, aliased to special names like `id` and `Class` and `SEL`.

* Operating System:

macOS

* Odin version/Commit:

3e67ae73391

## Expected Behavior

Code should compile

## Current Behavior

Panic: un-gep-able type

(type is rawptr)

## Failure Information (for bugs)

When running the build command:

    src/ir.cpp(4934): Panic: un-gep-able

I modified the compiler source to give more information:

				// GB_PANIC("un-gep-able type");
				GB_PANIC("un-gep-able type %s for proc %s", type_to_string(type), proc->name);

And now the error is:

    src/ir.cpp(4934): Panic: un-gep-able type rawptr for proc pg.alloc-4511

where `pg.alloc` will be shown in a sample code below.

### Steps to Reproduce

The basic setup is I have a struct with a typeid that's not directly used on the struct itself:

    Class :: struct(T: typeid) {
        ref: ObjcClass,
    }

    // where:
    ObjcClass :: opaque rawptr;

Now, I have two code samples. One that uses the ordinary builtin functions, and it works:

```odin

package pg2

import "core:fmt"

A :: struct (T: typeid) {
    name: string,
}

a_make :: proc(name: string, $T: typeid) -> A(T) {
    return A(T) { name };
}

alloc :: proc(a: A($T)) -> ^T {
    fmt.println("Allocating", a.name);
    return new(T);
}

main :: proc() {
    a0 := a_make("integer", int);
    x := alloc(a0);
    x^ = 20;
    fmt.println(x^);
}
```

The above sample works. The variable `a0` implicitly (at compile time) is of type `A(int)` and this allows it to be passed to a procedure `alloc` which knows that it should allocate an `int` based on the type.

This is just to demonstrate that in principle this should work.

Now for the bug:

I have something similar, but instead of calling to core procedures, I attempt to link to the objc api:

```odin

package pg

import "core:fmt"

foreign import objc "system:objc"
id :: opaque rawptr;
ObjcClass :: distinct id;
SEL :: distinct id;
@(default_calling_convention="c")
foreign objc {
    @(link_name="objc_msgSend")
    msg :: proc(ObjcClass, SEL) -> id ---;

    @(link_name="sel_registerName")
    sel :: proc(str: cstring) -> SEL ---;

    @(link_name="objc_getClass")
    get_cls :: proc(str: cstring) -> ObjcClass ---;
}

Class :: struct(T: typeid) {
    ref: ObjcClass, // the underlying objective-c class
}

cls :: inline proc(name: cstring, $T: typeid) -> Class(T) {
    return Class(T) { get_cls(name) };
}

alloc_sel := sel("alloc");

alloc :: proc(cls: Class($T)) -> T {
    return cast(T) msg(cls.ref, alloc_sel);
}

NSString :: distinct id;
NSString_Class := cls("NSString", NSString);

main :: proc() {
    str := alloc(NSString_Class);
    fmt.println(str);
}

```

Trying to build this results in the compiler panic-ing with 'un-gep-able type'.

Note however, I can make a small change to how I'm calling `alloc`:

change the signature to:

```odin

alloc :: proc(cls: ObjcClass) -> id {
    return msg(cls, alloc_sel);
}
```

and change the call site to:

```
str := cast(NSString) alloc(NSString_Class.ref);
```

and now it compiles! and also runs! (it prints nil; but that's besides the point).

As far as I can tell, the two versions of alloc should be equivalent. It's just one is doing the cast at the call site, the other is letting the polymorphic procedure perform the cast and return the casted pointer.

**Comment by gingerBill** [comment]
Does this still occur now?

**Comment by hasenj** [comment]
Still occurs after pulling `f0c6f29f`

(FWIW: I'm changing my code to not rely on this weird pattern of type enforcement, so it doesn't affect me per say, but I guess it's still useful to iron out this corner of the compiler).

**Comment by gingerBill** [comment]
Does this still occur on either backend?

**Comment by hasenj** [comment]
un-gep-able type does not get raised, but the resulting executable segfaults.
