### ISSUE TITLE
Linux shared libraries require main function and optimize out other unused functions

### ISSUE THREAD

**Issue by ghost** [odin-lang/Odin#54]
Because of this you have to write this craziness:

https://github.com/procedural/gpulib/blob/f6f71e2/gpulib.odin#L926-L1043

1. `main` procedure should not be required for shared libraries
2. Odin needs some way to tell that a procedure won't be optimized out (maybe all non `_`-prefixed functions?)

**Comment by gingerBill** [comment]
Maybe a `#required` tag may be a good thing.

At the moment, any "entity" name prefixed with an underscore will be a "private" entity that is local to that scope.

**Comment by ThisDrunkDane** [comment]
a `#required` seems pretty necessary for any making any library that builds as a dll, as some functions can be purely written to be used by the user and not the library itself. And there is the `DllMain` (at least on windows) entry point which is optional, so making `main :: proc()` optional when building as a DLL makes sense.
