### ISSUE TITLE
Error printing 128 integers. On windows this time.

### ISSUE THREAD

**Issue by lunaticLipid** [odin-lang/Odin#544]
* Operating System: Windows 10
* Odin version/Commit: 14c4fed9

### Steps to Reproduce

```
package main

import "core:fmt"

main :: proc() {
    n := ~u128(0);
    fmt.println(n);
}
```

`E:/Projects/Odin/core/strconv/integers.odin(136:17) Index 4294967295 is out of bounds range 0:17`

**Comment by gingerBill** [comment]
This is a known problem. It appears LLVM does support i128 properly on windows. I think I will need to bypass LLVM's logic.

**Comment by wilsonk** [comment]
On Win10 withOodin version dev-4-28-1-:94fd59e6 (after old backend removal) and on Debian 10(buster) I get this output:
```
340282366920938463463374607431768211455
```
which I assume is correct (python produces the same). Apparently fixed in llvm-11?
