### ISSUE TITLE
Bad LLVM ir output, integer constant must have integer type

### ISSUE THREAD

**Issue by thebirk** [odin-lang/Odin#550]
## Context

* Operating System: Window 10 x64
* Odin version/Commit: ff28769b7f1ed35b770bf8e4ef7de1e063e44bf8

## Current Behavior

Erroneous LLVM ir being generated

### Steps to Reproduce

Repro
```odin
package minrep

main :: proc() {
    a := union{int, string}(int(123));
}
```

### Failure Logs

```
opt.exe: <path>: error: integer constant must have integer type
        store {[0 x i64], [0 x i8], i64} 123, {[0 x i64], [0 x i8], i64}* %0
```

**Comment by Tetralux** [comment]
Is this still happening?

**Comment by sci4me** [comment]
Yes @Tetralux
