### ISSUE TITLE
Type checking nil access

### ISSUE THREAD

**Issue by hasenj** [odin-lang/Odin#551]
Note: this is not a real feature request. It's more of a feedback for the recently added `union #maybe` tag.

See also: #382

**Is your feature request related to a problem? Please describe.**

Some languages provide static type checking feature to prevent dereferencing a nil pointer.

For example, in Swift, to dereference a potentially null reference, you have to use this construct:

```
if let p = my_p {
    // p is guaranteed not nil within this scope
} else {
    // p does not exist in this scope
}
```

In Kotlin and Typescript, a potentially null reference can be verified within an if block without assigning to a new variable

```
if my_p != null {
    // my_p within this scope is guaranteed by compiler to not be null
} else {
    // my_p within this scope is guaranteed to be null
}
```

This kind of compile time checking for nil makes sense because memory in these languages is managed, and the only possible invalid pointer value is nil.

The new `#maybe` union flag in Odin does not provide this benefit.

```
my_p : union #maybe {T} = some_proc(...); // can return nil
p1, ok := my_p.?;
```

If I understood correctly, if `my_p` was nil, then now `p1` is also nil, which defeats the whole point of having an optional/maybe type.

If Odin wants to support compile time checking for nil access, the Kotlin route would make more sense.

However, overall I don't think that's a good idea for Odin.

In Odin, a pointer can be non-nil but still be invalid. Because Odin has custom allocators.

For example, the default temporary allocator in Odin is a ring buffer. This means memory addresses may eventually get reused by other objects after N allocations.

Another reason the feature is less useful is the pattern of procedure calls in Odin vs the other languages like Swift and Kotlin.

In Odin, there are no 'methods'. 

In languages like Swift/Kotlin/Typescript, people write code this way:

```
my_p.my_method(....)
```

But if `my_p` is null, then you will get a runtime error.

Checking for null in Swift/Kotlin/Typescript prevents you from calling a method on a null reference.

But in Odin, you would write:

```
my_proc(my_p, ....);
```

Which is not an error at all.

If `my_p` was nil, you can still pass it along to a procedure, and there's no reason to think this is in general undesirable.

**Describe the solution you'd like**

If Odin ever wants to implement compile time checking against dereferencing nil pointers, I would suggest to adopt a solution that does not introduce a new type.

Also I think the Kotlin/Typescript way is the least intrusive: inside the scope of an if statement, the compiler can guarantee non-nillness

```
if p != nil { // p must be a scope level variable
    // in this scope, compiler guarantees p is not nil
}
```

Another way is an early return when a variable is nil

```
if p == nil {
    return; // or something else to exit the scope
}

// p is guaranteed non-nil for the rest of the scope
```

I also don't know if in general we always want to enforce this pattern before dereferencing a nil. Since Odin wants to be a system's language, it might be possible for zero to be a perfectly valid memory address on some systems (or for kernel development, for example).

So I suggest that a modifier can be applied to a scope so that nil checking is enforced within that scope

```
p: ^T = procedure_call(....); // can potentially return nil
#nil_check { // inside this scope, nil-checking is enforced before dereferencing a pointer

    a := p.field; // compiler error; p was not checked for nil

    proc(p, ..); // ok; no reason to prevent passing nil as a parameter

    if p != nil {
        b := p.field; // ok, compiler knows p is not nil
    } else {
        c := b.field; // compiler error; p is known to be nil
    }
}

{ // regular scope, same as current rules
    p: ^T = procedure_call(....); // can potentially return nil
    a := p.field; // ok, same as now
}
```

**Comment by gingerBill** [comment]
Not going to implement this request. It requires too much magic.
