### ISSUE TITLE
Implement `@export` on globals variables.

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#557]
Making an issue for this as a reminder; on current master (25feb507a422fbb3eba9f33851e0a990ab09b477), this will not compile:
```odin
@export x: i64;

main :: proc() {
}
```
```
Unknown attribute element name 'export'
```
Asked Bill about this -- apparently this just wasn't gotten around to yet. :)

**Comment by gingerBill** [comment]
This should be implemented.
