### ISSUE TITLE
Win8.1 install problem..?

### ISSUE THREAD

**Issue by ffred** [odin-lang/Odin#559]
Hello,
got an error when trying to compile Odin on Windows 8.1 64bits, with VS 2019 BuildTools installed.
tried to compile after cloning Odin, and got this :
```
> vcvarsall.bat X64
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.0
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

> build.bat
main.cpp
Failed to execute command:
        "C:\Users\FLT\Downloads\odin\bin/opt" "C:/Users/FLT/Downloads/odin/demo.ll" -o "C:/Users/FLT/Downloads/odin/demo.bc" -memcpyopt -die
```
any idea of the problem..?
thanks

**Comment by ffred** [comment]
just tried the v0.12.0 release, instead of building it, and the "hellope" example is running great..

**Comment by ThisDrunkDane** [comment]
If you're compiling yourself you need to provide `opt.exe` and `llc.exe` yourself, but they're included in the pre-built releases. You can just copy them from the `bin` folder of pre-built release to your own compiled one, or download them from here: https://github.com/odin-lang/Odin/releases/tag/llvm-windows

This is outlined here https://github.com/odin-lang/Odin#setup

**Comment by ffred** [comment]
oops.. really sorry. forgot about that. did it on my Win10 computer at home and didn't remember about it here. sorry again. thanks.
