### ISSUE TITLE
`using` statements in a struct that points to another struct of the same type breaks implicit access through `using`.

### ISSUE THREAD

**Issue by John-Minor** [odin-lang/Odin#569]
In the following excerpt, in `make_leaf_node`, the compiler will complain that `first_pos` and `last_pos` are undefined even though they both exist in `Node_Base` and other members from `Node_Base` are correctly accessible. If I were to change the type of `first_pos` and `last_pos` to not refer to any of the `Node` types in the excerpt it would work fine. I could also access the members just fine if I used `temp_node.first_pos` and `temp_node.last_pos`.

It feels like `using` isn't able to resolve itself through the resolution of a trivial cyclical dependency.

```
Node_Base :: struct
{
    using value :^Token,
    nullable :bool,
    first_pos :[]^Leaf_Node,
    last_pos :[]^Leaf_Node,
}

Node :: union
{
    Leaf_Node,
    Unary_Node,
    Binary_Node,
}

Leaf_Node :: struct
{
    using base :Node_Base,
    id :u32,
    follow_pos :[]^Leaf_Node,
}

make_leaf_node :: proc(token :^Token, identifier :u32) -> (node :^Node)
{
    node = new(Node, context.temp_allocator);

    temp_node :Leaf_Node;

    using temp_node;

    value = token;
    id = identifier;
    first_pos = make([]^Leaf_Node, 1, context.temp_allocator);
    last_pos = make([]^Leaf_Node, 1, context.temp_allocator);

    node^ = temp_node;

    return;
}
```

**Comment by gingerBill** [comment]
I cannot replicate this without all the information.
