### ISSUE TITLE
@force doen't seem to have any effect.

### ISSUE THREAD

**Issue by powerc9000** [odin-lang/Odin#577]
## Context
When trying to compile raylib for macos with odin you need to link a bunch of different os frameworks. I had heard using `@force` would be able to clear up the issue but it doesn't seem to have had an effect. This is how I am doing the import. Please correct me if this is the wrong way to import these system libraries.

```
when ODIN_OS=="darwin" {
	foreign import raylib "libraylib.a";
	@force foreign import "system:Cocoa.framework";
	@force foreign import "system:IOKit.framework";
	@force foreign import "system:CoreVideo.framework";
	@force foreign import "system:GLUT.framework";
	@force foreign import "system:OpenGL.framework";
};
```

I get several messages like

```
"_CFArrayAppendValue", referenced from:
      __glfwInitJoysticksNS in libraylib.a(cocoa_joystick.m.o)
      _matchCallback in libraylib.a(cocoa_joystick.m.o)
```

I know linking these frameworks manually with `ld` is able to build the executable. But it feels hacky.

* Operating System: macos
* Odin version/Commit: 0.12.0 / 3d74c2f6c0797345c2bdfae77c619057227e8181

## Expected Behavior

We should be able to have a way to add things to the linking phase without doing linking manually.

## Current Behavior

We can't link with other libraries that are required for another static library.

**Comment by gingerBill** [comment]
@powerc9000 I recommend doing this if a library requires multiple things:
```odin
foreign import raylib {
    "librarylib.a",
    "system:Cocoa.framework",
    "system:IOKit.framework",
}
```

However, `@force` should work.

**Comment by powerc9000** [comment]
@gingerBill alright your other method seems to have fixed my issue thank you.

**Comment by Tetralux** [comment]
It may be worth leaving this open since `@force` still does not appear to work, even though you solved your problem.
