### ISSUE TITLE
Ability to call initialization code in the global scope which is executed before `main`

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#584]
**Is your feature request related to a problem? Please describe.**
Ability to call initialization code in the global scope which is executed before `main`

**Describe the solution you'd like**
```odin
Foo :: struct {...};
#global_init register_type(Foo, "Bar"); // called just before `main` is executed
```

**Comment by hasenj** [comment]
Can it also be applied to a block?

```odin
#global_init {
    something();
    another();
}
```

**Comment by gingerBill** [comment]
@hasenj I was considering only procedure calls but any statement could work in theory

**Comment by gingerBill** [comment]
The other solution it to hack the global variable decl system:
```odin
@require
_ := register_type(Foo, "Bar");
```
I think this might be a better approach, even if it is a bit of a hack.

**Comment by gingerBill** [comment]
Added with the following syntax:
```
@require
_ := register_type(Foo, "Bar");
```
