### ISSUE TITLE
Structs are sometimes not passed correctly to foreign functions in MacOs

### ISSUE THREAD

**Issue by powerc9000** [odin-lang/Odin#585]
## Context

Smaller structs seem to pass to foreign functions just fine. However larger structs that are more complex to not get passed correctly. I have included my minimal example and the LLVM bytecode it produces.

* Operating System:  64 bit macos 10.15.3
* Odin version/Commit: 3d74c2f6c0797345c2bdfae77c619057227e8181

## Expected Behavior
All structs of all size get passed to foreign functions correctly.

## Current Behavior
Structs seem to be passed by pointer in the bytecode when the foreign function expects a value. I am not the greatest at llvm however.

## Failure Information (for bugs)
The data passed seems to be a pointer interpreted on the foreign side as the struct. 

This happens in the example with the function call BeginMode2D.
Changing the foreign and odin side to use a pointer fixes the issue but it would be nice to be able to just pass by value.

### Steps to Reproduce
Run minimal example on MacOS and see how it differs from the screenshot.
<img width="912" alt="Screen Shot 2020-03-09 at 8 16 07 PM" src="https://user-images.githubusercontent.com/1013528/76331142-594bda00-62b4-11ea-866d-ea4092cd649d.png">

Minimal example zip. Includes all the temp files and llvm bytecode. Look for `BeginMode2D`

[bug.zip](https://github.com/odin-lang/Odin/files/4313381/bug.zip)

**Comment by gingerBill** [comment]
Could you test the latest commit please?

**Comment by powerc9000** [comment]
Just pulled the latest master and can confirm that the issue looks to be resolved.

**Comment by gingerBill** [comment]
Perfect! I will close this issue now.
