### ISSUE TITLE
Error When Using Switch Statement for 'any' Type

### ISSUE THREAD

**Issue by CaptainKraft** [odin-lang/Odin#591]
## Context

No relevant context.

* Operating System: Windows
* Odin version/Commit: 8dba0e33

## Expected Behavior

Compile and run.

## Current Behavior

Error message

## Failure Information (for bugs)

Compilation error: `'fallthrough' statement in illegal position, expected at the end of a 'case' block`

### Steps to Reproduce

```odin
package main;
import "core:fmt";

main :: proc() {
	a := any{nil, typeid_of(int)};
	switch v in a {
	case int: fallthrough;
	case: fmt.println("It works!");
	}
}
```

**Comment by gingerBill** [comment]
This is not a bug but does need a better error message.  `fallthrough` is not allowed in `switch in` statements because each case block creates a new variable with a unique type.
