### ISSUE TITLE
Declarations at file scope are evaluated in an inconsistent order

### ISSUE THREAD

**Issue by digitalagedragon** [odin-lang/Odin#593]
## Context

* Operating System: Debian (`Linux 5.4.0-4-amd64 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux`), or Debian on WSL (`Linux 4.4.0-18362-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 GNU/Linux`)
* Odin version/Commit: `8dba0e33`

## Expected Behavior

Creating multiple variables at file scope should result in their initialization happening in some kind of order (be it determined by data dependencies or file order) or at least result in an error if they depend on each other.

(I'll admit I'm a total Odin noob (I'm only here because a friend nerd-sniped me with the problem) so I don't know for sure what the correct behavior here should be, but I'm pretty sure what's happening now isn't right)

## Current Behavior

Variables are initialized in an arbitrary order that can change when unrelated parts of the code are changed. Inspection of the generated LLVM IR shows variables can be used before they are initialized.

### Steps to Reproduce

```
package main

import "core:fmt"
import "core:os"

c :: proc(code: int) -> string {
   return fmt.aprint(code);
}

when os.OS == "linux" {
   reset  := c(0);
   red    := c(31);
   cyan   := c(36);
}

placeholder :: proc(c: string) -> string {
   return fmt.aprint(cyan, c);
}

ph_a := placeholder("a");

main :: proc() {
   fmt.print(ph_a, '\n');
}

foo :: proc() {
   fmt.print();
}

bar :: proc() {
   fmt.print();
}

baz :: proc() {
   fmt.print();
}
```

Building and running this program will result in `a` being printed. Commenting any of the `foo`, `bar`, or `baz` functions, reordering the `reset`, `red`, `cyan` declarations, or a number of other (theoretically insignificant) changes results in the compiled program printing `36a`.

### Failure Logs

```
        %2475 = call %..string @main.placeholder(%..string {i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str$f3, i32 0, i32 0), i64 1}, %runtime.Context* noalias nonnull nocapture %0) noinline
        store %..string %2475, %..string* @main.ph_a
        %2476 = call %..string @main.c(i64 36, %runtime.Context* noalias nonnull nocapture %0) noinline
        store %..string %2476, %..string* @main.cyan
```
LLVM IR generated in `@__$startup_runtime()` for the `a` case (note `ph_a` is assigned before `cyan`)

```
        %2475 = call %..string @main.c(i64 36, %runtime.Context* noalias nonnull nocapture %0) noinline
        store %..string %2475, %..string* @main.cyan
        %2476 = call %..string @main.placeholder(%..string {i8* getelementptr inbounds ([2 x i8], [2 x i8]* @str$f3, i32 0, i32 0), i64 1}, %runtime.Context* noalias nonnull nocapture %0) noinline
        store %..string %2476, %..string* @main.ph_a
```
LLVM IR generated for the `36a` case (note `cyan` is assigned before `ph_a`)

**Comment by coalpha** [comment]
I can reproduce this on `WSL` (`Linux 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`) as well

**Comment by wilsonk** [comment]
With Debian 10(buster) and Odin version dev-2021-04:afe185ee, after the old backend removal, this seems to run fine...or at least consistently with it printing "36 a" in all cases mentioned above.
