### ISSUE TITLE
Remove `#defined` built-in procedure

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#594]
**Is your feature request related to a problem? Please describe.**
Remove `#defined` built-in procedure.

Having this features causes a race condition in conjunction with file-scope `when` statements across different files within a package.

The only two solutions are:

* enforce an evaluation order for the files within in a package, probably alphabetically,
* remove `#defined`

**Describe the solution you'd like**
Remove `#defined` built-in procedure

**Comment by Tetralux** [comment]
I currently use `when #defined(TEST_NAME)` - maybe `|| #defined(TEST_ALL)` as well  - for testing packages in a way that means I do not need to remove the `main` procedure that tests the package.

Without `#defined`, how would you do this instead, in just-a-simple a way?

**Comment by gingerBill** [comment]
The issue is trying to treat `#defined` as if it is a preprocessor approach when it isn't. The reason why it works fine in C's preprocessor is because everything is evaluated top-down, rather than Odin's out-of-order approach

**Comment by Tetralux** [comment]
Maybe the replacement is to have a global variable in the package `TEST :: false;` or whatever, and then
```
odin run . -set:TEST=true
```
Currently, if you do this, the value in the source code overrides the value given to `-define`.

**Comment by Tetralux** [comment]
Although, quite how you'd do the equivalent of `when #defined(TEST_THIS) || #defined(TEST)` I'm not sure. 🤔

**Comment by gingerBill** [comment]
Possible replacement idea:
`#config(TEST_THIS, default_value)`
