### ISSUE TITLE
Documentation: Enumerate all platform specific behavior

### ISSUE THREAD

**Issue by JesseRMeyer** [odin-lang/Odin#615]
Odin replaces undefined behavior for platform specific behavior  However, there is no documentation specifying which Odin constructs are platform defined.

**Comment by gingerBill** [comment]
I personally separate the different behaviours which C categories all under "undefined behaviour".

Odin will not have any __undefined__ behaviour but it will allow for _platform_ defined behaviour and _vendor_ defined behaviour.

As the language specification is not yet finalized, I will not documented the ins-and-outs yet.
