### ISSUE TITLE
Cannot build a DLL on windows

### ISSUE THREAD

**Issue by suleyth** [odin-lang/Odin#624]
## Context
* Operating System: Windows 10
* Odin version/Commit: 026bb8ed6f6e626c69ccfe32de5b2323d86b4620

## Expected Behavior
The DLL should build correctly without the need to specify a main procedure. Or, you should be able to specify it and make it override `DllMain`.

## Current Behavior
Building something as simple as this:
```odin
package test

@export foo::proc() {
    
}
```
with `odin build test.odin -build-mode=dll` yields this error message:
```
Creating library (file path)test.lib and object (file path)test.exp
libcmt.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)
(file path)test.dll : fatal error LNK1120: 1 unresolved externals
```
Using the `-lld` flag, the error message is simpler:
```
(odin path)bin\lld-link: error: entry point must be defined
```

## Failure Information (for bugs)
Trying to define a main procedure also yields an error:
```odin
package test

@export foo::proc() {
    
}

@export main::proc() {}
```
```
(file path)test.odin(8:15) The link name 'main' is reserved for internal use
```
Not `@export`ing the procedure gives the same `entry point must be defined` error.

### Steps to Reproduce
1. Install Odin latest commit
2. Try to build any file with `-build-mode:dll`

### Failure Logs
None.

**Comment by gingerBill** [comment]
I think this bug is fixed already. Can you see if you can replicate this, please.

**Comment by suleyth** [comment]
Yes, can confirm it's fixed with the latest commit. Both with and without `-lld`
