### ISSUE TITLE
Weird padding when optimizations are enabled

### ISSUE THREAD

**Issue by thabetx** [odin-lang/Odin#626]
## Context

* Operating System: Ubuntu 19.10
* Odin version/Commit: 9409f53a9bbf4a057ac45ae34b42d78ae4178d63

## Expected Behavior

When Executing this code, I expect the offset of serial to be 8
```
package test

import "core:fmt"

Test :: struct
{
	type: i32,
	serial: i64
};

main :: proc() {
	t : Test;
	fmt.println("type offset", cast(uintptr)&t.type - cast(uintptr)&t);
	fmt.println("serial offset", cast(uintptr)&t.serial - cast(uintptr)&t);
	fmt.println("test   address", cast(uintptr)&t);
	fmt.println("type   address", cast(uintptr)&t.type);
	fmt.println("serial address", cast(uintptr)&t.serial);
}
```

## Current Behavior

when I build with opt:0, the offset is correct

```
type offset 0
serial offset 8
test   address 140720308465584
type   address 140720308465584
serial address 140720308465592
```

But when I build with opt:1, the offset if 4

```
type offset 0
serial offset 4
test   address 140720308465184
type   address 140720308465184
serial address 140720308465192
```

Note that the printed address looks correct.

## Failure Information

There seems to be something wrong with the padding of the structure when optimizations are enabled. I was doing some C bindings and I had to insert `_ : i32` before serial to make things work as expected with optimizations. Without the extra 4 bytes I had wrong data when accessing the members of the struct. The code worked correctly with opt:0.

On a side note, printing the struct with `fmt.println` printed the struct properly and showed the correct data even without the 4-byte padding.

### Steps to Reproduce

Running the above snippet
```
odin build . -opt:1 && ./test
```

**Comment by gingerBill** [comment]
This appears to be purely an LLVM bug, but I have a guess as to what might be causing it and it is not good.

I think LLVM is changing the memory layout rules with the optimization levels.

**Comment by thabetx** [comment]
I had llvm-9 tool chain installed. I was curious whether this version of llvm had a problem, so I upgraded to llvm-10 using the automatic installation script from https://apt.llvm.org/ then added it to the path and made sure it became the default
```
thabetx@pc:~$ llvm-as --version
LLVM (http://llvm.org/):
  LLVM version 10.0.0

  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: znver2
thabetx@pc:~$ clang --version
clang version 10.0.0-++20200412073924+50d7e5d5e7d-1~exp1~20200412054519.133
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-10/bin
```
and then I rebuilt Odin and ran the tests but I get the same result.

**Comment by wilsonk** [comment]
Win10 with Odin version dev-4-28-1-:94fd59e6, after old backend removal and using llvm-11, this seems to be fixed. Offsets are 8 bytes for all optimization levels. Also seems to work on Debian 10 (buster) with same Odin version and llvm-11, of course.
