### ISSUE TITLE
Compiler fails when using --- keyword

### ISSUE THREAD

**Issue by TheMarcsOv** [odin-lang/Odin#631]
## Context
* Operating System: Windows 10, 64 bits
* Odin version/Commit: [8434cb8](https://github.com/odin-lang/Odin/commit/8434cb8951dabeae5c039b6f08bbab79d9d39d32)

## Current Behavior
Compiler stalls when trying to compile the following code.
```
package raytracer

import "core:fmt"
import "core:os"

IMG_W :: 256;
IMG_H :: 256;

COLOR_CHANNELS :: 3;

main :: proc() {
    fmt.println("Raytracer Start");

    //buffer : [IMG_W * IMG_H * COLOR_CHANNELS]   u8;  //works
    buffer : [IMG_W * IMG_H * COLOR_CHANNELS]u8 = ---; //fails

    index : uintptr = 0; 

    for y in 0..<IMG_H {
        if y % 16 == 0 {
            fmt.printf("Progress: %v%%\n", cast(int)(100.0 * cast(f64)y / cast(f64)IMG_H-1));
        }
        for x in 0..<IMG_W {
            r := cast(f64)x / cast(f64)(IMG_W-1);
            g := cast(f64)y / cast(f64)(IMG_H-1);
            b := 0.25;

            ir := cast(u8) (r * 255);
            ig := cast(u8) (g * 255);
            ib := cast(u8) (b * 255);
            buffer[index + 0] = ir;
            buffer[index + 1] = ig;
            buffer[index + 2] = ib;
            index += 3;
        }
    }

    fmt.println("Done");
}
```
## Failure Information (for bugs)
Nothing is outputted to the console, the compiler stalls and it is only possible to
terminate it using Ctrl+C.

Debugging odin.exe revealed that it is stuck at line 73 in src/main.cpp. 
### Steps to Reproduce
1. Use the latest version of Odin
2. Compile the given code. ``odin run raytracer.odin``

**Comment by hasenj** [comment]
Works for me (macOS)

**Comment by gingerBill** [comment]
This is an LLVM bug which causes LLC to go into an infinite loop, somehow.

**Comment by gingerBill** [comment]
I cannot replicate this on Windows with the new `-llvm-api`

**Comment by TheMarcsOv** [comment]
Updating to e1bdaa98 and using ``-llvm-api`` works, thanks!

**Comment by gingerBill** [comment]
This still happens without `-llvm-api` however.

**Comment by wilsonk** [comment]
Using Win10 with Odin version dev-4-28-1-:94fd59e6, after the old backend removal, and this example works fine. Not sure if there are other params that should be checked before closing?
