### ISSUE TITLE
Cannot put local functions after return

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#632]
```odin
package main

main :: proc() do f();

f :: proc() -> int {
    x := local_g();
    return x;

    local_g :: proc() -> int do return 4;
}
```
Output:
```
test.odin(7:5) Statements after this 'return' are never execu
testt.odin(10:1) Missing return statement at the end of the procedure 'f'
```

**Comment by gingerBill** [comment]
Not a bug really. It just a rule I added to prevent common mistakes of declaring after `return`

**Comment by Tetralux** [comment]
Since people from C might have often use a return-before-end-of-proc when testing something, it might be wise to add a suggestion "Use os.exit instead", or something to that effect.

That'd be orthogonal to this issue though.

This is more about just _constant declarations_ after a return.
