### ISSUE TITLE
Explicit context creation

### ISSUE THREAD

**Issue by oskarnp** [odin-lang/Odin#639]
Require context to be explicitly initialized by user, to allow a default context to be easily overriden:

```
main :: proc() { 
  context := default_context();
  // ...
}

foo :: proc "c" () { 
  context := default_context();
  // ...
}
```

It also avoids the mistake of a default context being created by mistake when a global override of the default allocator was intended.

**Comment by gingerBill** [comment]
This should only exist for none Odin calling convention. main should still have a default I think
