### ISSUE TITLE
Nested parapoly identifiers aren't treated as constant expressions

### ISSUE THREAD

**Issue by foxnne** [odin-lang/Odin#640]
## Context

* Operating System: Windows 10
* Odin version/Commit: 0.12.0

## Expected Behavior

Given the procedure:
`unroll :: proc(m: [$I][$J]$T) -> [I*J]T {
     ...
}`

expected to compile.

## Current Behavior

Error on compile.

## Failure Information (for bugs)

` 'I' is not an expression. `  
` 'J' is not an expression. `

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Write procedure requiring return type to perform operations on parapoly identifiers.
2. Attempt to compile.

Note: 
It may be a design decision, just was trying to write a procedure to take a matrix/2d array and output a single array containing the same quantity of elements.

Edit:
I thought maybe I could work around it by referencing len(m) in the above procedure, which will work for the length of the first array (returns I), and can be used with operators. However, I can't find a way to get the length of the second array as len(m[0]) returns an out of bounds error (not yet initialized?)

**Comment by hasenj** [comment]
It works if you do it this way:

```odin
unroll :: proc($I: int, $J: int, m: [I][J]$T) -> (out: [I*J]T)
```

and you can call it like this:

```odin
unroll(len(x), len(x[0]), x)
```

So I doubt this is a design decision ..

**Comment by gingerBill** [comment]
This wasn't a bug per se, but rather `[$I]T` could be an enumerated array and thus `I` could a type. This means that the expression `I*J` is ambiguous.
