### ISSUE TITLE
Compiler confused when preceding struct member has same name as a package

### ISSUE THREAD

**Issue by hasenj** [odin-lang/Odin#646]
## Context

* Operating System: macOS
* Odin version/Commit: e1bdaa9

## Code

Following code does not compile:

```odin
package main

import "core:fmt"

A :: struct {
    fmt: string,
    info: fmt.Info, // compiler thinks this is referencing the previously declared member 'fmt'
}

main :: proc() {
    a: A;
    a.fmt = "abc %d";
    fmt.printf(a.fmt, 10);
}
```

## Expected Behavior

Should compile without error

## Current Behavior

The following errors are printed:

```
pg.odin(6:5) Illegal declaration cycle of `fmt`
pg.odin(7:11) 'fmt' of type 'string' has no field 'Info'
pg.odin(7:15) 'fmt.Info' is not a type
```
## Workaround

It will compile and work if struct members are re-ordered such that the member with the same name as the package comes _after_ the member that references the package:

```odin
A :: struct {
    info: fmt.Info, // compiler is not confused now, maybe because it hasn't seen the `fmt` member yet
    fmt: string,
}
```

**Comment by gingerBill** [comment]
This isn't a bug and just basic scoping rules.
