### ISSUE TITLE
Compiler assertion when passing a pointer to a bitfield

### ISSUE THREAD

**Issue by jharler** [odin-lang/Odin#649]
* Operating System: Windows 10
* Odin version/Commit: current master (218c1599)

## Expected Behavior

A successful compile with the bitfield variable passed in by reference.

## Current Behavior

Compiler asserts: Odin\src\ir.cpp(3636): Assertion Failure: `is_type_bit_field(bft)`

### Steps to Reproduce

Compile the following:

```odin
package main

Asset_ID :: bit_field {
    index   : 20,
    counter : 12,
}

invalidate_asset_id :: proc (asset_id :^Asset_ID) {
    asset_id.index = 0;
    asset_id.counter = 0;
}

main :: proc() {
    asset_id : Asset_ID;
    invalidate_asset_id(&asset_id);
}
```

**Comment by ThisDrunkDane** [comment]
`bit_field` have been removed
