### ISSUE TITLE
Crash in debug mode when calling function pointer

### ISSUE THREAD

**Issue by ralph-the-mighty** [odin-lang/Odin#662]
## Context

* Operating System: Windows 10
* Odin version/Commit: 098699103da15894be771ce7c5f28812fd6de883

## Failure Information (for bugs)

When compiling the code below in to an executable, the .exe behaves as expected, printing to the console.  However, when trying to compile a debug build, it produces the .ll file then quits.  This seems to only be happening when calling a function pointer.

### Steps to Reproduce
```
package main;
import "core:fmt";

foo :: proc() {
  fmt.println("Hellope, World!");
}

bar := foo;

main :: proc() {
  bar();
}
```

`odin build . -debug`

**Comment by wilsonk** [comment]
The situation seems to have changed for this issue after removal of the old backend. On Win10 with odin verison dev-4-28-1-:94fd59e6 I get 
```
C:\Users\wilsonk\odin\src\llvm_backend.cpp(5697): Panic: Error in: C:/Users/wilsonk/odin/mine/issue-662.odin(4:1), missing procedure foo
```
with and without the -debug flag.

**Comment by gingerBill** [comment]
```
odin verison dev-4-28-1-:94fd59e
```

Looks like the versioning system for windows is broken too.

**Comment by gingerBill** [comment]
But I cannot replicate this on Windows any more on the latest commit.
