### ISSUE TITLE
Builtin procedures can be overwritten silently

### ISSUE THREAD

**Issue by atipls** [odin-lang/Odin#663]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10 x64 - 1903
* Odin version/Commit: 2020. 05. 29. nightly

## Expected Behavior
The following code should not compile or it should give a warning about "len" being a builtin procedure.
## Current Behavior
The code compiles, overwriting "len".
Console output:
```
len was overwritten!
Length of Hello! is 0.
```
 
### Steps to Reproduce
Compile the following code:
```odin
package repro;

import "core:fmt";

len :: proc(args: ..any) -> int {
	fmt.printf("len was overwritten!\n");
	return 0;
}

main :: proc() {
	str := "Hello!";
	fmt.printf("Length of {} is {}.\n", str, len(str));
}
```

**Comment by JoshuaManton** [comment]
I'm curious why you think this is a problem. Not being able to override compiler identifiers sounds really annoying imo.

**Comment by gingerBill** [comment]
This is not a bug. You can always get the built-in stuff still by importing the `builtin` package:
```odin
package main

import "builtin"
import "core:fmt"

main :: proc() {
    str := "Hellope!";
    fmt.println(len(str));
    fmt.println(builtin.len(str));
}
```

Not being able to override those identifiers is very annoying and can cause a lot of issues in other places.
