### ISSUE TITLE
Shift returns wrong result (in certain case) since #8589af1

### ISSUE THREAD

**Issue by zhibog** [odin-lang/Odin#666]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Win 10 Enterprise LTSC 1809
* Odin version/Commit: 8589af1

```odin
ROTL32 :: proc (a: u32, b: int) -> u32 {
    s := uint(b) & 31;
    return (a << s) | (a >> (32 - s));
}
```

This should return ``3578186250`` when called like this ``ROTL32(3578186250, 344677888)``.
Which it used to do, but on the latest commit the result changed to ``3578186251``, which is off by one.
\
The issue happens in the ``(a >> (32 - s))`` portion of the return.
Latest commit results in ``1`` whereas it used to be ``3578186250``.
\
I managed to get it working with some ugly casts to ``uint`` and finally back to ``u32`` but I would rather not have to do that.
```odin
ROTL32 :: proc (a: u32, b: int) -> u32 {
    s := uint(b) & 31;
    return u32((uint(a) << s) | (uint(a) >> (32 - s)));
}
```

**Comment by dotbmp** [comment]
@gingerBill I'm not sure what you mean... The new shift behavior should not affect shifts by less than the bit length of the type

**Comment by gingerBill** [comment]
@dotbmp Think of the new shift behaviour in this sense:
```
x << y == x << min(8*size_of(x), y)
x >> y == x >> min(8*size_of(x), y)

where `y` is unsigned
```

**Comment by zhibog** [comment]
@gingerBill 

If you remove the ``-1`` on this line and the one for the right shift, it works correctly.
https://github.com/odin-lang/Odin/blob/master/src/ir.cpp#L4551

What benefit does this ``-1`` give over not having it?
I also tested it against the crypto lib, which has a ton of shifting crap and nothing broke.

**Comment by oskarnp** [comment]
@gingerBill  This issue was regressed with commit 439e2c92426c59f84d51bfb594e9ac86d496c708 on old backend with Linux and should be re-opened.
