### ISSUE TITLE
Relative pointers crash the compiler when compiling with `-debug`

### ISSUE THREAD

**Issue by JoshuaManton** [odin-lang/Odin#670]
## Context

* Operating System: Windows 10
* Odin version/Commit: `8589af14585c1f0b1f8ad9f1c66669ede740a79d`

## Expected Behavior

I expect to be able to compile in debug mode when using relative pointers.

## Current Behavior

Given:

```
package test

Base :: struct {
    b: #relative(i16) ^Base,
}

main :: proc() {
    thing: Base;
    thing.b = &thing;
}
```

if I try to `odin build . -debug` the compiler panics in ir.cpp:

```
d:\programming\odin\src\ir.cpp(2811): Panic: Unreachable #relative(i16) ^Tracked_Asset
```

**Comment by gingerBill** [comment]
This should be fixed now.
