### ISSUE TITLE
Executable is very big in Linux

### ISSUE THREAD

**Issue by tuket** [odin-lang/Odin#683]
## Context
OS: Ubuntu 18.04
Odin 0.12.0

Sample program:
```c
package main
import "core:fmt"

main :: proc() {
    fmt.printf("Hello World\n");
}
```

Compile as:
```
$ odin version
odin version 0.12.0

$ odin build hello_world.odin -opt=3 -no-crt
$ du hello_word
164	hello_world
```
That value is in KBs.

In C:
```c
#include <stdio.h>

int main()
{
    printf("Hello World\n");
}
```

The executable is much smaller:
```
$ gcc hello_world.c -o hello_world
$ du hello_world
12	hello_world
```

Maybe I'm missing some compiler flags so it could be smaller?

**Comment by gingerBill** [comment]
@tuket This is because `fmt.printf` is not truly equivalent to C's `printf`. The former uses Runtime Type Information (RTTI). If you want something that is closer to the C equivalent:

```odin
package main
import "core:os"

main :: proc() {
    os.write_string(os.stdout, "Hellope!\n");
}
```

**Comment by tuket** [comment]
Thanks for your answer.
Now it's 36KB Odin vs 12KB C. Still not a fair comparison because the C version has CRT.

**Comment by gingerBill** [comment]
Odin statically links as much as it can. So it will be larger than most C versions which have an external runtime usually on most platforms.

On Windows, that example with `-no-crt` is 26KiB IIRC. And that's pretty good going for modern Windows too, and a language with a non-zero runtime too.

**Comment by tuket** [comment]
It looks like Odin links more dynamic libraries than C.
```bash
$ gcc hello.c -o hello -O3
$ ldd hello
    linux-vdso.so.1 (0x00007ffeca5cd000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb42a594000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fb42ab87000)
$ ./odin build hello.odin -opt=3 -no-crt
$ ldd hello
    linux-vdso.so.1 (0x00007ffda31bb000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9861389000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f986177a000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9860feb000)

```

**Comment by gingerBill** [comment]
Well, that will need to be reduced a lot on Linux.

**Comment by ThisDrunkDane** [comment]
All of this is valid but part of just ongoing work with other platforms, I don't think we need an issue here to remind us :)
