### ISSUE TITLE
#relative Strings

### ISSUE THREAD

**Issue by JoshuaManton** [odin-lang/Odin#687]
I have a `Static_String` structure that contains a static sized byte buffer and a string that points into that buffer in order to minimize string allocations.

```
Static_String :: struct(Cap: int) {
    str: string,
    buffer: [Cap]byte,
}

set_string :: proc(ss: ^Static_String($Cap), str: string) {
    assert(len(str) <= Cap);
    ss.str = bprint(ss.buffer[:], str);
}
```

However currently I need to be careful not to make any value-copies of this `Static_String` because the string's pointer will become invalidated.

If there was a way to do the following:

```
Static_String :: struct(Cap: int) {
    str: #relative(i16) string,
    buffer: [Cap]byte,
}
```

then my problem would be solved as the string would always correctly point into the buffer even on a value-copy.

**Comment by gingerBill** [comment]
`#relative(i16) []byte` exists. I could add the string type but it is a little weirder, and `#relative(?) cstring` would have to be supported to.
