### ISSUE TITLE
Error in core:odin/parser

### ISSUE THREAD

**Issue by JoshuaManton** [odin-lang/Odin#690]
## Context

* Operating System: Windows 10
* Odin version/Commit: `cb52f6986a4241becbce14867627939bfc05e5dd`

```
D:/Programming/Odin/core/odin/parser/parser.odin(1656:33) Cannot assign to 'names[0].derived.(ast.Ident).name'
```

This only just started showing up, I guess it's a new thing that you're not allowed to do that?

**Comment by gingerBill** [comment]
I might need to think that through.
