### ISSUE TITLE
Fail to build (warning C4819)

### ISSUE THREAD

**Issue by the-goodies** [odin-lang/Odin#694]
Trying to build Odin language with build.bat results in a failure:
_..\Odin\src\tokenizer.cpp(1038): warning C4819: The file contains a character that cannot be represented in the current code page (1257). Save the file in Unicode format to prevent data loss

* Operating System: Windows 10
* Odin version/Commit: c4067372dddbabd327cda1d4a821ef6b343a29b1

Fixed by adding "-wd4819" to build.bat compiler_warnings. Builds fine afterwards.

**Comment by gingerBill** [comment]
Does this happen in the latest commit now?

**Comment by the-goodies** [comment]
Doesn't anymore, builds fine now.
