### ISSUE TITLE
Odin attempting to transmute a 6 byte sized struct to u64 in the IR

### ISSUE THREAD

**Issue by powerc9000** [odin-lang/Odin#698]
## Context
Getting error ```src/ir.cpp(6071): Assertion Failure: `sz == dz` Invalid transmute conversion: 'Psd_Channel_Info' to 'u64'```

When attempting to append to an array.

`Psd_Channel_Info` looks like:

```
Psd_Channel_Info :: struct #packed {
	id   : i16be,
	data : i32be
}
```
a total of 6 bytes not 8.

* Operating System:
Macos
* Odin version/Commit:
3a1492fc995e4050796dc23eb2afda8e94101536

## Expected Behavior

We shouldn't get any error and compile

## Current Behavior

Getting an error from the IR generator trying to transmute the struct

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

```
src/ir.cpp(6071): Assertion Failure: `sz == dz` Invalid transmute conversion: 'Psd_Channel_Info' to 'u64'

### Steps to Reproduce

Unsure of a minimal reproduction of the issue

**Comment by gingerBill** [comment]
Is this still a bug?

**Comment by oskarnp** [comment]
@powerc9000 Please provide a minimal repro so we can verify this more easily.

**Comment by powerc9000** [comment]
Doesn't seem like this happens anymore in the latest.
