### ISSUE TITLE
 Question: Having one type of comment (Block comments)

### ISSUE THREAD

**Issue by HoTKreeZy** [odin-lang/Odin#699]
Currently, there is two types of comments:
- Line comment ( // My line comment )
- Block comments ( /* My block comment */ )

I think, having one type of comment (block comments) is better:
- You can easily extend your line comment to a block comments
- You can bind just one keyboard shortcut and quickly toggle from a non line/block comments to a line/block comments

Example:

With two type of comments
```odin
// My line comment
package main

// My multi
// line comment
import "core:fmt"

/*
    My block comment
*/
main :: proc() {
	fmt.println("Hello, World");
}
```

With one type of comment
```odin
/* My line comment */
package main

/*
    My multi
    line comment
*/
import "core:fmt"

/*
    My block comment

main :: proc() {
	fmt.println("Hello, World");
}

*/
```

**Comment by Platin21** [comment]
And what would be the benefit of removing it?

You can already do multline `/**/` and also single line `/**/` and for they key bindings you can create already one?

**Comment by HoTKreeZy** [comment]
I'm not telling that you should remove it.

I'm just thinking about why keeping two type of comments if only one can be used in all cases? And I'm thinking the same for all other languages, not just Odin.

I understand that it was a bit ridiculous but I wanted to know what "everyone" are thinking about it.
And we can totally close this issue 🙂
