### ISSUE TITLE
How to get Odin running?

### ISSUE THREAD

**Issue by clankill3r** [odin-lang/Odin#71]
What do I need to do in order to compile code?
(Like hot to set up odin?) So many weeks have past and I still don't know how.
Preferred platform is windows.

**Comment by FelixBrendel** [comment]
You will need Visual Studio because for the Microsoft C++ compiler `cl` and also for Microsoft's linker.
Then you have to find the file `vcvarsall.bat` Mine is in `D:\Programme\Visual Studio 15\VC\`. When run from a shell it will set all the paths and variables necessary for the C++ compiler to work.

1. Clone the GitHub repository
2. Open a command prompt in the folder containing `vcvarsall.bat` (shift+rightclick -> Open command window here)
3. type in `vcvarsall.bat x64` (might take some seconds)
4. `cd` into the cloned Odin repository
5. run `build.bat`

Now odin.exe should have been created in the same folder. To compile you Odin source code you need to run odin.exe [ build | run ] <filepath>. When Calling odin like that keep in mind that Odin uses Microsoft's linker so only call it after you called `vcvarsall.bat x64`.

On Linux you only need `llvm` and 'clang' installed to compile the compiler and Odin code.

**Comment by H-225** [comment]
You can make the situation with the Microsoft compiler stuff a bit easier by using a batch file.
Like this one: https://gist.github.com/H-225/821f1cab81bce979d4a74f6e46e78a81

**Comment by clankill3r** [comment]
When running build.bat I get:

> Failed to execute command:
>         "D:\Odin\bin/opt" "D:\Odin\code\demo".ll -o "D:\Odin\code\demo".bc -mem2reg -memcpyopt -die
> 

The bin folder is not created.
I am using visual studio 2015 (which uses a 14.0 folder, microsoft things...).

**Comment by gingerBill** [comment]
You need to make sure you have the bin directory with the LLVM binaries. https://github.com/gingerBill/Odin/releases/tag/llvm-4.0-windows

**Comment by clankill3r** [comment]
I realized that short after I posted previous comment.
Ok, I removed all my previous attempts and did:

1. cloned odin
2. added the bin folder
3. located C:\My Programs\Microsoft Visual Studio 14.0\VC
 started a command prompt from there and did run `vcvarsall.bat`.
4. using the same shell I `cd`'d into `d:\odin` and run `build.bat`.

Now I get `demo.exe` has stopped working.

Can it be that my version of visual studio is wrong (2015)?
(I'm installing visual studio 2017 now...)

**Comment by clankill3r** [comment]
Which is broken as fuck...

**Comment by gingerBill** [comment]
Is vcvarsall.bat setup for x64/amd64?

**Comment by clankill3r** [comment]
Thanks, that guided me in the right direction. I will make a post below this one of how to set up Odin for in case someone is as bad as me in those things :)

**Comment by clankill3r** [comment]
Odin setup instructions for windows (Modified version of FelixBrendel's instruction): 

You will need Visual Studio because for the Microsoft C++ compiler cl and also for Microsoft's linker.
Then you have to find the file vcvarsall.bat Mine is in D:\Programme\Visual Studio 15\VC\. When run from a shell it will set all the paths and variables necessary for the C++ compiler to work.

1. Clone the GitHub repository
2. Open a command prompt in the folder containing vcvarsall.bat
Here is a neat trick of how to open a command prompt with the path all set:
![cmd_trick](https://user-images.githubusercontent.com/738650/27439252-d521762c-5767-11e7-937d-2db25aa15e8b.gif)
3. type in `vcvarsall.bat x64` (might take some seconds)
4. `cd` into the cloned Odin repository
5. extract the binaries from here https://github.com/gingerBill/Odin/releases/tag/llvm-4.0-windows in the odin folder
6. run build.bat

Now odin.exe should have been created in the same folder. To compile you Odin source code you need to run odin.exe [ build | run ] <filepath>. When Calling odin like that keep in mind that Odin uses Microsoft's linker so only call it after you called vcvarsall.bat x64.

To make it easier for next time see this comment:
https://github.com/gingerBill/Odin/issues/71#issuecomment-308230244

**Comment by gingerBill** [comment]
This issue needs to be added to the new wiki on this GitHub project.

**Comment by ThisDrunkDane** [comment]
I'll close this issue as this information is on the wiki page now here https://github.com/odin-lang/Odin/wiki#getting-started-with-odin

**Comment by rodrigmars** [comment]
I'm making this bat file available to help anyone who wants to automate the ODIN.exe build process. I hope that ONE DAY the team responsible for the language will resolve how to remove Nostromo "Microsoft Visual Studio"...
The script is easy for layman, run it only for Windows OS...

-----------------------------------------

@echo off

SETLOCAL

SET OSARCHITECTURE=x64

SET PATH-ODIN=C:\odin-windows\Odin

SET PATH-MVS="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build"

SET VCVARSALL=%PATH-MVS%\vcvarsall.bat

SET BUILD-ODIN=%PATH-ODIN%\build.bat

CD /D %PATH-ODIN%

CALL %VCVARSALL% %OSARCHITECTURE%

CALL %BUILD-ODIN%

ENDLOCAL
