### ISSUE TITLE
OSX Calling Convention Bug.

### ISSUE THREAD

**Issue by Platin21** [odin-lang/Odin#716]
## Context

* Operating System: macOS Catalina 10.15.05 (19F72f)
* Odin version/Commit: 0.13.0 (51e50d3e, b9b2b90f)
* Library used: https://github.com/Platin21/odin-objc

## Expected Behavior

Program should not segfault. 

## Current Behavior

Program segfault's because the objc runtime try's to write to the first parameter of the function which is the class object but should actually be the return pointer. The pointer should be the first arg and of type ^CGRect.

## Failure Information (for bugs)

Is related to the calling convention on macOS e.g there ABI.

### Steps to Reproduce

Just try to build and run the source attached in source.zip I also added the il code.
[source.zip](https://github.com/odin-lang/Odin/files/5113896/source.zip)

**Comment by jkolb** [comment]
When a method returns a struct you have to call objc_msgSend_stret instead of objc_msgSend (it is not possible to tell from the info provided here if you are doing that or not).

https://developer.apple.com/documentation/objectivec/1456730-objc_msgsend_stret?language=objc

**Comment by Platin21** [comment]
Yeah you are right i should have said it’s about line 30 in the source code that i attached. And yes i use the correct method but the compiler doesn’t generate the correct return code.

**Comment by jkolb** [comment]
I found this (http://sealiesoftware.com/blog/archive/2008/10/30/objc_explain_objc_msgSend_stret.html) that makes it seem like on x86_64 platforms you may need to use objc_msgSend instead as some structs can be returned in registers, but I haven't found the rules on how to tell which ones meet that criteria since the Apple docs are obsolete. Probably have to search through the clang source code for the up to date rules.

Also I notice there is reference to more code in source.zip than there is at https://github.com/Platin21/odin-objc, would it be possible to release it (even if it isn't ready)?

**Comment by jkolb** [comment]
Strangely hard to find info on this subject, this (https://www.agner.org/optimize/calling_conventions.pdf) seems to have some good info in it.

**Comment by Platin21** [comment]
The fun part is that if use stret and add the structure return as a first pointer parameter it just works. While if i return it normally it doesn’t.

**Comment by jkolb** [comment]
From what I read in that PDF above it should be return them like this 

> four floats: XMM0 and XMM1

Why it's not working in Odin 🤷

I started thinking due to things like these it might be better to wrap Objective-C into C functions and let clang handle those issues.

**Comment by jkolb** [comment]
Whoops nevermind, I forgot CGFloat is double on 64-bit platforms

**Comment by Platin21** [comment]
Yeah thing is i don’t want to deal with a C build system. (Even if it would be just a makefile)

**Comment by powerc9000** [comment]
I've also had issues like this #587. Passing in a pointer as a return value is the way I worked around it in those cases. Would definitely like to see this fixed

**Comment by Platin21** [comment]
Yeah, llvm api looks promising for that but there needs to be something fixed about the way it passes args. Then we could go forward with that.
