### ISSUE TITLE
Question: Is there any static lib path like in C?

### ISSUE THREAD

**Issue by t0md3an** [odin-lang/Odin#717]
@kevinw @hasenj @Kelimion @zhiayang @castano 

I there any static lib path like in C? I mean any path like `/usr/include` to do something like this:

```odin
package main

import <core/fmt>

main :: proc() {
    using fmt;
    println("hi");
}
```

**Comment by gingerBill** [comment]
C's approach has numerous problems which Odin's approach solves. This is the reason behind library collections in Odin.
```go
import "relative/to/current/file"
import "library:relative/to/named/collection"
```

in the basic example:
```go
import "core:fmt"
```
means "look for the directory `fmt` in the library collection called `core`".

You can define your own library collection with the command line flag:
```
-collection:blah=path/to/thing
```

----

Also, please try not to tag people for help in a GitHub issue.

**Comment by t0md3an** [comment]
@gingerBill You have not answered on my question. I want to write package manager for Odin and I want to know where I should place packages.

**Comment by ThisDrunkDane** [comment]
There is the `shared` collection which is a folder next to the odin exe, but doing versioning there is gonna be annoying

**Comment by gingerBill** [comment]
@t0md3an You didn't ask that question initially and that question is quite a different beast.

If you want to make a package manager which installs into a __global__ directory, I personally don't recommend this for numerous reasons, and I recommend each project should be responsible for its dependencies. This also reduces the vast majority of versioning issues too which is a huge issue when using a global directory. 

Don't copy the mistakes that other languages do, especially C. There are better approaches to things. 

But if you seriously still want a package manager which installs into a _global_ directory, then define a place yourself for that package manager, and ask people to do `-collection:my_manager=/usr/odin-pkgm` and then they can do:
```odin
import blah "my_manager:amazing_library/of/the/thingy"

the_variable: blah.The_Data_Type;
```

Odin does have a default "shared" collection which is a directory next to the Odin executable if you want to use that, but I stress, please don't copy the mistakes of older languages.

**Comment by powerc9000** [comment]
I second Bill. Though not perfect, the way Nodejs handles this is decent for a first pass.
Have some file that defines your packages and then install the packages to a known folder eg `my_manager` then as said before tell users to use the `collection` flag.
