### ISSUE TITLE
Identifier missing in error message (import)

### ISSUE THREAD

**Issue by Amselchen** [odin-lang/Odin#720]
## Context

* Operating System: Windows 10
* Please paste `odin version` output: version 0.13.0-nightly-7309cfdb

## Expected Behavior

Error Message: Import name, odin-sdl2, cannot be used as an import name as it is not a valid identifier

## Current Behavior

Error Message: Import name, , cannot be use as an import name as it is not a valid identifier

## Failure Information (for bugs)

The identifier is missing in the error message.

### Steps to Reproduce

1. Create a new odin project with a .odin file
2. Copy the folder odin-sdl2 next to .odin file  (https://github.com/JoshuaManton/odin-sdl2)
3. import the odin-sdl2 package in your program:

```odin
import "odin-sdl2"
```

**Comment by wilsonk** [comment]
PR #915 may be a solution for this. It seems to work (it just produces a fairly self explanatory error message), but may be incomplete as I only tested on Win10.

**Comment by wilsonk** [comment]
I think this can be closed now, yes? The PR seems to have been applied and works as intended, I believe (apologies if I didn't link to this issue in the PR!)
