### ISSUE TITLE
Providing multiple packages to same "using" statement creates invalid namespace collisions

### ISSUE THREAD

**Issue by jockus** [odin-lang/Odin#723]
## Context

Windows
odin version 0.13.0

## Expected Behavior

There should be no difference having a single statement using many packages or splitting them to multiple statements.

## Current Behavior

Separating using to several statements works fine.

### Steps to Reproduce

``` go
package main

import "core:fmt"
import "core:math"

main :: proc() {
	BREAK :: true;
	when BREAK {
		using fmt, math;
	}
	else {
		using fmt;
		using math;
	}
}
```

### Failure Logs

test.odin(9:3) Namespace collision while 'using' 'fmt' of: DEFAULT_BUFFER_SIZE
        at Odin/core/fmt/fmt.odin(13:1)
        at Odin/core/fmt/fmt.odin(13:1)

**Comment by bttelle** [comment]
@gingerBill please close.
