### ISSUE TITLE
-build-mode=object always generates main etc

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#729]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows x64
* Please paste `odin version` output: `odin version 0.13.0-31989c93`

## Expected Behavior

Compiling a file **without** a main procedure with `odin build filename.odin -build-mode=object` **should not** generate a `main` or anything to support one. Or any of the code from `core:runtime`, if it's not being referenced.

## Current Behavior

It _does_ generate `main` etc.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Compile the following snippet with `odin build file.odin -build-mode=object`:
```odin
package main

@export f :: proc "c" () -> int {
    return 42;
}

```
2. Use `objdump -d x.obj | findstr main`
3. It shows the dissassembly for the `main` that should not be there.
4. You can also use `objdump -t x.obj` to get a list of symbols that are present. There are many more than just `f`.

**Comment by gingerBill** [comment]
This requires adding a `-no-entry-point` flag
