### ISSUE TITLE
casting ^u8 to cstring fails

### ISSUE THREAD

**Issue by GideonUng** [odin-lang/Odin#730]
## Context

casting ^u8 to cstring fails

`foo := cast(cstring)cast(^u8) uintptr(0);`
fails with 
`Cannot cast '0' as 'cstring' from '^u8'`

* Operating System:
windows 10
* Please paste `odin version` output:
odin version 0.13.0-nightly-079b8873

## Expected Behavior

cstring is an distinct alias of ^u8 so an explicit cast should succeed

## Current Behavior

cast fails

### Steps to Reproduce

```
package main
main :: proc () {
	foo := cast(cstring)cast(^u8) uintptr(0);
}
```

**Comment by gingerBill** [comment]
This is not actually a bug. This is because constant strings must be knowable at compile time. Odin's type system is very different to C. 
I could allow this but what I'd need to do is make it a non-constant when it casts.

**Comment by Tetralux** [comment]
This also does not work if you use `:=`, so it can't be because it must be a constant or known at compile time, surely?
