### ISSUE TITLE
Erroneous redeclaration error of polymorphic variable

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#741]
* Operating System: Windows x64
* `odin version` output: `odin version 0.13.1-10afc58d`

```odin
//
// Error message: `Redeclaration of 'T' in this scope` pointing to the two `$T`s.
//

main :: proc() {
    null_fn :: proc(arg: ^$T) {
        fmt.println("null_fn: ", arg^);
    }

    // NOTE: second T is not a new variable
    g :: proc(arg: ^$T, fn: proc(^T) = null_fn) {
        fn(arg);
    }

    i := 44;
    
    //
    // Either of these calls cause the same problem
    //

    g(&i);
    g(&i, proc(x: ^int) {
        fmt.println("callback: ", x^);
    });
}
```
Both of these problems appear to occur whether `null_fn` and `f`/`g` is at file scope or procedure scope.

I expected this to compile and run, outputting:
```
null_fn:  44
callback:  44
```

**Comment by bttelle** [comment]
Minimal reproducer:
```odin
package main;
main :: proc() {
    null_fn :: proc(arg: $T) {}
    g :: proc(arg: $T, fn: proc(int) = null_fn) {}
    g(0);
}
```

**Comment by Tetralux** [comment]
@gingerBill This bug still occurs on current master, as of 63b54ce7c695fb1e204fe77db029cdebf7206b28.

**Comment by gingerBill** [comment]
> @gingerBill This bug still occurs on current master. ([63b54ce](https://github.com/odin-lang/Odin/commit/63b54ce7c695fb1e204fe77db029cdebf7206b28).)

I fixed the thing that bttelle showed rather than yours. Yours is a different bug entirely, and probably shouldn't be allowed in the first place.

**Comment by Tetralux** [comment]
> > @gingerBill This bug still occurs on current master. ([63b54ce](https://github.com/odin-lang/Odin/commit/63b54ce7c695fb1e204fe77db029cdebf7206b28).)
> 
> I fixed the thing that bttelle showed rather than yours. Yours is a different bug entirely, and probably shouldn't be allowed in the first place.

Just to be clear, both examples (including bttle's) _still_ raise a redeclaration error.
