### ISSUE TITLE
Odin crashes on "core:log" and "core:math/linalg" conflict

### ISSUE THREAD

**Issue by jharler** [odin-lang/Odin#742]
## Context

Any procedure that uses both 'import: "core:log"' and 'using linalg;' crashes Odin.

* Operating System: Windows 10
* Please paste `odin version` output: odin version 0.13.1

## Expected Behavior

Valid compilation.

## Current Behavior

Complains about 'log' of type 'proc($T, $T) -> $T' has no field 'error'

It appears to be confusing the "log." which is a package with the "log" procedure in linalg package.  I would expect Odin to first search packages, then search procedures when looking up an identifier, and if there is an error with one, search the other.  In other words, in this case, Odin sees this particular issue with this identifier, it should check if the identifier is actually part of a package instead of exiting as an error.

### Steps to Reproduce

package main

import "core:log"
import "core:math/linalg"

main :: proc() {
	using linalg;
	log.error("testing");
}
### Failure Logs

Debugging into Odin reveals a crash in is_divigering_stmt() where type_of_expr is returning nullptr and it's not being checked for null before accessing.

**Comment by ThisDrunkDane** [comment]
With how Odin is _mostly_ explicit in nature, I'm would actually expect this to not compile and rather have you the user solve the conflict by using some other import name for `log`. The error message should be clearer tho' about why this doesn't compile, that's my 2 cents anyway.

**Comment by jharler** [comment]
It's not really a conflict though.  There's no reason why the package "log" (which always must be used as "log.<identifier>") and a procedure "log" (which will never have a "." after it) cannot co-exist without ambiguity.

**Comment by ThisDrunkDane** [comment]
In this instance yes, but it also makes the code susceptible where for example if `log` in `math` (for some weird reason) got changed to a struct called `log` with a proc ptr called `error`, which does it resolve to then? Yes it could just error out in that case, but I would be more annoyed with how it would work in some cases and not other. I'm not saying having having it solve the ambiguity wouldn't be nice, but with Odin focus on being explicit, I think I would prefer it to just error out always.

**Comment by jharler** [comment]
In that case I would expect an ambiguity error.  In this case, there is no ambiguity.  This isn't a matter of automatically converting one type to another.  This is resolving identifiers, which should be done automatically, IMO, like shadow variables are.

I suppose ultimately it's up to Bill on how to resolve this, but at the very least, the crash should be fixed.

**Comment by ThisDrunkDane** [comment]
Yes the crash should definitely be solved 😄 It is true about shadow variables being similar to this 🤔
