### ISSUE TITLE
llvm-api: Compiler crash when copying relative pointers

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#744]
* Operating System: Windows x64
* Please paste `odin version` output: `odin version 0.13.1-20e45489`

The following program, when compiled with `odin run file.odin -llvm-api` crashes the compiler with the following output.

```odin
main :: proc() {
    x: [4]byte;
    p  : #relative(i16) ^byte = &x[0];
    p2 := p;
}
```
```
test.main
lb_emit_conv: src -> dst
Not Identical #relative(i16) ^u8 != ^u8
Not Identical #relative(i16) ^u8 != ^u8
Not Identical 26273947700 != 26273948700
Not Identical 26273947700 != 26273948700
src\llvm_backend.cpp(6405): Panic: Invalid type conversion: '#relative(i16) ^u8' to '^u8' for procedure 'test.main'
```

**Comment by wilsonk** [comment]
Still seems to be happening after removal of the old backend. Win10 with odin version dev-4-28-1-:94fd59e6. Of course, -llvm-api is no longer required.

**Comment by gingerBill** [comment]
Relative pointers are an experimental feature and were rarely used, so I'll try and fix this.
