### ISSUE TITLE
Impropper linking on MacOS.

### ISSUE THREAD

**Issue by powerc9000** [odin-lang/Odin#748]
## Context
In the following code

```
	foreign import raylib_host {
		"libraylib.a",
		"raygui.o",
		"raylib.o",
		"system:Cocoa.framework",
		"system:IOKit.framework",
		"system:CoreVideo.framework",
		"system:GLUT.framework",
		"system:OpenGL.framework"
	}
```
The linking step fails with: `ld: library not found for -l/Users/powerc9000/harper_game/raylib/host/raylib.o`

This is because odin shouldn't be using `-l` as the flag for this import. This also fails on `raygui.o` if any file is renamed to be a `.a` file the error goes away. 

`-l` is only for libraries and will only search in the library search path.

* Operating System: Macos
* Please paste `odin version` output: odin version 0.13.1-464e733b

## Expected Behavior
The `ld` step should include `/Users/powerc9000/harper_game/raylib/host/raylib.o` as a normal file not as a library file

## Current Behavior
`ld` tried to load `raylib.o` as a library file

**Comment by Platin21** [comment]
That’s a easy fix in main.cpp, i‘ll take this.

**Comment by powerc9000** [comment]
Yeah this all worked fine before I updated to this version. I hadn't updated in a while before that so I don't know that I could say what version it broke on.

**Comment by Platin21** [comment]
Which version did you have before?

**Comment by powerc9000** [comment]
Not sure but it looks like the error comes from here: 
https://github.com/odin-lang/Odin/blob/1818ceb4f2b474152fed0cb7e5cfaeaa26e00105/src/main.cpp#L350

We only check if it ends in `.a` but not `.o` if that's a limitation of what the compiler is going to do that's fine.

**Comment by Platin21** [comment]
Looks more like nobody cared, not so long ago frameworks didn’t work either so no surprise.

**Comment by Platin21** [comment]
Here is the patch, pls try:
[patch.txt](https://github.com/odin-lang/Odin/files/5314335/patch.txt)

I'll need to create some sort of demo project myself to check the fail

**Comment by powerc9000** [comment]
I made about the same PR https://github.com/odin-lang/Odin/pull/749

**Comment by Platin21** [comment]
Ok

**Comment by Platin21** [comment]
@powerc9000 you know we both changed only the -llvm-api side, so that will not change anything in regards to the problem you had 😆

**Comment by Platin21** [comment]
@powerc9000 can you check if it’s fixed for you now?

**Comment by powerc9000** [comment]
It appears to have worked.
