### ISSUE TITLE
Typo in Language Spec

### ISSUE THREAD

**Issue by mb64** [odin-lang/Odin#750]
In the [Operators and Punctuation section](http://odin-lang.org/ref/spec/#operators-and-punctuation), it lists all of ≠, ≤, ≥, ∈, and ∉ as U+2260.

The real codepoint values are:

```
≠ U+2260
≤ U+2264
≥ U+2265
∈ U+2208
∉ U+2209
```

**Comment by gingerBill** [comment]
Those have been removed now, and the spec needs to reflect that.
