### ISSUE TITLE
PROPOSAL: Compiler flag -no-main

### ISSUE THREAD

**Issue by F0x1fy** [odin-lang/Odin#754]
# Proposal: -no-main

Author(s): F0x1fy
Last updated: 2020-10-08

## Abstract
This proposal suggests a `-no-main` flag to be used with `odin check` that removes the `Undefined entry point procedure 'main'` error.

## Proposal
The `-no-main` flag would be a flag specifically for `odin check`, raising an error when used with any other subcommands. This flag would remove the `Undefined entry point procedure 'main'` error, useful when programmatically checking several packages that do not have a `main` procedure. An example: `odin check . -no-main` would be a valid, but `odin build . -no-main` would not be, as for building (outside of libraries), a `main` procedure is required. The same would apply for `odin run`, and optionally `odin query`, `odin docs`, and `odin version`.

## Rationale
It's possible that someone may need to check a package that does not have a main, or multiple packages that do not have mains if the code is not currently linked in any way to the file which has their `main` procedure. This could be useful for checking code early on, checking code in isolation, or doing check on groups of unrelated packages, potentially libraries, for the sake of safety. Example of the rationale:
```
/home/f0x1fy/Programming/Projects/Dymagica/src/engine/entities/entity.odin(1:1) Undefined entry point procedure 'main'
/home/f0x1fy/Programming/Projects/Dymagica/src/engine/gui/context.odin(1:1) Undefined entry point procedure 'main'
/home/f0x1fy/Programming/Projects/Dymagica/src/engine/physics/gravity/gravity.odin(1:1) Undefined entry point procedure 'main'
/home/f0x1fy/Programming/Projects/Dymagica/src/engine/physics/materials/materials.odin(1:1) Undefined entry point procedure 'main'
/home/f0x1fy/Programming/Projects/Dymagica/src/engine/physics/materials/material_states/material_states.odin(1:1) Undefined entry point procedure 'main'
/home/f0x1fy/Programming/Projects/Dymagica/src/engine/physics/physics_types/types.odin(1:1) Undefined entry point procedure 'main'
/home/f0x1fy/Programming/Projects/Dymagica/src/engine/world/world.odin(1:1) Undefined entry point procedure 'main'
/home/f0x1fy/Programming/Projects/Dymagica/src/engine/world/world_data/world_data_meta/meta.odin(1:1) Undefined entry point procedure 'main'
/home/f0x1fy/Programming/Projects/Dymagica/src/engine/world/world_data/world_data_terrain/world_terrain.odin(1:1) Undefined entry point procedure 'main'
```

## Compatibility
There would be no compatibility issues with previous versions, unless one was trying to use the flag in previous versions.

## Implementation
The implementation would simply disable the `Undefined entry point procedure 'main'` error when the flag is enabled, through whichever normal means the compiler checks for flags.

**Comment by Tetralux** [comment]
Cross-linking to #729.
