### ISSUE TITLE
Cannot take address of field within union type

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#755]
## Context

* Operating System: Windows x64
* Please paste `odin version` output: `0.13.1-1b4bccbc`

## Expected Behavior

Compiles and all asserts pass.

## Current Behavior

Does not compile with error `Cannot take pointer address of 'u.(A).i'`.

```odin
package main

import "core:fmt"

main :: proc() {
	A :: struct {
		i: int,
	};

	B :: struct {
		f: f64,
	};

	U :: union {
		A,
		B,
	};

	u := U( A{int(42)} );

	v := &u.(A).i;

	assert(v^ == 42);

	inner := &u.(A);
	assert(v == &inner.i);

	fmt.println("All good");
}
```

**Comment by gingerBill** [comment]
This is not a bug and intended behaviour.

**Comment by Tetralux** [comment]
That might be the fastest yet. 🤣
