### ISSUE TITLE
compiler crash

### ISSUE THREAD

**Issue by benoitjacquier** [odin-lang/Odin#771]
## Context

Compiler crash using this code

```
package main

import "core:fmt"
//import mu "microui"       

main :: proc() {
    fmt.println("Hello World\n");
    // COMPILER CRASH
    ctx := new(mu.Context);
    mu.init(ctx);
    ctx.text_width = proc(font: mu.Font, str: string) -> i32 {
        return 0;
    };
    // COMPILER CRASH
}
```

* Operating System: Win 10
* Please paste `odin version` output: 0.13.1

## Failure Information (for bugs)
odin.exe crashes in is_divigering_stmt func:  base_type(t) returns null.
Can send minidump if needed.

Regards

**Comment by wilsonk** [comment]
I tested this on Win10 and Debian 10 (buster) just now with Odin version dev-4-28-1-:94fd59e6. It seems to work fine now on both systems. I didn't test macos. Perhaps this can be closed?
