### ISSUE TITLE
Failed conversion from u128 to f64 (at compile time)

### ISSUE THREAD

**Issue by hectormonacci** [odin-lang/Odin#777]
## Context

* Operating System: Void Linux (x86_64)
* odin version 0.13.1-7c5247f5

## Expected Behavior

`f64(340282366920938463463374607431768211455)` should yield a value similar to `3.402823669209385e+38`

## Current Behavior

`f64(340282366920938463463374607431768211455)` yields `4474081322694335476531.000`

## Failure Information (for bugs)

You cannot trust the result of the conversion from a really big u128-typed integer to a 64-bit floating point number, be it for printing to stdout or stderr or to use the converted number as part of further calculations. After the conversion to f64, the number is severely diminished in value.

### Steps to Reproduce

This is a MWE:

```odin
package main

import "core:fmt"

MAX : u128 : 340_282_366_920_938_463_463_374_607_431_768_211_455; // echo "(2^128) - 1" | bc

main :: proc() {
	fmt.println("If you convert", MAX, "to f64, you get", f64(MAX));	
}
```
The output should be similar to 340282366920938463463374607431768211455, but you get a much smaller number,  4474081322694335476531.000

### Failure Logs

There are no failure logs to be shown.

**Comment by gingerBill** [comment]
Related to issue #781

**Comment by gingerBill** [comment]
This will be fixed in a coming PR
