### ISSUE TITLE
Allow enums and bit_sets as values for -define

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#780]
For example:
```odin
package main

Level :: enum {
  None,
  Basic, 
  More,
  All,
}

debug :: proc(format: string, args: ..any) {
  when #config(PROJ_DEBUG, Level.None) > .None {
    s := fmt.aprintf(format, ..args);
    defer delete(s);
    fmt.printf("[debug] %v\n", s);
  }
}
```
```
odin build test.odin -define:PROJ_DEBUG=.All
```
The compiler exits immediately without doing any compilation, with an exit code of `1`.

Ideally, this would parse the value given and set `PROJ_DEBUG` to `Level.None`.

You could also imagine a similar thing if `Level` was a `bit_set` instead of an enum.

For example:
```
odin build test.odin -define:PROJ_DEBUG={.Basic, .More}
```

**Comment by gingerBill** [comment]
I am not sure I would allow this because would be an untyped literal, which is not allowed in Odin.

**Comment by Tetralux** [comment]
I wouldn't understand that it's a `Level` from the `when #config(PROJ_DEBUG, Level.None)` ?

**Comment by gingerBill** [comment]
Good point _but_ the this does lead to a question of whether or not it should allow any compound literal.

**Comment by Tetralux** [comment]
It would probably be a bit awkward to provide a full struct literal on the command line, though I imagine you could do it.
I'm not sure when you'd want/need to be able to do that, though, not sure I could preclude it.

**Comment by thebirk** [comment]
`-define:MY_CONFIG_STRUCT=./config.json` 😎
