### ISSUE TITLE
Casting i128s to floats is broken

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#781]
* Operating System: Linux x64
* Please paste `odin version` output: `odin version 0.13.1`

On ca4b0527 (current master):

```odin
package main

import "core:fmt"

main :: proc() {
	i := i128(42);

	f := f64(i);
	g := i64(i);

	fmt.println(i, f, g);  // 42 0.000 42
}
```
They should all be the same, but... `f` is wrong.

*On Windows, this is worse* - it crashes on the `f := f64(i);` line, while reportedly trying to read from `0xFFFFFFFFFFFFFFFF`. (According to Visual Studio.)

With `-llvm-api` however, this example works as expected - on Windows, at least. Obviously, I cannot currently test that on Linux.

Edit: I discovered this when the type of `i` was `distinct i128`, but it turns out that actually makes no difference; it does the same thing if it's just a normal `i128`.

**Comment by Tetralux** [comment]
Update: The fact that it's `distinct` **has no effect.**

**Comment by oskarnp** [comment]
This works fine for me on macOS.
