### ISSUE TITLE
Proposed/Implemented New Packages for `core`

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#782]
Proposed New Packages for `core`

* [ ] `archive/tar`
* [ ] `archive/zip`
* [x] `bufio` buffered I/O streams
* [x] `bytes` []byte version of `strings`
* [ ] `container` - more general container types
* [x] `c/token` - tokenizer for C with an inline preprocessor
* [ ] `c/parser` - parser for C
* [x] `compress/gzip`
* [ ] `compress/lzw`
* [ ] `compress/lz4`
* [x] `compress/zlib`
* [ ] `encoding/csv`
* [ ] `encoding/ini`
* [ ] `encoding/punycode` (maybe?)
* [ ] `encoding/toml` (maybe?)
* [ ] `encoding/xml`
* [x] `io` generic data streams
* [ ] `math/big` - arbitrary-precision arithmetic (i.e. big numbers) (integers, rationals, floating-points)
* [ ] `net` - portable interface for network I/O (TCP/IP, UDP, Unix sockets, etc)
* [ ] `net/http` - HTTP client and server implementations
* [ ] `net/smtp` - implementation of Simple Mail Transfer Protocol
* [ ] `odin/printer` - implements printing of AST nodes, useful for automatic formatting
* [ ] `odin/checker` - odin semantic checker (compiler frontend)
* [ ] `regexp` - regular expression matching, probably based on https://swtch.com/~rsc/regexp/regexp1.html
* [ ] `terminal` - package to control the _terminal/console_, allowing for colouring and cursor moving.
* [x] `text/scanner` - general scanner for work on Odin/C like strings
* [ ] `text/template` - data-driven template generation for textual output
* [ ] `time/tzdata` - embedded copy of the timezone database

**Comment by thebirk** [comment]
I wrote a basic tar and zip reader a while back, might serve as a, somewhat, useful start for `archive/tar` and `archive/zip`. At the very least it has some structs 😄 

Tar reader: https://gist.github.com/thebirk/4d78d0884b963ab7175e708a6933b681
Zip reader: https://gist.github.com/thebirk/bd478a8d0912f42b3e58cdae178dddbe

**Comment by gingerBill** [comment]
`package container` probably needs to be completely redone and rethought out. It might make more sense to have a sub-package for each data structure rather than have them in one big package.

And my original idea to reimplementations of a map and dynamic array was not a good idea, especially since it was not idiomatic.

**Comment by Kelimion** [comment]
`compress/gzip` and `compress/zlib` have their decompression routines done. Compression is underway.
