### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by dbechrd** [odin-lang/Odin#784]
## Context

Hello. I downloaded Odin like 5 minutes ago, so excuse the stupid code, but I tried to compile this:
```c
package test1
import "core:fmt"

main :: proc() {
    fmt.println("test", "test", "test", "test", sep=":");
}
```
and got this error:
```
test1.odin(5:52) Mixture of 'field = value' and value elements in a procedure all is not allowed
```
I haven't really tried to figure the error out, but I'm pretty sure the word `all` should be `call` in the error message.

**Comment by Tetralux** [comment]
Probably, yeah.

You can avoid this error, by the way, with `fmt.println(args={"test", "test", "test", "test"}, sep=":");`.

https://github.com/odin-lang/Odin/blob/260e28c0af2130a78862a5e253b98178fb480f02/core/fmt/fmt.odin#L117

**Comment by dbechrd** [comment]
https://github.com/odin-lang/Odin/pull/787
