### ISSUE TITLE
Not providing type in assignment causes codegen assert to fail

### ISSUE THREAD

**Issue by Lord-Remington-the-3rd** [odin-lang/Odin#791]
## Context

`old_base := pop(&tag_stack);
 base := old_base[:len(old_base) - 1];`

* Operating System: Linux 4.16.18-galliumos (ubuntu distro for chromebooks)
* Odin Version: 0.13.1-nightly-a55568b0
  
## Current Behavior
If 'old_base' is not annotated as a string it will result in the crash below. Including the type in assignment fixes this error. The frontend does not seems to be the issue at all, since when trying: `old_base: int` I was correctly told that 'old_base' was a string.

## Failure Information (for bugs)
**src/ir.cpp(8934): Assertion Failure: `type == t_string` 
Illegal instruction (core dumped)**

**Comment by gingerBill** [comment]
@Lord-Remington-the-3rd Can you provide a minimal replication of this bug please?

**Comment by Lord-Remington-the-3rd** [comment]
`package main

main :: proc() {
    arr := make([dynamic] string, 0, 10);
    append(&arr, "Hi Ginger Bill! \n");
    
    str := pop(&arr);
    new_str := str[:len(str) - 1];
    
}
`
Also, if str is a literal instead of being supplied by pop, it works.

**Comment by Lord-Remington-the-3rd** [comment]
You might have noticed that I had to edit that post 4000 times. Sorry about that, im new to this.

**Comment by Lord-Remington-the-3rd** [comment]
@gingerBill so i believe i can pinpoint why its erroring out in the first place now. If you delete the slice operator and have it just be `new_str := str;` it works. So the compiler seems to bug out due to a combination of type inference and slicing. 

PS: As a reminder, annotating str as a string also fixes the issue.

**Comment by ThisDrunkDane** [comment]
This is from the old backend, no longer applicable
