### ISSUE TITLE
Odin fails `brew test` on Big Sur

### ISSUE THREAD

**Issue by carlocab** [odin-lang/Odin#792]
## Context

* Operating System: macOS 11.0.1
* Please paste `odin version` output: 
```sh
❯ odin version
odin version 0.13.0-
```
## Expected Behavior

`brew test odin` should succeed.

## Current Behavior

`brew test odin` produces the following error:

```sh
Error: odin: failed
An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - ./hellope
[snip]
```

See https://github.com/Homebrew/homebrew-core/pull/65223#issuecomment-733654271 for details.

### Steps to Reproduce

Run the following commands in a terminal.
1. `brew install odin`
2. `brew test odin`

### Failure Logs

[test.01.odin.log](https://github.com/odin-lang/Odin/files/5596693/test.01.odin.log)
```sh
❯ brew install odin && brew test odin
==> Downloading https://homebrew.bintray.com/bottles/odin-0.13.0.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/772509e10bf0a73af78b51e4f85309eb6d25e0078d1f2fa02bfa2d252e0055ca?respons
######################################################################## 100.0%
==> Pouring odin-0.13.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/odin/0.13.0: 133 files, 2.6MB
==> Testing odin
==> /usr/local/Cellar/odin/0.13.0/bin/odin version
==> /usr/local/Cellar/odin/0.13.0/bin/odin build hellope.odin
Error: odin: failed
An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - ./hellope
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/odin.rb:49:in ``'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/odin.rb:49:in `block in <class:Odin>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1862:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:500:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1861:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:900:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1860:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2104:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1854:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:42:in `<main>'
```

**Comment by carlocab** [comment]
For reference, `brew test odin` attempts to compile the following program:

```
package main

import "core:fmt"

main :: proc() {
    fmt.println("Hellope!");
}
```

Compiling this program produces this error:
```
❯ odin build test.odin
ld: library not found for -lc
```

**Comment by gingerBill** [comment]
Odin requires LLVM in order to work and it appears that LLVM is not being installed alongside Odin.

I don't know who has set up the homebrew for Odin.

**Comment by carlocab** [comment]
Odin declares llvm as a dependency. You don't see it installed in the snippet I shared because I already have it installed an included in my `PATH`.

```sh
❯ brew info odin
odin: stable 0.13.0 (bottled), HEAD
Programming language with focus on simplicity, performance and modern systems
https://odin-lang.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/odin.rb
License: BSD-2-Clause
==> Dependencies
Required: llvm ✔
[snip]
```

If you check the logs in the PR I linked, you'll see that `brew test odin` succeeds on 10.14 and 10.15.

**Comment by gingerBill** [comment]
Wait a minute... the problem appears to be `-lc` is missing which should only be called on Linux, not macOS.

**Comment by carlocab** [comment]
I see. Well, for some reason, it is being called on Big Sur but not on earlier versions of macOS.

**Comment by Platin21** [comment]
You can’t add -lc in the macOS big sur version.

**Comment by gingerBill** [comment]
I don't even see where `-lc` is being added either.

**Comment by carlocab** [comment]
> You can’t add -lc in the macOS big sur version.

Noted. I didn't add it.

**Comment by Platin21** [comment]
It’s bit added for macOS and the main reason is that it doesn’t work. There is no library for tht anymore they moved that completely to System.

**Comment by Platin21** [comment]
Yeah it’s not in 13.0 but in current master it is correct.

**Comment by carlocab** [comment]
Homebrew can also apply a patch to 13.0 to get it working if the new version isn't going to be released soon.

**Comment by Platin21** [comment]
Thing is the patch would be inside of this repo itself. Just to fix that github changed there default macOS version.

**Comment by carlocab** [comment]
Yes, I understand that. Is there a specific commit on this repo that can be applied to 13.0?

If not, then, if the patch is small, it can be added directly in the Homebrew formula (the Ruby file that determines how Odin I is installed). If it isn't, then I can submit it to Homebrew/formula-patches for hosting until the next version of Odin is released.

**Comment by Platin21** [comment]
Should be https://github.com/odin-lang/Odin/commit/81398d21ed25ca50dcfab7b9c7135c33adbb8e34 i think.

**Comment by carlocab** [comment]
Great, thanks. Let me try and see if that commit will apply.

**Comment by carlocab** [comment]
Patch doesn't apply cleanly, sadly.
```
==> Patching
==> Applying 81398d21ed25ca50dcfab7b9c7135c33adbb8e34.patch
patching file src/main.cpp
Hunk #1 FAILED at 431.
Hunk #2 FAILED at 2221.
2 out of 2 hunks FAILED -- saving rejects to file src/main.cpp.rej
patching file src/main.cpp
Hunk #2 succeeded at 2100 (offset -39 lines).
patching file src/main.cpp
Hunk #1 FAILED at 435.
1 out of 1 hunk FAILED -- saving rejects to file src/main.cpp.rej
patching file src/main.cpp
Hunk #2 FAILED at 431.
Hunk #3 succeeded at 2097 (offset -39 lines).
Hunk #4 FAILED at 2181.
2 out of 4 hunks FAILED -- saving rejects to file src/main.cpp.rej
patching file src/main.cpp
Hunk #2 FAILED at 434.
Hunk #3 succeeded at 2100 (offset -39 lines).
Hunk #4 FAILED at 2187.
2 out of 4 hunks FAILED -- saving rejects to file src/main.cpp.rej
patching file src/main.cpp
Hunk #2 FAILED at 431.
Hunk #3 succeeded at 2097 (offset -39 lines).
Hunk #4 FAILED at 2182.
2 out of 4 hunks FAILED -- saving rejects to file src/main.cpp.rej
```

**Comment by Platin21** [comment]
Yeah i almost suspected that because it’s a merge and there where other changes.

**Comment by carlocab** [comment]
I see. 

Well, if you can come up with a single patch that can work (or even a series of commits that will), I'd be happy to fix the brew formula so that it'll work.

Otherwise, I guess brew-packaged Odin may have to wait for the next release to work on Big Sur.

**Comment by Rylan12** [comment]
I've opened a PR to backport the patch to work until the next version of `odin` is released. That should solve the problem. 

https://github.com/Homebrew/homebrew-core/pull/66906

**Comment by carlocab** [comment]
Thanks, @Rylan12!
