### ISSUE TITLE
Returning function call that returns tuple, miscompiles

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#795]
* Operating System: Windows x64
* Please paste `odin version` output: `odin version 0.13.1-5803fcc1`

The following code compiles--but shouldn't--if you use the old backend, and fails a compiler assertion with `-llvm-api`:
```
src\llvm_backend.cpp(508): Assertion Failure: `are_types_identical(a, value.type)` Equal_Proc != proc "contextless" (rawptr, rawptr) -> bool
```

```odin
package test

import "core:fmt"

main :: proc() {
        using fmt;

	E :: enum {
		Ok,
		Bad = 41,
	};

	g :: proc() -> (int, E) {
		return 0, .Bad;
	}

	f :: proc() -> (int, bool) {
		return g(); // should not compile, but does!!!
	}

	i, b := f();
	println(i, b, int(b)); // 0 true 1
        // if `f` returns `(int, int)` instead: 0 41 41
}
```

**Comment by Tetralux** [comment]
Update: On latest commit (400816ebf71c94cbc1a4454e72c2d12ec93b847c) `-llvm-api` no longer _asserts_, but does miscompile in the same way as the old backend.

**Comment by gingerBill** [comment]
@Tetralux This is a weird frontend bug and I will have to check it out later.
