### ISSUE TITLE
Odin doc -all-packages misses "slices" package

### ISSUE THREAD

**Issue by serge-hulne** [odin-lang/Odin#796]
## Context

* Operating System: 
Windows 10 (MSYS2)

* Please paste `odin version` : output : 
odin-windows-amd64\windows_artifacts\odin.exe version 0.13.1-nightly-a6301ab5

"odin doc Odin/ > doc.txt -all-packages" does not contain entries referring to the sort() or sort_by() procs.
("Odin" refers to my local Github clone of Odin (root level))

**Comment by gingerBill** [comment]
`-all-packages` needs to be renamed to `-all-packages-used` or `-all-packages-imported` to clarify its meaning

**Comment by serge-hulne** [comment]
Is there a way to extract the entire doc of Odin from the source, like Doxygen for C++ or pydoc?
