### ISSUE TITLE
LLVM IR error

### ISSUE THREAD

**Issue by st142148** [odin-lang/Odin#798]
## Context
* Operating System: Arch Linux 5.9.9-zen1-1-zen
* Odin version: 0.13.1-0ed1300b

```package main

import "core:fmt"

main :: proc () {
        fmt.println("Hello");
}
```

## Expected Behavior

It builds.

## Current Behavior

```
opt: test.ll:92:33: error: expected top-level entity
%io.Seek_Proc = type {i64, i32} (%io.Stream_VTable* , i64 , i64, i64, %runtime.Context*)*
                                ^

```

**Comment by gingerBill** [comment]
So I understand what this bug is, and it's a issue with LLVM's named types system which doesn't work for procedure types for some reason

**Comment by gingerBill** [comment]
@st142148 Does this still happen in the latest commit?

**Comment by st142148** [comment]
Yes, still there on 0.13.1-09a52b7e:

```
clang src/main.cpp -Wno-switch -Wno-pointer-sign -Wno-tautological-constant-out-of-range-compare -Wno-tautological-compare -Wno-macro-redefined -std=c++11 -DGIT_SHA=\"09a52b7e\" -g -pthread -ldl -lm -lstdc++ -o odin
./odin run examples/demo/demo.odin
opt: demo.ll:91:33: error: expected top-level entity
%io.Seek_Proc = type {i64, i32} (%io.Stream_VTable* , i64 , i64, i64, %runtime.Context*)*

```

**Comment by gingerBill** [comment]
Thank you for replicating it. I'll see how to resolve this as soon as possible since it's a breaking change.

**Comment by gingerBill** [comment]
I think I have fixed the bug now. Looks like LLVM craps out with parsing type names of procedure types which return a struct.
