### ISSUE TITLE
A `scan_peek` in `core:text/scanner`

### ISSUE THREAD

**Issue by ThisDrunkDane** [odin-lang/Odin#800]
**Is your feature request related to a problem? Please describe.**
In `core:text/scanner` I want a `peek` that actually does the `scan` behavior but resets the position in the data instead of just giving us the next `rune`.

**Describe the solution you'd like**
A probably smarter solution than below as I believe a few of them are reset anyway each scan/advance:
```odin
scan_peek :: proc(s: ^Scanner) -> rune {
    src_pos := s.src_pos;
    src_end := s.src_end;
    tok_pos := s.tok_pos;
    tok_end := s.tok_end;
    ch := s.ch;
    line := s.line;
    column := s.column;
    prev_line_len := s.prev_line_len;
    prev_char_len := s.prev_char_len;

    tok := scan(s);

    s.src_pos = src_pos;
    s.src_end = src_end;
    s.tok_pos = tok_pos;
    s.tok_end = tok_end;
    s.ch = ch;
    s.line = line;
    s.column = column;
    s.prev_line_len = prev_line_len;
    s.prev_char_len = prev_char_len;

    return tok;
}
```

**Comment by gingerBill** [comment]
Implemented with `scanner.peek_n` with commit 96d8971d

**Comment by ThisDrunkDane** [comment]
That does not implement the `scan` behavior? It just calls next which calls peek which calls advance?.

**Comment by gingerBill** [comment]
Whoops. I'll add peek_token_n too.
