### ISSUE TITLE
Labeled loop names bleeding across scope

### ISSUE THREAD

**Issue by jockus** [odin-lang/Odin#801]
## Context
```go
package main
import "core:fmt"
main :: proc() {
	{
		loop1: for i in 0..3 {
			fmt.println(i);
		}
	}

	{
		loop1: for i in 0..3 {  // Duplicate label with the name 'loop1'
			if i == 2 do continue loop1; 
			fmt.println(i);
		}
	}
}
```
* Operating System:
odin version 0.13.1-0ef02e67

## Expected Behavior
There shouldn't be any confusion regarding which loop label is being targeted

## Current Behavior

Does not compile with error above

**Comment by gingerBill** [comment]
That's by design. It's because labels are unique to the procedure, not unique to the scope.
