### ISSUE TITLE
Self Importing module is legal

### ISSUE THREAD

**Issue by Lord-Remington-the-3rd** [odin-lang/Odin#802]
## Context

* Linux x64, kernel 4.16.18
* odin version 0.13.1-nightly-98c8fde0

## Expected Behavior

An error disallowing self import.

## Current Behavior

A non-main module can import itself.
This allows me to prefix other public symbols in the module with the module name.

### Steps to Reproduce
make a module with name (we'll use target), make sure to name folder the same thing.

````
package target 

import "../target"

Y :: target.X;
X :: 4;
````

**Comment by Lord-Remington-the-3rd** [comment]
Also, I'm 'Bobby Shmurda'/Colby/'Motivated McGregor' on the discord. This and that other bug report (the one about type inference) prove I'm not useless after all. (I hope)

**Comment by gingerBill** [comment]
Not a bug. This is intended behaviour.
