### ISSUE TITLE
Compiler crash with unions

### ISSUE THREAD

**Issue by rytc** [odin-lang/Odin#809]
## Context

Compiler crash using unions. The crash happens with the below minimum example. 

If the `type: i16` under "AddEntity :: struct" is commented out, the crash does not happen.

* Operating System: Ubuntu 20.04
* `odin version 0.13.1`

## Failure Information (for bugs)

`src/check_type.cpp(2096): Assertion Failure: types.count > 0`

### Steps to Reproduce

```odin
package main

Segment_Types :: union {
    ClientInit,
    EntityPosition,
    AddEntity
}

Segment :: struct {
    opcode : u8,
    target : u8,
    data : Segment_Types,
}

ClientInit :: struct {
    x : i16,
    z : i16,
}

EntityPosition :: struct {
    x : i16,
    z : i16
}

AddEntity :: struct {
    x : i16,
    z : i16,
    type: i16
}

write_segment :: proc(segment: Segment) {
    switch data in segment.data {
        case ClientInit: {
        }
        case EntityPosition: {
        }
        case AddEntity: {
        }
    }
}

main :: proc() {
    t := Segment{};
    t.opcode = 3;
    t.target = 2;
    t.data = EntityPosition{3, 6};
    
    write_segment(t);
}
```

**Comment by oskarnp** [comment]
@rytc Please include the full output from `odin version` (with the git commit hash)

**Comment by rytc** [comment]
Commit hash: `b6aa549eb8a746837782ebba9eec07d0ca17b8a6`

**Comment by rytc** [comment]
After some more investigation, it looks like the problem is related to passing the struct to a procedure
`write_segment :: proc(segment: Segment) {`
If I change that to take a pointer, the crash doesn't happen. ie
`write_segment :: proc(segment: ^Segment) {`

**Comment by wilsonk** [comment]
Testing this example on Debian 10 (buster) and Win10 with Odin version dev-4-28-1-:94fd59e6 works now with the above code. It also works is you change 'write_segment' to accept a pointer to a struct and then use an '&' when sending 't' to 'write_segment'. Should this issue be closed?
