### ISSUE TITLE
Cannot use @disable with `-define`d value

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#815]
## Context

* Operating System: Windows x64
* Please paste `odin version` output: `odin version 0.13.1-3558848d`

## Expected Behavior

Produce no output, unless compiled with `-define:XXX=true`, in which case it should print:
```
Hi 12
```

## Current Behavior

Compiles, but never prints anything.

## Failure Information (for bugs)

In my larger project, where I originally tried to do this, it causes the compiler to crash when the `-define` is passed.

### Steps to Reproduce

```odin
package test

XXX :: false; // because it needs to be defined in order to use `@disabled` with it.
@(disabled=!XXX)
f :: proc(format: string, args: ..any) {
	fmt.printf(format, ..args);
}

main :: proc() {
	x := 12;
	f("Hi %v", x);
}

```

**Comment by Tetralux** [comment]
Note that if this specific set up is not meant to work (i.e: with `XXX :: false;` _and_ `-define`ing it), then it might still be nice to have the ability to achieve this, where you can `@disable` based on a `-define`d constant.

**Comment by hasenj** [comment]
Is `-define` supposed to overwrite constants defined in source files? 

I think you're supposed to use `#config` when you want a defined value to have a default value.

Examples from core library:

core/runtime/default_allocators.odin:30

```odin
DEFAULT_TEMP_ALLOCATOR_BACKING_SIZE: int : #config(DEFAULT_TEMP_ALLOCATOR_BACKING_SIZE, 1<<22);
```

core/math/linalg/specific.odin:8

```odin
Float :: f64 when #config(ODIN_MATH_LINALG_USE_F64, false) else f32;
```

**Comment by Tetralux** [comment]
Ah-ha! Yep, completely forgot `#config` was a thing, for some reason!
That appears to work.
