### ISSUE TITLE
LLVM API - Debug Symbol Support

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#818]
Integrate Debug Symbols using the LLVM C API for `-llvm-api` backend.

Related branch: https://github.com/odin-lang/Odin/tree/llvm-debug-symbols

**Comment by Platin21** [comment]
I'll take a look on the current problems and report. (I'll first need to setup the build for the Xcode project)

**Comment by ThisDrunkDane** [comment]
@gingerBill what is the state for this? What platforms currently "work" and at what state? I think it would help having a progress list  in this issue so we can see where we should help if we can, instead of chasing solved problems.

**Comment by gingerBill** [comment]
@ThisDrunkDane The state is that it's entirely blocked by LLVM. NO platform works. I cannot generate the debug information for each statement correctly without it producing an non-useful error message.

**Comment by Platin21** [comment]
Yeah also when i enable asserts it’s throws and throws and throws for all sorts of stuff.
First thing i had was noalias on integers which LLVM didn’t like for some reasons.

**Comment by gingerBill** [comment]
This is now working correctly with the LLVM API. Works for Windows but not working correctly for \*nix yet.

**Comment by ThisDrunkDane** [comment]
Still not working for *nix?

**Comment by Platin21** [comment]
On Linux it seems to now work for macOS i didn’t try right now. I report back if it works
