### ISSUE TITLE
LLVM API - Darwin ARM64 Support (e.g. M1 Mac)

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#819]
Support for the Darwin ARM64 (e.g. M1 Mac).

Requirements:

* [x] Compile on the M1 Mac
* [x] Support the ARM64 ABI fully

**Comment by powerc9000** [comment]
I have access to an ARM64 mac if you have builds that need testing etc.

**Comment by Platin21** [comment]
I think it more a thing of fixing the abi right now? And to add the correct target triple.
