### ISSUE TITLE
Call of @disable'd proc still evaluates arguments' values

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#823]
Calling a procedure that's marked `@disable`d, and passing a procedure call as an argument, that procedure call is executed, even if it's disabled.

* Operating System: Windows x64
* Please paste `odin version` output: `odin version 0.13.1-5aab5841`

```odin
package main

import "core:fmt"
import "core:mem"

@(disabled=true)
f :: proc(s: string) {
    fmt.println(s);
}


g :: proc() -> string {
    fmt.println("g() was called");
    return fmt.aprintf("the string returned from g()");
}

main :: proc() {
    arena: mem.Arena;
    mem.init_arena(&arena, make([]u8, 4096));
    context.allocator = mem.arena_allocator(&arena);

    f(g());

    fmt.printf("%v bytes allocated.\n", arena.peak_used);
    assert(arena.peak_used == 0);
}

```
```
g() was called
62 bytes allocated.
bug.odin(25:5) runtime assertion
```

**Comment by gingerBill** [comment]
I am not sure if this is a bug or not. It's clearly not the behaviour you wanted, but I am not sure if this the correct behaviour to have.

**Comment by ThisDrunkDane** [comment]
Personally I would also expect `g()` not to be called, that would mainly just force me to wrap anything I use which might get `disabled` because I don't want the program to do the extra "work" that was required to call `f()`

**Comment by Tetralux** [comment]
This  bug means that a `printf` that is `@disabled` unless I pass a `-define:`, for example, is not as useful as it could be.
... which is the context I originally came across this.
