### ISSUE TITLE
Usage of break in switch should be flagged as a compile error

### ISSUE THREAD

**Issue by pepa65** [odin-lang/Odin#824]
In switch, cases stop being evaluated after the first (break is the default). Hence, the break statement should not be allowed (unless it breaks out an enclosing loop!).

When there is no enclosing loop, and a break statement is used within a switch, it should be flagged as a syntax error. If there is an enclosing loop, the break within a switch should break out of the first enclosing loop. Right now, the break does nothing, it doesn't function in the switch, and it doesn't break out of the loop, and yet it is allowed to just be there.

**Comment by gingerBill** [comment]
One argument keep `break` is that it can help with reading, especially for empty case blocks.

**Comment by pepa65** [comment]
We know from documentation that empty case blocks are valid, and if the case matches, the next case will not be evaluated. This is idiomatic Odin. Right now we have to use a label to break out of any enclosing loop, and that should not be necessary. I didn't even know break in switch was still legal from the documentation, and it clearly says that in Odin, there is no need for a break statement in a switch construct. An empty case block is very easy to spot, and the semantics are known. Be bold in doing away with the break in switch, even if C people expect the opposite..!

**Comment by krixano** [comment]
Break can be used to break out of a switch early in an if statement, for example. So disallowing break in switches makes absolutely no sense.

> Right now we have to use a label to break out of any enclosing loop, and that should not be necessary

This is not true, afaik

**Comment by pepa65** [comment]
@krixano I mean: to break out of a loop that is enclosing a switch statement. It is nice to use break to break out of a loop. In Odin, we don't need a break to break out of a switch -- what's next, allowing break to break out of an if statement??
I think a language should be proud of its semantics, and aim for internal consistency, there is beauty in that.

**Comment by krixano** [comment]
By disallowing break in special circumstances you are actually being inconsistent.

1.) Odin *DOES* allow you to break out of if statements. That's already part of the language semantics.
2.) You *DO* need to be able to break out of switch statements in certain circumstances just not **at the end of a switch case**.
3.) You can already break out of loops within switch statements.

**Comment by pepa65** [comment]
OK, sorry, I was not aware of this broad allowance of break everywhere. I still think you shouldn't need it, except to break out of a loop, where you really do need it. But if it's already a widely ingrained part of the language, then I guess that's it...

**Comment by krixano** [comment]
Except sometimes you DO actually need break. Why do you continue to think break is *never* needed in switch statement?!?

**Comment by pepa65** [comment]
Because it is always avoidable, you can always make your way to the end of the case without using break (or goto).

And you can't break out of an if statement with break in Odin, only switches and loops.

If break is allowed within a switch, then you must use a label if you want to break out of an enclosing loop.

**Comment by gingerBill** [comment]
@pepa65 This is not true.

```odin
foo: {
   break foo;
}
```

**Comment by krixano** [comment]
> you can always make your way to the end of the case without using break (or goto).

This is not true in the case of goto. Period.

> And you can't break out of an if statement with break in Odin, only switches and loops.

Yes you can, with labels.

> If break is allowed within a switch, then you must use a label if you want to break out of an enclosing loop.

Which is consistent with everything else.

**Comment by pepa65** [comment]
OK, it said differently in the Overview, it said break can be used on `switch` and `for`. I can see how it might be a "better goto" to escape any context.

**Comment by krixano** [comment]
Saying break can be used in certain cases does NOT imply it cannot be used in cases not mentioned unless it uses the word "only"

**Comment by pepa65** [comment]
It seems that the break in Odin is a virtual goto, with the merit that it works on scopes (because labels work on scopes). I have never needed a break except to break out of a loop, perhaps that's a style issue... OK, I give up, if break is so pervasive in Odin, then let it be.

**Comment by gingerBill** [comment]
`break` is a `goto` in all languages. 

labels allow for a structured for of `goto`, as `goto` is inherently unstructured.
