### ISSUE TITLE
Allow negative values in slice expressions

### ISSUE THREAD

**Issue by pepa65** [odin-lang/Odin#828]
It would be so handy if we can use negative values in slice expressions (as in: designates the underlying array element as counted from the end), where -1 denotes the last element of an array. Especially for strings, selecting the last 3 positions: `str[-3:]`, or checking if the fourth from the last position is a dot: `str[-5:-4] == "."`.

**Comment by gingerBill** [comment]
No. As useful as they are in languages like Python, they are too costly to add to Odin. It requires branching on every index, which is very slow.

I do not want to allow this just for constant indices either.
