### ISSUE TITLE
Tried to compile sample code but it says "Windows SDK not found."

### ISSUE THREAD

**Issue by kcvinker** [odin-lang/Odin#830]
Hi all,
I did these things.
1. Downloaded prebuilt odin executables.
2. Extracted and pasted them in C:\Odin\
3. Added that path + bin path in env variable
4. Made sure that cmd is recognizing the term "odin".
5. Write a sample hello world program.
6. Tried to compile with this command - "odin run hello.odin".
But the result is - "Windows SDK not found." 
I am using Windows 10 x64.
My odin version is - " 0.13.1-nightly-53d8ec4d"

**Comment by ThisDrunkDane** [comment]
Do you have visual studio build tools installed?

**Comment by vinodvinu** [comment]
> Do you have visual studio build tools installed?

I have installed Visual Studio 2019 and i am doing some c# & vb.net programming.

**Comment by ThisDrunkDane** [comment]
You might be missing some development libraries if you only installed VS with the .NET tools, try and run the VS installer again and install the SDKs for C++ as well

**Comment by vinodvinu** [comment]
Thanks. Let me try.

**Comment by vinodvinu** [comment]
> You might be missing some development libraries if you only installed VS with the .NET tools, try and run the VS installer again and install the SDKs for C++ as well

Hi, I just installed VC++ build tools and it worked like a charm. Now, i want to learn more Odin and have some fun with GUI desktopp applications for my own use. I am looking for a direction to start.

**Comment by Tetralux** [comment]
The Discord's a good place for asking questions for how to approach stuff: https://discord.gg/CwtQABZ3.
Generally though, Win32 GUI stuff is probably gonna involve importing `core:sys/windows` though.

**Comment by vinodvinu** [comment]
Thanks @Tetralux  :)

**Comment by 89z** [comment]
Would maintainers consider offering a non Visual Studio option for Windows? This would solve the issue posted here.

Further, this is already done by several popular languages, such as:

- Go
- Rust
- Nim
- D
- Zig

**Comment by gingerBill** [comment]
@89z Why are you posting on a dead issue and replying with something that is irrelevant to the issue itself?

**Comment by 89z** [comment]
> Why are you posting on a dead issue

1. I post comment on OPEN issue
2. @gingerBill closes issue
3. @gingerBill complains user is commenting on closed issue

good game

> and replying with something that is irrelevant to the issue itself?

Assuming my suggestion was followed, it would literally solve the problem in the original issue. It seems you've never heard of an XY problem:

https://meta.stackexchange.com/a/233676
