### ISSUE TITLE
Typo not catched by the compiler, making opt throw an error

### ISSUE THREAD

**Issue by J-Revel** [odin-lang/Odin#832]
## Context

I introduced a typo in my code, that should have triggered a compiler error, but instead it is the opt that returned an error. Here is the minimal repro code :

I have Test_Struct in a my_package folder : 
```
Test_Struct :: struct(T: typeid)
{
    element: T
}
```

and in the main.odin :

```
package main

import "my_package"

test_proc :: proc(input: ^my_package.Test_Struct) // Typo here : works with Test_Struct($T)
{

}

main :: proc()
{
    input: my_package.Test_Struct(f32);
    test_proc(&input);
}
```

### Failure Logs

```
E:\Logiciels\Odin\bin/opt: E:/Projets/Perso/Advent-Of-Code-2020/bug.ll:5805:89: error: use of undefined type named 'my_package.Test_Struct-568'
        %2 = bitcast %"my_package.Test_Struct-568.my_package.Test_Struct\28f32\29-8572"* %0 to %my_package.Test_Struct-568*
```

**Comment by wilsonk** [comment]
Ok, I tested this on Win10 with odin version dev-4-28-1-:94fd59e6 (after old backend removal) and the above test doesn't throw any error now when compiling and running with "^my_package.Test_Struct". It also compiles and runs with "^my_package.Test_Struct($T)".

The issue now, is that I think the first case should still be an error caught by the compiler. It is shown as an error if you try to use Test_Struct.element inside of test_proc like this:

```
test_proc :: proc(input: ^my_package.Test_Struct) // Typo here : works with Test_Struct($T)
{
    fmt.println("{}", typeid_of(type_of(input.element)));
}
```

```
output:  'input' of type '^Test_Struct' has no field 'element'
```

This procedure prints the type just fine is you have the correct "Test_Struct($T)", however.
```
output: {} f32
```

**Comment by gingerBill** [comment]
This might still be a bug. What is the full error message when using:
```odin
test_proc :: proc(input: ^my_package.Test_Struct) // Typo here : works with Test_Struct($T) {}
```

**Comment by wilsonk** [comment]
The full error message is:
```
C:/Users/wilsonk/odin/mine/issue-832.odin(8:41) 'input' of type '^Test_Struct' has no field 'element'
```
if you use the Test_Struct.element inside the test_proc. There is no error if you don't use the Test_Struct.element inside test_proc...it just compiles and runs with
```
test_proc :: proc(input: ^my_package.Test_Struct)
```
but it doesn't output anything!  So I guess that there should be some error generated when the '($T)' is missing?

**Comment by gingerBill** [comment]
Yes. I'll fix this.

**Comment by gingerBill** [comment]
I don't get the same error message
