### ISSUE TITLE
SIMD support

### ISSUE THREAD

**Issue by ib00** [odin-lang/Odin#837]
What is the level of SIMD support in Odin?
Are there any examples of its use?

**Comment by Tetralux** [comment]
Odin currently has experiemental SIMD support, though my understanding is there is room for improvement.
```odin
x := [?]f32{1, 1, 1, 1};
y := transmute(#simd[4]f32) x;
y += 5; // uses SIMD ops
x = transmute(#simd[4]f32) y;
```
