### ISSUE TITLE
printf Returns Incorrect Value

### ISSUE THREAD

**Issue by Denzeduous** [odin-lang/Odin#841]
## Context

Using 0.13.1. Still happens on newer versions (according to TylerE), but the result of the bug is different on each one.

* Operating System: Linux
* Please paste `odin version` output: odin version 0.13.1-27d06605

## Expected Behavior

The return value of `printf` should return the length of the printed string (unless this was explained incorrectly to me).

## Current Behavior

Prints out nonsensical numbers on older versions and 0 on newer versions.

## Failure Information (for bugs)

Any `printf` fails.

### Steps to Reproduce

```
package printf_bug

import "core:fmt"

main :: proc () {
    length := fmt.printf ("Hello, World!\n");
    fmt.println (length);
}
```

### Failure Logs

```
Hello, World!
139968689209358
```

**Comment by terickson001** [comment]
On the latest version (0.13.1-effee8e8), `fmt.printf` seems to always return `0`

**Comment by gingerBill** [comment]
This appears to be related to `os.stdout` as a stream than `fmt.*`

**Comment by gingerBill** [comment]
Is this a problem any more?

**Comment by F0x1fy** [comment]
Unknown. I will check whenever I have the chance. I’m pretty busy today, so possibly tomorrow

**Comment by Kelimion** [comment]
Still prints `0` as of the current build.

**Comment by mateus-md** [comment]
> This appears to be related to `os.stdout` as a stream than `fmt.*`

Debugging the problem I reached the potential root of the problem. And it's not restricted to os.stdout, but for os.stderr too. As far as I noticed, the problem involves the os_linux:_unix_fstat proc. I don't know how further it involves that
