### ISSUE TITLE
clone_dynamic_array() causes compiler assertion to be hit.

### ISSUE THREAD

**Issue by sumofat** [odin-lang/Odin#847]
## Context
```

buf_copy :: proc(buf : ^Buffer($element_type),copy_contents : bool  = false) -> Buffer(element_type)
{
    assert(buf != nil);
    result : Buffer(element_type);
    result.current_id = buf.current_id;
    result.borrow_count = buf.borrow_count;
    result.buffer = clone_dynamic_array(buf.buffer);    
    return result;
}
```

Windows 
odin version 0.13.1-d168c793

## Expected Behavior

Reasonable compiler error

## Current Behavior

Assertion hit in compiler.

## Failure Information (for bugs)

Seems I am doing something that I shouldnt be but still the compiler should not crash.

### Failure Logs

Odin\src\ir.cpp(8176): Assertion Failure: `tv.mode != Addressing_Invalid`

**Comment by ThisDrunkDane** [comment]
Old backend bug
