### ISSUE TITLE
Simplify pointer and dereference syntax so that XOR can have a proper operator

### ISSUE THREAD

**Issue by PeteyChan** [odin-lang/Odin#848]
I just stumbled on this language and I'm liking what I've seen so far. Just going through the docs and I was hoping you'd entertain a suggestion.

I think having  ^  to denote a pointer and & for address could be simplified to just & as the semantic difference between the two is pretty negligible. This also strengthens the relationship between pointer types and getting the address of an identifier making it simpler concept for people coming from lanugages without pointers trying out odin. 

As for dereferencing this could be simplified to a simple . since this already means dereference when accessing members. This frees up the ^ symbol which could then be used as an operator, such as  possibly for  xor  which from what I can tell currently  shares ~ with bitwise NOT.
```
// from 
ptr: ^int; i := ptr^; x:= &i;

// to
ptr: &int; i := ptr.; x:= &i;
```

**Comment by gingerBill** [comment]
^ is used for pointers on purpose. This is because of thr Pascal tradition. It also follows the convention of type on the left, usage on the right.

Your proposal would remove all consistency and also be ambiguous too. I will not be accepting it.
