### ISSUE TITLE
odin build segfaults when missing main procedure

### ISSUE THREAD

**Issue by weshardee** [odin-lang/Odin#858]
## Context

Odin used to warn when compiling without a main procedure. Now, it segfaults, even if compiling as a shared library.

* Operating System: macOS v11.2.2
* `odin version` output: 
  * issue detected on 0.13.1-6ffb4d26 & 0.13.1-575c7ff0

## Expected Behavior

* `odin build some_file_without_main.odin` should produce an error letting the user know they're forgetting to include main.
* `odin build some_file_without_main.odin -build-mode:shared` should compile fine without a main procedure

## Current Behavior

* `odin build file_without_main.odin` segfaults
* `odin build file_without_main.odin -build-mode:shared` segfaults

### Steps to Reproduce

Make a file containing only:
```
package main
```
and run `odin build file_without_main.odin`

### Failure Logs

I did `git bisect` on Odin and found the issue was introduced in 575c7ff031f67ec4c479fa1cd6e22491e2b7a79e

**Comment by gingerBill** [comment]
Is this still an issue any more?

**Comment by rasa-silva** [comment]
Did not reproduce with `./odin version 0.13.1-8239cd34` on OSX 10.15.7:
`no_main.odin(1:1) Undefined entry point procedure 'main'`

**Comment by weshardee** [comment]
I can confirm that I can no longer repro.
