### ISSUE TITLE
Corrupted data in complex structures with default build parameters

### ISSUE THREAD

**Issue by kennethmaples** [odin-lang/Odin#859]
## Context

I am seeing data corruption in complex structures when default build flags are used. This manifests in two ways:
* Sometimes parameters to structures aren't being set properly in assignments.
* Return values with complex struct types can lead to

This error only (apparently) manifests when binaries are built with `odin build fname.odin`. When debug symbols are added (`-debug`) or higher optimization levels are specified (`-opt:1`) then there is no error.

* Changing the return type to `B` (from the compound `(B, bool, []byte))` fixes part of the issue.
* Changing the return type to `(^B, bool, []byte)` (and allocating B on the heap) fixes the issue.
* Changing `B` to only hold the slice fixes the issue.
* Compiling with `-opt:3` or `-opt:1` fixes the issue
* Compiling with `-debug` fixes the issue

## System information

* Operating System: linux
* Please paste `odin version` output: `/home/kenneth/build/Odin/odin version 0.13.1-6ffb4d26`

## Example code

The following program illustrates the error (I am not able to reproduce the behavior with a simpler return type):
```
// $ odin build badret.odin
// $ ./badret

package main

import "core:fmt"

E :: enum {
    zero = 0,
    one = 1,
    two = 2,
}

A :: struct {
    e: E,
    b1: bool,
    a: int,
    b2: bool,
}

B :: struct {
    a: A,
    d: []byte,
}

bad :: proc(buffer: []byte) -> (B, bool, []byte) {
    a := A{
        e= .one,
        b1= true,
        a= 7,
        b2= true,
    };

    b: B;
    b.a = a;
    b.d = buffer[:];

    fmt.println("inside bad:", b);
    return b, true, buffer[:];
}

main :: proc() {
    data := make([]byte, 17);
    for _, k in data {
        data[k] = 7;
    }
    b, _, _ := bad(data);
    fmt.println("after return:", b);
}
```
## Expected Behavior

The program should print
```
inside bad: B{a = A{e = one, b1 = true, a = 7, b2 = true}, d = [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]}
after return: B{a = A{e = one, b1 = true, a = 7, b2 = true}, d = [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]}
```

## Current Behavior

The program prints
```
inside bad: B{a = A{e = one, b1 = true, a = 7, b2 = false}, d = [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]}
after return: B{a = A{e = one, b1 = true, a = 7, b2 = false}, d = []}
```

Note that `b2` is always wrong, and `d` is wrong after the return.

**Comment by wilsonk** [comment]
I tested this on Win10 and Debian 10 (buster) just now with Odin version dev-2021-04:94fd59e6 (Apr 26, 2021). It seems to work fine now with the proper 'expected behavior' output being displayed (didn't test macos).  Ready to close? Fixed by old backend removal, I guess.

**Comment by gingerBill** [comment]
This appears to be an old backend bug, but this needs to be double checked before closing.

**Comment by kennethmaples** [comment]
I can't run the current master branch (known PIE issues on linux) but can check once that's resolved/stabilized.

**Comment by gingerBill** [comment]
PIE fix is coming soon, gotta do some tests
