### ISSUE TITLE
append struct (that only has a single union) causes compiler panic

### ISSUE THREAD

**Issue by awwdev** [odin-lang/Odin#860]
## Context
OS: Ubuntu 20.04.2 LTS
ODIN: version 0.13.1 (fa09640e7e8cdb8dfcbf91c23f9d82a0b7701454)

## Behavior

Appending a struct, that consists of single union, to a dynamic array will cause a compiler panic.

## Code
```c
S :: struct { 
    u: union{f32, int} //does not matter how many union members nor their type
};
arr: [dynamic]S;
append(&arr, S{}); //causes error

//same error
//tmp: S = { 4.2 };
//append(&arr, tmp); 
```

## Error
`ir.cpp(1005): Panic: Invalid abi type pass kind: union {f32, int}`

## More 
```c
S :: struct { 
    u: union{f32, int},  
    more: int, //does not matter which types or how many
};
arr: [dynamic]S;
append(&arr, S{});
```
When you add one or more members to the struct, it will suddenly compile.

**Comment by wilsonk** [comment]
I tested this on Win10 and Debian 10 (buster) just now and it seems to work with the compiler from today Apr 28, 2021. Hopefully this can be closed as fixed (assuming that it works on macos).
