### ISSUE TITLE
Compiler Segfaults Without main (Linux - Pop!_OS 20.10)

### ISSUE THREAD

**Issue by F0x1fy** [odin-lang/Odin#861]
## Context

When running anything with Odin, including `check`, and even if `-no-entry-point` is defined, compiler segfaults if there is no main procedure.

* Operating System: Linux (Pop!_OS 20.10)
* Please paste `odin version` output: odin version 0.13.1

## Expected Behavior

Compiler should output the appropriate error when there is no main proc, and `-no-entry-point` should properly subdue that error.

## Current Behavior

Compiler will segfaults. It also segfaults before reading all errors. I intentionally added two errors in two separate files. It caught the error of the first file, but immediately segfaulted and did not report any errors with the second.

## Failure Information (for bugs)

Simply outputs `Segmentation fault (core dumped)`.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create an empty file (or two with separate type-checking errors)
2. Run `odin check .`

### Failure Logs

Simply outputs `Segmentation fault (core dumped)`.

**Comment by rytc** [comment]
With `dev-2021-05:e08f39ec`, it does not segfault with no main defined, it provides a `Undefined entry point procedure 'main'
` message. Tested under Ubuntu 20.04

`odin check . -no-entry-point` is also working.

However it segfaults with `odin build . -no-entry-point`

```
Thread 1 "odin" received signal SIGSEGV, Segmentation fault.
0x0000000000554437 in lb_find_procedure_value_from_entity (m=0x7fffffffc9f8, e=0x0) at src/llvm_backend.cpp:5792
5792		GB_ASSERT(is_type_proc(e->type));
(gdb) bt
#0  0x0000000000554437 in lb_find_procedure_value_from_entity (m=0x7fffffffc9f8, e=0x0) at src/llvm_backend.cpp:5792
#1  0x00000000005a8a78 in lb_create_main_procedure (m=0x7fffffffc9f8, startup_runtime=0x7fff682a2a30) at src/llvm_backend.cpp:14255
#2  0x00000000005ac878 in lb_generate_code (gen=0x7fffffffc8b0) at src/llvm_backend.cpp:14944
#3  0x00000000005bfaa5 in main (arg_count=4, arg_ptr=0x7fffffffdfd8) at src/main.cpp:2170
```
In lb_find_procedure_value_from_entity, `e` is null.

In `lb_create_main_procedure` the `m->info->entry_point` is null
`lbValue entry_point = lb_find_procedure_value_from_entity(m, m->info->entry_point);`
