### ISSUE TITLE
Consider adding a way to change error location from `(Line:Column)` to :Line:Column

### ISSUE THREAD

**Issue by atkurtul** [odin-lang/Odin#866]
**Is your feature request related to a problem? Please describe.**
It is incredibly useful for errors to be reported this way. Vscode allows jumping to location from terminal with a single click.

**Describe the solution you'd like**
Enable this feature by setting ODIN_VSCODE_ERRORS enviroment variable?

**Comment by gingerBill** [comment]
Does VSCode not allow you to change the way it checks for the file position? In Sublime, this is easily configurable with the build system. I don't know much about VSCode

**Comment by Kelimion** [comment]
See [VS Code documentation](https://code.visualstudio.com/Docs/editor/tasks#_defining-a-problem-matcher) for how to write a so-called "problem matcher".

**Comment by atkurtul** [comment]
I was not aware i could change that. Most compilers (gcc, go, clang, rustc) report errors in this format, i didnt need to change it before
