### ISSUE TITLE
Layout Issues possibly related with #626

### ISSUE THREAD

**Issue by atkurtul** [odin-lang/Odin#870]
## Context

* Operating System: Ubuntu 20.10
* Please paste `odin version` output:
odin version 0.13.1-4e2a2ac8

**Minimal code to reproduce**

```odin
handle: uintptr = 0xdeadbeef;

Builder::struct {
  x0: i32,
  x1: uintptr,
  x2: i32,
}

main::proc() {
  info := Builder {
    x1 = handle,
    x2 = 1,
  };

  fmt.printf("%v\n", info);
}
```
Output:
```
Builder{x0 = 0, x1 = 3735928559, x2 = 0}
```
Expected output:
```
Builder{x0 = 0, x1 = 3735928559, x2 = 1}
```

This only happens in debug mode.
Llvm generated looks very strange
```llvm
define void @main.main() #0 {
decls-0:
	%0 = alloca %main.Builder, align 16
	%1 = alloca %main.Builder, align 16 ; why?
	; info
	%2 = bitcast %main.Builder* %0 to %..rawptr
	%3 = call %..rawptr @runtime.mem_zero(%..rawptr %2, i64 24)
	%4 = bitcast %main.Builder* %1 to %..rawptr
	%5 = call %..rawptr @runtime.mem_zero(%..rawptr %4, i64 24) ; why?
	%6 = bitcast %main.Builder* %1 to %..rawptr
	%7 = call %..rawptr @runtime.mem_zero(%..rawptr %6, i64 24) ; why?
	store %main.Builder {i32 zeroinitializer, i64 zeroinitializer, i32 1}, %main.Builder* %1 ; why?
	%8 = load i64, i64* @main.handle, align 8
	%9 = getelementptr inbounds %main.Builder, %main.Builder* %1, i32 0, i32 1
	store i64 %8, i64* %9
	%10 = load %main.Builder, %main.Builder* %1, align 8
	store %main.Builder %10, %main.Builder* %0
	ret void
}
```
It seems to be allocating space for 2 variables to inialize 1, zeroing the latter twice and storing another temporary into it. I think the issue is mainly caused by this line
``` llvm
store %main.Builder {i32 zeroinitializer, i64 zeroinitializer, i32 1}, %main.Builder* %1
```
Setting each field seperately should solve this issue, but im not exactly sure how it is handled in the compiler

**Comment by atkurtul** [comment]
Looking at the disassembly, it is probably caused by the last store instruction. For some reason it skips the last 8 bytes while copying
```asm
mov    rcx,QWORD PTR [rsp+0x28] ; <main.handle>
mov    rdx,QWORD PTR [rcx]      ; rdx = handle
mov    QWORD PTR [rsp+0x38],rdx ; tmp.x1 = rdx
mov    rdx,QWORD PTR [rsp+0x30] ; rdx = tmp.x0
mov    QWORD PTR [rsp+0x50],rdx ; info.x0 = rdx
mov    rdx,QWORD PTR [rsp+0x38] ; rdx = tmp.x1
mov    QWORD PTR [rsp+0x58],rdx ; info.x1 = rdx
add    rsp,0x68
ret
```

**Comment by kennethmaples** [comment]
I suspect this is also related to what I was seeing in issue #859.

I think the error has something to do with padding the struct. The llvm type is
```%main.Builder = type {i32, i64, i32}```
and it is inconsistently treating it as 16 bytes (incorrect) and 24 bytes (correct), which explains the failed copy.

You can fix the error by swapping the order of declaration of `x1` and `x2` in your parameter, which also supports this theory.

**Comment by gingerBill** [comment]
@kennethmaples This may be due to a struct reordering "optimization" which I DO NOT WANT to happen. I need to find out how to make LLVM disable this since it is causing many bugs.

**Comment by wilsonk** [comment]
I tested this on Win10 and Debian 10 (buster) just now with Odin version dev-2021-04:94fd59e6 (Apr 26, 2021). It seems to work fine now with the proper 'expected output' being displayed (didn't test macos). I didn't check the llvm output. Possibly able to close?

**Comment by gingerBill** [comment]
@atkurtul Can you confirm that his has been fixed?

**Comment by atkurtul** [comment]
Yes, this has been fixed with llvm-api
