### ISSUE TITLE
Nested Unions With Pointers Bug

### ISSUE THREAD

**Issue by Denzeduous** [odin-lang/Odin#873]
## Context

This is a bug that occurs with pointer-nested unions that are not unions of intrinsic types.

* Operating System: Pop!_OS 20.10
* Please paste `odin version` output: odin version 0.13.1

## Expected Behavior

This should properly compile.

## Current Behavior

It gives an error about variant types. It seems the bug most likely occurs due to it trying to go down the line recursively with a pointer and erroring out due to that.

## Failure Information (for bugs)

It seems it doesn't like recursive unions, even if they are simply pointers back to the union.

### Steps to Reproduce

Minimum repo:
```
package odin_variant_error
 
Foo_Bar_And_Baz :: union {Foo, Bar, Baz}
Foo :: struct {union1: ^Some_Union}
Bar :: struct {union1: ^Some_Union}
Baz :: struct {union1: ^Some_Union}
 
Some_Union :: union {
    Foo_Bar_And_Baz,
}
 
Error_Union :: union {
    Some_Union, // This errors out
}
```
It seems the issue arises from union pointers being nested layers within the unions themselves. Here is a subsection of the original code for a bit more context as to why I ran into this issue (slightly different way I ran into it):
<details>
    <summary>
        Context
    </summary>

```
package odin_variant_error
 
Type :: union {
    
}
 
Assignment_Or_Declaration :: union {Assignment_Implied_Declaration, Assignment_Explicit_Declaration, Assignment_No_Declaration, Declaration}
Assignment_Implied_Declaration :: struct {value: ^Expression}
Assignment_Explicit_Declaration :: struct {type: Type, value: ^Expression}
Assignment_No_Declaration :: struct {value: ^Expression}
 
Declaration :: struct {type: Type}
 
Operation :: union {
    Assignment_Or_Declaration,
    // Unary_Expression_Operation,
    // Binary_Expression_Operation,
    // Construct_Operation,
}
 
Expression :: union {
    Assignment_Or_Declaration, // This errors out for no known reason
    Operation, // This also errors out
    // Constant_Value,
    Type,
}
```
</details>

### Failure Logs

```
odin-test/source/test.odin(9:5) Invalid variant type in union 'Foo_Bar_And_Baz'                                                                             
odin-test/source/test.odin(13:5) Invalid variant type in union 'Some_Union'
```

**Comment by awwdev** [comment]
```odin
U2 :: union  {U1};
U1 :: union  {S1};
S1 :: struct {u: ^U2};
```
Here is a more condensed version.
Error: `Invalid variant type in union 'U1'`
