### ISSUE TITLE
Coercion to/from non-native endian type when casting from int<>float fails without going through native type first.

### ISSUE THREAD

**Issue by Kelimion** [odin-lang/Odin#881]
## Context

* Operating System: Windows 10
* Please paste `odin version` output: odin version 0.13.1-7a045bd9

## Expected Behavior

Expected behavior is for non-native endian types to cast from int to float base types or vice versa without first needing to cast to that base type.

```odin
	numerator  := u32be(45_000);
	divisor    := f32(100_000.0);
	as_f32     := f32(numerator) / divisor;      // This should work, but doesn't.
	as_f32_b   := f32(u32(numerator)) / divisor; // This fixes it.

	fmt.printf("Result: %v %v\n", as_f32, as_f32_b);

	val        := f64(1234.25);
	as_u32be   := u32be(val);      // This should work, but doesn't.
	as_u32be_b := u32be(u32(val)); // This fixes it.

	fmt.printf("Result: %v %v\n", as_u32be, as_u32be_b);

	assert(as_f32_b   == as_f32);
	assert(as_u32be_b == as_u32be);
```
Result: 0.450 0.450
Result: 1234 1234

Expected is for both numbers to be the same and the assert not to fail.
## Current Behavior

Result: 33669.121 0.450
Result: 3523477504 1234

Both asserts fail.
## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

See minrep above.

**Comment by gingerBill** [comment]
This has been fixed in 0ccf103160f0aaf8854306979efdee6a02562236
