### ISSUE TITLE
#load segfaults on a 349520 byte file

### ISSUE THREAD

**Issue by weshardee** [odin-lang/Odin#882]
## Context

* Operating System: macOS v11.2.3
* odin version 0.13.1

## Expected Behavior

I'm uncertain if the 349519 byte limit when using `#load` is by design. It took me a bit to track down what was happening due to the ambiguous error message.

If this is an unintended limit, then the file should load.

If this is a designed limit, then a better error message or possibly a compiler error pointing directly to the offending line would be nice.

## Current Behavior

`odin build` has an ambiguous error message followed by a segmentation fault if you `#load("foo")` a file that is at least 349520 bytes. 349519 and below seems to work fine.

### Steps to Reproduce

1. make a test file of the specified size: `head -c 349520 /dev/zero > test`
2. make a main.odin file that does `#load("test")`
3. build

Here's the simple main.odin file I tested with:

```
package main

main :: proc() {
  a := #load("test");
}
```

### Failure Logs

I get this message in console when building:

```
Arena out of memory
zsh: segmentation fault  odin build main.odin
```

**Comment by gingerBill** [comment]
This is an LLVM bug, and there is very little I can technically do about it directly.

**Comment by ThisDrunkDane** [comment]
Are you sure bill? The error message is from `gb.h` https://github.com/odin-lang/Odin/blob/85fd8aaf37c505c7ed48160d181a2106d9ef3eff/src/gb/gb.h#L5566

**Comment by atkurtul** [comment]
```gdb
Thread 1 "odin" received signal SIGSEGV, Segmentation fault.
0x00000000005ff93b in ir_print_escape_string (f=0x7fffffffaab0, name=..., print_quotes=false, prefix_with_dot=false) at src/ir_print.cpp:172
(gdb) backtrace
#0  0x00000000005ff93b in ir_print_escape_string (f=0x7fffffffaab0, name=..., print_quotes=false, prefix_with_dot=false) at src/ir_print.cpp:172
#1  0x000000000060336a in ir_print_exact_value (f=0x7fffffffaab0, m=0x7fffffffc380, value=..., type=0x7fff98716710) at src/ir_print.cpp:811
#2  0x0000000000607c82 in ir_print_value (f=0x7fffffffaab0, m=0x7fffffffc380, value=0x7fff99198ca0, type_hint=0x7fff98716710)
    at src/ir_print.cpp:1366
#3  0x0000000000610282 in print_llvm_ir (ir=0x7fffffffc380) at src/ir_print.cpp:2807
#4  0x0000000000624f0f in main (arg_count=4, arg_ptr=0x7fffffffdf38) at src/main.cpp:2226
```
Temp allocator runs out of memory possible here https://github.com/odin-lang/Odin/blob/85fd8aaf37c505c7ed48160d181a2106d9ef3eff/src/ir_print.cpp#L155

**Comment by gingerBill** [comment]
> Are you sure bill? The error message is from `gb.h`
> 
> https://github.com/odin-lang/Odin/blob/85fd8aaf37c505c7ed48160d181a2106d9ef3eff/src/gb/gb.h#L5566

It's good to know it is my code here since there is an LLVM error with a very similar error message.
