### ISSUE TITLE
New Odin Versioning System for Pre Version 1.0

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#887]
The current versioning system in Odin has not been working very well and does not map very well to the development of Odin, its official compiler, and the core library. Once v1.0 has been reached, an actual [semantic versioning convention](https://semver.org/) will be used.

As a proposal, I am suggesting we change the naming convention to be monthly based, which each month there being a new release regardless of how big or small the changes have been.

General ideas for the naming convention:

```
dev-2021.04
alpha-2021.04
```

**Comment by gingerBill** [comment]
This versioning system is to be automatically handled by the monthly build system rather than by hand. 

In the very unlikely case that there are no changes the has happened in that month, then a build should not be produced for that month.

The monthly build system should build a release near the beginning of that month (compared to nearer the end of the month) so that users know that they are on the latest one.

**Comment by goolic** [comment]
I would propose dev-2021.04.build01, sometimes you will ship a mistake and issue several new builds in a row to try and resolve it, this scheme makes that super clear.

**Comment by gingerBill** [comment]
If a multiple build is required, a letter will be appended (like housing numbers). If people want the most recent build, the use can use a nightly build.

**Comment by goolic** [comment]
I was serious, then i realized it was a joke and feel a little bit
ashamed...

Hahaha thanks for the good laugh.

Em qui., 1 de abr. de 2021 às 15:33, gingerBill ***@***.***>
escreveu:

**Comment by gingerBill** [comment]
This was not an April Fool's Joke but an absolutely serious proposal. We are going to transition from "v0.13.1" style release numbers to using monthly releases before version 1.0 is released.

**Comment by Platin21** [comment]
I think the initial proposal of `<Modifier>-<YYYY>-<0M>` is pretty good. Not sure if the pace is now considered to be faster but if it's a running number for the month might not be too bad?
