### ISSUE TITLE
16-bit IEEE 754 binary floating point support: `f16`

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#889]
**Is your feature request related to a problem? Please describe.**
Along side `f32` and `f64` in Odin, add a half precision `f16` type. 

The endian specific `f16le` and `f16be` will be required to be consistent with the other singular scalar numeric types.

`complex32` and `quaternion64` will be required too with the addition of `f16`

**Describe the solution you'd like**
Many domains will benefit from having `f16`:

* File formats (HDR image formats, data compression, GPU graphical files, vector fields, etc)
* GPU related data (common data type used for optimizations and reducing memory usage)
* Minimizing memory usage.

Some architectures, especially the newer ARM64 (AARCH64) architectures, support `f16` instructions natively. Many x86 processors allow for conversions between half-precision floats and single-precision floats with the [F16C](https://en.wikipedia.org/wiki/F16C) instruction set.

**Additional context**
One general issue with adding `f16` is that there are two popular formats: IEEE 754 and `bfloat16`. The latter effectively being a trunctated `f32`. `bfloat16` types support the same (exponent) range as `f32` but with a much smaller precision (due to the truncated mantissa)

**Comment by Kelimion** [comment]
Are there practical considerations to prefer one over the other instead of allowing both `f16` and `bfloat16`, other than adding support for their endian counterparts and making sure f16 coerces properly to bfloat16 and promotes properly to f32 and f64?

**Comment by gingerBill** [comment]
From a practical standpoint, I don't really see much of a need to add `bfloat16` whatsoever a core language concept. `f16` is much more consistent with the rest of the floating point types.

**Comment by Kelimion** [comment]
I'm inclined to agree. As far as I understand, OpenGL and OpenEXR both use IEEE f16 as their half float.

**Comment by Kelimion** [comment]
> @Kelimion Apparently bfloat16 is more commonly used in AI/Neuralnetwork’ not sure about the particular need for it though.

Indeed. For that use case, it's fine to use user-level code, because you're unlikely to interface on that boundary on each frame as you would in OpenGL. It's far more likely you'd require bfloats only to set initial weights or serialize a model after it's done training, not in the hot path.

**Comment by gingerBill** [comment]
Basic functionality implemented in 54e6c507698bf68b040400783f05686cacaddff1

**Comment by gingerBill** [comment]
Support for `f16` has been added to:

* core:math - 63bb26c0e0964a0a08d43bd2029e935988da65f6
* core:math/linalg - 0fc04a939e56f269aeaff2e97ba248411cebcd10

**Comment by gingerBill** [comment]
This was not an April Fool's Joke. And now has been successfully implemented into the language.
