### ISSUE TITLE
Fixed Point Arithmetic Types

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#890]
**Is your feature request related to a problem? Please describe.**
Fixed point arithmetic type support within Odin. 

**Describe the solution you'd like**
Allow through a built-in procedure to produce the data types:
```odin
Fix16_16 :: fixed_point_arithmetic_type_generator(integer=16, fraction=16);

a: Fix16_16 = fixed_pointer_arithmetic_type_value(123.345);
b: Fix16_16 = fixed_pointer_arithmetic_type_value(345.234);

fmt.println(a + b); // fixed_pointer_arithmetic_type_value(468.579)
```

LLVM has native intrinsic support for floating point arithmetic allowing for fast optimizations for such data types.
See: https://llvm.org/docs/LangRef.html#fixed-point-arithmetic-intrinsics

**Comment by gingerBill** [comment]
> Is this so we get more banks to use odin?

This is correct. This will aid with the adoption of Odin in the financial and banking sectors. This is a very good marketing move to increase the usage of Odin across the board.

**Comment by gingerBill** [comment]
Implemented fixed-point arithmetic intrinsics for -llvm-api backend: https://github.com/odin-lang/Odin/commit/cef698afd63339a8ab3d684f1de6e10914ed3796

```
intrinsics.fixed_point_mul
intrinsics.fixed_point_div
intrinsics.fixed_point_mul_sat
intrinsics.fixed_point_div_sat
```

**Comment by krixano** [comment]
I actually just started working on making a library for this, lmao (https://gist.github.com/krixano/315fd08638b743e23194fcce550d5541)

Guess I don't need to continue it anymore

**Comment by gingerBill** [comment]
I've just added `core:math/fixed`: https://github.com/odin-lang/Odin/commit/bcda9ddee75510b5b79d212dd123bcd5e6136f0f
https://github.com/odin-lang/Odin/blob/master/core/math/fixed/fixed.odin

**Comment by gingerBill** [comment]
This was a partial April Fool's Joke. I was never going to implement fixed point numbers as part of the core language, but only add intrinsics to make it easier for people to implement their own fixed point arithmetic if necessarily. Along with the `core:math/fixed` package.
