### ISSUE TITLE
Replacing the Old Backend with the New Backend Transition Period

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#891]
**Is your feature request related to a problem? Please describe.**
Replacing the Old Backend with the New Backend.

**Describe the solution you'd like**

* Replace the old backend with the new backend
* Make the CI for the nightly builds compile the new backend for all platforms
* Transition this over a period of weeks until everything is stable and tested

**Additional context**

* The new backend is nearly fully functioning with code generation working at all optimization levels. 
* The new generated code is better than the old backend (not full exhaustive testing but good enough).
* The new backend generates debug symbols correctly, and with much better detail the old backend end ever did.
* The new backend can be up to date with the LLVM versions much quicker and allow for better uses of newer features.
* New backend can be parallelized with having multiple modules (for development builds) allow for faster compile times (due to LLVM scaling O(N^2) with the size of module).
* Having to maintain one less backend makes everyone's life a lot easier

**Comment by Platin21** [comment]
We right now don’t have the correct flags for building on macOS with brew llvm.

**Comment by powerc9000** [comment]
> We right now don’t have the correct flags for building on macOS with brew llvm.
> Ideally that build would also set the Rpath‘s

For what it's worth. This is what I had to do to compile with brew `llvm clang src/main.cpp -Wno-switch -Wno-pointer-sign -Wno-tautological-constant-out-of-range-compare -Wno-tautological-compare -Wno-macro-redefined -std=c++11 -DGIT_SHA=\"685b42d8\" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -L /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib -O3 -march=native -pthread -ldl -lm -lstdc++ -liconv -o odin`

**Comment by gingerBill** [comment]
@Platin21 
> We right now don’t have the correct flags for building on macOS with brew llvm.
> Ideally that build would also set the Rpath‘s

Mac M1 support was pretty simple to add now that `llvm` is easy to install. I did not require that complex of a build system that @powerc9000 has written to get it working, but I support the Intel Macs do require all of that to work.

**Comment by Platin21** [comment]
I did jet not try to use the m1 build sh file but i thought a unified way todo this for macOS in say the makefile would actually make more sense.

**Comment by gingerBill** [comment]
Another thing for the transition period with @ThisDrunkDane has suggested is to get the new backend compiling with CI for all platforms and then just remove the old backend straightaway. If people require the old backend still, they can still use a previous version if necessary.

**Comment by gingerBill** [comment]
n.b. This is not an April Fool's Joke.

**Comment by Platin21** [comment]
I didn‘t expect anything else maybe we should also switch to makefiles for nix completely.

**Comment by ThisDrunkDane** [comment]
I would prefer if we switch to makefiles _completely_ for all platforms.

**Comment by Kelimion** [comment]
That would add another dependency to Odin for Windows, like mingw. Alternatively, we could implement our own `make` in Odin, one that works across platforms, and ship a compiled version of it with releases.

**Comment by Platin21** [comment]
Also a option still requires a initial build system or is the consideration doing that manually?

**Comment by ThisDrunkDane** [comment]
> That would add another dependency to Odin for Windows, like mingw. Alternatively, we could implement our own `make` in Odin, one that works across platforms, and ship a compiled version of it with releases.

It's a dependency we already have? You need the VS build tools to build on windows and `nmake` is included in that which can build makefiles

**Comment by Platin21** [comment]
Ohh so there is make anyways on each platform hmm then upvote for using make everywhere.

**Comment by gingerBill** [comment]
`-llvm-api` appears to work fine unofficially for Linux and Mac on AMD64. We just need to get the CI building those backends correctly. Once that happens, two things can happen:

* New Versioning System can be implemented (https://github.com/odin-lang/Odin/issues/887)
* Old Backend can be removed entirely

**Comment by ThisDrunkDane** [comment]
I'll get started on that then, should be fairly simple to do if I leave out the entire "build LLVM in the CI" itself
