### ISSUE TITLE
Can't build demo.odin

### ISSUE THREAD

**Issue by Platin21** [odin-lang/Odin#895]
## Context

* LLVM API
This is enabled in my case and uses llvm11.1 (as for the other are no binaries available)

* Operating System:
MacOS 11.2.3 on x86_AMD64 

* Please paste `odin version` output:
Commit => d3665331c76cd10658d921ec141759c4ec833693
odin version 0.13.1-d3665331

## Expected Behavior

The demo program builds and links without any problems. 

## Current Behavior

The compilation of the demo program fails.

## Failure Information (for bugs)

It seems like there is a function used in the codegen which is not existent for this architecture.
This seems to be `___extendhfsf2` 

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. type => odin build examples/demo/demo.odin

### Failure Logs

Undefined symbols for architecture x86_64:
  "___extendhfsf2", referenced from:
      _fmt.fmt_arg in demo.o
ld: symbol(s) not found for architecture x86_64

#### Notes: 
@ThisDrunkDane it seems like the build system doesn't check wether demo.odin did even run correctly or somehow didn't catch this as it can be clearly seen for odin run that it get's the same output as I do.

**Comment by Platin21** [comment]
Hmm interesting it seems like this something inside the compiler_rt library is this suppose to be used?

**Comment by Kelimion** [comment]
`extendhfsf2` is used by the new f16 functionality.

**Comment by Platin21** [comment]
@Kelimion Yes something I expected too from the name of it. What I don't get though is from where does it get normally delivered and is this something llvm generates or is this added explicitly through adding that function?

**Comment by Platin21** [comment]
I suspect it uses this => https://code.woboq.org/llvm/compiler-rt/lib/builtins/extendhfsf2.c.html on other platforms but I don't think we do link on macOS with the compiler-rt of clang/llvm.

**Comment by Kelimion** [comment]
> I suspect it uses this => https://code.woboq.org/llvm/compiler-rt/lib/builtins/extendhfsf2.c.html on other platforms but I don't think we do link on macOS with the compiler-rt of clang/llvm.

A bit surprising it's not in the Mac release given that I see references to `extendhfsf2.c` dating back to 2015.

**Comment by Kelimion** [comment]
It's also in the latest clang on Apple's site: https://opensource.apple.com/source/clang/clang-800.0.42.1/src/projects/compiler-rt/lib/builtins/extendhfsf2.c.auto.html

**Comment by Platin21** [comment]
Yeah it very well is meanwhile the build had the same problem here on GitHub.

**Comment by Platin21** [comment]
So it's definitely not a env thing on my side as https://github.com/odin-lang/Odin/runs/2260609199 also fails todo anything meaningful. I will take a look if the compiler-rt has the symbol in it..

**Comment by ThisDrunkDane** [comment]
I thought it was fixed that `odin run` would pass through the exit code if it failed _pre_ execution @gingerBill ?

**Comment by Platin21** [comment]
From the current outcome:
```
  ./odin run examples/demo/demo.odin
3
  shell: /bin/bash -e {0}
4
  env:
5
    CPATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/user/include
6
Undefined symbols for architecture x86_64:
7
  "___extendhfsf2", referenced from:
8
      _fmt.fmt_arg in demo.o
9
ld: symbol(s) not found for architecture x86_64
```

It doesn't look like it's doing the correct thing :)

**Comment by ThisDrunkDane** [comment]
Clearly the exit code from `ld` isn't getting passed up the chain

**Comment by Platin21** [comment]
Yeah it doesn't do so for ld and also lld but it also doesn't do so for MSVC-LINK..

**Comment by Platin21** [comment]
This is fixed now thanks and the linker also now returns the value because of #896 and commit 19470683e75d036d02327421a1a36181b8d741a8 fixed the bug was just a missing runtime proc.
