### ISSUE TITLE
`odin build` or `odin run` fail to link on Linux

### ISSUE THREAD

**Issue by corruptmemory** [odin-lang/Odin#919]
## Context

* Operating System: Linux

```
uname --all
Linux godlike 5.11.16-arch1-1 #1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000 x86_64 GNU/Linux
```

* Clang info:

```
clang --version
clang version 11.1.0
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

* Please paste `odin version` output:

```
odin version
/home/jim/projects/Odin/odin version dev-2021-04:afe185ee
```

## Expected Behavior

Running `make all` in the root of the Odin project directory should produce a compiler and run the `demo` program

## Current Behavior

```
make all
clang src/main.cpp -Wno-switch -Wno-pointer-sign -Wno-tautological-constant-out-of-range-compare -Wno-tautological-compare -Wno-macro-redefined -std=c++14 -DGIT_SHA=\"afe185ee\" -DODIN_VERSION_RAW=\"dev-2021-04\" -I/usr/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -L/usr/lib  -g -pthread -ldl -lm -lstdc++ -lLLVM-11 -o odin
./odin run examples/demo/demo.odin
/usr/bin/ld: demo.o: relocation R_X86_64_32S against `.data' can not be used when making a PIE object; recompile with -fPIE
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clone the Odin git repo
2. cd into the cloned directory
3. Run `make all`

**Comment by gingerBill** [comment]
This is related to `PIE` which is not correctly supported by Odin yet. I think the best approach is to disable PIE for the time being on Linux.

**Comment by corruptmemory** [comment]
This now links.  Thanks

**Comment by baynarikattu** [comment]
> the best approach is to disable PIE for the time being on Linux.

Btw, Android (Termux) doesn't support non-PIE executables:
```console
~/raymarcher $ odin run .
error: /data/data/com.termux/files/home/raymarcher/raymarcher: Android only supports position-independent executables (-fPIE)
```

Are there any workarounds?

**Comment by laytan** [comment]
@baynarikattu From the top of my head: `-reloc-mode:pic`, but check the help for that flag.

**Comment by baynarikattu** [comment]
> [@baynarikattu](https://github.com/baynarikattu) From the top of my head: `-reloc-mode:pic`, but check the help for that flag.

That flag fixed the issue with PIE, thank you!
But now I'm getting another error. I should probably ask for help on Discord.
