### ISSUE TITLE
Incorrect return values in the presence of slices (for `strconv.parse_f32` only?)

### ISSUE THREAD

**Issue by corruptmemory** [odin-lang/Odin#945]
## Context

This problem may be more widespread than this example indicates, but this is what I have been able to narrow things down to for now.

Example program:

```odin
package main

import "core:strconv"
import "core:fmt"

USE_SUBSTRING :: #config(USE_SUBSTRING, false);

get_float :: proc(s: string) -> (f32, bool) {
  if len(s) > 0 {
    f, ok := strconv.parse_f32(s);
    fmt.printf("s: '%s', f: %f, ok: %v\n", s, f, ok);
    return f, ok;
  }
  return 0.0, false;
}

main :: proc() {
  floats := "-1.000000";
  f: f32;
  ok: bool;
  when USE_SUBSTRING == true {
    f, ok = get_float(floats[0:len(floats)]);
    fmt.printf("floats[0:len(floats)]: '%s', f: %v, ok: %v\n", floats[0:len(floats)], f, ok);
  } else {
    f, ok = get_float(floats);
    fmt.printf("floats: '%s', f: %v, ok: %v\n", floats, f, ok);
  }
}
```

Build 1:

```bash
$ odin build test-case.odin -define:USE_SUBSTRING=true
$ ./test-case
s: '-1.000000', f: -1.000, ok: false
floats[0:len(floats)]: '-1.000000', f: -1.000, ok: true
```

Build 2:

```bash
$ odin build test-case.odin -define:USE_SUBSTRING=false
$ ./test-case
s: '-1.000000', f: -1.000, ok: false
floats: '-1.000000', f: -1.000, ok: false
```

* Operating System:

```bash
$ uname --all
Linux nomad-arch 5.11.16-arch1-1 #1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000 x86_64 GNU/Linux
```

* Clang info:

```bash
$ clang --version
clang version 11.1.0
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

* Please paste `odin version` output:

This is built after a fresh pull from `master`, but this problem has been happening for at least a week.

```bash
$ odin version
/home/jim/projects/Odin/odin version dev-2021-05:b6a1ec02
```

## Expected Behavior

1. The output of `Build 1` and `Build 2` should be the same (ignoring the embedded `[0:len(floats)]` in `Build 1`)
2. The return value of ` strconv.parse_f32` should return `-1.000` and `true`
3. The value returned to `main` should have the same values as the corresponding variables in `get_float`

## Current Behavior

1. The output of `Build 1` and `Build 2` differ  (ignoring the embedded `[0:len(floats)]` in `Build 1`)
2. The return value of ` strconv.parse_f32` returns `-1.000` and `false`
3. In `Build 1` the local value of `ok` in the function `get_float` is reported as `false` but is returned as `true` in `main`

### Steps to Reproduce

1. Use provided example program above
2. Build as indicated with `Build 1` and `Build 2`

**Comment by gingerBill** [comment]
Is this still a problem?

**Comment by corruptmemory** [comment]
Nice!

```bash
➞ ../Odin/odin build test-case.odin -define:USE_SUBSTRING=true
➞ ./test-case
s: '-1.000000', f: -1.000, ok: true
floats[0:len(floats)]: '-1.000000', f: -1.000, ok: true

➞ ../Odin/odin build test-case.odin -define:USE_SUBSTRING=false
➞ ./test-case
s: '-1.000000', f: -1.000, ok: true
floats: '-1.000000', f: -1.000, ok: true

➞ ../Odin/odin version
../Odin/odin version dev-2021-05:d2fcbf0e
```

This is a nice fix, but literally all my other programs completely fail even though they compile without issues:

```bash
➞ ./tests.sh
---- Build - channel_test.odin:
---- Test - channel_test.odin:
futex-FUTEX_WAIT: Bad address
./tests.sh: line 5: 154305 Segmentation fault      (core dumped) ./${x%.odin}
      --------
---- Build - thread_test.odin:
---- Test - thread_test.odin:
./tests.sh: line 5: 154964 Segmentation fault      (core dumped) ./${x%.odin}
      --------
---- Build - wavefront_object_loader_test.odin:
---- Test - wavefront_object_loader_test.odin:
./tests.sh: line 5: 155626 Segmentation fault      (core dumped) ./${x%.odin}
      --------
```

**Comment by corruptmemory** [comment]
For clarification: before the issue identified in this ticket all those "tests" worked without issue.  I'll have to dig up and narrow-down what are the new other issues and make tickets for them.

**Comment by gingerBill** [comment]
@corruptmemory If those are the channels in `package sync`, I am completely rewriting those entirely with sync2 for this month

**Comment by corruptmemory** [comment]
No, I've implemented my own version of `Channel`.  To the extent possible, I am trying to get Golang Channel semantics and I use `futex` instead of anything in the `pthreads` library as much as I can.  Hopefully, the "Futex 2" stuff will land soon and I can move over to that.

**Comment by gingerBill** [comment]
@corruptmemory That's awesome! I'm guessing the `futex` is purely for `select` statements. Windows equivalent would be the `WaitOnAddress` and `WakeByAddress*` stuff.

Is this code available anywhere?

**Comment by corruptmemory** [comment]
Short version "yes-ish": https://gitlab.com/corruptmemory/tic-tac-toe/-/blob/base-game-state/tsync/channel.odin

As you can see the `select` function is yet to be done :stuck_out_tongue: 

There are also some corner-cases that I'm working out as well ... as I have time
