### ISSUE TITLE
Procedure does not return the correct values

### ISSUE THREAD

**Issue by DanielGavin** [odin-lang/Odin#949]
## Context

This only happens on Linux(Also some indication that this happens on MacOS through my tests with CI on MacOS latest).

Operating System: Manjaro Linux

Ran code with `odin run main.odin` and with latest Odin version c85c5ec38cae351ef8394553cdc701cb854656c9

## Expected Behavior

Stdout with 'succeded'

## Current Behavior

Chooses randomly between 'failed' and 'succeded' 

## Code

```odin
package fuzzy_test

import "core:fmt"


fuzzy_match :: proc(word: string) -> (f32, bool) {
	return 2, true;
}

main :: proc() {


    if score, ok := fuzzy_match("group_function"); ok {
        fmt.println("succeded");
    } else {
        fmt.println("failed");
    }

}
```

**Comment by gingerBill** [comment]
This should work now.
