### ISSUE TITLE
Integer overflow causes range based loop to run forever

### ISSUE THREAD

**Issue by zagortenay333** [odin-lang/Odin#990]
The following loop will run forever in odin:

```odin
package main

main :: proc () {
    x : u8 = 0;
    y : u8 = 255;
    for i in x..y { }
}
```

It's because the loop terminates when x is strictly larger than y, but that's not possible here.

That is, the sequence goes: `0..255   ->   254..255   ->   255..255   ->   0..255   ->   ...`

In my own compiler I handle these in the following way:

![cfg](https://user-images.githubusercontent.com/11144630/118364109-583cc980-b597-11eb-9035-2067bf6e173f.png)

Just do a `less than equal` check at the loop entrance, and in the continue block do an `equal` check followed by increment.

**Comment by gingerBill** [comment]
This is something that I am not particularly sure how to deal with. Odin's integer arithmetic is defined to be two's complement, and wrapping is not an error.

Currently, `for i in x .. y {}` is trivially defined with:
```
for i := x; i <= y; i += 1 {}
```
And that means wrapping will happen if `y` is the maximum value.

Your approach adds an extra branch check which may not be a good idea in terms of performance but it does solve the wrapping issue.

**Comment by gingerBill** [comment]
I've implemented this behaviour in f7b1290fe930099a1250dbde64cc1c081fbd4828

I am not wondering what optimizations I could do.

**Comment by zagortenay333** [comment]
Note, there is no extra branch check here. Two checks are performed on the first iteration, and only 1 on all the subsequent iterations.

**Comment by gingerBill** [comment]
> Note, there is no extra branch check here. Two checks are performed on the first iteration, and only 1 on all the subsequent iterations.

There has to be an extra branch check IFF the upper bound is not constant.
```
for i in x .. foo() {
}
```
where `foo()`  is re-evaluated once per loop.

**Comment by zagortenay333** [comment]
In the discussion part you showed the following:

```
for i := x; i <= y; /**/ {
    // body
   if i == y {
       break;
   }
   i += 1;
}
```
This does not match the above CFG. In your code (unless you made a mistake) you will perform two checks *each* iteration. In my code you only perform two check on the first iteration, and only 1 check on the subsequent ones.

**Comment by zagortenay333** [comment]
Oh wait a minute. You call foo() once per iteration? I'm not familiar with the semantics of odin. In my language you would call foo() only once and that's it.

**Comment by gingerBill** [comment]
> Oh wait a minute. You call foo() once per iteration? I'm not familiar with the semantics of odin. In my language you would call foo() only once and that's it.

Yes, that is correct. I'll show a basic example showing what Odin does:
```odin
package main

import "core:fmt"

print :: proc(x: u8) {
	fmt.println(x);
}

upper :: #force_no_inline proc "contextless" () -> u8 {
	return 255;
}

test_constant :: proc() {
	x, y: u8 = 0, 255;
	for i in x..y {
		print(i);
	}
}

test_variable :: proc() {
	x: u8 = 0;
	for i in x..upper() {
		print(i);
	}
}

main :: proc() {
	test_constant();
	test_variable();
}
```

```llvm
; Function Attrs: noinline nounwind
define i8 @main.upper() #0 {
decls:
  ret i8 -1
}

define void @main.test_constant(i8* noalias nocapture nonnull %__.context_ptr) {
decls:
  br label %for.interval.loop

for.interval.loop:                                ; preds = %for.interval.post, %decls
  %.01 = phi i8 [ 0, %decls ], [ %1, %for.interval.post ]
  %.0 = phi i64 [ 0, %decls ], [ %2, %for.interval.post ]
  call void @main.print(i8 %.01, i8* %__.context_ptr)
  %0 = icmp ne i8 %.01, -1
  br i1 %0, label %for.interval.post, label %for.interval.done

for.interval.post:                                ; preds = %for.interval.loop
  %1 = add i8 %.01, 1
  %2 = add i64 %.0, 1
  br label %for.interval.loop

for.interval.done:                                ; preds = %for.interval.loop
  ret void
}

define void @main.test_variable(i8* noalias nocapture nonnull %__.context_ptr) {
decls:
  br label %for.interval.loop

for.interval.loop:                                ; preds = %for.interval.post, %decls
  %.01 = phi i8 [ 0, %decls ], [ %3, %for.interval.post ]
  %.0 = phi i64 [ 0, %decls ], [ %4, %for.interval.post ]
  %0 = call i8 @main.upper()
  %1 = icmp ule i8 %.01, %0
  br i1 %1, label %for.interval.body, label %for.interval.done

for.interval.body:                                ; preds = %for.interval.loop
  call void @main.print(i8 %.01, i8* %__.context_ptr)
  %2 = icmp ne i8 %.01, %0
  br i1 %2, label %for.interval.post, label %for.interval.done

for.interval.post:                                ; preds = %for.interval.body
  %3 = add i8 %.01, 1
  %4 = add i64 %.0, 1
  br label %for.interval.loop

for.interval.done:                                ; preds = %for.interval.body, %for.interval.loop
  ret void
}

define void @main.main(i8* noalias nocapture nonnull %__.context_ptr) {
decls:
  call void @main.test_constant(i8* %__.context_ptr)
  call void @main.test_variable(i8* %__.context_ptr)
  ret void
}
```

**Comment by gingerBill** [comment]
In the constant case, no extra branch is required because the upper value only needs to be evaluated once. In the second example, an extra branch is required because the upper bound is checked each iteration.

**Comment by zagortenay333** [comment]
Well, having to eval the range expression once per iteration does make this a lot uglier.

I find that behavior quite uninutitive if I may say. I would expect that:

```
for i in bar()..foo() {}
```

is just syntactic sugar for:

```
x := bar();
y := foo();
for i in x..y {}
```

Any reason why you've done it this way?

**Comment by gingerBill** [comment]
As I said, it makes loads of sense if you think of it as being sugar for a normal c-style for loop:
```odin
for i in bar() .. foo() {}

for i := bar(); i <= foo(); i += 1 {}
```

**Comment by zagortenay333** [comment]
Fair enough.

**Comment by zagortenay333** [comment]
I'm wondering whether you can still do as I showed above by just evaling the upper bound in the second LOOP_CONTINUE block:
```
y := foo();

loop_start:
    // loop body...
    if i == y { goto loop_end; }
    y = foo();
    i++;
    goto loop_start;

loop_end:
```

That way you only perform one check per iteration but still eval the upper bound expression once per iteration.
