### ISSUE TITLE
Errors in core:* when targeting Wasm

### ISSUE THREAD

**Issue by judah-caruso** [odin-lang/Odin#993]
## Context

Errors in `core:runtime`, `core:os`, and `core:time` stop compilation when targeting `js_wasm32`.

* Operating System: Windows 10
* Odin Version: dev-2021-05:6ef96d33

## Expected Behavior

Successful compilation to Wasm

## Current Behavior

```
Odin/core/runtime/internal.odin(647:9) Cannot convert '1e12' to 'int' from 'untyped integer
Odin/core/os/stream.odin(46:16) Undeclared name: seek
Odin/core/os/stream.odin(46:3) Assignment count mismatch '2' = '1'
Odin/core/time/perf.odin(8:9) Undeclared name: _tick_now
Odin/core/time/time.odin(52:21) Undeclared name: now
```

## Failure Information (for bugs)

These errors are not raised when targeting other platforms.

### Steps to Reproduce

1. Create a simple program:
    ```odin
    package main
    main :: proc() {}
    ```
2. `build` or `run` with the `-target=js_wasm32` flag

**Comment by judah-caruso** [comment]
On commit `312a1e8a`, compiling with `-target=freestanding_wasm32` still produces:

```
Odin/core/time/perf.odin(8:9) Undeclared name: _tick_now                               
Odin/core/time/time.odin(52:21) Undeclared name: now
```

**Comment by gingerBill** [comment]
Are you just doing an empty project like the above?

**Comment by judah-caruso** [comment]
Sorry for taking a while to get back to this! I wanted to do a full rebase, build, and test but hadn't found time to do so.

Creating an empty project and running `odin build wasm.odin -target:freestanding_wasm32` on `35230b1a` would output:
```sh
Failed to execute command:
    "Odin\\bin\wasm-ld" "sandbox/wasm.wasm-obj" -o "sandbox/wasm.wasm" --no-entry --export-table --export-all --allow-undefined
```

until I copied `wasm-ld.exe` from my LLVM install directory to Odin's `bin/` directory. The above command now outputs:

```sh
wasm-ld: error: cannot open sandbox/wasm.wasm-obj: no such file or directory
```

`wasm.odin` is still:
```odin
package main
main :: proc() {}
```

**Comment by Platin21** [comment]
And it generated a obj file?

**Comment by judah-caruso** [comment]
It did successfully generate a `.wasm.o` file
